.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80011488

dlabel D_80011488
    /* 1C88 80011488 */ .asciz "+"
    /* 2B000000 */
.align 2
    /* 1C8C 8001148C 28000A00 */ .word 0x000A0028
    /* 1C90 80011490 24002200 */ .word 0x00220024
    /* 1C94 80011494 2C000300 */ .word 0x0003002C
    /* 1C98 80011498 29002600 */ .word 0x00260029
    /* 1C9C 8001149C 09002D00 */ .word 0x002D0009
    /* 1CA0 800114A0 08003100 */ .word 0x00310008
    /* 1CA4 800114A4 30003300 */ .word 0x00330030
    /* 1CA8 800114A8 2A000700 */ .word 0x0007002A
    /* 1CAC 800114AC 04002700 */ .word 0x00270004
    /* 1CB0 800114B0 20002F00 */ .word 0x002F0020
    /* 1CB4 800114B4 2E001F00 */ .word 0x001F002E
    /* 1CB8 800114B8 38002600 */ .word 0x00260038
    /* 1CBC 800114BC 00002300 */ .word 0x00230000
    /* 1CC0 800114C0 1F000A00 */ .word 0x000A001F
    /* 1CC4 800114C4 27002C00 */ .word 0x002C0027
    /* 1CC8 800114C8 24000300 */ .word 0x00030024
    /* 1CCC 800114CC 21002800 */ .word 0x00280021
    /* 1CD0 800114D0 25000900 */ .word 0x00090025
    /* 1CD4 800114D4 08003100 */ .word 0x00310008
    /* 1CD8 800114D8 30002200 */ .word 0x00220030
    /* 1CDC 800114DC 33000700 */ .word 0x00070033
    /* 1CE0 800114E0 2F002E00 */ .word 0x002E002F
    /* 1CE4 800114E4 2A002900 */ .word 0x0029002A
    /* 1CE8 800114E8 09003800 */ .word 0x00380009
    /* 1CEC 800114EC 2A002700 */ .word 0x0027002A
    /* 1CF0 800114F0 23003700 */ .word 0x00370023
    /* 1CF4 800114F4 02000800 */ .word 0x00080002
    /* 1CF8 800114F8 07002B00 */ .word 0x002B0007
    /* 1CFC 800114FC 21002C00 */ .word 0x002C0021
    /* 1D00 80011500 28002500 */ .word 0x00250028
    /* 1D04 80011504 29000600 */ .word 0x00060029
    /* 1D08 80011508 33003200 */ .word 0x00320033
    /* 1D0C 8001150C 30002600 */ .word 0x00260030
    /* 1D10 80011510 2E002D00 */ .word 0x002D002E
    /* 1D14 80011514 1F001E00 */ .word 0x001E001F
    /* 1D18 80011518 00000000 */ .word 0x00000000
enddlabel D_80011488


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8008FADC, 0x2E4

glabel func_8008FADC
    /* 802DC 8008FADC D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 802E0 8008FAE0 2000BFAF */  sw         $ra, 0x20($sp)
    /* 802E4 8008FAE4 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 802E8 8008FAE8 1800B2AF */  sw         $s2, 0x18($sp)
    /* 802EC 8008FAEC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 802F0 8008FAF0 1000B0AF */  sw         $s0, 0x10($sp)
    /* 802F4 8008FAF4 EFE9030C */  jal        func_800FA7BC
    /* 802F8 8008FAF8 21908000 */   addu      $s2, $a0, $zero
    /* 802FC 8008FAFC 100040AE */  sw         $zero, 0x10($s2)
    /* 80300 8008FB00 140040AE */  sw         $zero, 0x14($s2)
    /* 80304 8008FB04 180040AE */  sw         $zero, 0x18($s2)
    /* 80308 8008FB08 1C0040AE */  sw         $zero, 0x1C($s2)
    /* 8030C 8008FB0C 200040AE */  sw         $zero, 0x20($s2)
    /* 80310 8008FB10 240040AE */  sw         $zero, 0x24($s2)
    /* 80314 8008FB14 280040AE */  sw         $zero, 0x28($s2)
    /* 80318 8008FB18 2C0040AE */  sw         $zero, 0x2C($s2)
    /* 8031C 8008FB1C 300040AE */  sw         $zero, 0x30($s2)
    /* 80320 8008FB20 340040AE */  sw         $zero, 0x34($s2)
    /* 80324 8008FB24 380040AE */  sw         $zero, 0x38($s2)
    /* 80328 8008FB28 3C0040AE */  sw         $zero, 0x3C($s2)
    /* 8032C 8008FB2C 400040AE */  sw         $zero, 0x40($s2)
    /* 80330 8008FB30 440040AE */  sw         $zero, 0x44($s2)
    /* 80334 8008FB34 480040AE */  sw         $zero, 0x48($s2)
    /* 80338 8008FB38 4C0040AE */  sw         $zero, 0x4C($s2)
    /* 8033C 8008FB3C 500040AE */  sw         $zero, 0x50($s2)
    /* 80340 8008FB40 540040AE */  sw         $zero, 0x54($s2)
    /* 80344 8008FB44 580040AE */  sw         $zero, 0x58($s2)
    /* 80348 8008FB48 5C0040AE */  sw         $zero, 0x5C($s2)
    /* 8034C 8008FB4C 600040AE */  sw         $zero, 0x60($s2)
    /* 80350 8008FB50 640040AE */  sw         $zero, 0x64($s2)
    /* 80354 8008FB54 680040AE */  sw         $zero, 0x68($s2)
    /* 80358 8008FB58 6C0040A6 */  sh         $zero, 0x6C($s2)
    /* 8035C 8008FB5C 6E0040A6 */  sh         $zero, 0x6E($s2)
    /* 80360 8008FB60 00401124 */  addiu      $s1, $zero, 0x4000
    /* 80364 8008FB64 700051A6 */  sh         $s1, 0x70($s2)
    /* 80368 8008FB68 720051A6 */  sh         $s1, 0x72($s2)
    /* 8036C 8008FB6C 7A0040A6 */  sh         $zero, 0x7A($s2)
    /* 80370 8008FB70 7C0040A6 */  sh         $zero, 0x7C($s2)
    /* 80374 8008FB74 740040A6 */  sh         $zero, 0x74($s2)
    /* 80378 8008FB78 01001024 */  addiu      $s0, $zero, 0x1
    /* 8037C 8008FB7C 760050A6 */  sh         $s0, 0x76($s2)
    /* 80380 8008FB80 780050A6 */  sh         $s0, 0x78($s2)
    /* 80384 8008FB84 9AE0030C */  jal        func_800F8268
    /* 80388 8008FB88 84004426 */   addiu     $a0, $s2, 0x84
    /* 8038C 8008FB8C EFE9030C */  jal        func_800FA7BC
    /* 80390 8008FB90 B0004426 */   addiu     $a0, $s2, 0xB0
    /* 80394 8008FB94 C00040AE */  sw         $zero, 0xC0($s2)
    /* 80398 8008FB98 C40040AE */  sw         $zero, 0xC4($s2)
    /* 8039C 8008FB9C C80040AE */  sw         $zero, 0xC8($s2)
    /* 803A0 8008FBA0 CC0040AE */  sw         $zero, 0xCC($s2)
    /* 803A4 8008FBA4 D00040AE */  sw         $zero, 0xD0($s2)
    /* 803A8 8008FBA8 D40040AE */  sw         $zero, 0xD4($s2)
    /* 803AC 8008FBAC D80040AE */  sw         $zero, 0xD8($s2)
    /* 803B0 8008FBB0 DC0040AE */  sw         $zero, 0xDC($s2)
    /* 803B4 8008FBB4 E00040AE */  sw         $zero, 0xE0($s2)
    /* 803B8 8008FBB8 E40040AE */  sw         $zero, 0xE4($s2)
    /* 803BC 8008FBBC E80040AE */  sw         $zero, 0xE8($s2)
    /* 803C0 8008FBC0 EC0040AE */  sw         $zero, 0xEC($s2)
    /* 803C4 8008FBC4 F00040AE */  sw         $zero, 0xF0($s2)
    /* 803C8 8008FBC8 F40040AE */  sw         $zero, 0xF4($s2)
    /* 803CC 8008FBCC F80040AE */  sw         $zero, 0xF8($s2)
    /* 803D0 8008FBD0 FC0040AE */  sw         $zero, 0xFC($s2)
    /* 803D4 8008FBD4 000140AE */  sw         $zero, 0x100($s2)
    /* 803D8 8008FBD8 040140AE */  sw         $zero, 0x104($s2)
    /* 803DC 8008FBDC 080140AE */  sw         $zero, 0x108($s2)
    /* 803E0 8008FBE0 0C0140AE */  sw         $zero, 0x10C($s2)
    /* 803E4 8008FBE4 100140AE */  sw         $zero, 0x110($s2)
    /* 803E8 8008FBE8 140140AE */  sw         $zero, 0x114($s2)
    /* 803EC 8008FBEC 180140AE */  sw         $zero, 0x118($s2)
    /* 803F0 8008FBF0 1C0140A6 */  sh         $zero, 0x11C($s2)
    /* 803F4 8008FBF4 1E0140A6 */  sh         $zero, 0x11E($s2)
    /* 803F8 8008FBF8 200151A6 */  sh         $s1, 0x120($s2)
    /* 803FC 8008FBFC 220151A6 */  sh         $s1, 0x122($s2)
    /* 80400 8008FC00 2A0140A6 */  sh         $zero, 0x12A($s2)
    /* 80404 8008FC04 2C0140A6 */  sh         $zero, 0x12C($s2)
    /* 80408 8008FC08 240140A6 */  sh         $zero, 0x124($s2)
    /* 8040C 8008FC0C 260150A6 */  sh         $s0, 0x126($s2)
    /* 80410 8008FC10 280150A6 */  sh         $s0, 0x128($s2)
    /* 80414 8008FC14 340140AE */  sw         $zero, 0x134($s2)
    /* 80418 8008FC18 380140AE */  sw         $zero, 0x138($s2)
    /* 8041C 8008FC1C 3C0140AE */  sw         $zero, 0x13C($s2)
    /* 80420 8008FC20 01000224 */  addiu      $v0, $zero, 0x1
    /* 80424 8008FC24 400142A2 */  sb         $v0, 0x140($s2)
    /* 80428 8008FC28 0180023C */  lui        $v0, %hi(D_800138BC)
    /* 8042C 8008FC2C BC384224 */  addiu      $v0, $v0, %lo(D_800138BC)
    /* 80430 8008FC30 AC0042AE */  sw         $v0, 0xAC($s2)
    /* 80434 8008FC34 340140AE */  sw         $zero, 0x134($s2)
    /* 80438 8008FC38 440140AE */  sw         $zero, 0x144($s2)
    /* 8043C 8008FC3C 9AE0030C */  jal        func_800F8268
    /* 80440 8008FC40 48014426 */   addiu     $a0, $s2, 0x148
    /* 80444 8008FC44 9AE0030C */  jal        func_800F8268
    /* 80448 8008FC48 74014426 */   addiu     $a0, $s2, 0x174
    /* 8044C 8008FC4C 9AE0030C */  jal        func_800F8268
    /* 80450 8008FC50 A0014426 */   addiu     $a0, $s2, 0x1A0
    /* 80454 8008FC54 9AE0030C */  jal        func_800F8268
    /* 80458 8008FC58 CC014426 */   addiu     $a0, $s2, 0x1CC
    /* 8045C 8008FC5C F80140AE */  sw         $zero, 0x1F8($s2)
    /* 80460 8008FC60 FC015126 */  addiu      $s1, $s2, 0x1FC
    /* 80464 8008FC64 3B001024 */  addiu      $s0, $zero, 0x3B
    /* 80468 8008FC68 FFFF1324 */  addiu      $s3, $zero, -0x1
  .L8008FC6C:
    /* 8046C 8008FC6C FCEC030C */  jal        func_800FB3F0
    /* 80470 8008FC70 21202002 */   addu      $a0, $s1, $zero
    /* 80474 8008FC74 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 80478 8008FC78 FCFF1316 */  bne        $s0, $s3, .L8008FC6C
    /* 8047C 8008FC7C 94003126 */   addiu     $s1, $s1, 0x94
    /* 80480 8008FC80 9C255126 */  addiu      $s1, $s2, 0x259C
    /* 80484 8008FC84 03001024 */  addiu      $s0, $zero, 0x3
    /* 80488 8008FC88 FFFF1324 */  addiu      $s3, $zero, -0x1
  .L8008FC8C:
    /* 8048C 8008FC8C FCEC030C */  jal        func_800FB3F0
    /* 80490 8008FC90 21202002 */   addu      $a0, $s1, $zero
    /* 80494 8008FC94 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 80498 8008FC98 FCFF1316 */  bne        $s0, $s3, .L8008FC8C
    /* 8049C 8008FC9C 94003126 */   addiu     $s1, $s1, 0x94
    /* 804A0 8008FCA0 EC275126 */  addiu      $s1, $s2, 0x27EC
    /* 804A4 8008FCA4 03001024 */  addiu      $s0, $zero, 0x3
    /* 804A8 8008FCA8 FFFF1324 */  addiu      $s3, $zero, -0x1
  .L8008FCAC:
    /* 804AC 8008FCAC FCEC030C */  jal        func_800FB3F0
    /* 804B0 8008FCB0 21202002 */   addu      $a0, $s1, $zero
    /* 804B4 8008FCB4 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 804B8 8008FCB8 FCFF1316 */  bne        $s0, $s3, .L8008FCAC
    /* 804BC 8008FCBC 94003126 */   addiu     $s1, $s1, 0x94
    /* 804C0 8008FCC0 3C2A5126 */  addiu      $s1, $s2, 0x2A3C
    /* 804C4 8008FCC4 03001024 */  addiu      $s0, $zero, 0x3
    /* 804C8 8008FCC8 FFFF1324 */  addiu      $s3, $zero, -0x1
  .L8008FCCC:
    /* 804CC 8008FCCC FCEC030C */  jal        func_800FB3F0
    /* 804D0 8008FCD0 21202002 */   addu      $a0, $s1, $zero
    /* 804D4 8008FCD4 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 804D8 8008FCD8 FCFF1316 */  bne        $s0, $s3, .L8008FCCC
    /* 804DC 8008FCDC 94003126 */   addiu     $s1, $s1, 0x94
    /* 804E0 8008FCE0 8C2C5126 */  addiu      $s1, $s2, 0x2C8C
    /* 804E4 8008FCE4 03001024 */  addiu      $s0, $zero, 0x3
    /* 804E8 8008FCE8 FFFF1324 */  addiu      $s3, $zero, -0x1
  .L8008FCEC:
    /* 804EC 8008FCEC FCEC030C */  jal        func_800FB3F0
    /* 804F0 8008FCF0 21202002 */   addu      $a0, $s1, $zero
    /* 804F4 8008FCF4 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 804F8 8008FCF8 FCFF1316 */  bne        $s0, $s3, .L8008FCEC
    /* 804FC 8008FCFC 94003126 */   addiu     $s1, $s1, 0x94
    /* 80500 8008FD00 9AE0030C */  jal        func_800F8268
    /* 80504 8008FD04 DC2E4426 */   addiu     $a0, $s2, 0x2EDC
    /* 80508 8008FD08 1680043C */  lui        $a0, %hi(D_801594DC)
    /* 8050C 8008FD0C DC948424 */  addiu      $a0, $a0, %lo(D_801594DC)
    /* 80510 8008FD10 221B040C */  jal        func_80106C88
    /* 80514 8008FD14 00000000 */   nop
    /* 80518 8008FD18 08108287 */  lh         $v0, %gp_rel(D_801594E0)($gp)
    /* 8051C 8008FD1C 80020324 */  addiu      $v1, $zero, 0x280
    /* 80520 8008FD20 23186200 */  subu       $v1, $v1, $v0
    /* 80524 8008FD24 C2170300 */  srl        $v0, $v1, 31
    /* 80528 8008FD28 21186200 */  addu       $v1, $v1, $v0
    /* 8052C 8008FD2C 43180300 */  sra        $v1, $v1, 1
    /* 80530 8008FD30 500383A7 */  sh         $v1, %gp_rel(D_80158828)($gp)
    /* 80534 8008FD34 0180043C */  lui        $a0, %hi(D_800113CC)
    /* 80538 8008FD38 CC138424 */  addiu      $a0, $a0, %lo(D_800113CC)
    /* 8053C 8008FD3C 1C2F4526 */  addiu      $a1, $s2, 0x2F1C
    /* 80540 8008FD40 7AE0030C */  jal        func_800F81E8
    /* 80544 8008FD44 BA000624 */   addiu     $a2, $zero, 0xBA
    /* 80548 8008FD48 0180043C */  lui        $a0, %hi(D_80011488)
    /* 8054C 8008FD4C 88148424 */  addiu      $a0, $a0, %lo(D_80011488)
    /* 80550 8008FD50 D62F4526 */  addiu      $a1, $s2, 0x2FD6
    /* 80554 8008FD54 7AE0030C */  jal        func_800F81E8
    /* 80558 8008FD58 90000624 */   addiu     $a2, $zero, 0x90
    /* 8055C 8008FD5C 540392AF */  sw         $s2, %gp_rel(D_8015882C)($gp)
    /* 80560 8008FD60 21180000 */  addu       $v1, $zero, $zero
    /* 80564 8008FD64 80100300 */  sll        $v0, $v1, 2
  .L8008FD68:
    /* 80568 8008FD68 21105200 */  addu       $v0, $v0, $s2
    /* 8056C 8008FD6C AC2440AC */  sw         $zero, 0x24AC($v0)
    /* 80570 8008FD70 01006324 */  addiu      $v1, $v1, 0x1
    /* 80574 8008FD74 3C006228 */  slti       $v0, $v1, 0x3C
    /* 80578 8008FD78 FBFF4014 */  bnez       $v0, .L8008FD68
    /* 8057C 8008FD7C 80100300 */   sll       $v0, $v1, 2
    /* 80580 8008FD80 743040A6 */  sh         $zero, 0x3074($s2)
    /* 80584 8008FD84 763040A6 */  sh         $zero, 0x3076($s2)
    /* 80588 8008FD88 08108297 */  lhu        $v0, %gp_rel(D_801594E0)($gp)
    /* 8058C 8008FD8C 00000000 */  nop
    /* 80590 8008FD90 783042A6 */  sh         $v0, 0x3078($s2)
    /* 80594 8008FD94 28000224 */  addiu      $v0, $zero, 0x28
    /* 80598 8008FD98 7A3042A6 */  sh         $v0, 0x307A($s2)
    /* 8059C 8008FD9C 21104002 */  addu       $v0, $s2, $zero
    /* 805A0 8008FDA0 2000BF8F */  lw         $ra, 0x20($sp)
    /* 805A4 8008FDA4 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 805A8 8008FDA8 1800B28F */  lw         $s2, 0x18($sp)
    /* 805AC 8008FDAC 1400B18F */  lw         $s1, 0x14($sp)
    /* 805B0 8008FDB0 1000B08F */  lw         $s0, 0x10($sp)
    /* 805B4 8008FDB4 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 805B8 8008FDB8 0800E003 */  jr         $ra
    /* 805BC 8008FDBC 00000000 */   nop
endlabel func_8008FADC
