.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80011E40

dlabel D_80011E40
    /* 2640 80011E40 */ .asciz "Sound Test Mode"
    /* 536F756E642054657374204D6F646500 */
.align 2
enddlabel D_80011E40


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800A82A4, 0x100

glabel func_800A82A4
    /* 98AA4 800A82A4 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 98AA8 800A82A8 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* 98AAC 800A82AC 2800B0AF */  sw         $s0, 0x28($sp)
    /* 98AB0 800A82B0 10000224 */  addiu      $v0, $zero, 0x10
    /* 98AB4 800A82B4 1A000324 */  addiu      $v1, $zero, 0x1A
    /* 98AB8 800A82B8 2000A2A7 */  sh         $v0, 0x20($sp)
    /* 98ABC 800A82BC 2200A3A7 */  sh         $v1, 0x22($sp)
    /* 98AC0 800A82C0 30010224 */  addiu      $v0, $zero, 0x130
    /* 98AC4 800A82C4 2400A2A7 */  sh         $v0, 0x24($sp)
    /* 98AC8 800A82C8 E2000224 */  addiu      $v0, $zero, 0xE2
    /* 98ACC 800A82CC 2600A2A7 */  sh         $v0, 0x26($sp)
    /* 98AD0 800A82D0 1000A0AF */  sw         $zero, 0x10($sp)
    /* 98AD4 800A82D4 2000A427 */  addiu      $a0, $sp, 0x20
    /* 98AD8 800A82D8 21280000 */  addu       $a1, $zero, $zero
    /* 98ADC 800A82DC 78000624 */  addiu      $a2, $zero, 0x78
    /* 98AE0 800A82E0 7D1C040C */  jal        func_801071F4
    /* 98AE4 800A82E4 E8030724 */   addiu     $a3, $zero, 0x3E8
    /* 98AE8 800A82E8 B31E040C */  jal        func_80107ACC
    /* 98AEC 800A82EC 00000000 */   nop
    /* 98AF0 800A82F0 20010224 */  addiu      $v0, $zero, 0x120
    /* 98AF4 800A82F4 1000A2AF */  sw         $v0, 0x10($sp)
    /* 98AF8 800A82F8 C8000224 */  addiu      $v0, $zero, 0xC8
    /* 98AFC 800A82FC 1400A2AF */  sw         $v0, 0x14($sp)
    /* 98B00 800A8300 1800A0AF */  sw         $zero, 0x18($sp)
    /* 98B04 800A8304 0180043C */  lui        $a0, %hi(D_80011E40)
    /* 98B08 800A8308 401E8424 */  addiu      $a0, $a0, %lo(D_80011E40)
    /* 98B0C 800A830C 21280000 */  addu       $a1, $zero, $zero
    /* 98B10 800A8310 10000624 */  addiu      $a2, $zero, 0x10
    /* 98B14 800A8314 A019040C */  jal        func_80106680
    /* 98B18 800A8318 1A000724 */   addiu     $a3, $zero, 0x1A
    /* 98B1C 800A831C 21804000 */  addu       $s0, $v0, $zero
    /* 98B20 800A8320 1B000012 */  beqz       $s0, .L800A8390
    /* 98B24 800A8324 00000000 */   nop
    /* 98B28 800A8328 0400048E */  lw         $a0, 0x4($s0)
    /* 98B2C 800A832C 0A80063C */  lui        $a2, %hi(func_800A7F58)
    /* 98B30 800A8330 587FC624 */  addiu      $a2, $a2, %lo(func_800A7F58)
    /* 98B34 800A8334 161C040C */  jal        func_80107058
    /* 98B38 800A8338 FCFF0524 */   addiu     $a1, $zero, -0x4
    /* 98B3C 800A833C 01000224 */  addiu      $v0, $zero, 0x1
    /* 98B40 800A8340 1680013C */  lui        $at, %hi(D_80158608)
    /* 98B44 800A8344 088622AC */  sw         $v0, %lo(D_80158608)($at)
    /* 98B48 800A8348 540880AF */  sw         $zero, %gp_rel(D_80158D2C)($gp)
  .L800A834C:
    /* 98B4C 800A834C 1680023C */  lui        $v0, %hi(D_80158608)
    /* 98B50 800A8350 0886428C */  lw         $v0, %lo(D_80158608)($v0)
    /* 98B54 800A8354 00000000 */  nop
    /* 98B58 800A8358 05004018 */  blez       $v0, .L800A8370
    /* 98B5C 800A835C 00000000 */   nop
    /* 98B60 800A8360 1E12040C */  jal        func_80104878
    /* 98B64 800A8364 00000000 */   nop
    /* 98B68 800A8368 D3A00208 */  j          .L800A834C
    /* 98B6C 800A836C 00000000 */   nop
  .L800A8370:
    /* 98B70 800A8370 101A040C */  jal        func_80106840
    /* 98B74 800A8374 21200002 */   addu      $a0, $s0, $zero
    /* 98B78 800A8378 1000A0AF */  sw         $zero, 0x10($sp)
    /* 98B7C 800A837C 2000A427 */  addiu      $a0, $sp, 0x20
    /* 98B80 800A8380 21280000 */  addu       $a1, $zero, $zero
    /* 98B84 800A8384 78000624 */  addiu      $a2, $zero, 0x78
    /* 98B88 800A8388 011D040C */  jal        func_80107404
    /* 98B8C 800A838C E8030724 */   addiu     $a3, $zero, 0x3E8
  .L800A8390:
    /* 98B90 800A8390 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* 98B94 800A8394 2800B08F */  lw         $s0, 0x28($sp)
    /* 98B98 800A8398 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 98B9C 800A839C 0800E003 */  jr         $ra
    /* 98BA0 800A83A0 00000000 */   nop
endlabel func_800A82A4
