.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_800108E8

dlabel D_800108E8
    /* 10E8 800108E8 */ .asciz "^^Saving..."
    /* 5E5E536176696E672E2E2E00 */
.align 2
enddlabel D_800108E8


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8006C4F8, 0x9CC

glabel func_8006C4F8
    /* 5CCF8 8006C4F8 08FDBD27 */  addiu      $sp, $sp, -0x2F8
    /* 5CCFC 8006C4FC F402BFAF */  sw         $ra, 0x2F4($sp)
    /* 5CD00 8006C500 F002BEAF */  sw         $fp, 0x2F0($sp)
    /* 5CD04 8006C504 EC02B7AF */  sw         $s7, 0x2EC($sp)
    /* 5CD08 8006C508 E802B6AF */  sw         $s6, 0x2E8($sp)
    /* 5CD0C 8006C50C E402B5AF */  sw         $s5, 0x2E4($sp)
    /* 5CD10 8006C510 E002B4AF */  sw         $s4, 0x2E0($sp)
    /* 5CD14 8006C514 DC02B3AF */  sw         $s3, 0x2DC($sp)
    /* 5CD18 8006C518 D802B2AF */  sw         $s2, 0x2D8($sp)
    /* 5CD1C 8006C51C D402B1AF */  sw         $s1, 0x2D4($sp)
    /* 5CD20 8006C520 D002B0AF */  sw         $s0, 0x2D0($sp)
    /* 5CD24 8006C524 21F08000 */  addu       $fp, $a0, $zero
    /* 5CD28 8006C528 C002A5AF */  sw         $a1, 0x2C0($sp)
    /* 5CD2C 8006C52C 21B8C000 */  addu       $s7, $a2, $zero
    /* 5CD30 8006C530 01000824 */  addiu      $t0, $zero, 0x1
    /* 5CD34 8006C534 C802A8AF */  sw         $t0, 0x2C8($sp)
    /* 5CD38 8006C538 1800A427 */  addiu      $a0, $sp, 0x18
    /* 5CD3C 8006C53C ADC5020C */  jal        func_800B16B4
    /* 5CD40 8006C540 00200524 */   addiu     $a1, $zero, 0x2000
    /* 5CD44 8006C544 03000224 */  addiu      $v0, $zero, 0x3
    /* 5CD48 8006C548 4D0282A3 */  sb         $v0, %gp_rel(D_80158725)($gp)
    /* 5CD4C 8006C54C 1800B027 */  addiu      $s0, $sp, 0x18
    /* 5CD50 8006C550 08000224 */  addiu      $v0, $zero, 0x8
    /* 5CD54 8006C554 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5CD58 8006C558 21200002 */  addu       $a0, $s0, $zero
    /* 5CD5C 8006C55C 21280000 */  addu       $a1, $zero, $zero
    /* 5CD60 8006C560 21300000 */  addu       $a2, $zero, $zero
    /* 5CD64 8006C564 1EC7020C */  jal        func_800B1C78
    /* 5CD68 8006C568 21380000 */   addu      $a3, $zero, $zero
    /* 5CD6C 8006C56C 21200002 */  addu       $a0, $s0, $zero
    /* 5CD70 8006C570 F8FF0524 */  addiu      $a1, $zero, -0x8
    /* 5CD74 8006C574 5AC8020C */  jal        func_800B2168
    /* 5CD78 8006C578 F8FF0624 */   addiu     $a2, $zero, -0x8
    /* 5CD7C 8006C57C 1680053C */  lui        $a1, %hi(D_801586B8)
    /* 5CD80 8006C580 B886A524 */  addiu      $a1, $a1, %lo(D_801586B8)
    /* 5CD84 8006C584 1CC8020C */  jal        func_800B2070
    /* 5CD88 8006C588 21200002 */   addu      $a0, $s0, $zero
    /* 5CD8C 8006C58C 21200002 */  addu       $a0, $s0, $zero
    /* 5CD90 8006C590 39C8020C */  jal        func_800B20E4
    /* 5CD94 8006C594 10010524 */   addiu     $a1, $zero, 0x110
    /* 5CD98 8006C598 21200002 */  addu       $a0, $s0, $zero
    /* 5CD9C 8006C59C 88E2020C */  jal        func_800B8A20
    /* 5CDA0 8006C5A0 28000524 */   addiu     $a1, $zero, 0x28
    /* 5CDA4 8006C5A4 1680053C */  lui        $a1, %hi(D_801586C0)
    /* 5CDA8 8006C5A8 C086A524 */  addiu      $a1, $a1, %lo(D_801586C0)
    /* 5CDAC 8006C5AC 69C7020C */  jal        func_800B1DA4
    /* 5CDB0 8006C5B0 21200002 */   addu      $a0, $s0, $zero
    /* 5CDB4 8006C5B4 0180053C */  lui        $a1, %hi(D_800108E8)
    /* 5CDB8 8006C5B8 E808A524 */  addiu      $a1, $a1, %lo(D_800108E8)
    /* 5CDBC 8006C5BC 69C7020C */  jal        func_800B1DA4
    /* 5CDC0 8006C5C0 21200002 */   addu      $a0, $s0, $zero
    /* 5CDC4 8006C5C4 0180053C */  lui        $a1, %hi(D_800108F4)
    /* 5CDC8 8006C5C8 F408A524 */  addiu      $a1, $a1, %lo(D_800108F4)
    /* 5CDCC 8006C5CC 69C7020C */  jal        func_800B1DA4
    /* 5CDD0 8006C5D0 21200002 */   addu      $a0, $s0, $zero
    /* 5CDD4 8006C5D4 1680053C */  lui        $a1, %hi(D_801586C0)
    /* 5CDD8 8006C5D8 C086A524 */  addiu      $a1, $a1, %lo(D_801586C0)
    /* 5CDDC 8006C5DC 69C7020C */  jal        func_800B1DA4
    /* 5CDE0 8006C5E0 21200002 */   addu      $a0, $s0, $zero
    /* 5CDE4 8006C5E4 21200002 */  addu       $a0, $s0, $zero
    /* 5CDE8 8006C5E8 52DF020C */  jal        func_800B7D48
    /* 5CDEC 8006C5EC 21280000 */   addu      $a1, $zero, $zero
    /* 5CDF0 8006C5F0 94E2020C */  jal        func_800B8A50
    /* 5CDF4 8006C5F4 21200002 */   addu      $a0, $s0, $zero
    /* 5CDF8 8006C5F8 2120C003 */  addu       $a0, $fp, $zero
    /* 5CDFC 8006C5FC 0ABE010C */  jal        func_8006F828
    /* 5CE00 8006C600 01000524 */   addiu     $a1, $zero, 0x1
    /* 5CE04 8006C604 00140200 */  sll        $v0, $v0, 16
    /* 5CE08 8006C608 06004104 */  bgez       $v0, .L8006C624
    /* 5CE0C 8006C60C 0100043C */   lui       $a0, (0x1C800 >> 16)
    /* 5CE10 8006C610 21200002 */  addu       $a0, $s0, $zero
    /* 5CE14 8006C614 0AC7020C */  jal        func_800B1C28
    /* 5CE18 8006C618 02000524 */   addiu     $a1, $zero, 0x2
    /* 5CE1C 8006C61C A4B30108 */  j          .L8006CE90
    /* 5CE20 8006C620 01000224 */   addiu     $v0, $zero, 0x1
  .L8006C624:
    /* 5CE24 8006C624 FED4030C */  jal        func_800F53F8
    /* 5CE28 8006C628 00C88434 */   ori       $a0, $a0, (0x1C800 & 0xFFFF)
    /* 5CE2C 8006C62C 21A84000 */  addu       $s5, $v0, $zero
    /* 5CE30 8006C630 7CD6030C */  jal        func_800F59F0
    /* 5CE34 8006C634 2120A002 */   addu      $a0, $s5, $zero
    /* 5CE38 8006C638 21B04000 */  addu       $s6, $v0, $zero
    /* 5CE3C 8006C63C 0100043C */  lui        $a0, (0x14000 >> 16)
    /* 5CE40 8006C640 00408434 */  ori        $a0, $a0, (0x14000 & 0xFFFF)
    /* 5CE44 8006C644 0281030C */  jal        func_800E0408
    /* 5CE48 8006C648 2120C402 */   addu      $a0, $s6, $a0
    /* 5CE4C 8006C64C 0003C426 */  addiu      $a0, $s6, 0x300
    /* 5CE50 8006C650 69C1010C */  jal        func_800705A4
    /* 5CE54 8006C654 01000524 */   addiu     $a1, $zero, 0x1
    /* 5CE58 8006C658 21984000 */  addu       $s3, $v0, $zero
    /* 5CE5C 8006C65C 1280103C */  lui        $s0, %hi(D_8011A26E)
    /* 5CE60 8006C660 6EA21026 */  addiu      $s0, $s0, %lo(D_8011A26E)
    /* 5CE64 8006C664 1280023C */  lui        $v0, %hi(D_8011ACB4)
    /* 5CE68 8006C668 B4AC4290 */  lbu        $v0, %lo(D_8011ACB4)($v0)
    /* 5CE6C 8006C66C 00000000 */  nop
    /* 5CE70 8006C670 000002A2 */  sb         $v0, 0x0($s0)
    /* 5CE74 8006C674 27000224 */  addiu      $v0, $zero, 0x27
    /* 5CE78 8006C678 B802A2AF */  sw         $v0, 0x2B8($sp)
    /* 5CE7C 8006C67C B802A427 */  addiu      $a0, $sp, 0x2B8
    /* 5CE80 8006C680 04000524 */  addiu      $a1, $zero, 0x4
    /* 5CE84 8006C684 01000624 */  addiu      $a2, $zero, 0x1
    /* 5CE88 8006C688 80C1010C */  jal        func_80070600
    /* 5CE8C 8006C68C 21386002 */   addu      $a3, $s3, $zero
    /* 5CE90 8006C690 FC014010 */  beqz       $v0, .L8006CE84
    /* 5CE94 8006C694 1800A427 */   addiu     $a0, $sp, 0x18
    /* 5CE98 8006C698 5000E012 */  beqz       $s7, .L8006C7DC
    /* 5CE9C 8006C69C 01001224 */   addiu     $s2, $zero, 0x1
    /* 5CEA0 8006C6A0 ECFF0296 */  lhu        $v0, -0x14($s0)
    /* 5CEA4 8006C6A4 00000000 */  nop
    /* 5CEA8 8006C6A8 40004234 */  ori        $v0, $v0, 0x40
    /* 5CEAC 8006C6AC ECFF02A6 */  sh         $v0, -0x14($s0)
    /* 5CEB0 8006C6B0 21800000 */  addu       $s0, $zero, $zero
  .L8006C6B4:
    /* 5CEB4 8006C6B4 1280013C */  lui        $at, %hi(D_8011A2E5)
    /* 5CEB8 8006C6B8 21083000 */  addu       $at, $at, $s0
    /* 5CEBC 8006C6BC E5A220A0 */  sb         $zero, %lo(D_8011A2E5)($at)
    /* 5CEC0 8006C6C0 01001124 */  addiu      $s1, $zero, 0x1
    /* 5CEC4 8006C6C4 21202002 */  addu       $a0, $s1, $zero
  .L8006C6C8:
    /* 5CEC8 8006C6C8 8ACA010C */  jal        func_80072A28
    /* 5CECC 8006C6CC 21280002 */   addu      $a1, $s0, $zero
    /* 5CED0 8006C6D0 09004010 */  beqz       $v0, .L8006C6F8
    /* 5CED4 8006C6D4 04183202 */   sllv      $v1, $s2, $s1
    /* 5CED8 8006C6D8 1280013C */  lui        $at, %hi(D_8011A2E5)
    /* 5CEDC 8006C6DC 21083000 */  addu       $at, $at, $s0
    /* 5CEE0 8006C6E0 E5A22290 */  lbu        $v0, %lo(D_8011A2E5)($at)
    /* 5CEE4 8006C6E4 00000000 */  nop
    /* 5CEE8 8006C6E8 25104300 */  or         $v0, $v0, $v1
    /* 5CEEC 8006C6EC 1280013C */  lui        $at, %hi(D_8011A2E5)
    /* 5CEF0 8006C6F0 21083000 */  addu       $at, $at, $s0
    /* 5CEF4 8006C6F4 E5A222A0 */  sb         $v0, %lo(D_8011A2E5)($at)
  .L8006C6F8:
    /* 5CEF8 8006C6F8 01003126 */  addiu      $s1, $s1, 0x1
    /* 5CEFC 8006C6FC 0800222A */  slti       $v0, $s1, 0x8
    /* 5CF00 8006C700 F1FF4014 */  bnez       $v0, .L8006C6C8
    /* 5CF04 8006C704 21202002 */   addu      $a0, $s1, $zero
    /* 5CF08 8006C708 1280013C */  lui        $at, %hi(D_8011A2E5)
    /* 5CF0C 8006C70C 21083000 */  addu       $at, $at, $s0
    /* 5CF10 8006C710 E5A22480 */  lb         $a0, %lo(D_8011A2E5)($at)
    /* 5CF14 8006C714 00000000 */  nop
    /* 5CF18 8006C718 17008010 */  beqz       $a0, .L8006C778
    /* 5CF1C 8006C71C 00000000 */   nop
    /* 5CF20 8006C720 0B3B030C */  jal        func_800CEC2C
    /* 5CF24 8006C724 00000000 */   nop
    /* 5CF28 8006C728 06005210 */  beq        $v0, $s2, .L8006C744
    /* 5CF2C 8006C72C 08000224 */   addiu     $v0, $zero, 0x8
    /* 5CF30 8006C730 1280013C */  lui        $at, %hi(D_8011A288)
    /* 5CF34 8006C734 21083000 */  addu       $at, $at, $s0
    /* 5CF38 8006C738 88A222A0 */  sb         $v0, %lo(D_8011A288)($at)
    /* 5CF3C 8006C73C DFB10108 */  j          .L8006C77C
    /* 5CF40 8006C740 01001026 */   addiu     $s0, $s0, 0x1
  .L8006C744:
    /* 5CF44 8006C744 01001124 */  addiu      $s1, $zero, 0x1
    /* 5CF48 8006C748 21202002 */  addu       $a0, $s1, $zero
  .L8006C74C:
    /* 5CF4C 8006C74C 8ACA010C */  jal        func_80072A28
    /* 5CF50 8006C750 21280002 */   addu      $a1, $s0, $zero
    /* 5CF54 8006C754 04004010 */  beqz       $v0, .L8006C768
    /* 5CF58 8006C758 00000000 */   nop
    /* 5CF5C 8006C75C 1280013C */  lui        $at, %hi(D_8011A288)
    /* 5CF60 8006C760 21083000 */  addu       $at, $at, $s0
    /* 5CF64 8006C764 88A231A0 */  sb         $s1, %lo(D_8011A288)($at)
  .L8006C768:
    /* 5CF68 8006C768 01003126 */  addiu      $s1, $s1, 0x1
    /* 5CF6C 8006C76C 0800222A */  slti       $v0, $s1, 0x8
    /* 5CF70 8006C770 F6FF4014 */  bnez       $v0, .L8006C74C
    /* 5CF74 8006C774 21202002 */   addu      $a0, $s1, $zero
  .L8006C778:
    /* 5CF78 8006C778 01001026 */  addiu      $s0, $s0, 0x1
  .L8006C77C:
    /* 5CF7C 8006C77C 5D00022A */  slti       $v0, $s0, 0x5D
    /* 5CF80 8006C780 CCFF4014 */  bnez       $v0, .L8006C6B4
    /* 5CF84 8006C784 01001124 */   addiu     $s1, $zero, 0x1
    /* 5CF88 8006C788 40101100 */  sll        $v0, $s1, 1
  .L8006C78C:
    /* 5CF8C 8006C78C 21105100 */  addu       $v0, $v0, $s1
    /* 5CF90 8006C790 80100200 */  sll        $v0, $v0, 2
    /* 5CF94 8006C794 23105100 */  subu       $v0, $v0, $s1
    /* 5CF98 8006C798 00110200 */  sll        $v0, $v0, 4
    /* 5CF9C 8006C79C 23105100 */  subu       $v0, $v0, $s1
    /* 5CFA0 8006C7A0 C0100200 */  sll        $v0, $v0, 3
    /* 5CFA4 8006C7A4 1180013C */  lui        $at, %hi(D_80117690)
    /* 5CFA8 8006C7A8 21082200 */  addu       $at, $at, $v0
    /* 5CFAC 8006C7AC 90762394 */  lhu        $v1, %lo(D_80117690)($at)
    /* 5CFB0 8006C7B0 00000000 */  nop
    /* 5CFB4 8006C7B4 96FF6330 */  andi       $v1, $v1, 0xFF96
    /* 5CFB8 8006C7B8 1180013C */  lui        $at, %hi(D_80117690)
    /* 5CFBC 8006C7BC 21082200 */  addu       $at, $at, $v0
    /* 5CFC0 8006C7C0 907623A4 */  sh         $v1, %lo(D_80117690)($at)
    /* 5CFC4 8006C7C4 01003126 */  addiu      $s1, $s1, 0x1
    /* 5CFC8 8006C7C8 0800222A */  slti       $v0, $s1, 0x8
    /* 5CFCC 8006C7CC EFFF4014 */  bnez       $v0, .L8006C78C
    /* 5CFD0 8006C7D0 40101100 */   sll       $v0, $s1, 1
    /* 5CFD4 8006C7D4 FDB10108 */  j          .L8006C7F4
    /* 5CFD8 8006C7D8 00000000 */   nop
  .L8006C7DC:
    /* 5CFDC 8006C7DC 1280033C */  lui        $v1, %hi(D_8011A25A)
    /* 5CFE0 8006C7E0 5AA26324 */  addiu      $v1, $v1, %lo(D_8011A25A)
    /* 5CFE4 8006C7E4 00006294 */  lhu        $v0, 0x0($v1)
    /* 5CFE8 8006C7E8 00000000 */  nop
    /* 5CFEC 8006C7EC BFFF4230 */  andi       $v0, $v0, 0xFFBF
    /* 5CFF0 8006C7F0 000062A4 */  sh         $v0, 0x0($v1)
  .L8006C7F4:
    /* 5CFF4 8006C7F4 0700E016 */  bnez       $s7, .L8006C814
    /* 5CFF8 8006C7F8 01001124 */   addiu     $s1, $zero, 0x1
    /* 5CFFC 8006C7FC 1280023C */  lui        $v0, %hi(D_8011A25A)
    /* 5D000 8006C800 5AA24294 */  lhu        $v0, %lo(D_8011A25A)($v0)
    /* 5D004 8006C804 00000000 */  nop
    /* 5D008 8006C808 80004230 */  andi       $v0, $v0, 0x80
    /* 5D00C 8006C80C 83004010 */  beqz       $v0, .L8006CA1C
    /* 5D010 8006C810 00000000 */   nop
  .L8006C814:
    /* 5D014 8006C814 40101100 */  sll        $v0, $s1, 1
  .L8006C818:
    /* 5D018 8006C818 21105100 */  addu       $v0, $v0, $s1
    /* 5D01C 8006C81C 80100200 */  sll        $v0, $v0, 2
    /* 5D020 8006C820 23105100 */  subu       $v0, $v0, $s1
    /* 5D024 8006C824 00110200 */  sll        $v0, $v0, 4
    /* 5D028 8006C828 23105100 */  subu       $v0, $v0, $s1
    /* 5D02C 8006C82C C0900200 */  sll        $s2, $v0, 3
    /* 5D030 8006C830 1180013C */  lui        $at, %hi(D_80117698)
    /* 5D034 8006C834 21083200 */  addu       $at, $at, $s2
    /* 5D038 8006C838 98762384 */  lh         $v1, %lo(D_80117698)($at)
    /* 5D03C 8006C83C 00000000 */  nop
    /* 5D040 8006C840 40100300 */  sll        $v0, $v1, 1
    /* 5D044 8006C844 21104300 */  addu       $v0, $v0, $v1
    /* 5D048 8006C848 00110200 */  sll        $v0, $v0, 4
    /* 5D04C 8006C84C 1180013C */  lui        $at, %hi(D_80116ADE)
    /* 5D050 8006C850 21082200 */  addu       $at, $at, $v0
    /* 5D054 8006C854 DE6A2284 */  lh         $v0, %lo(D_80116ADE)($at)
    /* 5D058 8006C858 00000000 */  nop
    /* 5D05C 8006C85C 18004004 */  bltz       $v0, .L8006C8C0
    /* 5D060 8006C860 40101100 */   sll       $v0, $s1, 1
    /* 5D064 8006C864 00811100 */  sll        $s0, $s1, 4
    /* 5D068 8006C868 23801102 */  subu       $s0, $s0, $s1
    /* 5D06C 8006C86C C0801000 */  sll        $s0, $s0, 3
    /* 5D070 8006C870 21801102 */  addu       $s0, $s0, $s1
    /* 5D074 8006C874 40801000 */  sll        $s0, $s0, 1
    /* 5D078 8006C878 1180023C */  lui        $v0, %hi(D_80116EF2)
    /* 5D07C 8006C87C F26E4224 */  addiu      $v0, $v0, %lo(D_80116EF2)
    /* 5D080 8006C880 21800202 */  addu       $s0, $s0, $v0
    /* 5D084 8006C884 CB1A030C */  jal        func_800C6B2C
    /* 5D088 8006C888 21200002 */   addu      $a0, $s0, $zero
    /* 5D08C 8006C88C 1180013C */  lui        $at, %hi(D_80117698)
    /* 5D090 8006C890 21083200 */  addu       $at, $at, $s2
    /* 5D094 8006C894 98762384 */  lh         $v1, %lo(D_80117698)($at)
    /* 5D098 8006C898 00000000 */  nop
    /* 5D09C 8006C89C 40100300 */  sll        $v0, $v1, 1
    /* 5D0A0 8006C8A0 21104300 */  addu       $v0, $v0, $v1
    /* 5D0A4 8006C8A4 00110200 */  sll        $v0, $v0, 4
    /* 5D0A8 8006C8A8 1180013C */  lui        $at, %hi(D_80116ADE)
    /* 5D0AC 8006C8AC 21082200 */  addu       $at, $at, $v0
    /* 5D0B0 8006C8B0 DE6A2584 */  lh         $a1, %lo(D_80116ADE)($at)
    /* 5D0B4 8006C8B4 651B030C */  jal        func_800C6D94
    /* 5D0B8 8006C8B8 21200002 */   addu      $a0, $s0, $zero
    /* 5D0BC 8006C8BC 40101100 */  sll        $v0, $s1, 1
  .L8006C8C0:
    /* 5D0C0 8006C8C0 21105100 */  addu       $v0, $v0, $s1
    /* 5D0C4 8006C8C4 80100200 */  sll        $v0, $v0, 2
    /* 5D0C8 8006C8C8 23105100 */  subu       $v0, $v0, $s1
    /* 5D0CC 8006C8CC 00110200 */  sll        $v0, $v0, 4
    /* 5D0D0 8006C8D0 23105100 */  subu       $v0, $v0, $s1
    /* 5D0D4 8006C8D4 C0900200 */  sll        $s2, $v0, 3
    /* 5D0D8 8006C8D8 1180013C */  lui        $at, %hi(D_80117698)
    /* 5D0DC 8006C8DC 21083200 */  addu       $at, $at, $s2
    /* 5D0E0 8006C8E0 98762384 */  lh         $v1, %lo(D_80117698)($at)
    /* 5D0E4 8006C8E4 00000000 */  nop
    /* 5D0E8 8006C8E8 40100300 */  sll        $v0, $v1, 1
    /* 5D0EC 8006C8EC 21104300 */  addu       $v0, $v0, $v1
    /* 5D0F0 8006C8F0 00110200 */  sll        $v0, $v0, 4
    /* 5D0F4 8006C8F4 1180013C */  lui        $at, %hi(D_80116ADC)
    /* 5D0F8 8006C8F8 21082200 */  addu       $at, $at, $v0
    /* 5D0FC 8006C8FC DC6A2284 */  lh         $v0, %lo(D_80116ADC)($at)
    /* 5D100 8006C900 00000000 */  nop
    /* 5D104 8006C904 18004004 */  bltz       $v0, .L8006C968
    /* 5D108 8006C908 40101100 */   sll       $v0, $s1, 1
    /* 5D10C 8006C90C 00811100 */  sll        $s0, $s1, 4
    /* 5D110 8006C910 23801102 */  subu       $s0, $s0, $s1
    /* 5D114 8006C914 C0801000 */  sll        $s0, $s0, 3
    /* 5D118 8006C918 21801102 */  addu       $s0, $s0, $s1
    /* 5D11C 8006C91C 40801000 */  sll        $s0, $s0, 1
    /* 5D120 8006C920 1180023C */  lui        $v0, %hi(D_80116EDA)
    /* 5D124 8006C924 DA6E4224 */  addiu      $v0, $v0, %lo(D_80116EDA)
    /* 5D128 8006C928 21800202 */  addu       $s0, $s0, $v0
    /* 5D12C 8006C92C CB1A030C */  jal        func_800C6B2C
    /* 5D130 8006C930 21200002 */   addu      $a0, $s0, $zero
    /* 5D134 8006C934 1180013C */  lui        $at, %hi(D_80117698)
    /* 5D138 8006C938 21083200 */  addu       $at, $at, $s2
    /* 5D13C 8006C93C 98762384 */  lh         $v1, %lo(D_80117698)($at)
    /* 5D140 8006C940 00000000 */  nop
    /* 5D144 8006C944 40100300 */  sll        $v0, $v1, 1
    /* 5D148 8006C948 21104300 */  addu       $v0, $v0, $v1
    /* 5D14C 8006C94C 00110200 */  sll        $v0, $v0, 4
    /* 5D150 8006C950 1180013C */  lui        $at, %hi(D_80116ADC)
    /* 5D154 8006C954 21082200 */  addu       $at, $at, $v0
    /* 5D158 8006C958 DC6A2584 */  lh         $a1, %lo(D_80116ADC)($at)
    /* 5D15C 8006C95C 651B030C */  jal        func_800C6D94
    /* 5D160 8006C960 21200002 */   addu      $a0, $s0, $zero
    /* 5D164 8006C964 40101100 */  sll        $v0, $s1, 1
  .L8006C968:
    /* 5D168 8006C968 21105100 */  addu       $v0, $v0, $s1
    /* 5D16C 8006C96C 80100200 */  sll        $v0, $v0, 2
    /* 5D170 8006C970 23105100 */  subu       $v0, $v0, $s1
    /* 5D174 8006C974 00110200 */  sll        $v0, $v0, 4
    /* 5D178 8006C978 23105100 */  subu       $v0, $v0, $s1
    /* 5D17C 8006C97C C0900200 */  sll        $s2, $v0, 3
    /* 5D180 8006C980 1180013C */  lui        $at, %hi(D_80117698)
    /* 5D184 8006C984 21083200 */  addu       $at, $at, $s2
    /* 5D188 8006C988 98762384 */  lh         $v1, %lo(D_80117698)($at)
    /* 5D18C 8006C98C 00000000 */  nop
    /* 5D190 8006C990 40100300 */  sll        $v0, $v1, 1
    /* 5D194 8006C994 21104300 */  addu       $v0, $v0, $v1
    /* 5D198 8006C998 00110200 */  sll        $v0, $v0, 4
    /* 5D19C 8006C99C 1180013C */  lui        $at, %hi(D_80116ADA)
    /* 5D1A0 8006C9A0 21082200 */  addu       $at, $at, $v0
    /* 5D1A4 8006C9A4 DA6A2284 */  lh         $v0, %lo(D_80116ADA)($at)
    /* 5D1A8 8006C9A8 00000000 */  nop
    /* 5D1AC 8006C9AC 17004004 */  bltz       $v0, .L8006CA0C
    /* 5D1B0 8006C9B0 00000000 */   nop
    /* 5D1B4 8006C9B4 00811100 */  sll        $s0, $s1, 4
    /* 5D1B8 8006C9B8 23801102 */  subu       $s0, $s0, $s1
    /* 5D1BC 8006C9BC C0801000 */  sll        $s0, $s0, 3
    /* 5D1C0 8006C9C0 21801102 */  addu       $s0, $s0, $s1
    /* 5D1C4 8006C9C4 40801000 */  sll        $s0, $s0, 1
    /* 5D1C8 8006C9C8 1180023C */  lui        $v0, %hi(D_80116EC2)
    /* 5D1CC 8006C9CC C26E4224 */  addiu      $v0, $v0, %lo(D_80116EC2)
    /* 5D1D0 8006C9D0 21800202 */  addu       $s0, $s0, $v0
    /* 5D1D4 8006C9D4 CB1A030C */  jal        func_800C6B2C
    /* 5D1D8 8006C9D8 21200002 */   addu      $a0, $s0, $zero
    /* 5D1DC 8006C9DC 1180013C */  lui        $at, %hi(D_80117698)
    /* 5D1E0 8006C9E0 21083200 */  addu       $at, $at, $s2
    /* 5D1E4 8006C9E4 98762384 */  lh         $v1, %lo(D_80117698)($at)
    /* 5D1E8 8006C9E8 00000000 */  nop
    /* 5D1EC 8006C9EC 40100300 */  sll        $v0, $v1, 1
    /* 5D1F0 8006C9F0 21104300 */  addu       $v0, $v0, $v1
    /* 5D1F4 8006C9F4 00110200 */  sll        $v0, $v0, 4
    /* 5D1F8 8006C9F8 1180013C */  lui        $at, %hi(D_80116ADA)
    /* 5D1FC 8006C9FC 21082200 */  addu       $at, $at, $v0
    /* 5D200 8006CA00 DA6A2584 */  lh         $a1, %lo(D_80116ADA)($at)
    /* 5D204 8006CA04 651B030C */  jal        func_800C6D94
    /* 5D208 8006CA08 21200002 */   addu      $a0, $s0, $zero
  .L8006CA0C:
    /* 5D20C 8006CA0C 01003126 */  addiu      $s1, $s1, 0x1
    /* 5D210 8006CA10 0800222A */  slti       $v0, $s1, 0x8
    /* 5D214 8006CA14 80FF4014 */  bnez       $v0, .L8006C818
    /* 5D218 8006CA18 40101100 */   sll       $v0, $s1, 1
  .L8006CA1C:
    /* 5D21C 8006CA1C 1280043C */  lui        $a0, %hi(D_8011A250)
    /* 5D220 8006CA20 50A28424 */  addiu      $a0, $a0, %lo(D_8011A250)
    /* 5D224 8006CA24 40010524 */  addiu      $a1, $zero, 0x140
    /* 5D228 8006CA28 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D22C 8006CA2C 80C1010C */  jal        func_80070600
    /* 5D230 8006CA30 21386002 */   addu      $a3, $s3, $zero
    /* 5D234 8006CA34 12014010 */  beqz       $v0, .L8006CE80
    /* 5D238 8006CA38 90070524 */   addiu     $a1, $zero, 0x790
    /* 5D23C 8006CA3C 1180043C */  lui        $a0, %hi(D_80116EC0)
    /* 5D240 8006CA40 C06E8424 */  addiu      $a0, $a0, %lo(D_80116EC0)
    /* 5D244 8006CA44 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D248 8006CA48 80C1010C */  jal        func_80070600
    /* 5D24C 8006CA4C 21386002 */   addu      $a3, $s3, $zero
    /* 5D250 8006CA50 0B014010 */  beqz       $v0, .L8006CE80
    /* 5D254 8006CA54 C02B0524 */   addiu     $a1, $zero, 0x2BC0
    /* 5D258 8006CA58 1180043C */  lui        $a0, %hi(D_80117690)
    /* 5D25C 8006CA5C 90768424 */  addiu      $a0, $a0, %lo(D_80117690)
    /* 5D260 8006CA60 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D264 8006CA64 80C1010C */  jal        func_80070600
    /* 5D268 8006CA68 21386002 */   addu      $a3, $s3, $zero
    /* 5D26C 8006CA6C 04014010 */  beqz       $v0, .L8006CE80
    /* 5D270 8006CA70 21206002 */   addu      $a0, $s3, $zero
    /* 5D274 8006CA74 1060020C */  jal        func_80098040
    /* 5D278 8006CA78 21280000 */   addu      $a1, $zero, $zero
    /* 5D27C 8006CA7C 01014014 */  bnez       $v0, .L8006CE84
    /* 5D280 8006CA80 1800A427 */   addiu     $a0, $sp, 0x18
    /* 5D284 8006CA84 1280103C */  lui        $s0, %hi(D_8011C312)
    /* 5D288 8006CA88 12C31026 */  addiu      $s0, $s0, %lo(D_8011C312)
    /* 5D28C 8006CA8C 00000286 */  lh         $v0, 0x0($s0)
    /* 5D290 8006CA90 02000586 */  lh         $a1, 0x2($s0)
    /* 5D294 8006CA94 1680043C */  lui        $a0, %hi(D_801589B4)
    /* 5D298 8006CA98 B489848C */  lw         $a0, %lo(D_801589B4)($a0)
    /* 5D29C 8006CA9C 18004500 */  mult       $v0, $a1
    /* 5D2A0 8006CAA0 12280000 */  mflo       $a1
    /* 5D2A4 8006CAA4 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D2A8 8006CAA8 80C1010C */  jal        func_80070600
    /* 5D2AC 8006CAAC 21386002 */   addu      $a3, $s3, $zero
    /* 5D2B0 8006CAB0 F3004010 */  beqz       $v0, .L8006CE80
    /* 5D2B4 8006CAB4 01000624 */   addiu     $a2, $zero, 0x1
    /* 5D2B8 8006CAB8 00000286 */  lh         $v0, 0x0($s0)
    /* 5D2BC 8006CABC 02000586 */  lh         $a1, 0x2($s0)
    /* 5D2C0 8006CAC0 1680043C */  lui        $a0, %hi(D_801589B8)
    /* 5D2C4 8006CAC4 B889848C */  lw         $a0, %lo(D_801589B8)($a0)
    /* 5D2C8 8006CAC8 18004500 */  mult       $v0, $a1
    /* 5D2CC 8006CACC 12280000 */  mflo       $a1
    /* 5D2D0 8006CAD0 80C1010C */  jal        func_80070600
    /* 5D2D4 8006CAD4 21386002 */   addu      $a3, $s3, $zero
    /* 5D2D8 8006CAD8 E9004010 */  beqz       $v0, .L8006CE80
    /* 5D2DC 8006CADC 00040524 */   addiu     $a1, $zero, 0x400
    /* 5D2E0 8006CAE0 1180043C */  lui        $a0, %hi(D_8010CC64)
    /* 5D2E4 8006CAE4 64CC8424 */  addiu      $a0, $a0, %lo(D_8010CC64)
    /* 5D2E8 8006CAE8 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D2EC 8006CAEC 80C1010C */  jal        func_80070600
    /* 5D2F0 8006CAF0 21386002 */   addu      $a3, $s3, $zero
    /* 5D2F4 8006CAF4 E3004010 */  beqz       $v0, .L8006CE84
    /* 5D2F8 8006CAF8 1800A427 */   addiu     $a0, $sp, 0x18
    /* 5D2FC 8006CAFC 1280023C */  lui        $v0, %hi(D_8011A280)
    /* 5D300 8006CB00 80A24284 */  lh         $v0, %lo(D_8011A280)($v0)
    /* 5D304 8006CB04 00000000 */  nop
    /* 5D308 8006CB08 0C004010 */  beqz       $v0, .L8006CB3C
    /* 5D30C 8006CB0C 40280200 */   sll       $a1, $v0, 1
    /* 5D310 8006CB10 2128A200 */  addu       $a1, $a1, $v0
    /* 5D314 8006CB14 80280500 */  sll        $a1, $a1, 2
    /* 5D318 8006CB18 2128A200 */  addu       $a1, $a1, $v0
    /* 5D31C 8006CB1C 1180043C */  lui        $a0, %hi(D_8010D6B4)
    /* 5D320 8006CB20 B4D68424 */  addiu      $a0, $a0, %lo(D_8010D6B4)
    /* 5D324 8006CB24 40280500 */  sll        $a1, $a1, 1
    /* 5D328 8006CB28 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D32C 8006CB2C 80C1010C */  jal        func_80070600
    /* 5D330 8006CB30 21386002 */   addu      $a3, $s3, $zero
    /* 5D334 8006CB34 D3004010 */  beqz       $v0, .L8006CE84
    /* 5D338 8006CB38 1800A427 */   addiu     $a0, $sp, 0x18
  .L8006CB3C:
    /* 5D33C 8006CB3C 1280023C */  lui        $v0, %hi(D_8011A282)
    /* 5D340 8006CB40 82A24284 */  lh         $v0, %lo(D_8011A282)($v0)
    /* 5D344 8006CB44 00000000 */  nop
    /* 5D348 8006CB48 0C004010 */  beqz       $v0, .L8006CB7C
    /* 5D34C 8006CB4C 40280200 */   sll       $a1, $v0, 1
    /* 5D350 8006CB50 2128A200 */  addu       $a1, $a1, $v0
    /* 5D354 8006CB54 80280500 */  sll        $a1, $a1, 2
    /* 5D358 8006CB58 2328A200 */  subu       $a1, $a1, $v0
    /* 5D35C 8006CB5C 1180043C */  lui        $a0, %hi(D_80113ED0)
    /* 5D360 8006CB60 D03E8424 */  addiu      $a0, $a0, %lo(D_80113ED0)
    /* 5D364 8006CB64 C0280500 */  sll        $a1, $a1, 3
    /* 5D368 8006CB68 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D36C 8006CB6C 80C1010C */  jal        func_80070600
    /* 5D370 8006CB70 21386002 */   addu      $a3, $s3, $zero
    /* 5D374 8006CB74 C3004010 */  beqz       $v0, .L8006CE84
    /* 5D378 8006CB78 1800A427 */   addiu     $a0, $sp, 0x18
  .L8006CB7C:
    /* 5D37C 8006CB7C 21880000 */  addu       $s1, $zero, $zero
    /* 5D380 8006CB80 1180123C */  lui        $s2, %hi(D_80116AD3)
    /* 5D384 8006CB84 D36A5226 */  addiu      $s2, $s2, %lo(D_80116AD3)
    /* 5D388 8006CB88 1180143C */  lui        $s4, %hi(D_80116AD4)
    /* 5D38C 8006CB8C D46A9426 */  addiu      $s4, $s4, %lo(D_80116AD4)
    /* 5D390 8006CB90 1500222A */  slti       $v0, $s1, 0x15
  .L8006CB94:
    /* 5D394 8006CB94 19004010 */  beqz       $v0, .L8006CBFC
    /* 5D398 8006CB98 40101100 */   sll       $v0, $s1, 1
    /* 5D39C 8006CB9C 21105100 */  addu       $v0, $v0, $s1
    /* 5D3A0 8006CBA0 00810200 */  sll        $s0, $v0, 4
    /* 5D3A4 8006CBA4 21201202 */  addu       $a0, $s0, $s2
    /* 5D3A8 8006CBA8 01000524 */  addiu      $a1, $zero, 0x1
    /* 5D3AC 8006CBAC 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D3B0 8006CBB0 80C1010C */  jal        func_80070600
    /* 5D3B4 8006CBB4 21386002 */   addu      $a3, $s3, $zero
    /* 5D3B8 8006CBB8 B1004010 */  beqz       $v0, .L8006CE80
    /* 5D3BC 8006CBBC 02004426 */   addiu     $a0, $s2, 0x2
    /* 5D3C0 8006CBC0 21200402 */  addu       $a0, $s0, $a0
    /* 5D3C4 8006CBC4 01000524 */  addiu      $a1, $zero, 0x1
    /* 5D3C8 8006CBC8 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D3CC 8006CBCC 80C1010C */  jal        func_80070600
    /* 5D3D0 8006CBD0 21386002 */   addu      $a3, $s3, $zero
    /* 5D3D4 8006CBD4 AA004010 */  beqz       $v0, .L8006CE80
    /* 5D3D8 8006CBD8 21201402 */   addu      $a0, $s0, $s4
    /* 5D3DC 8006CBDC 01000524 */  addiu      $a1, $zero, 0x1
    /* 5D3E0 8006CBE0 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D3E4 8006CBE4 80C1010C */  jal        func_80070600
    /* 5D3E8 8006CBE8 21386002 */   addu      $a3, $s3, $zero
    /* 5D3EC 8006CBEC A4004010 */  beqz       $v0, .L8006CE80
    /* 5D3F0 8006CBF0 01003126 */   addiu     $s1, $s1, 0x1
    /* 5D3F4 8006CBF4 E5B20108 */  j          .L8006CB94
    /* 5D3F8 8006CBF8 1500222A */   slti      $v0, $s1, 0x15
  .L8006CBFC:
    /* 5D3FC 8006CBFC 1680043C */  lui        $a0, %hi(D_80158886)
    /* 5D400 8006CC00 86888424 */  addiu      $a0, $a0, %lo(D_80158886)
    /* 5D404 8006CC04 02000524 */  addiu      $a1, $zero, 0x2
    /* 5D408 8006CC08 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D40C 8006CC0C 80C1010C */  jal        func_80070600
    /* 5D410 8006CC10 21386002 */   addu      $a3, $s3, $zero
    /* 5D414 8006CC14 9A004010 */  beqz       $v0, .L8006CE80
    /* 5D418 8006CC18 02000524 */   addiu     $a1, $zero, 0x2
    /* 5D41C 8006CC1C 1680043C */  lui        $a0, %hi(D_80158888)
    /* 5D420 8006CC20 88888424 */  addiu      $a0, $a0, %lo(D_80158888)
    /* 5D424 8006CC24 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D428 8006CC28 80C1010C */  jal        func_80070600
    /* 5D42C 8006CC2C 21386002 */   addu      $a3, $s3, $zero
    /* 5D430 8006CC30 93004010 */  beqz       $v0, .L8006CE80
    /* 5D434 8006CC34 30000524 */   addiu     $a1, $zero, 0x30
    /* 5D438 8006CC38 1280033C */  lui        $v1, %hi(D_8011A26D)
    /* 5D43C 8006CC3C 6DA26380 */  lb         $v1, %lo(D_8011A26D)($v1)
    /* 5D440 8006CC40 00000000 */  nop
    /* 5D444 8006CC44 40100300 */  sll        $v0, $v1, 1
    /* 5D448 8006CC48 21104300 */  addu       $v0, $v0, $v1
    /* 5D44C 8006CC4C 80100200 */  sll        $v0, $v0, 2
    /* 5D450 8006CC50 23104300 */  subu       $v0, $v0, $v1
    /* 5D454 8006CC54 00110200 */  sll        $v0, $v0, 4
    /* 5D458 8006CC58 23104300 */  subu       $v0, $v0, $v1
    /* 5D45C 8006CC5C C0100200 */  sll        $v0, $v0, 3
    /* 5D460 8006CC60 1180013C */  lui        $at, %hi(D_80117698)
    /* 5D464 8006CC64 21082200 */  addu       $at, $at, $v0
    /* 5D468 8006CC68 98762284 */  lh         $v0, %lo(D_80117698)($at)
    /* 5D46C 8006CC6C 00000000 */  nop
    /* 5D470 8006CC70 40200200 */  sll        $a0, $v0, 1
    /* 5D474 8006CC74 21208200 */  addu       $a0, $a0, $v0
    /* 5D478 8006CC78 00210400 */  sll        $a0, $a0, 4
    /* 5D47C 8006CC7C 1180023C */  lui        $v0, %hi(D_80116AD0)
    /* 5D480 8006CC80 D06A4224 */  addiu      $v0, $v0, %lo(D_80116AD0)
    /* 5D484 8006CC84 21208200 */  addu       $a0, $a0, $v0
    /* 5D488 8006CC88 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D48C 8006CC8C 80C1010C */  jal        func_80070600
    /* 5D490 8006CC90 21386002 */   addu      $a3, $s3, $zero
    /* 5D494 8006CC94 7A004010 */  beqz       $v0, .L8006CE80
    /* 5D498 8006CC98 B0040524 */   addiu     $a1, $zero, 0x4B0
    /* 5D49C 8006CC9C 1280043C */  lui        $a0, %hi(D_8011A748)
    /* 5D4A0 8006CCA0 48A78424 */  addiu      $a0, $a0, %lo(D_8011A748)
    /* 5D4A4 8006CCA4 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D4A8 8006CCA8 80C1010C */  jal        func_80070600
    /* 5D4AC 8006CCAC 21386002 */   addu      $a3, $s3, $zero
    /* 5D4B0 8006CCB0 74004010 */  beqz       $v0, .L8006CE84
    /* 5D4B4 8006CCB4 1800A427 */   addiu     $a0, $sp, 0x18
    /* 5D4B8 8006CCB8 1280043C */  lui        $a0, %hi(D_8011A596)
    /* 5D4BC 8006CCBC 96A58424 */  addiu      $a0, $a0, %lo(D_8011A596)
    /* 5D4C0 8006CCC0 1680063C */  lui        $a2, %hi(D_801588CC)
    /* 5D4C4 8006CCC4 CC88C624 */  addiu      $a2, $a2, %lo(D_801588CC)
    /* 5D4C8 8006CCC8 0300C288 */  lwl        $v0, 0x3($a2)
    /* 5D4CC 8006CCCC 0000C298 */  lwr        $v0, 0x0($a2)
    /* 5D4D0 8006CCD0 0700C388 */  lwl        $v1, 0x7($a2)
    /* 5D4D4 8006CCD4 0400C398 */  lwr        $v1, 0x4($a2)
    /* 5D4D8 8006CCD8 030082A8 */  swl        $v0, 0x3($a0)
    /* 5D4DC 8006CCDC 000082B8 */  swr        $v0, 0x0($a0)
    /* 5D4E0 8006CCE0 070083A8 */  swl        $v1, 0x7($a0)
    /* 5D4E4 8006CCE4 040083B8 */  swr        $v1, 0x4($a0)
    /* 5D4E8 8006CCE8 FEFF8424 */  addiu      $a0, $a0, -0x2
    /* 5D4EC 8006CCEC 32000524 */  addiu      $a1, $zero, 0x32
    /* 5D4F0 8006CCF0 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D4F4 8006CCF4 80C1010C */  jal        func_80070600
    /* 5D4F8 8006CCF8 21386002 */   addu      $a3, $s3, $zero
    /* 5D4FC 8006CCFC 60004010 */  beqz       $v0, .L8006CE80
    /* 5D500 8006CD00 21880000 */   addu      $s1, $zero, $zero
    /* 5D504 8006CD04 1280123C */  lui        $s2, %hi(D_8011E956)
    /* 5D508 8006CD08 56E95226 */  addiu      $s2, $s2, %lo(D_8011E956)
    /* 5D50C 8006CD0C 1280143C */  lui        $s4, %hi(D_8011E95E)
    /* 5D510 8006CD10 5EE99426 */  addiu      $s4, $s4, %lo(D_8011E95E)
  .L8006CD14:
    /* 5D514 8006CD14 2900201E */  bgtz       $s1, .L8006CDBC
    /* 5D518 8006CD18 40101100 */   sll       $v0, $s1, 1
    /* 5D51C 8006CD1C 21105100 */  addu       $v0, $v0, $s1
    /* 5D520 8006CD20 80100200 */  sll        $v0, $v0, 2
    /* 5D524 8006CD24 23105100 */  subu       $v0, $v0, $s1
    /* 5D528 8006CD28 80810200 */  sll        $s0, $v0, 6
    /* 5D52C 8006CD2C 21201202 */  addu       $a0, $s0, $s2
    /* 5D530 8006CD30 02000524 */  addiu      $a1, $zero, 0x2
    /* 5D534 8006CD34 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D538 8006CD38 80C1010C */  jal        func_80070600
    /* 5D53C 8006CD3C 21386002 */   addu      $a3, $s3, $zero
    /* 5D540 8006CD40 4F004010 */  beqz       $v0, .L8006CE80
    /* 5D544 8006CD44 02004426 */   addiu     $a0, $s2, 0x2
    /* 5D548 8006CD48 21200402 */  addu       $a0, $s0, $a0
    /* 5D54C 8006CD4C 02000524 */  addiu      $a1, $zero, 0x2
    /* 5D550 8006CD50 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D554 8006CD54 80C1010C */  jal        func_80070600
    /* 5D558 8006CD58 21386002 */   addu      $a3, $s3, $zero
    /* 5D55C 8006CD5C 48004010 */  beqz       $v0, .L8006CE80
    /* 5D560 8006CD60 04004426 */   addiu     $a0, $s2, 0x4
    /* 5D564 8006CD64 21200402 */  addu       $a0, $s0, $a0
    /* 5D568 8006CD68 02000524 */  addiu      $a1, $zero, 0x2
    /* 5D56C 8006CD6C 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D570 8006CD70 80C1010C */  jal        func_80070600
    /* 5D574 8006CD74 21386002 */   addu      $a3, $s3, $zero
    /* 5D578 8006CD78 41004010 */  beqz       $v0, .L8006CE80
    /* 5D57C 8006CD7C 06004426 */   addiu     $a0, $s2, 0x6
    /* 5D580 8006CD80 21200402 */  addu       $a0, $s0, $a0
    /* 5D584 8006CD84 02000524 */  addiu      $a1, $zero, 0x2
    /* 5D588 8006CD88 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D58C 8006CD8C 80C1010C */  jal        func_80070600
    /* 5D590 8006CD90 21386002 */   addu      $a3, $s3, $zero
    /* 5D594 8006CD94 3A004010 */  beqz       $v0, .L8006CE80
    /* 5D598 8006CD98 21201402 */   addu      $a0, $s0, $s4
    /* 5D59C 8006CD9C 02000524 */  addiu      $a1, $zero, 0x2
    /* 5D5A0 8006CDA0 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D5A4 8006CDA4 80C1010C */  jal        func_80070600
    /* 5D5A8 8006CDA8 21386002 */   addu      $a3, $s3, $zero
    /* 5D5AC 8006CDAC 34004010 */  beqz       $v0, .L8006CE80
    /* 5D5B0 8006CDB0 01003126 */   addiu     $s1, $s1, 0x1
    /* 5D5B4 8006CDB4 45B30108 */  j          .L8006CD14
    /* 5D5B8 8006CDB8 00000000 */   nop
  .L8006CDBC:
    /* 5D5BC 8006CDBC 0700E016 */  bnez       $s7, .L8006CDDC
    /* 5D5C0 8006CDC0 00000000 */   nop
    /* 5D5C4 8006CDC4 1280023C */  lui        $v0, %hi(D_8011A25A)
    /* 5D5C8 8006CDC8 5AA24294 */  lhu        $v0, %lo(D_8011A25A)($v0)
    /* 5D5CC 8006CDCC 00000000 */  nop
    /* 5D5D0 8006CDD0 80004230 */  andi       $v0, $v0, 0x80
    /* 5D5D4 8006CDD4 09004010 */  beqz       $v0, .L8006CDFC
    /* 5D5D8 8006CDD8 00000000 */   nop
  .L8006CDDC:
    /* 5D5DC 8006CDDC 1280043C */  lui        $a0, %hi(D_8011A390)
    /* 5D5E0 8006CDE0 90A38424 */  addiu      $a0, $a0, %lo(D_8011A390)
    /* 5D5E4 8006CDE4 64000524 */  addiu      $a1, $zero, 0x64
    /* 5D5E8 8006CDE8 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D5EC 8006CDEC 80C1010C */  jal        func_80070600
    /* 5D5F0 8006CDF0 21386002 */   addu      $a3, $s3, $zero
    /* 5D5F4 8006CDF4 23004010 */  beqz       $v0, .L8006CE84
    /* 5D5F8 8006CDF8 1800A427 */   addiu     $a0, $sp, 0x18
  .L8006CDFC:
    /* 5D5FC 8006CDFC 1280043C */  lui        $a0, %hi(D_8011A3F4)
    /* 5D600 8006CE00 F4A38424 */  addiu      $a0, $a0, %lo(D_8011A3F4)
    /* 5D604 8006CE04 52010524 */  addiu      $a1, $zero, 0x152
    /* 5D608 8006CE08 01000624 */  addiu      $a2, $zero, 0x1
    /* 5D60C 8006CE0C 80C1010C */  jal        func_80070600
    /* 5D610 8006CE10 21386002 */   addu      $a3, $s3, $zero
    /* 5D614 8006CE14 1B004010 */  beqz       $v0, .L8006CE84
    /* 5D618 8006CE18 1800A427 */   addiu     $a0, $sp, 0x18
    /* 5D61C 8006CE1C 09C2010C */  jal        func_80070824
    /* 5D620 8006CE20 21206002 */   addu      $a0, $s3, $zero
    /* 5D624 8006CE24 1800A327 */  addiu      $v1, $sp, 0x18
    /* 5D628 8006CE28 1000A3AF */  sw         $v1, 0x10($sp)
    /* 5D62C 8006CE2C 2120C003 */  addu       $a0, $fp, $zero
    /* 5D630 8006CE30 C002A58F */  lw         $a1, 0x2C0($sp)
    /* 5D634 8006CE34 2130C002 */  addu       $a2, $s6, $zero
    /* 5D638 8006CE38 0EBF010C */  jal        func_8006FC38
    /* 5D63C 8006CE3C 21384000 */   addu      $a3, $v0, $zero
    /* 5D640 8006CE40 00140200 */  sll        $v0, $v0, 16
    /* 5D644 8006CE44 03140200 */  sra        $v0, $v0, 16
    /* 5D648 8006CE48 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 5D64C 8006CE4C 07004314 */  bne        $v0, $v1, .L8006CE6C
    /* 5D650 8006CE50 00000000 */   nop
    /* 5D654 8006CE54 89D6030C */  jal        func_800F5A24
    /* 5D658 8006CE58 2120A002 */   addu      $a0, $s5, $zero
    /* 5D65C 8006CE5C C6D5030C */  jal        func_800F5718
    /* 5D660 8006CE60 2120A002 */   addu      $a0, $s5, $zero
    /* 5D664 8006CE64 A1B30108 */  j          .L8006CE84
    /* 5D668 8006CE68 1800A427 */   addiu     $a0, $sp, 0x18
  .L8006CE6C:
    /* 5D66C 8006CE6C 89D6030C */  jal        func_800F5A24
    /* 5D670 8006CE70 2120A002 */   addu      $a0, $s5, $zero
    /* 5D674 8006CE74 C6D5030C */  jal        func_800F5718
    /* 5D678 8006CE78 2120A002 */   addu      $a0, $s5, $zero
    /* 5D67C 8006CE7C C802A0AF */  sw         $zero, 0x2C8($sp)
  .L8006CE80:
    /* 5D680 8006CE80 1800A427 */  addiu      $a0, $sp, 0x18
  .L8006CE84:
    /* 5D684 8006CE84 0AC7020C */  jal        func_800B1C28
    /* 5D688 8006CE88 02000524 */   addiu     $a1, $zero, 0x2
    /* 5D68C 8006CE8C C802A28F */  lw         $v0, 0x2C8($sp)
  .L8006CE90:
    /* 5D690 8006CE90 F402BF8F */  lw         $ra, 0x2F4($sp)
    /* 5D694 8006CE94 F002BE8F */  lw         $fp, 0x2F0($sp)
    /* 5D698 8006CE98 EC02B78F */  lw         $s7, 0x2EC($sp)
    /* 5D69C 8006CE9C E802B68F */  lw         $s6, 0x2E8($sp)
    /* 5D6A0 8006CEA0 E402B58F */  lw         $s5, 0x2E4($sp)
    /* 5D6A4 8006CEA4 E002B48F */  lw         $s4, 0x2E0($sp)
    /* 5D6A8 8006CEA8 DC02B38F */  lw         $s3, 0x2DC($sp)
    /* 5D6AC 8006CEAC D802B28F */  lw         $s2, 0x2D8($sp)
    /* 5D6B0 8006CEB0 D402B18F */  lw         $s1, 0x2D4($sp)
    /* 5D6B4 8006CEB4 D002B08F */  lw         $s0, 0x2D0($sp)
    /* 5D6B8 8006CEB8 F802BD27 */  addiu      $sp, $sp, 0x2F8
    /* 5D6BC 8006CEBC 0800E003 */  jr         $ra
    /* 5D6C0 8006CEC0 00000000 */   nop
endlabel func_8006C4F8
