.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80013204

dlabel D_80013204
    /* 3A04 80013204 */ .asciz "SIVI2.TIM"
    /* 53495649322E54494D000000 */
.align 2
enddlabel D_80013204


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800DA0C8, 0x270

glabel func_800DA0C8
    /* CA8C8 800DA0C8 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* CA8CC 800DA0CC 2000BFAF */  sw         $ra, 0x20($sp)
    /* CA8D0 800DA0D0 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* CA8D4 800DA0D4 1800B0AF */  sw         $s0, 0x18($sp)
    /* CA8D8 800DA0D8 1680043C */  lui        $a0, %hi(D_8015EE88)
    /* CA8DC 800DA0DC 88EE8424 */  addiu      $a0, $a0, %lo(D_8015EE88)
    /* CA8E0 800DA0E0 0180053C */  lui        $a1, %hi(D_80013204)
    /* CA8E4 800DA0E4 0432A524 */  addiu      $a1, $a1, %lo(D_80013204)
    /* CA8E8 800DA0E8 0A000624 */  addiu      $a2, $zero, 0xA
    /* CA8EC 800DA0EC 76E2030C */  jal        func_800F89D8
    /* CA8F0 800DA0F0 C0000724 */   addiu     $a3, $zero, 0xC0
    /* CA8F4 800DA0F4 10001124 */  addiu      $s1, $zero, 0x10
    /* CA8F8 800DA0F8 1000B1AF */  sw         $s1, 0x10($sp)
    /* CA8FC 800DA0FC 1380043C */  lui        $a0, %hi(D_80135CC0)
    /* CA900 800DA100 C05C8424 */  addiu      $a0, $a0, %lo(D_80135CC0)
    /* CA904 800DA104 21280000 */  addu       $a1, $zero, $zero
    /* CA908 800DA108 21300000 */  addu       $a2, $zero, $zero
    /* CA90C 800DA10C 6D63030C */  jal        func_800D8DB4
    /* CA910 800DA110 10000724 */   addiu     $a3, $zero, 0x10
    /* CA914 800DA114 1000B1AF */  sw         $s1, 0x10($sp)
    /* CA918 800DA118 1380043C */  lui        $a0, %hi(D_80135D54)
    /* CA91C 800DA11C 545D8424 */  addiu      $a0, $a0, %lo(D_80135D54)
    /* CA920 800DA120 10000524 */  addiu      $a1, $zero, 0x10
    /* CA924 800DA124 21300000 */  addu       $a2, $zero, $zero
    /* CA928 800DA128 6D63030C */  jal        func_800D8DB4
    /* CA92C 800DA12C 10000724 */   addiu     $a3, $zero, 0x10
    /* CA930 800DA130 1000B1AF */  sw         $s1, 0x10($sp)
    /* CA934 800DA134 1380043C */  lui        $a0, %hi(D_80135DE8)
    /* CA938 800DA138 E85D8424 */  addiu      $a0, $a0, %lo(D_80135DE8)
    /* CA93C 800DA13C 10000524 */  addiu      $a1, $zero, 0x10
    /* CA940 800DA140 60000624 */  addiu      $a2, $zero, 0x60
    /* CA944 800DA144 6D63030C */  jal        func_800D8DB4
    /* CA948 800DA148 10000724 */   addiu     $a3, $zero, 0x10
    /* CA94C 800DA14C 08001024 */  addiu      $s0, $zero, 0x8
    /* CA950 800DA150 1000B0AF */  sw         $s0, 0x10($sp)
    /* CA954 800DA154 1380043C */  lui        $a0, %hi(D_80135E7C)
    /* CA958 800DA158 7C5E8424 */  addiu      $a0, $a0, %lo(D_80135E7C)
    /* CA95C 800DA15C 40000524 */  addiu      $a1, $zero, 0x40
    /* CA960 800DA160 60000624 */  addiu      $a2, $zero, 0x60
    /* CA964 800DA164 6D63030C */  jal        func_800D8DB4
    /* CA968 800DA168 08000724 */   addiu     $a3, $zero, 0x8
    /* CA96C 800DA16C 1000B0AF */  sw         $s0, 0x10($sp)
    /* CA970 800DA170 1380043C */  lui        $a0, %hi(D_80135F10)
    /* CA974 800DA174 105F8424 */  addiu      $a0, $a0, %lo(D_80135F10)
    /* CA978 800DA178 48000524 */  addiu      $a1, $zero, 0x48
    /* CA97C 800DA17C 60000624 */  addiu      $a2, $zero, 0x60
    /* CA980 800DA180 6D63030C */  jal        func_800D8DB4
    /* CA984 800DA184 08000724 */   addiu     $a3, $zero, 0x8
    /* CA988 800DA188 1000B1AF */  sw         $s1, 0x10($sp)
    /* CA98C 800DA18C 1380043C */  lui        $a0, %hi(D_80135FA4)
    /* CA990 800DA190 A45F8424 */  addiu      $a0, $a0, %lo(D_80135FA4)
    /* CA994 800DA194 21280000 */  addu       $a1, $zero, $zero
    /* CA998 800DA198 70000624 */  addiu      $a2, $zero, 0x70
    /* CA99C 800DA19C 6D63030C */  jal        func_800D8DB4
    /* CA9A0 800DA1A0 10000724 */   addiu     $a3, $zero, 0x10
    /* CA9A4 800DA1A4 1000B1AF */  sw         $s1, 0x10($sp)
    /* CA9A8 800DA1A8 1380043C */  lui        $a0, %hi(D_80136038)
    /* CA9AC 800DA1AC 38608424 */  addiu      $a0, $a0, %lo(D_80136038)
    /* CA9B0 800DA1B0 10000524 */  addiu      $a1, $zero, 0x10
    /* CA9B4 800DA1B4 70000624 */  addiu      $a2, $zero, 0x70
    /* CA9B8 800DA1B8 6D63030C */  jal        func_800D8DB4
    /* CA9BC 800DA1BC 10000724 */   addiu     $a3, $zero, 0x10
    /* CA9C0 800DA1C0 1000B1AF */  sw         $s1, 0x10($sp)
    /* CA9C4 800DA1C4 1380043C */  lui        $a0, %hi(D_801360CC)
    /* CA9C8 800DA1C8 CC608424 */  addiu      $a0, $a0, %lo(D_801360CC)
    /* CA9CC 800DA1CC 30000524 */  addiu      $a1, $zero, 0x30
    /* CA9D0 800DA1D0 60000624 */  addiu      $a2, $zero, 0x60
    /* CA9D4 800DA1D4 6D63030C */  jal        func_800D8DB4
    /* CA9D8 800DA1D8 10000724 */   addiu     $a3, $zero, 0x10
    /* CA9DC 800DA1DC 1000B0AF */  sw         $s0, 0x10($sp)
    /* CA9E0 800DA1E0 1380043C */  lui        $a0, %hi(D_801361F4)
    /* CA9E4 800DA1E4 F4618424 */  addiu      $a0, $a0, %lo(D_801361F4)
    /* CA9E8 800DA1E8 50000524 */  addiu      $a1, $zero, 0x50
    /* CA9EC 800DA1EC 60000624 */  addiu      $a2, $zero, 0x60
    /* CA9F0 800DA1F0 6D63030C */  jal        func_800D8DB4
    /* CA9F4 800DA1F4 08000724 */   addiu     $a3, $zero, 0x8
    /* CA9F8 800DA1F8 1000B0AF */  sw         $s0, 0x10($sp)
    /* CA9FC 800DA1FC 1380043C */  lui        $a0, %hi(D_80136288)
    /* CAA00 800DA200 88628424 */  addiu      $a0, $a0, %lo(D_80136288)
    /* CAA04 800DA204 58000524 */  addiu      $a1, $zero, 0x58
    /* CAA08 800DA208 60000624 */  addiu      $a2, $zero, 0x60
    /* CAA0C 800DA20C 6D63030C */  jal        func_800D8DB4
    /* CAA10 800DA210 08000724 */   addiu     $a3, $zero, 0x8
    /* CAA14 800DA214 1000B1AF */  sw         $s1, 0x10($sp)
    /* CAA18 800DA218 1380043C */  lui        $a0, %hi(D_8013631C)
    /* CAA1C 800DA21C 1C638424 */  addiu      $a0, $a0, %lo(D_8013631C)
    /* CAA20 800DA220 80000524 */  addiu      $a1, $zero, 0x80
    /* CAA24 800DA224 60000624 */  addiu      $a2, $zero, 0x60
    /* CAA28 800DA228 6D63030C */  jal        func_800D8DB4
    /* CAA2C 800DA22C 10000724 */   addiu     $a3, $zero, 0x10
    /* CAA30 800DA230 1000B0AF */  sw         $s0, 0x10($sp)
    /* CAA34 800DA234 1380043C */  lui        $a0, %hi(D_8013656C)
    /* CAA38 800DA238 6C658424 */  addiu      $a0, $a0, %lo(D_8013656C)
    /* CAA3C 800DA23C 50000524 */  addiu      $a1, $zero, 0x50
    /* CAA40 800DA240 68000624 */  addiu      $a2, $zero, 0x68
    /* CAA44 800DA244 6D63030C */  jal        func_800D8DB4
    /* CAA48 800DA248 08000724 */   addiu     $a3, $zero, 0x8
    /* CAA4C 800DA24C 1000B0AF */  sw         $s0, 0x10($sp)
    /* CAA50 800DA250 1380043C */  lui        $a0, %hi(D_80136600)
    /* CAA54 800DA254 00668424 */  addiu      $a0, $a0, %lo(D_80136600)
    /* CAA58 800DA258 58000524 */  addiu      $a1, $zero, 0x58
    /* CAA5C 800DA25C 68000624 */  addiu      $a2, $zero, 0x68
    /* CAA60 800DA260 6D63030C */  jal        func_800D8DB4
    /* CAA64 800DA264 08000724 */   addiu     $a3, $zero, 0x8
    /* CAA68 800DA268 1000B0AF */  sw         $s0, 0x10($sp)
    /* CAA6C 800DA26C 1380043C */  lui        $a0, %hi(D_80136694)
    /* CAA70 800DA270 94668424 */  addiu      $a0, $a0, %lo(D_80136694)
    /* CAA74 800DA274 60000524 */  addiu      $a1, $zero, 0x60
    /* CAA78 800DA278 68000624 */  addiu      $a2, $zero, 0x68
    /* CAA7C 800DA27C 6D63030C */  jal        func_800D8DB4
    /* CAA80 800DA280 08000724 */   addiu     $a3, $zero, 0x8
    /* CAA84 800DA284 1000B0AF */  sw         $s0, 0x10($sp)
    /* CAA88 800DA288 1380043C */  lui        $a0, %hi(D_80136728)
    /* CAA8C 800DA28C 28678424 */  addiu      $a0, $a0, %lo(D_80136728)
    /* CAA90 800DA290 68000524 */  addiu      $a1, $zero, 0x68
    /* CAA94 800DA294 68000624 */  addiu      $a2, $zero, 0x68
    /* CAA98 800DA298 6D63030C */  jal        func_800D8DB4
    /* CAA9C 800DA29C 08000724 */   addiu     $a3, $zero, 0x8
    /* CAAA0 800DA2A0 1000B0AF */  sw         $s0, 0x10($sp)
    /* CAAA4 800DA2A4 1380043C */  lui        $a0, %hi(D_801367BC)
    /* CAAA8 800DA2A8 BC678424 */  addiu      $a0, $a0, %lo(D_801367BC)
    /* CAAAC 800DA2AC 40000524 */  addiu      $a1, $zero, 0x40
    /* CAAB0 800DA2B0 68000624 */  addiu      $a2, $zero, 0x68
    /* CAAB4 800DA2B4 6D63030C */  jal        func_800D8DB4
    /* CAAB8 800DA2B8 08000724 */   addiu     $a3, $zero, 0x8
    /* CAABC 800DA2BC 1680043C */  lui        $a0, %hi(D_8015EE88)
    /* CAAC0 800DA2C0 88EE8424 */  addiu      $a0, $a0, %lo(D_8015EE88)
    /* CAAC4 800DA2C4 21280000 */  addu       $a1, $zero, $zero
    /* CAAC8 800DA2C8 A9E0030C */  jal        func_800F82A4
    /* CAACC 800DA2CC 21300000 */   addu      $a2, $zero, $zero
    /* CAAD0 800DA2D0 1680043C */  lui        $a0, %hi(D_8015EE88)
    /* CAAD4 800DA2D4 88EE8424 */  addiu      $a0, $a0, %lo(D_8015EE88)
    /* CAAD8 800DA2D8 0180053C */  lui        $a1, %hi(D_80013210)
    /* CAADC 800DA2DC 1032A524 */  addiu      $a1, $a1, %lo(D_80013210)
    /* CAAE0 800DA2E0 FFFF0624 */  addiu      $a2, $zero, -0x1
    /* CAAE4 800DA2E4 76E2030C */  jal        func_800F89D8
    /* CAAE8 800DA2E8 C0000724 */   addiu     $a3, $zero, 0xC0
    /* CAAEC 800DA2EC 20000224 */  addiu      $v0, $zero, 0x20
    /* CAAF0 800DA2F0 1000A2AF */  sw         $v0, 0x10($sp)
    /* CAAF4 800DA2F4 1380043C */  lui        $a0, %hi(D_80136160)
    /* CAAF8 800DA2F8 60618424 */  addiu      $a0, $a0, %lo(D_80136160)
    /* CAAFC 800DA2FC 21280000 */  addu       $a1, $zero, $zero
    /* CAB00 800DA300 22000624 */  addiu      $a2, $zero, 0x22
    /* CAB04 800DA304 6D63030C */  jal        func_800D8DB4
    /* CAB08 800DA308 20000724 */   addiu     $a3, $zero, 0x20
    /* CAB0C 800DA30C 1680043C */  lui        $a0, %hi(D_8015EE88)
    /* CAB10 800DA310 88EE8424 */  addiu      $a0, $a0, %lo(D_8015EE88)
    /* CAB14 800DA314 21280000 */  addu       $a1, $zero, $zero
    /* CAB18 800DA318 A9E0030C */  jal        func_800F82A4
    /* CAB1C 800DA31C 21300000 */   addu      $a2, $zero, $zero
    /* CAB20 800DA320 2000BF8F */  lw         $ra, 0x20($sp)
    /* CAB24 800DA324 1C00B18F */  lw         $s1, 0x1C($sp)
    /* CAB28 800DA328 1800B08F */  lw         $s0, 0x18($sp)
    /* CAB2C 800DA32C 2800BD27 */  addiu      $sp, $sp, 0x28
    /* CAB30 800DA330 0800E003 */  jr         $ra
    /* CAB34 800DA334 00000000 */   nop
endlabel func_800DA0C8
