.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80012C74

dlabel D_80012C74
    /* 3474 80012C74 */ .asciz "LAUNCH.STR"
    /* 4C41554E43482E5354520000 */
.align 2
enddlabel D_80012C74


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800CE140, 0xE8

glabel func_800CE140
    /* BE940 800CE140 58FFBD27 */  addiu      $sp, $sp, -0xA8
    /* BE944 800CE144 A000BFAF */  sw         $ra, 0xA0($sp)
    /* BE948 800CE148 9C00B1AF */  sw         $s1, 0x9C($sp)
    /* BE94C 800CE14C 9800B0AF */  sw         $s0, 0x98($sp)
    /* BE950 800CE150 659F020C */  jal        func_800A7D94
    /* BE954 800CE154 21888000 */   addu      $s1, $a0, $zero
    /* BE958 800CE158 3E82030C */  jal        __builtin_new
    /* BE95C 800CE15C 88010424 */   addiu     $a0, $zero, 0x188
    /* BE960 800CE160 43D7030C */  jal        func_800F5D0C
    /* BE964 800CE164 21204000 */   addu      $a0, $v0, $zero
    /* BE968 800CE168 841522AE */  sw         $v0, 0x1584($s1)
    /* BE96C 800CE16C CB1A030C */  jal        func_800C6B2C
    /* BE970 800CE170 1800A427 */   addiu     $a0, $sp, 0x18
    /* BE974 800CE174 1800B027 */  addiu      $s0, $sp, 0x18
    /* BE978 800CE178 0180053C */  lui        $a1, %hi(D_80012C74)
    /* BE97C 800CE17C 742CA524 */  addiu      $a1, $a1, %lo(D_80012C74)
    /* BE980 800CE180 9987030C */  jal        func_800E1E64
    /* BE984 800CE184 21200002 */   addu      $a0, $s0, $zero
    /* BE988 800CE188 3C000224 */  addiu      $v0, $zero, 0x3C
    /* BE98C 800CE18C 1000A2AF */  sw         $v0, 0x10($sp)
    /* BE990 800CE190 8415248E */  lw         $a0, 0x1584($s1)
    /* BE994 800CE194 1680053C */  lui        $a1, %hi(D_801591A8)
    /* BE998 800CE198 A891A524 */  addiu      $a1, $a1, %lo(D_801591A8)
    /* BE99C 800CE19C 00080624 */  addiu      $a2, $zero, 0x800
    /* BE9A0 800CE1A0 B8D7030C */  jal        func_800F5EE0
    /* BE9A4 800CE1A4 21380000 */   addu      $a3, $zero, $zero
    /* BE9A8 800CE1A8 8415248E */  lw         $a0, 0x1584($s1)
    /* BE9AC 800CE1AC FAD7030C */  jal        func_800F5FE8
    /* BE9B0 800CE1B0 21280002 */   addu      $a1, $s0, $zero
    /* BE9B4 800CE1B4 16004014 */  bnez       $v0, .L800CE210
    /* BE9B8 800CE1B8 00000000 */   nop
    /* BE9BC 800CE1BC 7907040C */  jal        func_80101DE4
    /* BE9C0 800CE1C0 01000424 */   addiu     $a0, $zero, 0x1
    /* BE9C4 800CE1C4 1C07040C */  jal        func_80101C70
    /* BE9C8 800CE1C8 00000000 */   nop
    /* BE9CC 800CE1CC 8415248E */  lw         $a0, 0x1584($s1)
    /* BE9D0 800CE1D0 01000524 */  addiu      $a1, $zero, 0x1
    /* BE9D4 800CE1D4 16D8030C */  jal        func_800F6058
    /* BE9D8 800CE1D8 9D000624 */   addiu     $a2, $zero, 0x9D
    /* BE9DC 800CE1DC 8415248E */  lw         $a0, 0x1584($s1)
    /* BE9E0 800CE1E0 45D8030C */  jal        SsQuit
    /* BE9E4 800CE1E4 00000000 */   nop
    /* BE9E8 800CE1E8 8415248E */  lw         $a0, 0x1584($s1)
    /* BE9EC 800CE1EC EFEA030C */  jal        func_800FABBC
    /* BE9F0 800CE1F0 2C008424 */   addiu     $a0, $a0, 0x2C
    /* BE9F4 800CE1F4 8415248E */  lw         $a0, 0x1584($s1)
    /* BE9F8 800CE1F8 00000000 */  nop
    /* BE9FC 800CE1FC 03008010 */  beqz       $a0, .L800CE20C
    /* BEA00 800CE200 00000000 */   nop
    /* BEA04 800CE204 9BD7030C */  jal        func_800F5E6C
    /* BEA08 800CE208 03000524 */   addiu     $a1, $zero, 0x3
  .L800CE20C:
    /* BEA0C 800CE20C 841520AE */  sw         $zero, 0x1584($s1)
  .L800CE210:
    /* BEA10 800CE210 A000BF8F */  lw         $ra, 0xA0($sp)
    /* BEA14 800CE214 9C00B18F */  lw         $s1, 0x9C($sp)
    /* BEA18 800CE218 9800B08F */  lw         $s0, 0x98($sp)
    /* BEA1C 800CE21C A800BD27 */  addiu      $sp, $sp, 0xA8
    /* BEA20 800CE220 0800E003 */  jr         $ra
    /* BEA24 800CE224 00000000 */   nop
endlabel func_800CE140
