.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80010954

dlabel D_80010954
    /* 1154 80010954 */ .asciz "Here is the Hall of Fame."
    /* 48657265206973207468652048616C6C206F662046616D652E000000 */
.align 2
enddlabel D_80010954


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8006DF00, 0x15C

glabel func_8006DF00
    /* 5E700 8006DF00 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 5E704 8006DF04 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 5E708 8006DF08 1800B2AF */  sw         $s2, 0x18($sp)
    /* 5E70C 8006DF0C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 5E710 8006DF10 1000B0AF */  sw         $s0, 0x10($sp)
    /* 5E714 8006DF14 80100400 */  sll        $v0, $a0, 2
    /* 5E718 8006DF18 1680013C */  lui        $at, %hi(D_80158740)
    /* 5E71C 8006DF1C 21082200 */  addu       $at, $at, $v0
    /* 5E720 8006DF20 4087228C */  lw         $v0, %lo(D_80158740)($at)
    /* 5E724 8006DF24 00000000 */  nop
    /* 5E728 8006DF28 03004324 */  addiu      $v1, $v0, 0x3
    /* 5E72C 8006DF2C 0500622C */  sltiu      $v0, $v1, 0x5
    /* 5E730 8006DF30 43004010 */  beqz       $v0, .L8006E040
    /* 5E734 8006DF34 2188A000 */   addu      $s1, $a1, $zero
    /* 5E738 8006DF38 80100300 */  sll        $v0, $v1, 2
    /* 5E73C 8006DF3C 0180013C */  lui        $at, %hi(jtbl_80010CB4)
    /* 5E740 8006DF40 21082200 */  addu       $at, $at, $v0
    /* 5E744 8006DF44 B40C228C */  lw         $v0, %lo(jtbl_80010CB4)($at)
    /* 5E748 8006DF48 00000000 */  nop
    /* 5E74C 8006DF4C 08004000 */  jr         $v0
    /* 5E750 8006DF50 00000000 */   nop
  .L8006DF54:
    /* 5E754 8006DF54 7802828F */  lw         $v0, %gp_rel(D_80158750)($gp)
    /* 5E758 8006DF58 00000000 */  nop
    /* 5E75C 8006DF5C 02004228 */  slti       $v0, $v0, 0x2
    /* 5E760 8006DF60 05004014 */  bnez       $v0, .L8006DF78
    /* 5E764 8006DF64 80810400 */   sll       $s0, $a0, 6
    /* 5E768 8006DF68 0180053C */  lui        $a1, %hi(D_80010954)
    /* 5E76C 8006DF6C 5409A524 */  addiu      $a1, $a1, %lo(D_80010954)
    /* 5E770 8006DF70 0EB80108 */  j          .L8006E038
    /* 5E774 8006DF74 21202002 */   addu      $a0, $s1, $zero
  .L8006DF78:
    /* 5E778 8006DF78 1180123C */  lui        $s2, %hi(D_8010BEB0)
    /* 5E77C 8006DF7C B0BE5226 */  addiu      $s2, $s2, %lo(D_8010BEB0)
    /* 5E780 8006DF80 0180053C */  lui        $a1, %hi(D_80010970)
    /* 5E784 8006DF84 7009A524 */  addiu      $a1, $a1, %lo(D_80010970)
    /* 5E788 8006DF88 9D87030C */  jal        func_800E1E74
    /* 5E78C 8006DF8C 21201202 */   addu      $a0, $s0, $s2
    /* 5E790 8006DF90 2B004014 */  bnez       $v0, .L8006E040
    /* 5E794 8006DF94 1F004626 */   addiu     $a2, $s2, 0x1F
    /* 5E798 8006DF98 21202002 */  addu       $a0, $s1, $zero
    /* 5E79C 8006DF9C 1180013C */  lui        $at, %hi(D_8010BEE4)
    /* 5E7A0 8006DFA0 21083000 */  addu       $at, $at, $s0
    /* 5E7A4 8006DFA4 E4BE2584 */  lh         $a1, %lo(D_8010BEE4)($at)
    /* 5E7A8 8006DFA8 31C2010C */  jal        func_800708C4
    /* 5E7AC 8006DFAC 21300602 */   addu      $a2, $s0, $a2
    /* 5E7B0 8006DFB0 1680043C */  lui        $a0, %hi(D_801586CC)
    /* 5E7B4 8006DFB4 CC868424 */  addiu      $a0, $a0, %lo(D_801586CC)
    /* 5E7B8 8006DFB8 4551000C */  jal        func_80014514
    /* 5E7BC 8006DFBC 21282002 */   addu      $a1, $s1, $zero
    /* 5E7C0 8006DFC0 10B80108 */  j          .L8006E040
    /* 5E7C4 8006DFC4 00000000 */   nop
  .L8006DFC8:
    /* 5E7C8 8006DFC8 7802828F */  lw         $v0, %gp_rel(D_80158750)($gp)
    /* 5E7CC 8006DFCC 00000000 */  nop
    /* 5E7D0 8006DFD0 01004338 */  xori       $v1, $v0, 0x1
    /* 5E7D4 8006DFD4 0100632C */  sltiu      $v1, $v1, 0x1
    /* 5E7D8 8006DFD8 03004238 */  xori       $v0, $v0, 0x3
    /* 5E7DC 8006DFDC 0100422C */  sltiu      $v0, $v0, 0x1
    /* 5E7E0 8006DFE0 25186200 */  or         $v1, $v1, $v0
    /* 5E7E4 8006DFE4 05006010 */  beqz       $v1, .L8006DFFC
    /* 5E7E8 8006DFE8 21202002 */   addu      $a0, $s1, $zero
    /* 5E7EC 8006DFEC 0180053C */  lui        $a1, %hi(D_8001097C)
    /* 5E7F0 8006DFF0 7C09A524 */  addiu      $a1, $a1, %lo(D_8001097C)
    /* 5E7F4 8006DFF4 0EB80108 */  j          .L8006E038
    /* 5E7F8 8006DFF8 00000000 */   nop
  .L8006DFFC:
    /* 5E7FC 8006DFFC 0180053C */  lui        $a1, %hi(D_80010994)
    /* 5E800 8006E000 9409A524 */  addiu      $a1, $a1, %lo(D_80010994)
    /* 5E804 8006E004 0EB80108 */  j          .L8006E038
    /* 5E808 8006E008 00000000 */   nop
  .L8006E00C:
    /* 5E80C 8006E00C 0180053C */  lui        $a1, %hi(D_800109B0)
    /* 5E810 8006E010 B009A524 */  addiu      $a1, $a1, %lo(D_800109B0)
    /* 5E814 8006E014 0EB80108 */  j          .L8006E038
    /* 5E818 8006E018 21202002 */   addu      $a0, $s1, $zero
  .L8006E01C:
    /* 5E81C 8006E01C 0180053C */  lui        $a1, %hi(D_800109D8)
    /* 5E820 8006E020 D809A524 */  addiu      $a1, $a1, %lo(D_800109D8)
    /* 5E824 8006E024 0EB80108 */  j          .L8006E038
    /* 5E828 8006E028 21202002 */   addu      $a0, $s1, $zero
  .L8006E02C:
    /* 5E82C 8006E02C 21202002 */  addu       $a0, $s1, $zero
    /* 5E830 8006E030 0180053C */  lui        $a1, %hi(D_80010A00)
    /* 5E834 8006E034 000AA524 */  addiu      $a1, $a1, %lo(D_80010A00)
  .L8006E038:
    /* 5E838 8006E038 9987030C */  jal        func_800E1E64
    /* 5E83C 8006E03C 00000000 */   nop
  .L8006E040:
    /* 5E840 8006E040 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 5E844 8006E044 1800B28F */  lw         $s2, 0x18($sp)
    /* 5E848 8006E048 1400B18F */  lw         $s1, 0x14($sp)
    /* 5E84C 8006E04C 1000B08F */  lw         $s0, 0x10($sp)
    /* 5E850 8006E050 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 5E854 8006E054 0800E003 */  jr         $ra
    /* 5E858 8006E058 00000000 */   nop
endlabel func_8006DF00
