.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80011A7C

dlabel D_80011A7C
    /* 227C 80011A7C */ .asciz "         PAUSED\n"
    /* 2020202020202020205041555345440A00000000 */
.align 2
enddlabel D_80011A7C

.align 2
nonmatching D_80011A90

dlabel D_80011A90
    /* 2290 80011A90 */ .asciz "Please insert controller!\n"
    /* 506C6561736520696E7365727420636F6E74726F6C6C6572210A0000 */
.align 2
enddlabel D_80011A90

.align 2
nonmatching D_80011AAC

dlabel D_80011AAC
    /* 22AC 80011AAC */ .asciz "  Press X to continue"
    /* 20205072657373205820746F20636F6E74696E7565000000 */
.align 2
enddlabel D_80011AAC


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8009D1AC, 0x284

glabel func_8009D1AC
    /* 8D9AC 8009D1AC D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 8D9B0 8009D1B0 2400BFAF */  sw         $ra, 0x24($sp)
    /* 8D9B4 8009D1B4 2000B0AF */  sw         $s0, 0x20($sp)
    /* 8D9B8 8009D1B8 21808000 */  addu       $s0, $a0, $zero
    /* 8D9BC 8009D1BC ED12040C */  jal        func_80104BB4
    /* 8D9C0 8009D1C0 21200000 */   addu      $a0, $zero, $zero
    /* 8D9C4 8009D1C4 21184000 */  addu       $v1, $v0, $zero
    /* 8D9C8 8009D1C8 1680023C */  lui        $v0, %hi(D_801584E8)
    /* 8D9CC 8009D1CC E884428C */  lw         $v0, %lo(D_801584E8)($v0)
    /* 8D9D0 8009D1D0 00000000 */  nop
    /* 8D9D4 8009D1D4 03004010 */  beqz       $v0, .L8009D1E4
    /* 8D9D8 8009D1D8 01000224 */   addiu     $v0, $zero, 0x1
    /* 8D9DC 8009D1DC 1680013C */  lui        $at, %hi(D_801584E4)
    /* 8D9E0 8009D1E0 E48422AC */  sw         $v0, %lo(D_801584E4)($at)
  .L8009D1E4:
    /* 8D9E4 8009D1E4 1680023C */  lui        $v0, %hi(D_801584E4)
    /* 8D9E8 8009D1E8 E484428C */  lw         $v0, %lo(D_801584E4)($v0)
    /* 8D9EC 8009D1EC 00000000 */  nop
    /* 8D9F0 8009D1F0 73004010 */  beqz       $v0, .L8009D3C0
    /* 8D9F4 8009D1F4 00086230 */   andi      $v0, $v1, 0x800
    /* 8D9F8 8009D1F8 1280023C */  lui        $v0, %hi(D_8011E764)
    /* 8D9FC 8009D1FC 64E7428C */  lw         $v0, %lo(D_8011E764)($v0)
    /* 8DA00 8009D200 00000000 */  nop
    /* 8DA04 8009D204 0400448C */  lw         $a0, 0x4($v0)
    /* 8DA08 8009D208 D707040C */  jal        func_80101F5C
    /* 8DA0C 8009D20C 00000000 */   nop
    /* 8DA10 8009D210 4D000224 */  addiu      $v0, $zero, 0x4D
    /* 8DA14 8009D214 1000A2A7 */  sh         $v0, 0x10($sp)
    /* 8DA18 8009D218 25000224 */  addiu      $v0, $zero, 0x25
    /* 8DA1C 8009D21C 1200A2A7 */  sh         $v0, 0x12($sp)
    /* 8DA20 8009D220 F3000224 */  addiu      $v0, $zero, 0xF3
    /* 8DA24 8009D224 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 8DA28 8009D228 6B000224 */  addiu      $v0, $zero, 0x6B
    /* 8DA2C 8009D22C 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 8DA30 8009D230 1000A427 */  addiu      $a0, $sp, 0x10
    /* 8DA34 8009D234 A314020C */  jal        func_8008528C
    /* 8DA38 8009D238 21280000 */   addu      $a1, $zero, $zero
    /* 8DA3C 8009D23C 3405828F */  lw         $v0, %gp_rel(D_80158A0C)($gp)
    /* 8DA40 8009D240 00000000 */  nop
    /* 8DA44 8009D244 31004014 */  bnez       $v0, .L8009D30C
    /* 8DA48 8009D248 00000000 */   nop
    /* 8DA4C 8009D24C 05000016 */  bnez       $s0, .L8009D264
    /* 8DA50 8009D250 00000000 */   nop
    /* 8DA54 8009D254 3805828F */  lw         $v0, %gp_rel(D_80158A10)($gp)
    /* 8DA58 8009D258 00000000 */  nop
    /* 8DA5C 8009D25C 2B004010 */  beqz       $v0, .L8009D30C
    /* 8DA60 8009D260 00000000 */   nop
  .L8009D264:
    /* 8DA64 8009D264 45A3030C */  jal        SpuSetMute
    /* 8DA68 8009D268 01000424 */   addiu     $a0, $zero, 0x1
    /* 8DA6C 8009D26C 1280043C */  lui        $a0, %hi(D_80121340)
    /* 8DA70 8009D270 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 8DA74 8009D274 CB1A030C */  jal        func_800C6B2C
    /* 8DA78 8009D278 00000000 */   nop
    /* 8DA7C 8009D27C 57000224 */  addiu      $v0, $zero, 0x57
    /* 8DA80 8009D280 1800A2A7 */  sh         $v0, 0x18($sp)
    /* 8DA84 8009D284 35000224 */  addiu      $v0, $zero, 0x35
    /* 8DA88 8009D288 1A00A2A7 */  sh         $v0, 0x1A($sp)
    /* 8DA8C 8009D28C F3000224 */  addiu      $v0, $zero, 0xF3
    /* 8DA90 8009D290 1C00A2A7 */  sh         $v0, 0x1C($sp)
    /* 8DA94 8009D294 6B000224 */  addiu      $v0, $zero, 0x6B
    /* 8DA98 8009D298 1280043C */  lui        $a0, %hi(D_80121340)
    /* 8DA9C 8009D29C 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 8DAA0 8009D2A0 0180053C */  lui        $a1, %hi(D_80011A7C)
    /* 8DAA4 8009D2A4 7C1AA524 */  addiu      $a1, $a1, %lo(D_80011A7C)
    /* 8DAA8 8009D2A8 9987030C */  jal        func_800E1E64
    /* 8DAAC 8009D2AC 1E00A2A7 */   sh        $v0, 0x1E($sp)
    /* 8DAB0 8009D2B0 1680023C */  lui        $v0, %hi(D_801584E8)
    /* 8DAB4 8009D2B4 E884428C */  lw         $v0, %lo(D_801584E8)($v0)
    /* 8DAB8 8009D2B8 00000000 */  nop
    /* 8DABC 8009D2BC 07004010 */  beqz       $v0, .L8009D2DC
    /* 8DAC0 8009D2C0 00000000 */   nop
    /* 8DAC4 8009D2C4 1280043C */  lui        $a0, %hi(D_80121340)
    /* 8DAC8 8009D2C8 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 8DACC 8009D2CC 0180053C */  lui        $a1, %hi(D_80011A90)
    /* 8DAD0 8009D2D0 901AA524 */  addiu      $a1, $a1, %lo(D_80011A90)
    /* 8DAD4 8009D2D4 9987030C */  jal        func_800E1E64
    /* 8DAD8 8009D2D8 00000000 */   nop
  .L8009D2DC:
    /* 8DADC 8009D2DC 1280043C */  lui        $a0, %hi(D_80121340)
    /* 8DAE0 8009D2E0 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 8DAE4 8009D2E4 0180053C */  lui        $a1, %hi(D_80011AAC)
    /* 8DAE8 8009D2E8 AC1AA524 */  addiu      $a1, $a1, %lo(D_80011AAC)
    /* 8DAEC 8009D2EC 9987030C */  jal        func_800E1E64
    /* 8DAF0 8009D2F0 00000000 */   nop
    /* 8DAF4 8009D2F4 1280043C */  lui        $a0, %hi(D_80121340)
    /* 8DAF8 8009D2F8 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 8DAFC 8009D2FC 1800A527 */  addiu      $a1, $sp, 0x18
    /* 8DB00 8009D300 DC0F040C */  jal        func_80103F70
    /* 8DB04 8009D304 10000624 */   addiu     $a2, $zero, 0x10
    /* 8DB08 8009D308 340582AF */  sw         $v0, %gp_rel(D_80158A0C)($gp)
  .L8009D30C:
    /* 8DB0C 8009D30C 3405848F */  lw         $a0, %gp_rel(D_80158A0C)($gp)
    /* 8DB10 8009D310 7D11040C */  jal        func_801045F4
    /* 8DB14 8009D314 00000000 */   nop
    /* 8DB18 8009D318 3805838F */  lw         $v1, %gp_rel(D_80158A10)($gp)
    /* 8DB1C 8009D31C 00000000 */  nop
    /* 8DB20 8009D320 04006228 */  slti       $v0, $v1, 0x4
    /* 8DB24 8009D324 04004010 */  beqz       $v0, .L8009D338
    /* 8DB28 8009D328 01006224 */   addiu     $v0, $v1, 0x1
    /* 8DB2C 8009D32C 380582AF */  sw         $v0, %gp_rel(D_80158A10)($gp)
    /* 8DB30 8009D330 00750208 */  j          .L8009D400
    /* 8DB34 8009D334 00000000 */   nop
  .L8009D338:
    /* 8DB38 8009D338 ED12040C */  jal        func_80104BB4
    /* 8DB3C 8009D33C 21200000 */   addu      $a0, $zero, $zero
    /* 8DB40 8009D340 05004010 */  beqz       $v0, .L8009D358
    /* 8DB44 8009D344 00000000 */   nop
    /* 8DB48 8009D348 6184030C */  jal        VSync
    /* 8DB4C 8009D34C 21200000 */   addu      $a0, $zero, $zero
    /* 8DB50 8009D350 CE740208 */  j          .L8009D338
    /* 8DB54 8009D354 00000000 */   nop
  .L8009D358:
    /* 8DB58 8009D358 ED12040C */  jal        func_80104BB4
    /* 8DB5C 8009D35C 21200000 */   addu      $a0, $zero, $zero
    /* 8DB60 8009D360 50084230 */  andi       $v0, $v0, 0x850
    /* 8DB64 8009D364 05004014 */  bnez       $v0, .L8009D37C
    /* 8DB68 8009D368 00000000 */   nop
    /* 8DB6C 8009D36C 6184030C */  jal        VSync
    /* 8DB70 8009D370 21200000 */   addu      $a0, $zero, $zero
    /* 8DB74 8009D374 D6740208 */  j          .L8009D358
    /* 8DB78 8009D378 00000000 */   nop
  .L8009D37C:
    /* 8DB7C 8009D37C ED12040C */  jal        func_80104BB4
    /* 8DB80 8009D380 21200000 */   addu      $a0, $zero, $zero
    /* 8DB84 8009D384 05004010 */  beqz       $v0, .L8009D39C
    /* 8DB88 8009D388 03000224 */   addiu     $v0, $zero, 0x3
    /* 8DB8C 8009D38C 6184030C */  jal        VSync
    /* 8DB90 8009D390 21200000 */   addu      $a0, $zero, $zero
    /* 8DB94 8009D394 DF740208 */  j          .L8009D37C
    /* 8DB98 8009D398 00000000 */   nop
  .L8009D39C:
    /* 8DB9C 8009D39C 1680013C */  lui        $at, %hi(D_801584E4)
    /* 8DBA0 8009D3A0 E48420AC */  sw         $zero, %lo(D_801584E4)($at)
    /* 8DBA4 8009D3A4 380580AF */  sw         $zero, %gp_rel(D_80158A10)($gp)
    /* 8DBA8 8009D3A8 1680013C */  lui        $at, %hi(D_801584EC)
    /* 8DBAC 8009D3AC EC8422AC */  sw         $v0, %lo(D_801584EC)($at)
    /* 8DBB0 8009D3B0 45A3030C */  jal        SpuSetMute
    /* 8DBB4 8009D3B4 21200000 */   addu      $a0, $zero, $zero
    /* 8DBB8 8009D3B8 00750208 */  j          .L8009D400
    /* 8DBBC 8009D3BC 00000000 */   nop
  .L8009D3C0:
    /* 8DBC0 8009D3C0 08004010 */  beqz       $v0, .L8009D3E4
    /* 8DBC4 8009D3C4 00000000 */   nop
    /* 8DBC8 8009D3C8 1680023C */  lui        $v0, %hi(D_801584EC)
    /* 8DBCC 8009D3CC EC84428C */  lw         $v0, %lo(D_801584EC)($v0)
    /* 8DBD0 8009D3D0 00000000 */  nop
    /* 8DBD4 8009D3D4 0300401C */  bgtz       $v0, .L8009D3E4
    /* 8DBD8 8009D3D8 01000224 */   addiu     $v0, $zero, 0x1
    /* 8DBDC 8009D3DC 1680013C */  lui        $at, %hi(D_801584E4)
    /* 8DBE0 8009D3E0 E48422AC */  sw         $v0, %lo(D_801584E4)($at)
  .L8009D3E4:
    /* 8DBE4 8009D3E4 3405848F */  lw         $a0, %gp_rel(D_80158A0C)($gp)
    /* 8DBE8 8009D3E8 00000000 */  nop
    /* 8DBEC 8009D3EC 04008010 */  beqz       $a0, .L8009D400
    /* 8DBF0 8009D3F0 00000000 */   nop
    /* 8DBF4 8009D3F4 E511040C */  jal        func_80104794
    /* 8DBF8 8009D3F8 00000000 */   nop
    /* 8DBFC 8009D3FC 340580AF */  sw         $zero, %gp_rel(D_80158A0C)($gp)
  .L8009D400:
    /* 8DC00 8009D400 1680023C */  lui        $v0, %hi(D_801584EC)
    /* 8DC04 8009D404 EC84428C */  lw         $v0, %lo(D_801584EC)($v0)
    /* 8DC08 8009D408 00000000 */  nop
    /* 8DC0C 8009D40C 03004018 */  blez       $v0, .L8009D41C
    /* 8DC10 8009D410 FFFF4224 */   addiu     $v0, $v0, -0x1
    /* 8DC14 8009D414 1680013C */  lui        $at, %hi(D_801584EC)
    /* 8DC18 8009D418 EC8422AC */  sw         $v0, %lo(D_801584EC)($at)
  .L8009D41C:
    /* 8DC1C 8009D41C 2400BF8F */  lw         $ra, 0x24($sp)
    /* 8DC20 8009D420 2000B08F */  lw         $s0, 0x20($sp)
    /* 8DC24 8009D424 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 8DC28 8009D428 0800E003 */  jr         $ra
    /* 8DC2C 8009D42C 00000000 */   nop
endlabel func_8009D1AC
