.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
nonmatching jtbl_80011B44

dlabel jtbl_80011B44
    /* 2344 80011B44 AC1E0A80 */ .word .L800A1EAC
    /* 2348 80011B48 581F0A80 */ .word .L800A1F58
    /* 234C 80011B4C 581F0A80 */ .word .L800A1F58
    /* 2350 80011B50 581F0A80 */ .word .L800A1F58
    /* 2354 80011B54 581F0A80 */ .word .L800A1F58
    /* 2358 80011B58 581F0A80 */ .word .L800A1F58
    /* 235C 80011B5C 581F0A80 */ .word .L800A1F58
    /* 2360 80011B60 581F0A80 */ .word .L800A1F58
    /* 2364 80011B64 581F0A80 */ .word .L800A1F58
    /* 2368 80011B68 581F0A80 */ .word .L800A1F58
    /* 236C 80011B6C 581F0A80 */ .word .L800A1F58
    /* 2370 80011B70 581F0A80 */ .word .L800A1F58
    /* 2374 80011B74 581F0A80 */ .word .L800A1F58
    /* 2378 80011B78 581F0A80 */ .word .L800A1F58
    /* 237C 80011B7C AC1E0A80 */ .word .L800A1EAC
    /* 2380 80011B80 581F0A80 */ .word .L800A1F58
    /* 2384 80011B84 581F0A80 */ .word .L800A1F58
    /* 2388 80011B88 581F0A80 */ .word .L800A1F58
    /* 238C 80011B8C 581F0A80 */ .word .L800A1F58
    /* 2390 80011B90 581F0A80 */ .word .L800A1F58
    /* 2394 80011B94 581F0A80 */ .word .L800A1F58
    /* 2398 80011B98 581F0A80 */ .word .L800A1F58
    /* 239C 80011B9C 581F0A80 */ .word .L800A1F58
    /* 23A0 80011BA0 581F0A80 */ .word .L800A1F58
    /* 23A4 80011BA4 581F0A80 */ .word .L800A1F58
    /* 23A8 80011BA8 581F0A80 */ .word .L800A1F58
    /* 23AC 80011BAC 581F0A80 */ .word .L800A1F58
    /* 23B0 80011BB0 581F0A80 */ .word .L800A1F58
    /* 23B4 80011BB4 581F0A80 */ .word .L800A1F58
    /* 23B8 80011BB8 581F0A80 */ .word .L800A1F58
    /* 23BC 80011BBC 581F0A80 */ .word .L800A1F58
    /* 23C0 80011BC0 581F0A80 */ .word .L800A1F58
    /* 23C4 80011BC4 581F0A80 */ .word .L800A1F58
    /* 23C8 80011BC8 581F0A80 */ .word .L800A1F58
    /* 23CC 80011BCC 581F0A80 */ .word .L800A1F58
    /* 23D0 80011BD0 581F0A80 */ .word .L800A1F58
    /* 23D4 80011BD4 581F0A80 */ .word .L800A1F58
    /* 23D8 80011BD8 581F0A80 */ .word .L800A1F58
    /* 23DC 80011BDC 581F0A80 */ .word .L800A1F58
    /* 23E0 80011BE0 581F0A80 */ .word .L800A1F58
    /* 23E4 80011BE4 581F0A80 */ .word .L800A1F58
    /* 23E8 80011BE8 581F0A80 */ .word .L800A1F58
    /* 23EC 80011BEC AC1E0A80 */ .word .L800A1EAC
    /* 23F0 80011BF0 581F0A80 */ .word .L800A1F58
    /* 23F4 80011BF4 581F0A80 */ .word .L800A1F58
    /* 23F8 80011BF8 581F0A80 */ .word .L800A1F58
    /* 23FC 80011BFC 581F0A80 */ .word .L800A1F58
    /* 2400 80011C00 581F0A80 */ .word .L800A1F58
    /* 2404 80011C04 581F0A80 */ .word .L800A1F58
    /* 2408 80011C08 581F0A80 */ .word .L800A1F58
    /* 240C 80011C0C 581F0A80 */ .word .L800A1F58
    /* 2410 80011C10 581F0A80 */ .word .L800A1F58
    /* 2414 80011C14 581F0A80 */ .word .L800A1F58
    /* 2418 80011C18 581F0A80 */ .word .L800A1F58
    /* 241C 80011C1C 581F0A80 */ .word .L800A1F58
    /* 2420 80011C20 581F0A80 */ .word .L800A1F58
    /* 2424 80011C24 581F0A80 */ .word .L800A1F58
    /* 2428 80011C28 581F0A80 */ .word .L800A1F58
    /* 242C 80011C2C 581F0A80 */ .word .L800A1F58
    /* 2430 80011C30 581F0A80 */ .word .L800A1F58
    /* 2434 80011C34 581F0A80 */ .word .L800A1F58
    /* 2438 80011C38 581F0A80 */ .word .L800A1F58
    /* 243C 80011C3C 581F0A80 */ .word .L800A1F58
    /* 2440 80011C40 581F0A80 */ .word .L800A1F58
    /* 2444 80011C44 581F0A80 */ .word .L800A1F58
    /* 2448 80011C48 581F0A80 */ .word .L800A1F58
    /* 244C 80011C4C 581F0A80 */ .word .L800A1F58
    /* 2450 80011C50 581F0A80 */ .word .L800A1F58
    /* 2454 80011C54 581F0A80 */ .word .L800A1F58
    /* 2458 80011C58 581F0A80 */ .word .L800A1F58
    /* 245C 80011C5C 581F0A80 */ .word .L800A1F58
    /* 2460 80011C60 581F0A80 */ .word .L800A1F58
    /* 2464 80011C64 581F0A80 */ .word .L800A1F58
    /* 2468 80011C68 581F0A80 */ .word .L800A1F58
    /* 246C 80011C6C 581F0A80 */ .word .L800A1F58
    /* 2470 80011C70 581F0A80 */ .word .L800A1F58
    /* 2474 80011C74 581F0A80 */ .word .L800A1F58
    /* 2478 80011C78 581F0A80 */ .word .L800A1F58
    /* 247C 80011C7C 581F0A80 */ .word .L800A1F58
    /* 2480 80011C80 581F0A80 */ .word .L800A1F58
    /* 2484 80011C84 581F0A80 */ .word .L800A1F58
    /* 2488 80011C88 581F0A80 */ .word .L800A1F58
    /* 248C 80011C8C 581F0A80 */ .word .L800A1F58
    /* 2490 80011C90 581F0A80 */ .word .L800A1F58
    /* 2494 80011C94 3C1F0A80 */ .word .L800A1F3C
    /* 2498 80011C98 341F0A80 */ .word .L800A1F34
    /* 249C 80011C9C 2C1F0A80 */ .word .L800A1F2C
    /* 24A0 80011CA0 441F0A80 */ .word .L800A1F44
    /* 24A4 80011CA4 581F0A80 */ .word .L800A1F58
    /* 24A8 80011CA8 241F0A80 */ .word .L800A1F24
    /* 24AC 80011CAC 4C1F0A80 */ .word .L800A1F4C
    /* 24B0 80011CB0 541F0A80 */ .word .L800A1F54
    /* 24B4 80011CB4 1C1F0A80 */ .word .L800A1F1C
enddlabel jtbl_80011B44


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800A1B74, 0x538

glabel func_800A1B74
    /* 92374 800A1B74 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 92378 800A1B78 3C00BFAF */  sw         $ra, 0x3C($sp)
    /* 9237C 800A1B7C 3800B4AF */  sw         $s4, 0x38($sp)
    /* 92380 800A1B80 3400B3AF */  sw         $s3, 0x34($sp)
    /* 92384 800A1B84 3000B2AF */  sw         $s2, 0x30($sp)
    /* 92388 800A1B88 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* 9238C 800A1B8C 2800B0AF */  sw         $s0, 0x28($sp)
    /* 92390 800A1B90 9405888F */  lw         $t0, %gp_rel(D_80158A6C)($gp)
    /* 92394 800A1B94 00000000 */  nop
    /* 92398 800A1B98 0A000229 */  slti       $v0, $t0, 0xA
    /* 9239C 800A1B9C 2F004010 */  beqz       $v0, .L800A1C5C
    /* 923A0 800A1BA0 FFFFA330 */   andi      $v1, $a1, 0xFFFF
    /* 923A4 800A1BA4 0F000224 */  addiu      $v0, $zero, 0xF
    /* 923A8 800A1BA8 32016214 */  bne        $v1, $v0, .L800A2074
    /* 923AC 800A1BAC FFFFA530 */   andi      $a1, $a1, 0xFFFF
    /* 923B0 800A1BB0 40210800 */  sll        $a0, $t0, 5
    /* 923B4 800A1BB4 40180800 */  sll        $v1, $t0, 1
    /* 923B8 800A1BB8 21186800 */  addu       $v1, $v1, $t0
    /* 923BC 800A1BBC C0180300 */  sll        $v1, $v1, 3
    /* 923C0 800A1BC0 1000A0A7 */  sh         $zero, 0x10($sp)
    /* 923C4 800A1BC4 F0000224 */  addiu      $v0, $zero, 0xF0
    /* 923C8 800A1BC8 23104300 */  subu       $v0, $v0, $v1
    /* 923CC 800A1BCC 1200A2A7 */  sh         $v0, 0x12($sp)
    /* 923D0 800A1BD0 1400A4A7 */  sh         $a0, 0x14($sp)
    /* 923D4 800A1BD4 F0000224 */  addiu      $v0, $zero, 0xF0
    /* 923D8 800A1BD8 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 923DC 800A1BDC 1000A427 */  addiu      $a0, $sp, 0x10
    /* 923E0 800A1BE0 A314020C */  jal        func_8008528C
    /* 923E4 800A1BE4 21280000 */   addu      $a1, $zero, $zero
    /* 923E8 800A1BE8 1000A297 */  lhu        $v0, 0x10($sp)
    /* 923EC 800A1BEC 00000000 */  nop
    /* 923F0 800A1BF0 03004224 */  addiu      $v0, $v0, 0x3
    /* 923F4 800A1BF4 1000A2A7 */  sh         $v0, 0x10($sp)
    /* 923F8 800A1BF8 1200A297 */  lhu        $v0, 0x12($sp)
    /* 923FC 800A1BFC 00000000 */  nop
    /* 92400 800A1C00 10004224 */  addiu      $v0, $v0, 0x10
    /* 92404 800A1C04 1200A2A7 */  sh         $v0, 0x12($sp)
    /* 92408 800A1C08 1400A297 */  lhu        $v0, 0x14($sp)
    /* 9240C 800A1C0C 00000000 */  nop
    /* 92410 800A1C10 FCFF4224 */  addiu      $v0, $v0, -0x4
    /* 92414 800A1C14 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 92418 800A1C18 1600A297 */  lhu        $v0, 0x16($sp)
    /* 9241C 800A1C1C 00000000 */  nop
    /* 92420 800A1C20 F0FF4224 */  addiu      $v0, $v0, -0x10
    /* 92424 800A1C24 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 92428 800A1C28 1480043C */  lui        $a0, %hi(D_801388D0)
    /* 9242C 800A1C2C D0888424 */  addiu      $a0, $a0, %lo(D_801388D0)
    /* 92430 800A1C30 1280053C */  lui        $a1, %hi(D_8011E758)
    /* 92434 800A1C34 58E7A524 */  addiu      $a1, $a1, %lo(D_8011E758)
    /* 92438 800A1C38 21300000 */  addu       $a2, $zero, $zero
    /* 9243C 800A1C3C F5E4030C */  jal        func_800F93D4
    /* 92440 800A1C40 1000A727 */   addiu     $a3, $sp, 0x10
    /* 92444 800A1C44 9405828F */  lw         $v0, %gp_rel(D_80158A6C)($gp)
    /* 92448 800A1C48 00000000 */  nop
    /* 9244C 800A1C4C 01004224 */  addiu      $v0, $v0, 0x1
    /* 92450 800A1C50 940582AF */  sw         $v0, %gp_rel(D_80158A6C)($gp)
    /* 92454 800A1C54 4C870208 */  j          .L800A1D30
    /* 92458 800A1C58 02000224 */   addiu     $v0, $zero, 0x2
  .L800A1C5C:
    /* 9245C 800A1C5C 0B000229 */  slti       $v0, $t0, 0xB
    /* 92460 800A1C60 37004014 */  bnez       $v0, .L800A1D40
    /* 92464 800A1C64 0F000224 */   addiu     $v0, $zero, 0xF
    /* 92468 800A1C68 FFFFA330 */  andi       $v1, $a1, 0xFFFF
    /* 9246C 800A1C6C 01016214 */  bne        $v1, $v0, .L800A2074
    /* 92470 800A1C70 FFFFA530 */   andi      $a1, $a1, 0xFFFF
    /* 92474 800A1C74 15000224 */  addiu      $v0, $zero, 0x15
    /* 92478 800A1C78 23104800 */  subu       $v0, $v0, $t0
    /* 9247C 800A1C7C 40210200 */  sll        $a0, $v0, 5
    /* 92480 800A1C80 40180200 */  sll        $v1, $v0, 1
    /* 92484 800A1C84 21186200 */  addu       $v1, $v1, $v0
    /* 92488 800A1C88 C0180300 */  sll        $v1, $v1, 3
    /* 9248C 800A1C8C 1000A0A7 */  sh         $zero, 0x10($sp)
    /* 92490 800A1C90 F0000224 */  addiu      $v0, $zero, 0xF0
    /* 92494 800A1C94 23104300 */  subu       $v0, $v0, $v1
    /* 92498 800A1C98 1200A2A7 */  sh         $v0, 0x12($sp)
    /* 9249C 800A1C9C 1400A4A7 */  sh         $a0, 0x14($sp)
    /* 924A0 800A1CA0 F0000224 */  addiu      $v0, $zero, 0xF0
    /* 924A4 800A1CA4 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 924A8 800A1CA8 1000A427 */  addiu      $a0, $sp, 0x10
    /* 924AC 800A1CAC A314020C */  jal        func_8008528C
    /* 924B0 800A1CB0 21280000 */   addu      $a1, $zero, $zero
    /* 924B4 800A1CB4 1000A297 */  lhu        $v0, 0x10($sp)
    /* 924B8 800A1CB8 00000000 */  nop
    /* 924BC 800A1CBC 03004224 */  addiu      $v0, $v0, 0x3
    /* 924C0 800A1CC0 1000A2A7 */  sh         $v0, 0x10($sp)
    /* 924C4 800A1CC4 1200A297 */  lhu        $v0, 0x12($sp)
    /* 924C8 800A1CC8 00000000 */  nop
    /* 924CC 800A1CCC 10004224 */  addiu      $v0, $v0, 0x10
    /* 924D0 800A1CD0 1200A2A7 */  sh         $v0, 0x12($sp)
    /* 924D4 800A1CD4 1400A297 */  lhu        $v0, 0x14($sp)
    /* 924D8 800A1CD8 00000000 */  nop
    /* 924DC 800A1CDC FCFF4224 */  addiu      $v0, $v0, -0x4
    /* 924E0 800A1CE0 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 924E4 800A1CE4 1600A297 */  lhu        $v0, 0x16($sp)
    /* 924E8 800A1CE8 00000000 */  nop
    /* 924EC 800A1CEC F0FF4224 */  addiu      $v0, $v0, -0x10
    /* 924F0 800A1CF0 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 924F4 800A1CF4 1480043C */  lui        $a0, %hi(D_801388D0)
    /* 924F8 800A1CF8 D0888424 */  addiu      $a0, $a0, %lo(D_801388D0)
    /* 924FC 800A1CFC 1280053C */  lui        $a1, %hi(D_8011E758)
    /* 92500 800A1D00 58E7A524 */  addiu      $a1, $a1, %lo(D_8011E758)
    /* 92504 800A1D04 21300000 */  addu       $a2, $zero, $zero
    /* 92508 800A1D08 F5E4030C */  jal        func_800F93D4
    /* 9250C 800A1D0C 1000A727 */   addiu     $a3, $sp, 0x10
    /* 92510 800A1D10 9405828F */  lw         $v0, %gp_rel(D_80158A6C)($gp)
    /* 92514 800A1D14 00000000 */  nop
    /* 92518 800A1D18 01004224 */  addiu      $v0, $v0, 0x1
    /* 9251C 800A1D1C 940582AF */  sw         $v0, %gp_rel(D_80158A6C)($gp)
    /* 92520 800A1D20 16004228 */  slti       $v0, $v0, 0x16
    /* 92524 800A1D24 02004014 */  bnez       $v0, .L800A1D30
    /* 92528 800A1D28 02000224 */   addiu     $v0, $zero, 0x2
    /* 9252C 800A1D2C 940580AF */  sw         $zero, %gp_rel(D_80158A6C)($gp)
  .L800A1D30:
    /* 92530 800A1D30 1680013C */  lui        $at, %hi(D_801584EC)
    /* 92534 800A1D34 EC8422AC */  sw         $v0, %lo(D_801584EC)($at)
    /* 92538 800A1D38 22880208 */  j          .L800A2088
    /* 9253C 800A1D3C 21100000 */   addu      $v0, $zero, $zero
  .L800A1D40:
    /* 92540 800A1D40 05006210 */  beq        $v1, $v0, .L800A1D58
    /* 92544 800A1D44 00010224 */   addiu     $v0, $zero, 0x100
    /* 92548 800A1D48 4D006210 */  beq        $v1, $v0, .L800A1E80
    /* 9254C 800A1D4C FFFFC230 */   andi      $v0, $a2, 0xFFFF
    /* 92550 800A1D50 1D880208 */  j          .L800A2074
    /* 92554 800A1D54 FFFFA530 */   andi      $a1, $a1, 0xFFFF
  .L800A1D58:
    /* 92558 800A1D58 7907040C */  jal        func_80101DE4
    /* 9255C 800A1D5C 01000424 */   addiu     $a0, $zero, 0x1
    /* 92560 800A1D60 1680043C */  lui        $a0, %hi(D_80158886)
    /* 92564 800A1D64 86888484 */  lh         $a0, %lo(D_80158886)($a0)
    /* 92568 800A1D68 1680053C */  lui        $a1, %hi(D_80158888)
    /* 9256C 800A1D6C 8888A584 */  lh         $a1, %lo(D_80158888)($a1)
    /* 92570 800A1D70 2000A627 */  addiu      $a2, $sp, 0x20
    /* 92574 800A1D74 EE7D030C */  jal        func_800DF7B8
    /* 92578 800A1D78 2400A727 */   addiu     $a3, $sp, 0x24
    /* 9257C 800A1D7C 1480043C */  lui        $a0, %hi(D_801388EC)
    /* 92580 800A1D80 EC88848C */  lw         $a0, %lo(D_801388EC)($a0)
    /* 92584 800A1D84 00000000 */  nop
    /* 92588 800A1D88 0C008294 */  lhu        $v0, 0xC($a0)
    /* 9258C 800A1D8C 2000A397 */  lhu        $v1, 0x20($sp)
    /* 92590 800A1D90 00000000 */  nop
    /* 92594 800A1D94 21104300 */  addu       $v0, $v0, $v1
    /* 92598 800A1D98 1800A2A7 */  sh         $v0, 0x18($sp)
    /* 9259C 800A1D9C 0E008294 */  lhu        $v0, 0xE($a0)
    /* 925A0 800A1DA0 2400A397 */  lhu        $v1, 0x24($sp)
    /* 925A4 800A1DA4 00000000 */  nop
    /* 925A8 800A1DA8 21104300 */  addu       $v0, $v0, $v1
    /* 925AC 800A1DAC 1A00A2A7 */  sh         $v0, 0x1A($sp)
    /* 925B0 800A1DB0 01000224 */  addiu      $v0, $zero, 0x1
    /* 925B4 800A1DB4 1C00A2A7 */  sh         $v0, 0x1C($sp)
    /* 925B8 800A1DB8 1E00A2A7 */  sh         $v0, 0x1E($sp)
    /* 925BC 800A1DBC 1680023C */  lui        $v0, %hi(D_80158874)
    /* 925C0 800A1DC0 74884290 */  lbu        $v0, %lo(D_80158874)($v0)
    /* 925C4 800A1DC4 00000000 */  nop
    /* 925C8 800A1DC8 06004010 */  beqz       $v0, .L800A1DE4
    /* 925CC 800A1DCC FF7F0224 */   addiu     $v0, $zero, 0x7FFF
    /* 925D0 800A1DD0 1280053C */  lui        $a1, %hi(D_8011EAC0)
    /* 925D4 800A1DD4 C0EAA524 */  addiu      $a1, $a1, %lo(D_8011EAC0)
    /* 925D8 800A1DD8 0000A2AC */  sw         $v0, 0x0($a1)
    /* 925DC 800A1DDC 7C870208 */  j          .L800A1DF0
    /* 925E0 800A1DE0 1800A427 */   addiu     $a0, $sp, 0x18
  .L800A1DE4:
    /* 925E4 800A1DE4 1800A427 */  addiu      $a0, $sp, 0x18
    /* 925E8 800A1DE8 1280053C */  lui        $a1, %hi(D_8011EABC)
    /* 925EC 800A1DEC BCEAA524 */  addiu      $a1, $a1, %lo(D_8011EABC)
  .L800A1DF0:
    /* 925F0 800A1DF0 D78D030C */  jal        LoadImage
    /* 925F4 800A1DF4 00000000 */   nop
    /* 925F8 800A1DF8 1000A0A7 */  sh         $zero, 0x10($sp)
    /* 925FC 800A1DFC 1200A0A7 */  sh         $zero, 0x12($sp)
    /* 92600 800A1E00 40010224 */  addiu      $v0, $zero, 0x140
    /* 92604 800A1E04 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 92608 800A1E08 F0000224 */  addiu      $v0, $zero, 0xF0
    /* 9260C 800A1E0C 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 92610 800A1E10 1000A427 */  addiu      $a0, $sp, 0x10
    /* 92614 800A1E14 A314020C */  jal        func_8008528C
    /* 92618 800A1E18 21280000 */   addu      $a1, $zero, $zero
    /* 9261C 800A1E1C 1000A297 */  lhu        $v0, 0x10($sp)
    /* 92620 800A1E20 00000000 */  nop
    /* 92624 800A1E24 03004224 */  addiu      $v0, $v0, 0x3
    /* 92628 800A1E28 1000A2A7 */  sh         $v0, 0x10($sp)
    /* 9262C 800A1E2C 1200A297 */  lhu        $v0, 0x12($sp)
    /* 92630 800A1E30 00000000 */  nop
    /* 92634 800A1E34 10004224 */  addiu      $v0, $v0, 0x10
    /* 92638 800A1E38 1200A2A7 */  sh         $v0, 0x12($sp)
    /* 9263C 800A1E3C 1400A297 */  lhu        $v0, 0x14($sp)
    /* 92640 800A1E40 00000000 */  nop
    /* 92644 800A1E44 FCFF4224 */  addiu      $v0, $v0, -0x4
    /* 92648 800A1E48 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 9264C 800A1E4C 1600A297 */  lhu        $v0, 0x16($sp)
    /* 92650 800A1E50 00000000 */  nop
    /* 92654 800A1E54 F0FF4224 */  addiu      $v0, $v0, -0x10
    /* 92658 800A1E58 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 9265C 800A1E5C 1480043C */  lui        $a0, %hi(D_801388D0)
    /* 92660 800A1E60 D0888424 */  addiu      $a0, $a0, %lo(D_801388D0)
    /* 92664 800A1E64 1280053C */  lui        $a1, %hi(D_8011E758)
    /* 92668 800A1E68 58E7A524 */  addiu      $a1, $a1, %lo(D_8011E758)
    /* 9266C 800A1E6C 21300000 */  addu       $a2, $zero, $zero
    /* 92670 800A1E70 F5E4030C */  jal        func_800F93D4
    /* 92674 800A1E74 1000A727 */   addiu     $a3, $sp, 0x10
    /* 92678 800A1E78 22880208 */  j          .L800A2088
    /* 9267C 800A1E7C 21100000 */   addu      $v0, $zero, $zero
  .L800A1E80:
    /* 92680 800A1E80 F3FF4324 */  addiu      $v1, $v0, -0xD
    /* 92684 800A1E84 5D00622C */  sltiu      $v0, $v1, 0x5D
    /* 92688 800A1E88 33004010 */  beqz       $v0, .L800A1F58
    /* 9268C 800A1E8C FFFF1424 */   addiu     $s4, $zero, -0x1
    /* 92690 800A1E90 80100300 */  sll        $v0, $v1, 2
    /* 92694 800A1E94 0180013C */  lui        $at, %hi(jtbl_80011B44)
    /* 92698 800A1E98 21082200 */  addu       $at, $at, $v0
    /* 9269C 800A1E9C 441B228C */  lw         $v0, %lo(jtbl_80011B44)($at)
    /* 926A0 800A1EA0 00000000 */  nop
    /* 926A4 800A1EA4 08004000 */  jr         $v0
    /* 926A8 800A1EA8 00000000 */   nop
  .L800A1EAC:
    /* 926AC 800A1EAC 68000424 */  addiu      $a0, $zero, 0x68
    /* 926B0 800A1EB0 21280000 */  addu       $a1, $zero, $zero
    /* 926B4 800A1EB4 21300000 */  addu       $a2, $zero, $zero
    /* 926B8 800A1EB8 2B9D020C */  jal        func_800A74AC
    /* 926BC 800A1EBC 21380000 */   addu      $a3, $zero, $zero
    /* 926C0 800A1EC0 9405828F */  lw         $v0, %gp_rel(D_80158A6C)($gp)
    /* 926C4 800A1EC4 00000000 */  nop
    /* 926C8 800A1EC8 01004224 */  addiu      $v0, $v0, 0x1
    /* 926CC 800A1ECC 940582AF */  sw         $v0, %gp_rel(D_80158A6C)($gp)
    /* 926D0 800A1ED0 1C05848F */  lw         $a0, %gp_rel(D_801589F4)($gp)
    /* 926D4 800A1ED4 00000000 */  nop
    /* 926D8 800A1ED8 04008010 */  beqz       $a0, .L800A1EEC
    /* 926DC 800A1EDC 00000000 */   nop
    /* 926E0 800A1EE0 E511040C */  jal        func_80104794
    /* 926E4 800A1EE4 00000000 */   nop
    /* 926E8 800A1EE8 1C0580AF */  sw         $zero, %gp_rel(D_801589F4)($gp)
  .L800A1EEC:
    /* 926EC 800A1EEC 1280043C */  lui        $a0, %hi(D_8011E72C)
    /* 926F0 800A1EF0 2CE78424 */  addiu      $a0, $a0, %lo(D_8011E72C)
    /* 926F4 800A1EF4 1680053C */  lui        $a1, %hi(D_80158886)
    /* 926F8 800A1EF8 8688A584 */  lh         $a1, %lo(D_80158886)($a1)
    /* 926FC 800A1EFC 1680063C */  lui        $a2, %hi(D_80158888)
    /* 92700 800A1F00 8888C684 */  lh         $a2, %lo(D_80158888)($a2)
    /* 92704 800A1F04 D37B020C */  jal        func_8009EF4C
    /* 92708 800A1F08 00000000 */   nop
    /* 9270C 800A1F0C 5674020C */  jal        func_8009D158
    /* 92710 800A1F10 00000000 */   nop
    /* 92714 800A1F14 D6870208 */  j          .L800A1F58
    /* 92718 800A1F18 00000000 */   nop
  .L800A1F1C:
    /* 9271C 800A1F1C D6870208 */  j          .L800A1F58
    /* 92720 800A1F20 21A00000 */   addu      $s4, $zero, $zero
  .L800A1F24:
    /* 92724 800A1F24 D6870208 */  j          .L800A1F58
    /* 92728 800A1F28 01001424 */   addiu     $s4, $zero, 0x1
  .L800A1F2C:
    /* 9272C 800A1F2C D6870208 */  j          .L800A1F58
    /* 92730 800A1F30 02001424 */   addiu     $s4, $zero, 0x2
  .L800A1F34:
    /* 92734 800A1F34 D6870208 */  j          .L800A1F58
    /* 92738 800A1F38 03001424 */   addiu     $s4, $zero, 0x3
  .L800A1F3C:
    /* 9273C 800A1F3C D6870208 */  j          .L800A1F58
    /* 92740 800A1F40 04001424 */   addiu     $s4, $zero, 0x4
  .L800A1F44:
    /* 92744 800A1F44 D6870208 */  j          .L800A1F58
    /* 92748 800A1F48 05001424 */   addiu     $s4, $zero, 0x5
  .L800A1F4C:
    /* 9274C 800A1F4C D6870208 */  j          .L800A1F58
    /* 92750 800A1F50 06001424 */   addiu     $s4, $zero, 0x6
  .L800A1F54:
    /* 92754 800A1F54 07001424 */  addiu      $s4, $zero, 0x7
  .L800A1F58:
    /* 92758 800A1F58 4A008006 */  bltz       $s4, .L800A2084
    /* 9275C 800A1F5C 2000B227 */   addiu     $s2, $sp, 0x20
    /* 92760 800A1F60 2400B327 */  addiu      $s3, $sp, 0x24
    /* 92764 800A1F64 1680043C */  lui        $a0, %hi(D_80158886)
    /* 92768 800A1F68 86888484 */  lh         $a0, %lo(D_80158886)($a0)
    /* 9276C 800A1F6C 1680053C */  lui        $a1, %hi(D_80158888)
    /* 92770 800A1F70 8888A584 */  lh         $a1, %lo(D_80158888)($a1)
    /* 92774 800A1F74 21304002 */  addu       $a2, $s2, $zero
    /* 92778 800A1F78 EE7D030C */  jal        func_800DF7B8
    /* 9277C 800A1F7C 21386002 */   addu      $a3, $s3, $zero
    /* 92780 800A1F80 1480043C */  lui        $a0, %hi(D_801388EC)
    /* 92784 800A1F84 EC88848C */  lw         $a0, %lo(D_801388EC)($a0)
    /* 92788 800A1F88 00000000 */  nop
    /* 9278C 800A1F8C 0C008294 */  lhu        $v0, 0xC($a0)
    /* 92790 800A1F90 2000A397 */  lhu        $v1, 0x20($sp)
    /* 92794 800A1F94 00000000 */  nop
    /* 92798 800A1F98 21104300 */  addu       $v0, $v0, $v1
    /* 9279C 800A1F9C 1800A2A7 */  sh         $v0, 0x18($sp)
    /* 927A0 800A1FA0 0E008294 */  lhu        $v0, 0xE($a0)
    /* 927A4 800A1FA4 2400A397 */  lhu        $v1, 0x24($sp)
    /* 927A8 800A1FA8 00000000 */  nop
    /* 927AC 800A1FAC 21104300 */  addu       $v0, $v0, $v1
    /* 927B0 800A1FB0 1A00A2A7 */  sh         $v0, 0x1A($sp)
    /* 927B4 800A1FB4 01001024 */  addiu      $s0, $zero, 0x1
    /* 927B8 800A1FB8 1C00B0A7 */  sh         $s0, 0x1C($sp)
    /* 927BC 800A1FBC 1E00B0A7 */  sh         $s0, 0x1E($sp)
    /* 927C0 800A1FC0 1800B127 */  addiu      $s1, $sp, 0x18
    /* 927C4 800A1FC4 1280053C */  lui        $a1, %hi(D_8011EABC)
    /* 927C8 800A1FC8 BCEAA524 */  addiu      $a1, $a1, %lo(D_8011EABC)
    /* 927CC 800A1FCC D78D030C */  jal        LoadImage
    /* 927D0 800A1FD0 21202002 */   addu      $a0, $s1, $zero
    /* 927D4 800A1FD4 21208002 */  addu       $a0, $s4, $zero
    /* 927D8 800A1FD8 0880020C */  jal        func_800A0020
    /* 927DC 800A1FDC 21280000 */   addu      $a1, $zero, $zero
    /* 927E0 800A1FE0 01000224 */  addiu      $v0, $zero, 0x1
    /* 927E4 800A1FE4 1680013C */  lui        $at, %hi(D_80158874)
    /* 927E8 800A1FE8 748822A0 */  sb         $v0, %lo(D_80158874)($at)
    /* 927EC 800A1FEC 1680043C */  lui        $a0, %hi(D_80158886)
    /* 927F0 800A1FF0 86888484 */  lh         $a0, %lo(D_80158886)($a0)
    /* 927F4 800A1FF4 1680053C */  lui        $a1, %hi(D_80158888)
    /* 927F8 800A1FF8 8888A584 */  lh         $a1, %lo(D_80158888)($a1)
    /* 927FC 800A1FFC 21304002 */  addu       $a2, $s2, $zero
    /* 92800 800A2000 EE7D030C */  jal        func_800DF7B8
    /* 92804 800A2004 21386002 */   addu      $a3, $s3, $zero
    /* 92808 800A2008 1480043C */  lui        $a0, %hi(D_801388EC)
    /* 9280C 800A200C EC88848C */  lw         $a0, %lo(D_801388EC)($a0)
    /* 92810 800A2010 00000000 */  nop
    /* 92814 800A2014 0C008294 */  lhu        $v0, 0xC($a0)
    /* 92818 800A2018 2000A397 */  lhu        $v1, 0x20($sp)
    /* 9281C 800A201C 00000000 */  nop
    /* 92820 800A2020 21104300 */  addu       $v0, $v0, $v1
    /* 92824 800A2024 1800A2A7 */  sh         $v0, 0x18($sp)
    /* 92828 800A2028 0E008294 */  lhu        $v0, 0xE($a0)
    /* 9282C 800A202C 2400A397 */  lhu        $v1, 0x24($sp)
    /* 92830 800A2030 00000000 */  nop
    /* 92834 800A2034 21104300 */  addu       $v0, $v0, $v1
    /* 92838 800A2038 1A00A2A7 */  sh         $v0, 0x1A($sp)
    /* 9283C 800A203C 1C00B0A7 */  sh         $s0, 0x1C($sp)
    /* 92840 800A2040 1E00B0A7 */  sh         $s0, 0x1E($sp)
    /* 92844 800A2044 1280053C */  lui        $a1, %hi(D_8011EABC)
    /* 92848 800A2048 BCEAA524 */  addiu      $a1, $a1, %lo(D_8011EABC)
    /* 9284C 800A204C EF8D030C */  jal        StoreImage
    /* 92850 800A2050 21202002 */   addu      $a0, $s1, $zero
    /* 92854 800A2054 1280053C */  lui        $a1, %hi(D_8011EAC0)
    /* 92858 800A2058 C0EAA524 */  addiu      $a1, $a1, %lo(D_8011EAC0)
    /* 9285C 800A205C FF7F0224 */  addiu      $v0, $zero, 0x7FFF
    /* 92860 800A2060 0000A2AC */  sw         $v0, 0x0($a1)
    /* 92864 800A2064 D78D030C */  jal        LoadImage
    /* 92868 800A2068 21202002 */   addu      $a0, $s1, $zero
    /* 9286C 800A206C 22880208 */  j          .L800A2088
    /* 92870 800A2070 21100000 */   addu      $v0, $zero, $zero
  .L800A2074:
    /* 92874 800A2074 761B040C */  jal        func_80106DD8
    /* 92878 800A2078 FFFFC630 */   andi      $a2, $a2, 0xFFFF
    /* 9287C 800A207C 22880208 */  j          .L800A2088
    /* 92880 800A2080 00000000 */   nop
  .L800A2084:
    /* 92884 800A2084 21100000 */  addu       $v0, $zero, $zero
  .L800A2088:
    /* 92888 800A2088 3C00BF8F */  lw         $ra, 0x3C($sp)
    /* 9288C 800A208C 3800B48F */  lw         $s4, 0x38($sp)
    /* 92890 800A2090 3400B38F */  lw         $s3, 0x34($sp)
    /* 92894 800A2094 3000B28F */  lw         $s2, 0x30($sp)
    /* 92898 800A2098 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 9289C 800A209C 2800B08F */  lw         $s0, 0x28($sp)
    /* 928A0 800A20A0 4000BD27 */  addiu      $sp, $sp, 0x40
    /* 928A4 800A20A4 0800E003 */  jr         $ra
    /* 928A8 800A20A8 00000000 */   nop
endlabel func_800A1B74
