.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80012270

dlabel D_80012270
    /* 2A70 80012270 */ .asciz "MAINMENU"
    /* 4D41494E4D454E5500000000 */
.align 2
enddlabel D_80012270


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800B8910, 0x110

glabel func_800B8910
    /* A9110 800B8910 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* A9114 800B8914 3C00BFAF */  sw         $ra, 0x3C($sp)
    /* A9118 800B8918 3800B4AF */  sw         $s4, 0x38($sp)
    /* A911C 800B891C 3400B3AF */  sw         $s3, 0x34($sp)
    /* A9120 800B8920 3000B2AF */  sw         $s2, 0x30($sp)
    /* A9124 800B8924 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* A9128 800B8928 2800B0AF */  sw         $s0, 0x28($sp)
    /* A912C 800B892C 21808000 */  addu       $s0, $a0, $zero
    /* A9130 800B8930 2188A000 */  addu       $s1, $a1, $zero
    /* A9134 800B8934 2190C000 */  addu       $s2, $a2, $zero
    /* A9138 800B8938 2198E000 */  addu       $s3, $a3, $zero
    /* A913C 800B893C 5000B48F */  lw         $s4, 0x50($sp)
    /* A9140 800B8940 0180053C */  lui        $a1, %hi(D_80012270)
    /* A9144 800B8944 7022A524 */  addiu      $a1, $a1, %lo(D_80012270)
    /* A9148 800B8948 9D87030C */  jal        func_800E1E74
    /* A914C 800B894C 21202002 */   addu      $a0, $s1, $zero
    /* A9150 800B8950 09004014 */  bnez       $v0, .L800B8978
    /* A9154 800B8954 21200002 */   addu      $a0, $s0, $zero
    /* A9158 800B8958 1000A0AF */  sw         $zero, 0x10($sp)
    /* A915C 800B895C 1400A0AF */  sw         $zero, 0x14($sp)
    /* A9160 800B8960 1800A0AF */  sw         $zero, 0x18($sp)
    /* A9164 800B8964 1C00A0AF */  sw         $zero, 0x1C($sp)
    /* A9168 800B8968 2000A0AF */  sw         $zero, 0x20($sp)
    /* A916C 800B896C 21282002 */  addu       $a1, $s1, $zero
    /* A9170 800B8970 65E20208 */  j          .L800B8994
    /* A9174 800B8974 21300000 */   addu      $a2, $zero, $zero
  .L800B8978:
    /* A9178 800B8978 1000A0AF */  sw         $zero, 0x10($sp)
    /* A917C 800B897C 1400A0AF */  sw         $zero, 0x14($sp)
    /* A9180 800B8980 1800A0AF */  sw         $zero, 0x18($sp)
    /* A9184 800B8984 1C00A0AF */  sw         $zero, 0x1C($sp)
    /* A9188 800B8988 2000A0AF */  sw         $zero, 0x20($sp)
    /* A918C 800B898C 21282002 */  addu       $a1, $s1, $zero
    /* A9190 800B8990 01000624 */  addiu      $a2, $zero, 0x1
  .L800B8994:
    /* A9194 800B8994 2CE0020C */  jal        func_800B80B0
    /* A9198 800B8998 21380000 */   addu      $a3, $zero, $zero
    /* A919C 800B899C CC0114AE */  sw         $s4, 0x1CC($s0)
    /* A91A0 800B89A0 000092AE */  sw         $s2, 0x0($s4)
    /* A91A4 800B89A4 CC01028E */  lw         $v0, 0x1CC($s0)
    /* A91A8 800B89A8 00000000 */  nop
    /* A91AC 800B89AC 040053AC */  sw         $s3, 0x4($v0)
    /* A91B0 800B89B0 21200002 */  addu       $a0, $s0, $zero
    /* A91B4 800B89B4 39C8020C */  jal        func_800B20E4
    /* A91B8 800B89B8 10010524 */   addiu     $a1, $zero, 0x110
    /* A91BC 800B89BC CC01028E */  lw         $v0, 0x1CC($s0)
    /* A91C0 800B89C0 00000000 */  nop
    /* A91C4 800B89C4 14004284 */  lh         $v0, 0x14($v0)
    /* A91C8 800B89C8 00000000 */  nop
    /* A91CC 800B89CC 40280200 */  sll        $a1, $v0, 1
    /* A91D0 800B89D0 2128A200 */  addu       $a1, $a1, $v0
    /* A91D4 800B89D4 C0280500 */  sll        $a1, $a1, 3
    /* A91D8 800B89D8 21200002 */  addu       $a0, $s0, $zero
    /* A91DC 800B89DC 58C8020C */  jal        func_800B2160
    /* A91E0 800B89E0 0800A524 */   addiu     $a1, $a1, 0x8
    /* A91E4 800B89E4 B8000224 */  addiu      $v0, $zero, 0xB8
    /* A91E8 800B89E8 1000068E */  lw         $a2, 0x10($s0)
    /* A91EC 800B89EC 21200002 */  addu       $a0, $s0, $zero
    /* A91F0 800B89F0 19FC0524 */  addiu      $a1, $zero, -0x3E7
    /* A91F4 800B89F4 5AC8020C */  jal        func_800B2168
    /* A91F8 800B89F8 23304600 */   subu      $a2, $v0, $a2
    /* A91FC 800B89FC 3C00BF8F */  lw         $ra, 0x3C($sp)
    /* A9200 800B8A00 3800B48F */  lw         $s4, 0x38($sp)
    /* A9204 800B8A04 3400B38F */  lw         $s3, 0x34($sp)
    /* A9208 800B8A08 3000B28F */  lw         $s2, 0x30($sp)
    /* A920C 800B8A0C 2C00B18F */  lw         $s1, 0x2C($sp)
    /* A9210 800B8A10 2800B08F */  lw         $s0, 0x28($sp)
    /* A9214 800B8A14 4000BD27 */  addiu      $sp, $sp, 0x40
    /* A9218 800B8A18 0800E003 */  jr         $ra
    /* A921C 800B8A1C 00000000 */   nop
endlabel func_800B8910
