.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_800121AC

dlabel D_800121AC
    /* 29AC 800121AC */ .asciz " J:%X '%c'\n"
    /* 204A3A255820272563270A00 */
.align 2
enddlabel D_800121AC


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800B4C74, 0x1D0

glabel func_800B4C74
    /* A5474 800B4C74 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* A5478 800B4C78 2400BFAF */  sw         $ra, 0x24($sp)
    /* A547C 800B4C7C 2000B4AF */  sw         $s4, 0x20($sp)
    /* A5480 800B4C80 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* A5484 800B4C84 1800B2AF */  sw         $s2, 0x18($sp)
    /* A5488 800B4C88 1400B1AF */  sw         $s1, 0x14($sp)
    /* A548C 800B4C8C 1000B0AF */  sw         $s0, 0x10($sp)
    /* A5490 800B4C90 680A828F */  lw         $v0, %gp_rel(D_80158F40)($gp)
    /* A5494 800B4C94 00000000 */  nop
    /* A5498 800B4C98 0A024384 */  lh         $v1, 0x20A($v0)
    /* A549C 800B4C9C 8001428C */  lw         $v0, 0x180($v0)
    /* A54A0 800B4CA0 00000000 */  nop
    /* A54A4 800B4CA4 0800428C */  lw         $v0, 0x8($v0)
    /* A54A8 800B4CA8 00000000 */  nop
    /* A54AC 800B4CAC FFFF4224 */  addiu      $v0, $v0, -0x1
    /* A54B0 800B4CB0 2A106200 */  slt        $v0, $v1, $v0
    /* A54B4 800B4CB4 4B004010 */  beqz       $v0, .L800B4DE4
    /* A54B8 800B4CB8 21988000 */   addu      $s3, $a0, $zero
    /* A54BC 800B4CBC 21906000 */  addu       $s2, $v1, $zero
    /* A54C0 800B4CC0 00007092 */  lbu        $s0, 0x0($s3)
    /* A54C4 800B4CC4 01006292 */  lbu        $v0, 0x1($s3)
    /* A54C8 800B4CC8 00000000 */  nop
    /* A54CC 800B4CCC 00120200 */  sll        $v0, $v0, 8
    /* A54D0 800B4CD0 25800202 */  or         $s0, $s0, $v0
    /* A54D4 800B4CD4 FFFF1032 */  andi       $s0, $s0, 0xFFFF
    /* A54D8 800B4CD8 190B040C */  jal        func_80102C64
    /* A54DC 800B4CDC 21200002 */   addu      $a0, $s0, $zero
    /* A54E0 800B4CE0 21A04000 */  addu       $s4, $v0, $zero
    /* A54E4 800B4CE4 FF009132 */  andi       $s1, $s4, 0xFF
    /* A54E8 800B4CE8 0180043C */  lui        $a0, %hi(D_800121AC)
    /* A54EC 800B4CEC AC218424 */  addiu      $a0, $a0, %lo(D_800121AC)
    /* A54F0 800B4CF0 21280002 */  addu       $a1, $s0, $zero
    /* A54F4 800B4CF4 4551000C */  jal        func_80014514
    /* A54F8 800B4CF8 21302002 */   addu      $a2, $s1, $zero
    /* A54FC 800B4CFC 17002012 */  beqz       $s1, .L800B4D5C
    /* A5500 800B4D00 00000000 */   nop
    /* A5504 800B4D04 1280013C */  lui        $at, %hi(D_80120D6C)
    /* A5508 800B4D08 21083200 */  addu       $at, $at, $s2
    /* A550C 800B4D0C 6C0D2290 */  lbu        $v0, %lo(D_80120D6C)($at)
    /* A5510 800B4D10 00000000 */  nop
    /* A5514 800B4D14 09004014 */  bnez       $v0, .L800B4D3C
    /* A5518 800B4D18 00000000 */   nop
    /* A551C 800B4D1C 1280013C */  lui        $at, %hi(D_80120D6C)
    /* A5520 800B4D20 21083200 */  addu       $at, $at, $s2
    /* A5524 800B4D24 6C0D34A0 */  sb         $s4, %lo(D_80120D6C)($at)
    /* A5528 800B4D28 1280013C */  lui        $at, %hi(D_80120D6D)
    /* A552C 800B4D2C 21083200 */  addu       $at, $at, $s2
    /* A5530 800B4D30 6D0D20A0 */  sb         $zero, %lo(D_80120D6D)($at)
    /* A5534 800B4D34 52D30208 */  j          .L800B4D48
    /* A5538 800B4D38 00000000 */   nop
  .L800B4D3C:
    /* A553C 800B4D3C 1280013C */  lui        $at, %hi(D_80120D6C)
    /* A5540 800B4D40 21083200 */  addu       $at, $at, $s2
    /* A5544 800B4D44 6C0D34A0 */  sb         $s4, %lo(D_80120D6C)($at)
  .L800B4D48:
    /* A5548 800B4D48 680A838F */  lw         $v1, %gp_rel(D_80158F40)($gp)
    /* A554C 800B4D4C 00000000 */  nop
    /* A5550 800B4D50 0A026294 */  lhu        $v0, 0x20A($v1)
    /* A5554 800B4D54 78D30208 */  j          .L800B4DE0
    /* A5558 800B4D58 01004224 */   addiu     $v0, $v0, 0x1
  .L800B4D5C:
    /* A555C 800B4D5C 1280013C */  lui        $at, %hi(D_80120D6C)
    /* A5560 800B4D60 21083200 */  addu       $at, $at, $s2
    /* A5564 800B4D64 6C0D2290 */  lbu        $v0, %lo(D_80120D6C)($at)
    /* A5568 800B4D68 00000000 */  nop
    /* A556C 800B4D6C 0F004014 */  bnez       $v0, .L800B4DAC
    /* A5570 800B4D70 00000000 */   nop
    /* A5574 800B4D74 00006292 */  lbu        $v0, 0x0($s3)
    /* A5578 800B4D78 1280013C */  lui        $at, %hi(D_80120D6C)
    /* A557C 800B4D7C 21083200 */  addu       $at, $at, $s2
    /* A5580 800B4D80 6C0D22A0 */  sb         $v0, %lo(D_80120D6C)($at)
    /* A5584 800B4D84 01005226 */  addiu      $s2, $s2, 0x1
    /* A5588 800B4D88 01006292 */  lbu        $v0, 0x1($s3)
    /* A558C 800B4D8C 1280013C */  lui        $at, %hi(D_80120D6C)
    /* A5590 800B4D90 21083200 */  addu       $at, $at, $s2
    /* A5594 800B4D94 6C0D22A0 */  sb         $v0, %lo(D_80120D6C)($at)
    /* A5598 800B4D98 1280013C */  lui        $at, %hi(D_80120D6D)
    /* A559C 800B4D9C 21083200 */  addu       $at, $at, $s2
    /* A55A0 800B4DA0 6D0D20A0 */  sb         $zero, %lo(D_80120D6D)($at)
    /* A55A4 800B4DA4 73D30208 */  j          .L800B4DCC
    /* A55A8 800B4DA8 00000000 */   nop
  .L800B4DAC:
    /* A55AC 800B4DAC 00006292 */  lbu        $v0, 0x0($s3)
    /* A55B0 800B4DB0 1280013C */  lui        $at, %hi(D_80120D6C)
    /* A55B4 800B4DB4 21083200 */  addu       $at, $at, $s2
    /* A55B8 800B4DB8 6C0D22A0 */  sb         $v0, %lo(D_80120D6C)($at)
    /* A55BC 800B4DBC 01006292 */  lbu        $v0, 0x1($s3)
    /* A55C0 800B4DC0 1280013C */  lui        $at, %hi(D_80120D6D)
    /* A55C4 800B4DC4 21083200 */  addu       $at, $at, $s2
    /* A55C8 800B4DC8 6D0D22A0 */  sb         $v0, %lo(D_80120D6D)($at)
  .L800B4DCC:
    /* A55CC 800B4DCC 680A838F */  lw         $v1, %gp_rel(D_80158F40)($gp)
    /* A55D0 800B4DD0 00000000 */  nop
    /* A55D4 800B4DD4 0A026294 */  lhu        $v0, 0x20A($v1)
    /* A55D8 800B4DD8 00000000 */  nop
    /* A55DC 800B4DDC 02004224 */  addiu      $v0, $v0, 0x2
  .L800B4DE0:
    /* A55E0 800B4DE0 0A0262A4 */  sh         $v0, 0x20A($v1)
  .L800B4DE4:
    /* A55E4 800B4DE4 680A828F */  lw         $v0, %gp_rel(D_80158F40)($gp)
    /* A55E8 800B4DE8 00000000 */  nop
    /* A55EC 800B4DEC FC01448C */  lw         $a0, 0x1FC($v0)
    /* A55F0 800B4DF0 00000000 */  nop
    /* A55F4 800B4DF4 06008010 */  beqz       $a0, .L800B4E10
    /* A55F8 800B4DF8 00000000 */   nop
    /* A55FC 800B4DFC E511040C */  jal        func_80104794
    /* A5600 800B4E00 00000000 */   nop
    /* A5604 800B4E04 680A828F */  lw         $v0, %gp_rel(D_80158F40)($gp)
    /* A5608 800B4E08 00000000 */  nop
    /* A560C 800B4E0C FC0140AC */  sw         $zero, 0x1FC($v0)
  .L800B4E10:
    /* A5610 800B4E10 1280043C */  lui        $a0, %hi(D_80120D6C)
    /* A5614 800B4E14 6C0D8424 */  addiu      $a0, $a0, %lo(D_80120D6C)
    /* A5618 800B4E18 FBD2020C */  jal        func_800B4BEC
    /* A561C 800B4E1C 00000000 */   nop
    /* A5620 800B4E20 2400BF8F */  lw         $ra, 0x24($sp)
    /* A5624 800B4E24 2000B48F */  lw         $s4, 0x20($sp)
    /* A5628 800B4E28 1C00B38F */  lw         $s3, 0x1C($sp)
    /* A562C 800B4E2C 1800B28F */  lw         $s2, 0x18($sp)
    /* A5630 800B4E30 1400B18F */  lw         $s1, 0x14($sp)
    /* A5634 800B4E34 1000B08F */  lw         $s0, 0x10($sp)
    /* A5638 800B4E38 2800BD27 */  addiu      $sp, $sp, 0x28
    /* A563C 800B4E3C 0800E003 */  jr         $ra
    /* A5640 800B4E40 00000000 */   nop
endlabel func_800B4C74
