.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
nonmatching jtbl_80012744

dlabel jtbl_80012744
    /* 2F44 80012744 58760C80 */ .word .L800C7658
    /* 2F48 80012748 68760C80 */ .word .L800C7668
    /* 2F4C 8001274C 78760C80 */ .word .L800C7678
    /* 2F50 80012750 88760C80 */ .word .L800C7688
    /* 2F54 80012754 98760C80 */ .word .L800C7698
enddlabel jtbl_80012744


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800C7088, 0x678

glabel func_800C7088
    /* B7888 800C7088 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* B788C 800C708C 2800BFAF */  sw         $ra, 0x28($sp)
    /* B7890 800C7090 2400B1AF */  sw         $s1, 0x24($sp)
    /* B7894 800C7094 2000B0AF */  sw         $s0, 0x20($sp)
    /* B7898 800C7098 21888000 */  addu       $s1, $a0, $zero
    /* B789C 800C709C 180C80AF */  sw         $zero, %gp_rel(D_801590F0)($gp)
    /* B78A0 800C70A0 1280023C */  lui        $v0, %hi(D_8011A282)
    /* B78A4 800C70A4 82A24284 */  lh         $v0, %lo(D_8011A282)($v0)
    /* B78A8 800C70A8 00000000 */  nop
    /* B78AC 800C70AC 23004018 */  blez       $v0, .L800C713C
    /* B78B0 800C70B0 21800000 */   addu      $s0, $zero, $zero
    /* B78B4 800C70B4 1280053C */  lui        $a1, %hi(D_8011A282)
    /* B78B8 800C70B8 82A2A584 */  lh         $a1, %lo(D_8011A282)($a1)
    /* B78BC 800C70BC 40101000 */  sll        $v0, $s0, 1
  .L800C70C0:
    /* B78C0 800C70C0 21105000 */  addu       $v0, $v0, $s0
    /* B78C4 800C70C4 80100200 */  sll        $v0, $v0, 2
    /* B78C8 800C70C8 23105000 */  subu       $v0, $v0, $s0
    /* B78CC 800C70CC C0200200 */  sll        $a0, $v0, 3
    /* B78D0 800C70D0 1180013C */  lui        $at, %hi(D_80113ED8)
    /* B78D4 800C70D4 21082400 */  addu       $at, $at, $a0
    /* B78D8 800C70D8 D83E2280 */  lb         $v0, %lo(D_80113ED8)($at)
    /* B78DC 800C70DC 00000000 */  nop
    /* B78E0 800C70E0 12005114 */  bne        $v0, $s1, .L800C712C
    /* B78E4 800C70E4 00000000 */   nop
    /* B78E8 800C70E8 1180013C */  lui        $at, %hi(D_80113ED9)
    /* B78EC 800C70EC 21082400 */  addu       $at, $at, $a0
    /* B78F0 800C70F0 D93E2280 */  lb         $v0, %lo(D_80113ED9)($at)
    /* B78F4 800C70F4 1180013C */  lui        $at, %hi(D_80113F26)
    /* B78F8 800C70F8 21082400 */  addu       $at, $at, $a0
    /* B78FC 800C70FC 263F2380 */  lb         $v1, %lo(D_80113F26)($at)
    /* B7900 800C7100 00000000 */  nop
    /* B7904 800C7104 21104300 */  addu       $v0, $v0, $v1
    /* B7908 800C7108 1180013C */  lui        $at, %hi(D_80113F27)
    /* B790C 800C710C 21082400 */  addu       $at, $at, $a0
    /* B7910 800C7110 273F2380 */  lb         $v1, %lo(D_80113F27)($at)
    /* B7914 800C7114 00000000 */  nop
    /* B7918 800C7118 23104300 */  subu       $v0, $v0, $v1
    /* B791C 800C711C 180C838F */  lw         $v1, %gp_rel(D_801590F0)($gp)
    /* B7920 800C7120 00000000 */  nop
    /* B7924 800C7124 21104300 */  addu       $v0, $v0, $v1
    /* B7928 800C7128 180C82AF */  sw         $v0, %gp_rel(D_801590F0)($gp)
  .L800C712C:
    /* B792C 800C712C 01001026 */  addiu      $s0, $s0, 0x1
    /* B7930 800C7130 2A100502 */  slt        $v0, $s0, $a1
    /* B7934 800C7134 E2FF4014 */  bnez       $v0, .L800C70C0
    /* B7938 800C7138 40101000 */   sll       $v0, $s0, 1
  .L800C713C:
    /* B793C 800C713C 1C0C80AF */  sw         $zero, %gp_rel(D_801590F4)($gp)
    /* B7940 800C7140 21180000 */  addu       $v1, $zero, $zero
    /* B7944 800C7144 1280053C */  lui        $a1, %hi(D_8011A342)
    /* B7948 800C7148 42A3A524 */  addiu      $a1, $a1, %lo(D_8011A342)
    /* B794C 800C714C 40100300 */  sll        $v0, $v1, 1
  .L800C7150:
    /* B7950 800C7150 21104500 */  addu       $v0, $v0, $a1
    /* B7954 800C7154 00004484 */  lh         $a0, 0x0($v0)
    /* B7958 800C7158 00000000 */  nop
    /* B795C 800C715C 10008004 */  bltz       $a0, .L800C71A0
    /* B7960 800C7160 21808000 */   addu      $s0, $a0, $zero
    /* B7964 800C7164 40101000 */  sll        $v0, $s0, 1
    /* B7968 800C7168 21105000 */  addu       $v0, $v0, $s0
    /* B796C 800C716C 80100200 */  sll        $v0, $v0, 2
    /* B7970 800C7170 23105000 */  subu       $v0, $v0, $s0
    /* B7974 800C7174 C0100200 */  sll        $v0, $v0, 3
    /* B7978 800C7178 1180013C */  lui        $at, %hi(D_80113ED8)
    /* B797C 800C717C 21082200 */  addu       $at, $at, $v0
    /* B7980 800C7180 D83E2280 */  lb         $v0, %lo(D_80113ED8)($at)
    /* B7984 800C7184 00000000 */  nop
    /* B7988 800C7188 05005114 */  bne        $v0, $s1, .L800C71A0
    /* B798C 800C718C 00000000 */   nop
    /* B7990 800C7190 1C0C828F */  lw         $v0, %gp_rel(D_801590F4)($gp)
    /* B7994 800C7194 00000000 */  nop
    /* B7998 800C7198 14004224 */  addiu      $v0, $v0, 0x14
    /* B799C 800C719C 1C0C82AF */  sw         $v0, %gp_rel(D_801590F4)($gp)
  .L800C71A0:
    /* B79A0 800C71A0 01006324 */  addiu      $v1, $v1, 0x1
    /* B79A4 800C71A4 1C006228 */  slti       $v0, $v1, 0x1C
    /* B79A8 800C71A8 E9FF4014 */  bnez       $v0, .L800C7150
    /* B79AC 800C71AC 40100300 */   sll       $v0, $v1, 1
    /* B79B0 800C71B0 240C80AF */  sw         $zero, %gp_rel(D_801590FC)($gp)
    /* B79B4 800C71B4 200C80AF */  sw         $zero, %gp_rel(D_801590F8)($gp)
    /* B79B8 800C71B8 21202002 */  addu       $a0, $s1, $zero
    /* B79BC 800C71BC 0422030C */  jal        func_800C8810
    /* B79C0 800C71C0 01000524 */   addiu     $a1, $zero, 0x1
    /* B79C4 800C71C4 1680043C */  lui        $a0, %hi(D_80159178)
    /* B79C8 800C71C8 7891848C */  lw         $a0, %lo(D_80159178)($a0)
    /* B79CC 800C71CC 00000000 */  nop
    /* B79D0 800C71D0 19008010 */  beqz       $a0, .L800C7238
    /* B79D4 800C71D4 40101100 */   sll       $v0, $s1, 1
    /* B79D8 800C71D8 21105100 */  addu       $v0, $v0, $s1
    /* B79DC 800C71DC 80100200 */  sll        $v0, $v0, 2
    /* B79E0 800C71E0 23105100 */  subu       $v0, $v0, $s1
    /* B79E4 800C71E4 00110200 */  sll        $v0, $v0, 4
    /* B79E8 800C71E8 23105100 */  subu       $v0, $v0, $s1
    /* B79EC 800C71EC C0100200 */  sll        $v0, $v0, 3
    /* B79F0 800C71F0 1180013C */  lui        $at, %hi(D_80117A7A)
    /* B79F4 800C71F4 21082200 */  addu       $at, $at, $v0
    /* B79F8 800C71F8 7A7A2384 */  lh         $v1, %lo(D_80117A7A)($at)
    /* B79FC 800C71FC 00000000 */  nop
    /* B7A00 800C7200 0D006010 */  beqz       $v1, .L800C7238
    /* B7A04 800C7204 00000000 */   nop
    /* B7A08 800C7208 18006400 */  mult       $v1, $a0
    /* B7A0C 800C720C 12180000 */  mflo       $v1
    /* B7A10 800C7210 240C83AF */  sw         $v1, %gp_rel(D_801590FC)($gp)
    /* B7A14 800C7214 1180013C */  lui        $at, %hi(D_80117A74)
    /* B7A18 800C7218 21082200 */  addu       $at, $at, $v0
    /* B7A1C 800C721C 747A2290 */  lbu        $v0, %lo(D_80117A74)($at)
    /* B7A20 800C7220 00000000 */  nop
    /* B7A24 800C7224 10004230 */  andi       $v0, $v0, 0x10
    /* B7A28 800C7228 03004010 */  beqz       $v0, .L800C7238
    /* B7A2C 800C722C 00000000 */   nop
    /* B7A30 800C7230 200C83AF */  sw         $v1, %gp_rel(D_801590F8)($gp)
    /* B7A34 800C7234 240C80AF */  sw         $zero, %gp_rel(D_801590FC)($gp)
  .L800C7238:
    /* B7A38 800C7238 1280043C */  lui        $a0, %hi(D_8011A27C)
    /* B7A3C 800C723C 7CA28424 */  addiu      $a0, $a0, %lo(D_8011A27C)
    /* B7A40 800C7240 00008384 */  lh         $v1, 0x0($a0)
    /* B7A44 800C7244 FEFF8284 */  lh         $v0, -0x2($a0)
    /* B7A48 800C7248 00000000 */  nop
    /* B7A4C 800C724C 23186200 */  subu       $v1, $v1, $v0
    /* B7A50 800C7250 80100300 */  sll        $v0, $v1, 2
    /* B7A54 800C7254 21104300 */  addu       $v0, $v0, $v1
    /* B7A58 800C7258 40100200 */  sll        $v0, $v0, 1
    /* B7A5C 800C725C 23100200 */  negu       $v0, $v0
    /* B7A60 800C7260 280C82AF */  sw         $v0, %gp_rel(D_80159100)($gp)
    /* B7A64 800C7264 2C0C80AF */  sw         $zero, %gp_rel(D_80159104)($gp)
    /* B7A68 800C7268 E6FF8284 */  lh         $v0, -0x1A($a0)
    /* B7A6C 800C726C 00000000 */  nop
    /* B7A70 800C7270 C8004228 */  slti       $v0, $v0, 0xC8
    /* B7A74 800C7274 0A004014 */  bnez       $v0, .L800C72A0
    /* B7A78 800C7278 40101100 */   sll       $v0, $s1, 1
    /* B7A7C 800C727C 02008284 */  lh         $v0, 0x2($a0)
    /* B7A80 800C7280 00000000 */  nop
    /* B7A84 800C7284 40200200 */  sll        $a0, $v0, 1
    /* B7A88 800C7288 21208200 */  addu       $a0, $a0, $v0
    /* B7A8C 800C728C 21280000 */  addu       $a1, $zero, $zero
    /* B7A90 800C7290 F53A030C */  jal        func_800CEBD4
    /* B7A94 800C7294 64000624 */   addiu     $a2, $zero, 0x64
    /* B7A98 800C7298 2C0C82AF */  sw         $v0, %gp_rel(D_80159104)($gp)
    /* B7A9C 800C729C 40101100 */  sll        $v0, $s1, 1
  .L800C72A0:
    /* B7AA0 800C72A0 21105100 */  addu       $v0, $v0, $s1
    /* B7AA4 800C72A4 80100200 */  sll        $v0, $v0, 2
    /* B7AA8 800C72A8 23105100 */  subu       $v0, $v0, $s1
    /* B7AAC 800C72AC 00110200 */  sll        $v0, $v0, 4
    /* B7AB0 800C72B0 23105100 */  subu       $v0, $v0, $s1
    /* B7AB4 800C72B4 C0100200 */  sll        $v0, $v0, 3
    /* B7AB8 800C72B8 1180013C */  lui        $at, %hi(D_801176A3)
    /* B7ABC 800C72BC 21082200 */  addu       $at, $at, $v0
    /* B7AC0 800C72C0 A3762290 */  lbu        $v0, %lo(D_801176A3)($at)
    /* B7AC4 800C72C4 00000000 */  nop
    /* B7AC8 800C72C8 80280200 */  sll        $a1, $v0, 2
    /* B7ACC 800C72CC 2128A200 */  addu       $a1, $a1, $v0
    /* B7AD0 800C72D0 300C85AF */  sw         $a1, %gp_rel(D_80159108)($gp)
    /* B7AD4 800C72D4 1280023C */  lui        $v0, %hi(D_8011A273)
    /* B7AD8 800C72D8 73A24290 */  lbu        $v0, %lo(D_8011A273)($v0)
    /* B7ADC 800C72DC 00000000 */  nop
    /* B7AE0 800C72E0 40180200 */  sll        $v1, $v0, 1
    /* B7AE4 800C72E4 21186200 */  addu       $v1, $v1, $v0
    /* B7AE8 800C72E8 C0180300 */  sll        $v1, $v1, 3
    /* B7AEC 800C72EC 21186200 */  addu       $v1, $v1, $v0
    /* B7AF0 800C72F0 CEFF6324 */  addiu      $v1, $v1, -0x32
    /* B7AF4 800C72F4 3C0C83AF */  sw         $v1, %gp_rel(D_80159114)($gp)
    /* B7AF8 800C72F8 180C828F */  lw         $v0, %gp_rel(D_801590F0)($gp)
    /* B7AFC 800C72FC 1C0C848F */  lw         $a0, %gp_rel(D_801590F4)($gp)
    /* B7B00 800C7300 00000000 */  nop
    /* B7B04 800C7304 21104400 */  addu       $v0, $v0, $a0
    /* B7B08 800C7308 200C848F */  lw         $a0, %gp_rel(D_801590F8)($gp)
    /* B7B0C 800C730C 00000000 */  nop
    /* B7B10 800C7310 21104400 */  addu       $v0, $v0, $a0
    /* B7B14 800C7314 280C848F */  lw         $a0, %gp_rel(D_80159100)($gp)
    /* B7B18 800C7318 00000000 */  nop
    /* B7B1C 800C731C 21104400 */  addu       $v0, $v0, $a0
    /* B7B20 800C7320 2C0C848F */  lw         $a0, %gp_rel(D_80159104)($gp)
    /* B7B24 800C7324 00000000 */  nop
    /* B7B28 800C7328 21104400 */  addu       $v0, $v0, $a0
    /* B7B2C 800C732C 21104500 */  addu       $v0, $v0, $a1
    /* B7B30 800C7330 21104300 */  addu       $v0, $v0, $v1
    /* B7B34 800C7334 380C82AF */  sw         $v0, %gp_rel(D_80159110)($gp)
    /* B7B38 800C7338 02004104 */  bgez       $v0, .L800C7344
    /* B7B3C 800C733C 00000000 */   nop
    /* B7B40 800C7340 380C80AF */  sw         $zero, %gp_rel(D_80159110)($gp)
  .L800C7344:
    /* B7B44 800C7344 340C80AF */  sw         $zero, %gp_rel(D_8015910C)($gp)
    /* B7B48 800C7348 1280043C */  lui        $a0, %hi(D_8011A274)
    /* B7B4C 800C734C 74A28424 */  addiu      $a0, $a0, %lo(D_8011A274)
    /* B7B50 800C7350 00008390 */  lbu        $v1, 0x0($a0)
    /* B7B54 800C7354 00000000 */  nop
    /* B7B58 800C7358 FE006330 */  andi       $v1, $v1, 0xFE
    /* B7B5C 800C735C 01000224 */  addiu      $v0, $zero, 0x1
    /* B7B60 800C7360 04102202 */  sllv       $v0, $v0, $s1
    /* B7B64 800C7364 36006214 */  bne        $v1, $v0, .L800C7440
    /* B7B68 800C7368 00000000 */   nop
    /* B7B6C 800C736C EEFF8584 */  lh         $a1, -0x12($a0)
    /* B7B70 800C7370 DCFF8294 */  lhu        $v0, -0x24($a0)
    /* B7B74 800C7374 00000000 */  nop
    /* B7B78 800C7378 00014230 */  andi       $v0, $v0, 0x100
    /* B7B7C 800C737C 06004010 */  beqz       $v0, .L800C7398
    /* B7B80 800C7380 2118A000 */   addu      $v1, $a1, $zero
    /* B7B84 800C7384 FA000224 */  addiu      $v0, $zero, 0xFA
    /* B7B88 800C7388 2A104500 */  slt        $v0, $v0, $a1
    /* B7B8C 800C738C 02004010 */  beqz       $v0, .L800C7398
    /* B7B90 800C7390 FA000524 */   addiu     $a1, $zero, 0xFA
    /* B7B94 800C7394 21286000 */  addu       $a1, $v1, $zero
  .L800C7398:
    /* B7B98 800C7398 1280043C */  lui        $a0, %hi(D_8011A277)
    /* B7B9C 800C739C 77A28424 */  addiu      $a0, $a0, %lo(D_8011A277)
    /* B7BA0 800C73A0 00008290 */  lbu        $v0, 0x0($a0)
    /* B7BA4 800C73A4 00000000 */  nop
    /* B7BA8 800C73A8 40180200 */  sll        $v1, $v0, 1
    /* B7BAC 800C73AC 21186200 */  addu       $v1, $v1, $v0
    /* B7BB0 800C73B0 C0180300 */  sll        $v1, $v1, 3
    /* B7BB4 800C73B4 21186200 */  addu       $v1, $v1, $v0
    /* B7BB8 800C73B8 80180300 */  sll        $v1, $v1, 2
    /* B7BBC 800C73BC 3A020224 */  addiu      $v0, $zero, 0x23A
    /* B7BC0 800C73C0 23104500 */  subu       $v0, $v0, $a1
    /* B7BC4 800C73C4 40100200 */  sll        $v0, $v0, 1
    /* B7BC8 800C73C8 90014224 */  addiu      $v0, $v0, 0x190
    /* B7BCC 800C73CC 21186200 */  addu       $v1, $v1, $v0
    /* B7BD0 800C73D0 340C83AF */  sw         $v1, %gp_rel(D_8015910C)($gp)
    /* B7BD4 800C73D4 E3FF8294 */  lhu        $v0, -0x1D($a0)
    /* B7BD8 800C73D8 00000000 */  nop
    /* B7BDC 800C73DC 04004230 */  andi       $v0, $v0, 0x4
    /* B7BE0 800C73E0 07004010 */  beqz       $v0, .L800C7400
    /* B7BE4 800C73E4 80100300 */   sll       $v0, $v1, 2
    /* B7BE8 800C73E8 21104300 */  addu       $v0, $v0, $v1
    /* B7BEC 800C73EC 02004104 */  bgez       $v0, .L800C73F8
    /* B7BF0 800C73F0 00000000 */   nop
    /* B7BF4 800C73F4 03004224 */  addiu      $v0, $v0, 0x3
  .L800C73F8:
    /* B7BF8 800C73F8 83100200 */  sra        $v0, $v0, 2
    /* B7BFC 800C73FC 340C82AF */  sw         $v0, %gp_rel(D_8015910C)($gp)
  .L800C7400:
    /* B7C00 800C7400 1280023C */  lui        $v0, %hi(D_8011A25A)
    /* B7C04 800C7404 5AA24294 */  lhu        $v0, %lo(D_8011A25A)($v0)
    /* B7C08 800C7408 00000000 */  nop
    /* B7C0C 800C740C 08004230 */  andi       $v0, $v0, 0x8
    /* B7C10 800C7410 0B004010 */  beqz       $v0, .L800C7440
    /* B7C14 800C7414 6666023C */   lui       $v0, (0x66666667 >> 16)
    /* B7C18 800C7418 340C838F */  lw         $v1, %gp_rel(D_8015910C)($gp)
    /* B7C1C 800C741C 00000000 */  nop
    /* B7C20 800C7420 80180300 */  sll        $v1, $v1, 2
    /* B7C24 800C7424 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
    /* B7C28 800C7428 18006200 */  mult       $v1, $v0
    /* B7C2C 800C742C 10380000 */  mfhi       $a3
    /* B7C30 800C7430 43100700 */  sra        $v0, $a3, 1
    /* B7C34 800C7434 C31F0300 */  sra        $v1, $v1, 31
    /* B7C38 800C7438 23104300 */  subu       $v0, $v0, $v1
    /* B7C3C 800C743C 340C82AF */  sw         $v0, %gp_rel(D_8015910C)($gp)
  .L800C7440:
    /* B7C40 800C7440 400C80AF */  sw         $zero, %gp_rel(D_80159118)($gp)
    /* B7C44 800C7444 1280023C */  lui        $v0, %hi(D_8011A25A)
    /* B7C48 800C7448 5AA24294 */  lhu        $v0, %lo(D_8011A25A)($v0)
    /* B7C4C 800C744C 00000000 */  nop
    /* B7C50 800C7450 80004230 */  andi       $v0, $v0, 0x80
    /* B7C54 800C7454 07004010 */  beqz       $v0, .L800C7474
    /* B7C58 800C7458 00000000 */   nop
    /* B7C5C 800C745C 1280023C */  lui        $v0, %hi(D_8011A390)
    /* B7C60 800C7460 90A34294 */  lhu        $v0, %lo(D_8011A390)($v0)
    /* B7C64 800C7464 00000000 */  nop
    /* B7C68 800C7468 02004230 */  andi       $v0, $v0, 0x2
    /* B7C6C 800C746C 09004014 */  bnez       $v0, .L800C7494
    /* B7C70 800C7470 00000000 */   nop
  .L800C7474:
    /* B7C74 800C7474 340C828F */  lw         $v0, %gp_rel(D_8015910C)($gp)
    /* B7C78 800C7478 380C848F */  lw         $a0, %gp_rel(D_80159110)($gp)
    /* B7C7C 800C747C 00000000 */  nop
    /* B7C80 800C7480 2A184400 */  slt        $v1, $v0, $a0
    /* B7C84 800C7484 98006010 */  beqz       $v1, .L800C76E8
    /* B7C88 800C7488 00000000 */   nop
    /* B7C8C 800C748C BA1D0308 */  j          .L800C76E8
    /* B7C90 800C7490 21108000 */   addu      $v0, $a0, $zero
  .L800C7494:
    /* B7C94 800C7494 480C80AF */  sw         $zero, %gp_rel(D_80159120)($gp)
    /* B7C98 800C7498 4C0C80AF */  sw         $zero, %gp_rel(D_80159124)($gp)
    /* B7C9C 800C749C 500C80AF */  sw         $zero, %gp_rel(D_80159128)($gp)
    /* B7CA0 800C74A0 1280023C */  lui        $v0, %hi(D_8011A282)
    /* B7CA4 800C74A4 82A24284 */  lh         $v0, %lo(D_8011A282)($v0)
    /* B7CA8 800C74A8 00000000 */  nop
    /* B7CAC 800C74AC 2F004018 */  blez       $v0, .L800C756C
    /* B7CB0 800C74B0 21800000 */   addu      $s0, $zero, $zero
  .L800C74B4:
    /* B7CB4 800C74B4 FD25020C */  jal        func_800897F4
    /* B7CB8 800C74B8 21200002 */   addu      $a0, $s0, $zero
    /* B7CBC 800C74BC 21204000 */  addu       $a0, $v0, $zero
    /* B7CC0 800C74C0 480C828F */  lw         $v0, %gp_rel(D_80159120)($gp)
    /* B7CC4 800C74C4 00000000 */  nop
    /* B7CC8 800C74C8 21108200 */  addu       $v0, $a0, $v0
    /* B7CCC 800C74CC 480C82AF */  sw         $v0, %gp_rel(D_80159120)($gp)
    /* B7CD0 800C74D0 40101000 */  sll        $v0, $s0, 1
    /* B7CD4 800C74D4 21105000 */  addu       $v0, $v0, $s0
    /* B7CD8 800C74D8 80100200 */  sll        $v0, $v0, 2
    /* B7CDC 800C74DC 23105000 */  subu       $v0, $v0, $s0
    /* B7CE0 800C74E0 C0100200 */  sll        $v0, $v0, 3
    /* B7CE4 800C74E4 1180013C */  lui        $at, %hi(D_80113ED8)
    /* B7CE8 800C74E8 21082200 */  addu       $at, $at, $v0
    /* B7CEC 800C74EC D83E2380 */  lb         $v1, %lo(D_80113ED8)($at)
    /* B7CF0 800C74F0 1280023C */  lui        $v0, %hi(D_8011A3EA)
    /* B7CF4 800C74F4 EAA34284 */  lh         $v0, %lo(D_8011A3EA)($v0)
    /* B7CF8 800C74F8 00000000 */  nop
    /* B7CFC 800C74FC 06006214 */  bne        $v1, $v0, .L800C7518
    /* B7D00 800C7500 40101000 */   sll       $v0, $s0, 1
    /* B7D04 800C7504 4C0C828F */  lw         $v0, %gp_rel(D_80159124)($gp)
    /* B7D08 800C7508 00000000 */  nop
    /* B7D0C 800C750C 21108200 */  addu       $v0, $a0, $v0
    /* B7D10 800C7510 4C0C82AF */  sw         $v0, %gp_rel(D_80159124)($gp)
    /* B7D14 800C7514 40101000 */  sll        $v0, $s0, 1
  .L800C7518:
    /* B7D18 800C7518 21105000 */  addu       $v0, $v0, $s0
    /* B7D1C 800C751C 80100200 */  sll        $v0, $v0, 2
    /* B7D20 800C7520 23105000 */  subu       $v0, $v0, $s0
    /* B7D24 800C7524 C0100200 */  sll        $v0, $v0, 3
    /* B7D28 800C7528 1180013C */  lui        $at, %hi(D_80113ED8)
    /* B7D2C 800C752C 21082200 */  addu       $at, $at, $v0
    /* B7D30 800C7530 D83E2280 */  lb         $v0, %lo(D_80113ED8)($at)
    /* B7D34 800C7534 00000000 */  nop
    /* B7D38 800C7538 05005114 */  bne        $v0, $s1, .L800C7550
    /* B7D3C 800C753C 00000000 */   nop
    /* B7D40 800C7540 500C828F */  lw         $v0, %gp_rel(D_80159128)($gp)
    /* B7D44 800C7544 00000000 */  nop
    /* B7D48 800C7548 21108200 */  addu       $v0, $a0, $v0
    /* B7D4C 800C754C 500C82AF */  sw         $v0, %gp_rel(D_80159128)($gp)
  .L800C7550:
    /* B7D50 800C7550 01001026 */  addiu      $s0, $s0, 0x1
    /* B7D54 800C7554 1280023C */  lui        $v0, %hi(D_8011A282)
    /* B7D58 800C7558 82A24284 */  lh         $v0, %lo(D_8011A282)($v0)
    /* B7D5C 800C755C 00000000 */  nop
    /* B7D60 800C7560 2A100202 */  slt        $v0, $s0, $v0
    /* B7D64 800C7564 D3FF4014 */  bnez       $v0, .L800C74B4
    /* B7D68 800C7568 00000000 */   nop
  .L800C756C:
    /* B7D6C 800C756C 1280023C */  lui        $v0, %hi(D_8011A3EA)
    /* B7D70 800C7570 EAA34284 */  lh         $v0, %lo(D_8011A3EA)($v0)
    /* B7D74 800C7574 00000000 */  nop
    /* B7D78 800C7578 05004014 */  bnez       $v0, .L800C7590
    /* B7D7C 800C757C 02000224 */   addiu     $v0, $zero, 0x2
    /* B7D80 800C7580 500C828F */  lw         $v0, %gp_rel(D_80159128)($gp)
    /* B7D84 800C7584 00000000 */  nop
    /* B7D88 800C7588 4C0C82AF */  sw         $v0, %gp_rel(D_80159124)($gp)
    /* B7D8C 800C758C 02000224 */  addiu      $v0, $zero, 0x2
  .L800C7590:
    /* B7D90 800C7590 440C82AF */  sw         $v0, %gp_rel(D_8015911C)($gp)
    /* B7D94 800C7594 1280033C */  lui        $v1, %hi(D_8011A3EC)
    /* B7D98 800C7598 ECA36384 */  lh         $v1, %lo(D_8011A3EC)($v1)
    /* B7D9C 800C759C 4C0C828F */  lw         $v0, %gp_rel(D_80159124)($gp)
    /* B7DA0 800C75A0 00000000 */  nop
    /* B7DA4 800C75A4 2A104300 */  slt        $v0, $v0, $v1
    /* B7DA8 800C75A8 04004014 */  bnez       $v0, .L800C75BC
    /* B7DAC 800C75AC 00000000 */   nop
    /* B7DB0 800C75B0 440C80AF */  sw         $zero, %gp_rel(D_8015911C)($gp)
    /* B7DB4 800C75B4 841D0308 */  j          .L800C7610
    /* B7DB8 800C75B8 00000000 */   nop
  .L800C75BC:
    /* B7DBC 800C75BC 1280033C */  lui        $v1, %hi(D_8011A3EE)
    /* B7DC0 800C75C0 EEA36384 */  lh         $v1, %lo(D_8011A3EE)($v1)
    /* B7DC4 800C75C4 4C0C828F */  lw         $v0, %gp_rel(D_80159124)($gp)
    /* B7DC8 800C75C8 00000000 */  nop
    /* B7DCC 800C75CC 2A104300 */  slt        $v0, $v0, $v1
    /* B7DD0 800C75D0 0E004010 */  beqz       $v0, .L800C760C
    /* B7DD4 800C75D4 01000224 */   addiu     $v0, $zero, 0x1
    /* B7DD8 800C75D8 1280023C */  lui        $v0, %hi(D_8011A3F2)
    /* B7DDC 800C75DC F2A34284 */  lh         $v0, %lo(D_8011A3F2)($v0)
    /* B7DE0 800C75E0 4C0C838F */  lw         $v1, %gp_rel(D_80159124)($gp)
    /* B7DE4 800C75E4 00000000 */  nop
    /* B7DE8 800C75E8 2A104300 */  slt        $v0, $v0, $v1
    /* B7DEC 800C75EC 07004010 */  beqz       $v0, .L800C760C
    /* B7DF0 800C75F0 04000224 */   addiu     $v0, $zero, 0x4
    /* B7DF4 800C75F4 1280023C */  lui        $v0, %hi(D_8011A3F0)
    /* B7DF8 800C75F8 F0A34284 */  lh         $v0, %lo(D_8011A3F0)($v0)
    /* B7DFC 800C75FC 00000000 */  nop
    /* B7E00 800C7600 2A104300 */  slt        $v0, $v0, $v1
    /* B7E04 800C7604 02004014 */  bnez       $v0, .L800C7610
    /* B7E08 800C7608 03000224 */   addiu     $v0, $zero, 0x3
  .L800C760C:
    /* B7E0C 800C760C 440C82AF */  sw         $v0, %gp_rel(D_8015911C)($gp)
  .L800C7610:
    /* B7E10 800C7610 440C838F */  lw         $v1, %gp_rel(D_8015911C)($gp)
    /* B7E14 800C7614 1280023C */  lui        $v0, %hi(D_8011A3EA)
    /* B7E18 800C7618 EAA34284 */  lh         $v0, %lo(D_8011A3EA)($v0)
    /* B7E1C 800C761C 00000000 */  nop
    /* B7E20 800C7620 04004010 */  beqz       $v0, .L800C7634
    /* B7E24 800C7624 00000000 */   nop
    /* B7E28 800C7628 02002212 */  beq        $s1, $v0, .L800C7634
    /* B7E2C 800C762C 04000224 */   addiu     $v0, $zero, 0x4
    /* B7E30 800C7630 23184300 */  subu       $v1, $v0, $v1
  .L800C7634:
    /* B7E34 800C7634 0500622C */  sltiu      $v0, $v1, 0x5
    /* B7E38 800C7638 18004010 */  beqz       $v0, .L800C769C
    /* B7E3C 800C763C 80100300 */   sll       $v0, $v1, 2
    /* B7E40 800C7640 0180013C */  lui        $at, %hi(jtbl_80012744)
    /* B7E44 800C7644 21082200 */  addu       $at, $at, $v0
    /* B7E48 800C7648 4427228C */  lw         $v0, %lo(jtbl_80012744)($at)
    /* B7E4C 800C764C 00000000 */  nop
    /* B7E50 800C7650 08004000 */  jr         $v0
    /* B7E54 800C7654 00000000 */   nop
  .L800C7658:
    /* B7E58 800C7658 E8030224 */  addiu      $v0, $zero, 0x3E8
    /* B7E5C 800C765C 400C82AF */  sw         $v0, %gp_rel(D_80159118)($gp)
    /* B7E60 800C7660 A71D0308 */  j          .L800C769C
    /* B7E64 800C7664 00000000 */   nop
  .L800C7668:
    /* B7E68 800C7668 EE020224 */  addiu      $v0, $zero, 0x2EE
    /* B7E6C 800C766C 400C82AF */  sw         $v0, %gp_rel(D_80159118)($gp)
    /* B7E70 800C7670 A71D0308 */  j          .L800C769C
    /* B7E74 800C7674 00000000 */   nop
  .L800C7678:
    /* B7E78 800C7678 F4010224 */  addiu      $v0, $zero, 0x1F4
    /* B7E7C 800C767C 400C82AF */  sw         $v0, %gp_rel(D_80159118)($gp)
    /* B7E80 800C7680 A71D0308 */  j          .L800C769C
    /* B7E84 800C7684 00000000 */   nop
  .L800C7688:
    /* B7E88 800C7688 FA000224 */  addiu      $v0, $zero, 0xFA
    /* B7E8C 800C768C 400C82AF */  sw         $v0, %gp_rel(D_80159118)($gp)
    /* B7E90 800C7690 A71D0308 */  j          .L800C769C
    /* B7E94 800C7694 00000000 */   nop
  .L800C7698:
    /* B7E98 800C7698 400C80AF */  sw         $zero, %gp_rel(D_80159118)($gp)
  .L800C769C:
    /* B7E9C 800C769C 500C838F */  lw         $v1, %gp_rel(D_80159128)($gp)
    /* B7EA0 800C76A0 00000000 */  nop
    /* B7EA4 800C76A4 80100300 */  sll        $v0, $v1, 2
    /* B7EA8 800C76A8 21104300 */  addu       $v0, $v0, $v1
    /* B7EAC 800C76AC 40100200 */  sll        $v0, $v0, 1
    /* B7EB0 800C76B0 400C838F */  lw         $v1, %gp_rel(D_80159118)($gp)
    /* B7EB4 800C76B4 00000000 */  nop
    /* B7EB8 800C76B8 21184300 */  addu       $v1, $v0, $v1
    /* B7EBC 800C76BC 400C83AF */  sw         $v1, %gp_rel(D_80159118)($gp)
    /* B7EC0 800C76C0 340C828F */  lw         $v0, %gp_rel(D_8015910C)($gp)
    /* B7EC4 800C76C4 00000000 */  nop
    /* B7EC8 800C76C8 02004018 */  blez       $v0, .L800C76D4
    /* B7ECC 800C76CC 40100300 */   sll       $v0, $v1, 1
    /* B7ED0 800C76D0 400C82AF */  sw         $v0, %gp_rel(D_80159118)($gp)
  .L800C76D4:
    /* B7ED4 800C76D4 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* B7ED8 800C76D8 340C82AF */  sw         $v0, %gp_rel(D_8015910C)($gp)
    /* B7EDC 800C76DC 400C828F */  lw         $v0, %gp_rel(D_80159118)($gp)
    /* B7EE0 800C76E0 00000000 */  nop
    /* B7EE4 800C76E4 380C82AF */  sw         $v0, %gp_rel(D_80159110)($gp)
  .L800C76E8:
    /* B7EE8 800C76E8 2800BF8F */  lw         $ra, 0x28($sp)
    /* B7EEC 800C76EC 2400B18F */  lw         $s1, 0x24($sp)
    /* B7EF0 800C76F0 2000B08F */  lw         $s0, 0x20($sp)
    /* B7EF4 800C76F4 3000BD27 */  addiu      $sp, $sp, 0x30
    /* B7EF8 800C76F8 0800E003 */  jr         $ra
    /* B7EFC 800C76FC 00000000 */   nop
endlabel func_800C7088
