.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_800121F8

dlabel D_800121F8
    /* 29F8 800121F8 */ .asciz "  X-Continue,  Circle for explanation"
    /* 2020582D436F6E74696E75652C2020436972636C6520666F72206578706C616E6174696F6E000000 */
.align 2
enddlabel D_800121F8

.align 2
nonmatching D_80012220

dlabel D_80012220
    /* 2A20 80012220 */ .asciz "^  Use Up/Down to scroll explanation"
    /* 5E20205573652055702F446F776E20746F207363726F6C6C206578706C616E6174696F6E00000000 */
.align 2
enddlabel D_80012220


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800B7D48, 0x368

glabel func_800B7D48
    /* A8548 800B7D48 C8FEBD27 */  addiu      $sp, $sp, -0x138
    /* A854C 800B7D4C 3001BFAF */  sw         $ra, 0x130($sp)
    /* A8550 800B7D50 2C01B3AF */  sw         $s3, 0x12C($sp)
    /* A8554 800B7D54 2801B2AF */  sw         $s2, 0x128($sp)
    /* A8558 800B7D58 2401B1AF */  sw         $s1, 0x124($sp)
    /* A855C 800B7D5C 2001B0AF */  sw         $s0, 0x120($sp)
    /* A8560 800B7D60 21908000 */  addu       $s2, $a0, $zero
    /* A8564 800B7D64 1680133C */  lui        $s3, %hi(D_80158A04)
    /* A8568 800B7D68 048A738E */  lw         $s3, %lo(D_80158A04)($s3)
    /* A856C 800B7D6C 1680013C */  lui        $at, %hi(D_80158A04)
    /* A8570 800B7D70 048A20AC */  sw         $zero, %lo(D_80158A04)($at)
    /* A8574 800B7D74 3000428E */  lw         $v0, 0x30($s2)
    /* A8578 800B7D78 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* A857C 800B7D7C 24104300 */  and        $v0, $v0, $v1
    /* A8580 800B7D80 0D004010 */  beqz       $v0, .L800B7DB8
    /* A8584 800B7D84 2180A000 */   addu      $s0, $a1, $zero
    /* A8588 800B7D88 1680053C */  lui        $a1, %hi(D_80158F60)
    /* A858C 800B7D8C 608FA524 */  addiu      $a1, $a1, %lo(D_80158F60)
    /* A8590 800B7D90 69C7020C */  jal        func_800B1DA4
    /* A8594 800B7D94 00000000 */   nop
    /* A8598 800B7D98 0180053C */  lui        $a1, %hi(D_800121F8)
    /* A859C 800B7D9C F821A524 */  addiu      $a1, $a1, %lo(D_800121F8)
    /* A85A0 800B7DA0 69C7020C */  jal        func_800B1DA4
    /* A85A4 800B7DA4 21204002 */   addu      $a0, $s2, $zero
    /* A85A8 800B7DA8 0180053C */  lui        $a1, %hi(D_80012220)
    /* A85AC 800B7DAC 2022A524 */  addiu      $a1, $a1, %lo(D_80012220)
    /* A85B0 800B7DB0 69C7020C */  jal        func_800B1DA4
    /* A85B4 800B7DB4 21204002 */   addu      $a0, $s2, $zero
  .L800B7DB8:
    /* A85B8 800B7DB8 3000428E */  lw         $v0, 0x30($s2)
    /* A85BC 800B7DBC FFDF0324 */  addiu      $v1, $zero, -0x2001
    /* A85C0 800B7DC0 24184300 */  and        $v1, $v0, $v1
    /* A85C4 800B7DC4 00404230 */  andi       $v0, $v0, 0x4000
    /* A85C8 800B7DC8 04004010 */  beqz       $v0, .L800B7DDC
    /* A85CC 800B7DCC 300043AE */   sw        $v1, 0x30($s2)
    /* A85D0 800B7DD0 0100023C */  lui        $v0, (0x10000 >> 16)
    /* A85D4 800B7DD4 25106200 */  or         $v0, $v1, $v0
    /* A85D8 800B7DD8 300042AE */  sw         $v0, 0x30($s2)
  .L800B7DDC:
    /* A85DC 800B7DDC 2F53020C */  jal        func_80094CBC
    /* A85E0 800B7DE0 98014426 */   addiu     $a0, $s2, 0x198
    /* A85E4 800B7DE4 A8DB020C */  jal        func_800B6EA0
    /* A85E8 800B7DE8 21204002 */   addu      $a0, $s2, $zero
    /* A85EC 800B7DEC 3000438E */  lw         $v1, 0x30($s2)
    /* A85F0 800B7DF0 00000000 */  nop
    /* A85F4 800B7DF4 20006230 */  andi       $v0, $v1, 0x20
    /* A85F8 800B7DF8 A2004010 */  beqz       $v0, .L800B8084
    /* A85FC 800B7DFC 08006230 */   andi      $v0, $v1, 0x8
    /* A8600 800B7E00 A0004014 */  bnez       $v0, .L800B8084
    /* A8604 800B7E04 02000224 */   addiu     $v0, $zero, 0x2
    /* A8608 800B7E08 1680013C */  lui        $at, %hi(D_801584EC)
    /* A860C 800B7E0C EC8422AC */  sw         $v0, %lo(D_801584EC)($at)
    /* A8610 800B7E10 9401428E */  lw         $v0, 0x194($s2)
    /* A8614 800B7E14 00000000 */  nop
    /* A8618 800B7E18 15004010 */  beqz       $v0, .L800B7E70
    /* A861C 800B7E1C 00000000 */   nop
    /* A8620 800B7E20 3000428E */  lw         $v0, 0x30($s2)
    /* A8624 800B7E24 00000000 */  nop
    /* A8628 800B7E28 00044230 */  andi       $v0, $v0, 0x400
    /* A862C 800B7E2C 1C004014 */  bnez       $v0, .L800B7EA0
    /* A8630 800B7E30 00000000 */   nop
  .L800B7E34:
    /* A8634 800B7E34 9401428E */  lw         $v0, 0x194($s2)
    /* A8638 800B7E38 00000000 */  nop
    /* A863C 800B7E3C 09F84000 */  jalr       $v0
    /* A8640 800B7E40 21204002 */   addu      $a0, $s2, $zero
    /* A8644 800B7E44 03004010 */  beqz       $v0, .L800B7E54
    /* A8648 800B7E48 00000000 */   nop
    /* A864C 800B7E4C DAD1020C */  jal        func_800B4768
    /* A8650 800B7E50 00000000 */   nop
  .L800B7E54:
    /* A8654 800B7E54 3000428E */  lw         $v0, 0x30($s2)
    /* A8658 800B7E58 00000000 */  nop
    /* A865C 800B7E5C 00044230 */  andi       $v0, $v0, 0x400
    /* A8660 800B7E60 F4FF4010 */  beqz       $v0, .L800B7E34
    /* A8664 800B7E64 00000000 */   nop
    /* A8668 800B7E68 A8DF0208 */  j          .L800B7EA0
    /* A866C 800B7E6C 00000000 */   nop
  .L800B7E70:
    /* A8670 800B7E70 0000448E */  lw         $a0, 0x0($s2)
    /* A8674 800B7E74 14DE030C */  jal        func_800F7850
    /* A8678 800B7E78 2C008424 */   addiu     $a0, $a0, 0x2C
  .L800B7E7C:
    /* A867C 800B7E7C 3000428E */  lw         $v0, 0x30($s2)
    /* A8680 800B7E80 00000000 */  nop
    /* A8684 800B7E84 00044230 */  andi       $v0, $v0, 0x400
    /* A8688 800B7E88 05004014 */  bnez       $v0, .L800B7EA0
    /* A868C 800B7E8C 00000000 */   nop
    /* A8690 800B7E90 1E12040C */  jal        func_80104878
    /* A8694 800B7E94 00000000 */   nop
    /* A8698 800B7E98 9FDF0208 */  j          .L800B7E7C
    /* A869C 800B7E9C 00000000 */   nop
  .L800B7EA0:
    /* A86A0 800B7EA0 09000012 */  beqz       $s0, .L800B7EC8
    /* A86A4 800B7EA4 00000000 */   nop
    /* A86A8 800B7EA8 B401428E */  lw         $v0, 0x1B4($s2)
    /* A86AC 800B7EAC 00000000 */  nop
    /* A86B0 800B7EB0 05004010 */  beqz       $v0, .L800B7EC8
    /* A86B4 800B7EB4 00000000 */   nop
    /* A86B8 800B7EB8 1280053C */  lui        $a1, %hi(D_80120D6C)
    /* A86BC 800B7EBC 6C0DA524 */  addiu      $a1, $a1, %lo(D_80120D6C)
    /* A86C0 800B7EC0 A587030C */  jal        func_800E1E94
    /* A86C4 800B7EC4 21200002 */   addu      $a0, $s0, $zero
  .L800B7EC8:
    /* A86C8 800B7EC8 1800428E */  lw         $v0, 0x18($s2)
    /* A86CC 800B7ECC 00000000 */  nop
    /* A86D0 800B7ED0 02004228 */  slti       $v0, $v0, 0x2
    /* A86D4 800B7ED4 15004014 */  bnez       $v0, .L800B7F2C
    /* A86D8 800B7ED8 21800000 */   addu      $s0, $zero, $zero
    /* A86DC 800B7EDC 1280113C */  lui        $s1, %hi(D_8011FCF8)
    /* A86E0 800B7EE0 F8FC3126 */  addiu      $s1, $s1, %lo(D_8011FCF8)
  .L800B7EE4:
    /* A86E4 800B7EE4 1800428E */  lw         $v0, 0x18($s2)
    /* A86E8 800B7EE8 00000000 */  nop
    /* A86EC 800B7EEC 2A100202 */  slt        $v0, $s0, $v0
    /* A86F0 800B7EF0 0E004010 */  beqz       $v0, .L800B7F2C
    /* A86F4 800B7EF4 40101000 */   sll       $v0, $s0, 1
    /* A86F8 800B7EF8 21105000 */  addu       $v0, $v0, $s0
    /* A86FC 800B7EFC 00110200 */  sll        $v0, $v0, 4
    /* A8700 800B7F00 B401438E */  lw         $v1, 0x1B4($s2)
    /* A8704 800B7F04 00000000 */  nop
    /* A8708 800B7F08 21104300 */  addu       $v0, $v0, $v1
    /* A870C 800B7F0C 80281000 */  sll        $a1, $s0, 2
    /* A8710 800B7F10 2128B000 */  addu       $a1, $a1, $s0
    /* A8714 800B7F14 00290500 */  sll        $a1, $a1, 4
    /* A8718 800B7F18 1400448C */  lw         $a0, 0x14($v0)
    /* A871C 800B7F1C 1D5D020C */  jal        func_80097474
    /* A8720 800B7F20 2128B100 */   addu      $a1, $a1, $s1
    /* A8724 800B7F24 B9DF0208 */  j          .L800B7EE4
    /* A8728 800B7F28 01001026 */   addiu     $s0, $s0, 0x1
  .L800B7F2C:
    /* A872C 800B7F2C 3000438E */  lw         $v1, 0x30($s2)
    /* A8730 800B7F30 00000000 */  nop
    /* A8734 800B7F34 00106230 */  andi       $v0, $v1, 0x1000
    /* A8738 800B7F38 2C004010 */  beqz       $v0, .L800B7FEC
    /* A873C 800B7F3C 00000000 */   nop
    /* A8740 800B7F40 BC00428E */  lw         $v0, 0xBC($s2)
    /* A8744 800B7F44 00000000 */  nop
    /* A8748 800B7F48 43004014 */  bnez       $v0, .L800B8058
    /* A874C 800B7F4C 0400023C */   lui       $v0, (0x40000 >> 16)
    /* A8750 800B7F50 24106200 */  and        $v0, $v1, $v0
    /* A8754 800B7F54 20004010 */  beqz       $v0, .L800B7FD8
    /* A8758 800B7F58 00000000 */   nop
    /* A875C 800B7F5C BC01428E */  lw         $v0, 0x1BC($s2)
    /* A8760 800B7F60 00000000 */  nop
    /* A8764 800B7F64 1400448C */  lw         $a0, 0x14($v0)
    /* A8768 800B7F68 0F5D020C */  jal        func_8009743C
    /* A876C 800B7F6C 1000A527 */   addiu     $a1, $sp, 0x10
    /* A8770 800B7F70 7001428E */  lw         $v0, 0x170($s2)
    /* A8774 800B7F74 00000000 */  nop
    /* A8778 800B7F78 0400428C */  lw         $v0, 0x4($v0)
    /* A877C 800B7F7C 00000000 */  nop
    /* A8780 800B7F80 BC0042AE */  sw         $v0, 0xBC($s2)
    /* A8784 800B7F84 7001518E */  lw         $s1, 0x170($s2)
    /* A8788 800B7F88 21800000 */  addu       $s0, $zero, $zero
  .L800B7F8C:
    /* A878C 800B7F8C 32002012 */  beqz       $s1, .L800B8058
    /* A8790 800B7F90 002C1000 */   sll       $a1, $s0, 16
    /* A8794 800B7F94 BC01428E */  lw         $v0, 0x1BC($s2)
    /* A8798 800B7F98 00000000 */  nop
    /* A879C 800B7F9C 1400448C */  lw         $a0, 0x14($v0)
    /* A87A0 800B7FA0 032C0500 */  sra        $a1, $a1, 16
    /* A87A4 800B7FA4 0D5D020C */  jal        func_80097434
    /* A87A8 800B7FA8 9800A627 */   addiu     $a2, $sp, 0x98
    /* A87AC 800B7FAC 1000A427 */  addiu      $a0, $sp, 0x10
    /* A87B0 800B7FB0 9D87030C */  jal        func_800E1E74
    /* A87B4 800B7FB4 9800A527 */   addiu     $a1, $sp, 0x98
    /* A87B8 800B7FB8 04004014 */  bnez       $v0, .L800B7FCC
    /* A87BC 800B7FBC 00000000 */   nop
    /* A87C0 800B7FC0 0400228E */  lw         $v0, 0x4($s1)
    /* A87C4 800B7FC4 00000000 */  nop
    /* A87C8 800B7FC8 BC0042AE */  sw         $v0, 0xBC($s2)
  .L800B7FCC:
    /* A87CC 800B7FCC 0C00318E */  lw         $s1, 0xC($s1)
    /* A87D0 800B7FD0 E3DF0208 */  j          .L800B7F8C
    /* A87D4 800B7FD4 01001026 */   addiu     $s0, $s0, 0x1
  .L800B7FD8:
    /* A87D8 800B7FD8 6801428E */  lw         $v0, 0x168($s2)
    /* A87DC 800B7FDC 00000000 */  nop
    /* A87E0 800B7FE0 0400428C */  lw         $v0, 0x4($v0)
    /* A87E4 800B7FE4 16E00208 */  j          .L800B8058
    /* A87E8 800B7FE8 BC0042AE */   sw        $v0, 0xBC($s2)
  .L800B7FEC:
    /* A87EC 800B7FEC 3000428E */  lw         $v0, 0x30($s2)
    /* A87F0 800B7FF0 00000000 */  nop
    /* A87F4 800B7FF4 04004230 */  andi       $v0, $v0, 0x4
    /* A87F8 800B7FF8 17004010 */  beqz       $v0, .L800B8058
    /* A87FC 800B7FFC 21800000 */   addu      $s0, $zero, $zero
    /* A8800 800B8000 7001518E */  lw         $s1, 0x170($s2)
  .L800B8004:
    /* A8804 800B8004 00000000 */  nop
    /* A8808 800B8008 13002012 */  beqz       $s1, .L800B8058
    /* A880C 800B800C 00000000 */   nop
    /* A8810 800B8010 00002296 */  lhu        $v0, 0x0($s1)
    /* A8814 800B8014 00000000 */  nop
    /* A8818 800B8018 FBFF4430 */  andi       $a0, $v0, 0xFFFB
    /* A881C 800B801C 000024A6 */  sh         $a0, 0x0($s1)
    /* A8820 800B8020 80101000 */  sll        $v0, $s0, 2
    /* A8824 800B8024 21105000 */  addu       $v0, $v0, $s0
    /* A8828 800B8028 C0100200 */  sll        $v0, $v0, 3
    /* A882C 800B802C B001438E */  lw         $v1, 0x1B0($s2)
    /* A8830 800B8030 00000000 */  nop
    /* A8834 800B8034 21104300 */  addu       $v0, $v0, $v1
    /* A8838 800B8038 24004284 */  lh         $v0, 0x24($v0)
    /* A883C 800B803C 00000000 */  nop
    /* A8840 800B8040 02004010 */  beqz       $v0, .L800B804C
    /* A8844 800B8044 04008234 */   ori       $v0, $a0, 0x4
    /* A8848 800B8048 000022A6 */  sh         $v0, 0x0($s1)
  .L800B804C:
    /* A884C 800B804C 0C00318E */  lw         $s1, 0xC($s1)
    /* A8850 800B8050 01E00208 */  j          .L800B8004
    /* A8854 800B8054 01001026 */   addiu     $s0, $s0, 0x1
  .L800B8058:
    /* A8858 800B8058 3000428E */  lw         $v0, 0x30($s2)
    /* A885C 800B805C 00000000 */  nop
    /* A8860 800B8060 00084230 */  andi       $v0, $v0, 0x800
    /* A8864 800B8064 07004014 */  bnez       $v0, .L800B8084
    /* A8868 800B8068 00000000 */   nop
    /* A886C 800B806C BCC5020C */  jal        func_800B16F0
    /* A8870 800B8070 21204002 */   addu      $a0, $s2, $zero
    /* A8874 800B8074 1A12040C */  jal        func_80104868
    /* A8878 800B8078 00000000 */   nop
    /* A887C 800B807C BF12040C */  jal        func_80104AFC
    /* A8880 800B8080 00000000 */   nop
  .L800B8084:
    /* A8884 800B8084 1680013C */  lui        $at, %hi(D_80158A04)
    /* A8888 800B8088 048A33AC */  sw         $s3, %lo(D_80158A04)($at)
    /* A888C 800B808C BC00428E */  lw         $v0, 0xBC($s2)
    /* A8890 800B8090 3001BF8F */  lw         $ra, 0x130($sp)
    /* A8894 800B8094 2C01B38F */  lw         $s3, 0x12C($sp)
    /* A8898 800B8098 2801B28F */  lw         $s2, 0x128($sp)
    /* A889C 800B809C 2401B18F */  lw         $s1, 0x124($sp)
    /* A88A0 800B80A0 2001B08F */  lw         $s0, 0x120($sp)
    /* A88A4 800B80A4 3801BD27 */  addiu      $sp, $sp, 0x138
    /* A88A8 800B80A8 0800E003 */  jr         $ra
    /* A88AC 800B80AC 00000000 */   nop
endlabel func_800B7D48
