.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_80012020

dlabel jtbl_80012020
    /* 2820 80012020 5CB00A80 */ .word .L800AB05C
    /* 2824 80012024 BCB00A80 */ .word .L800AB0BC
    /* 2828 80012028 24B00A80 */ .word .L800AB024
    /* 282C 8001202C BCB00A80 */ .word .L800AB0BC
    /* 2830 80012030 5CB00A80 */ .word .L800AB05C
    /* 2834 80012034 BCB00A80 */ .word .L800AB0BC
    /* 2838 80012038 24B00A80 */ .word .L800AB024
    /* 283C 8001203C BCB00A80 */ .word .L800AB0BC
    /* 2840 80012040 BCB00A80 */ .word .L800AB0BC
    /* 2844 80012044 BCB00A80 */ .word .L800AB0BC
    /* 2848 80012048 BCB00A80 */ .word .L800AB0BC
    /* 284C 8001204C BCB00A80 */ .word .L800AB0BC
    /* 2850 80012050 BCB00A80 */ .word .L800AB0BC
    /* 2854 80012054 BCB00A80 */ .word .L800AB0BC
    /* 2858 80012058 BCB00A80 */ .word .L800AB0BC
    /* 285C 8001205C BCB00A80 */ .word .L800AB0BC
    /* 2860 80012060 BCB00A80 */ .word .L800AB0BC
    /* 2864 80012064 BCB00A80 */ .word .L800AB0BC
    /* 2868 80012068 BCB00A80 */ .word .L800AB0BC
    /* 286C 8001206C BCB00A80 */ .word .L800AB0BC
    /* 2870 80012070 BCB00A80 */ .word .L800AB0BC
    /* 2874 80012074 BCB00A80 */ .word .L800AB0BC
    /* 2878 80012078 BCB00A80 */ .word .L800AB0BC
    /* 287C 8001207C BCB00A80 */ .word .L800AB0BC
    /* 2880 80012080 BCB00A80 */ .word .L800AB0BC
    /* 2884 80012084 BCB00A80 */ .word .L800AB0BC
    /* 2888 80012088 BCB00A80 */ .word .L800AB0BC
    /* 288C 8001208C BCB00A80 */ .word .L800AB0BC
    /* 2890 80012090 BCB00A80 */ .word .L800AB0BC
    /* 2894 80012094 BCB00A80 */ .word .L800AB0BC
    /* 2898 80012098 BCB00A80 */ .word .L800AB0BC
    /* 289C 8001209C BCB00A80 */ .word .L800AB0BC
    /* 28A0 800120A0 BCB00A80 */ .word .L800AB0BC
    /* 28A4 800120A4 BCB00A80 */ .word .L800AB0BC
    /* 28A8 800120A8 BCB00A80 */ .word .L800AB0BC
    /* 28AC 800120AC BCB00A80 */ .word .L800AB0BC
    /* 28B0 800120B0 BCB00A80 */ .word .L800AB0BC
    /* 28B4 800120B4 BCB00A80 */ .word .L800AB0BC
    /* 28B8 800120B8 BCB00A80 */ .word .L800AB0BC
    /* 28BC 800120BC BCB00A80 */ .word .L800AB0BC
    /* 28C0 800120C0 BCB00A80 */ .word .L800AB0BC
    /* 28C4 800120C4 BCB00A80 */ .word .L800AB0BC
    /* 28C8 800120C8 BCB00A80 */ .word .L800AB0BC
    /* 28CC 800120CC BCB00A80 */ .word .L800AB0BC
    /* 28D0 800120D0 BCB00A80 */ .word .L800AB0BC
    /* 28D4 800120D4 BCB00A80 */ .word .L800AB0BC
    /* 28D8 800120D8 98B00A80 */ .word .L800AB098
enddlabel jtbl_80012020


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800AAFAC, 0x120

glabel func_800AAFAC
    /* 9B7AC 800AAFAC D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 9B7B0 800AAFB0 2000BFAF */  sw         $ra, 0x20($sp)
    /* 9B7B4 800AAFB4 21188000 */  addu       $v1, $a0, $zero
    /* 9B7B8 800AAFB8 6C08848F */  lw         $a0, %gp_rel(D_80158D44)($gp)
    /* 9B7BC 800AAFBC 00000000 */  nop
    /* 9B7C0 800AAFC0 040E8284 */  lh         $v0, 0xE04($a0)
    /* 9B7C4 800AAFC4 00000000 */  nop
    /* 9B7C8 800AAFC8 0A004014 */  bnez       $v0, .L800AAFF4
    /* 9B7CC 800AAFCC 21286000 */   addu      $a1, $v1, $zero
    /* 9B7D0 800AAFD0 00140300 */  sll        $v0, $v1, 16
    /* 9B7D4 800AAFD4 031C0200 */  sra        $v1, $v0, 16
    /* 9B7D8 800AAFD8 D3006228 */  slti       $v0, $v1, 0xD3
    /* 9B7DC 800AAFDC 37004010 */  beqz       $v0, .L800AB0BC
    /* 9B7E0 800AAFE0 D0006228 */   slti      $v0, $v1, 0xD0
    /* 9B7E4 800AAFE4 33004010 */  beqz       $v0, .L800AB0B4
    /* 9B7E8 800AAFE8 00000000 */   nop
    /* 9B7EC 800AAFEC 2FAC0208 */  j          .L800AB0BC
    /* 9B7F0 800AAFF0 00000000 */   nop
  .L800AAFF4:
    /* 9B7F4 800AAFF4 5EFFA224 */  addiu      $v0, $a1, -0xA2
    /* 9B7F8 800AAFF8 00140200 */  sll        $v0, $v0, 16
    /* 9B7FC 800AAFFC 031C0200 */  sra        $v1, $v0, 16
    /* 9B800 800AB000 2F00622C */  sltiu      $v0, $v1, 0x2F
    /* 9B804 800AB004 2D004010 */  beqz       $v0, .L800AB0BC
    /* 9B808 800AB008 80100300 */   sll       $v0, $v1, 2
    /* 9B80C 800AB00C 0180013C */  lui        $at, %hi(jtbl_80012020)
    /* 9B810 800AB010 21082200 */  addu       $at, $at, $v0
    /* 9B814 800AB014 2020228C */  lw         $v0, %lo(jtbl_80012020)($at)
    /* 9B818 800AB018 00000000 */  nop
    /* 9B81C 800AB01C 08004000 */  jr         $v0
    /* 9B820 800AB020 00000000 */   nop
  .L800AB024:
    /* 9B824 800AB024 7A088287 */  lh         $v0, %gp_rel(D_80158D52)($gp)
    /* 9B828 800AB028 00000000 */  nop
    /* 9B82C 800AB02C 05004018 */  blez       $v0, .L800AB044
    /* 9B830 800AB030 21184000 */   addu      $v1, $v0, $zero
    /* 9B834 800AB034 FFFF6224 */  addiu      $v0, $v1, -0x1
    /* 9B838 800AB038 7A0882A7 */  sh         $v0, %gp_rel(D_80158D52)($gp)
    /* 9B83C 800AB03C 2FAC0208 */  j          .L800AB0BC
    /* 9B840 800AB040 00000000 */   nop
  .L800AB044:
    /* 9B844 800AB044 C4108294 */  lhu        $v0, 0x10C4($a0)
    /* 9B848 800AB048 00000000 */  nop
    /* 9B84C 800AB04C FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 9B850 800AB050 7A0882A7 */  sh         $v0, %gp_rel(D_80158D52)($gp)
    /* 9B854 800AB054 2FAC0208 */  j          .L800AB0BC
    /* 9B858 800AB058 00000000 */   nop
  .L800AB05C:
    /* 9B85C 800AB05C 7A088387 */  lh         $v1, %gp_rel(D_80158D52)($gp)
    /* 9B860 800AB060 00000000 */  nop
    /* 9B864 800AB064 21286000 */  addu       $a1, $v1, $zero
    /* 9B868 800AB068 C4108284 */  lh         $v0, 0x10C4($a0)
    /* 9B86C 800AB06C 00000000 */  nop
    /* 9B870 800AB070 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 9B874 800AB074 2A186200 */  slt        $v1, $v1, $v0
    /* 9B878 800AB078 04006010 */  beqz       $v1, .L800AB08C
    /* 9B87C 800AB07C 0100A224 */   addiu     $v0, $a1, 0x1
    /* 9B880 800AB080 7A0882A7 */  sh         $v0, %gp_rel(D_80158D52)($gp)
    /* 9B884 800AB084 2FAC0208 */  j          .L800AB0BC
    /* 9B888 800AB088 00000000 */   nop
  .L800AB08C:
    /* 9B88C 800AB08C 7A0880A7 */  sh         $zero, %gp_rel(D_80158D52)($gp)
    /* 9B890 800AB090 2FAC0208 */  j          .L800AB0BC
    /* 9B894 800AB094 00000000 */   nop
  .L800AB098:
    /* 9B898 800AB098 7A088287 */  lh         $v0, %gp_rel(D_80158D52)($gp)
    /* 9B89C 800AB09C 00000000 */  nop
    /* 9B8A0 800AB0A0 40100200 */  sll        $v0, $v0, 1
    /* 9B8A4 800AB0A4 21104400 */  addu       $v0, $v0, $a0
    /* 9B8A8 800AB0A8 B4104294 */  lhu        $v0, 0x10B4($v0)
    /* 9B8AC 800AB0AC 00000000 */  nop
    /* 9B8B0 800AB0B0 080E82A4 */  sh         $v0, 0xE08($a0)
  .L800AB0B4:
    /* 9B8B4 800AB0B4 31DE030C */  jal        func_800F78C4
    /* 9B8B8 800AB0B8 BC008424 */   addiu     $a0, $a0, 0xBC
  .L800AB0BC:
    /* 9B8BC 800AB0BC 2000BF8F */  lw         $ra, 0x20($sp)
    /* 9B8C0 800AB0C0 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 9B8C4 800AB0C4 0800E003 */  jr         $ra
    /* 9B8C8 800AB0C8 00000000 */   nop
endlabel func_800AAFAC
