.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_8001321C

dlabel D_8001321C
    /* 3A1C 8001321C */ .asciz "TILES.SPS"
    /* 54494C45532E535053000000 */
.align 2
enddlabel D_8001321C


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800DA338, 0x50

glabel func_800DA338
    /* CAB38 800DA338 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* CAB3C 800DA33C 1000BFAF */  sw         $ra, 0x10($sp)
    /* CAB40 800DA340 0180043C */  lui        $a0, %hi(D_8001321C)
    /* CAB44 800DA344 1C328424 */  addiu      $a0, $a0, %lo(D_8001321C)
    /* CAB48 800DA348 EBF2030C */  jal        func_800FCBAC
    /* CAB4C 800DA34C 00000000 */   nop
    /* CAB50 800DA350 2667030C */  jal        func_800D9C98
    /* CAB54 800DA354 00000000 */   nop
    /* CAB58 800DA358 6D65030C */  jal        func_800D95B4
    /* CAB5C 800DA35C 00000000 */   nop
    /* CAB60 800DA360 A363030C */  jal        func_800D8E8C
    /* CAB64 800DA364 00000000 */   nop
    /* CAB68 800DA368 CD67030C */  jal        func_800D9F34
    /* CAB6C 800DA36C 00000000 */   nop
    /* CAB70 800DA370 0DF3030C */  jal        func_800FCC34
    /* CAB74 800DA374 00000000 */   nop
    /* CAB78 800DA378 1000BF8F */  lw         $ra, 0x10($sp)
    /* CAB7C 800DA37C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* CAB80 800DA380 0800E003 */  jr         $ra
    /* CAB84 800DA384 00000000 */   nop
endlabel func_800DA338
