.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80013228

dlabel D_80013228
    /* 3A28 80013228 */ .asciz "WINWIN.STR"
    /* 57494E57494E2E5354520000 */
.align 2
enddlabel D_80013228


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800DE1C8, 0xBC

glabel func_800DE1C8
    /* CE9C8 800DE1C8 C8FEBD27 */  addiu      $sp, $sp, -0x138
    /* CE9CC 800DE1CC 3001BFAF */  sw         $ra, 0x130($sp)
    /* CE9D0 800DE1D0 2C01B1AF */  sw         $s1, 0x12C($sp)
    /* CE9D4 800DE1D4 2801B0AF */  sw         $s0, 0x128($sp)
    /* CE9D8 800DE1D8 21888000 */  addu       $s1, $a0, $zero
    /* CE9DC 800DE1DC 299D020C */  jal        func_800A74A4
    /* CE9E0 800DE1E0 2180A000 */   addu      $s0, $a1, $zero
    /* CE9E4 800DE1E4 0400001E */  bgtz       $s0, .L800DE1F8
    /* CE9E8 800DE1E8 100230AE */   sw        $s0, 0x210($s1)
    /* CE9EC 800DE1EC 27101000 */  nor        $v0, $zero, $s0
    /* CE9F0 800DE1F0 01004224 */  addiu      $v0, $v0, 0x1
    /* CE9F4 800DE1F4 100222AE */  sw         $v0, 0x210($s1)
  .L800DE1F8:
    /* CE9F8 800DE1F8 221B040C */  jal        func_80106C88
    /* CE9FC 800DE1FC 1801A427 */   addiu     $a0, $sp, 0x118
    /* CEA00 800DE200 84003026 */  addiu      $s0, $s1, 0x84
    /* CEA04 800DE204 3C000224 */  addiu      $v0, $zero, 0x3C
    /* CEA08 800DE208 1000A2AF */  sw         $v0, 0x10($sp)
    /* CEA0C 800DE20C 21200002 */  addu       $a0, $s0, $zero
    /* CEA10 800DE210 1680053C */  lui        $a1, %hi(D_80159258)
    /* CEA14 800DE214 5892A524 */  addiu      $a1, $a1, %lo(D_80159258)
    /* CEA18 800DE218 00080624 */  addiu      $a2, $zero, 0x800
    /* CEA1C 800DE21C B8D7030C */  jal        func_800F5EE0
    /* CEA20 800DE220 21380000 */   addu      $a3, $zero, $zero
    /* CEA24 800DE224 0180053C */  lui        $a1, %hi(D_80013228)
    /* CEA28 800DE228 2832A524 */  addiu      $a1, $a1, %lo(D_80013228)
    /* CEA2C 800DE22C FAD7030C */  jal        func_800F5FE8
    /* CEA30 800DE230 21200002 */   addu      $a0, $s0, $zero
    /* CEA34 800DE234 0E80053C */  lui        $a1, %hi(func_800DE830)
    /* CEA38 800DE238 30E8A524 */  addiu      $a1, $a1, %lo(func_800DE830)
    /* CEA3C 800DE23C C3D8030C */  jal        func_800F630C
    /* CEA40 800DE240 21200002 */   addu      $a0, $s0, $zero
    /* CEA44 800DE244 400620A6 */  sh         $zero, 0x640($s1)
    /* CEA48 800DE248 3C000224 */  addiu      $v0, $zero, 0x3C
    /* CEA4C 800DE24C 420622A6 */  sh         $v0, 0x642($s1)
    /* CEA50 800DE250 40010224 */  addiu      $v0, $zero, 0x140
    /* CEA54 800DE254 440622A6 */  sh         $v0, 0x644($s1)
    /* CEA58 800DE258 B4000224 */  addiu      $v0, $zero, 0xB4
    /* CEA5C 800DE25C 460622A6 */  sh         $v0, 0x646($s1)
    /* CEA60 800DE260 9C79030C */  jal        func_800DE670
    /* CEA64 800DE264 21202002 */   addu      $a0, $s1, $zero
    /* CEA68 800DE268 01000224 */  addiu      $v0, $zero, 0x1
    /* CEA6C 800DE26C 3001BF8F */  lw         $ra, 0x130($sp)
    /* CEA70 800DE270 2C01B18F */  lw         $s1, 0x12C($sp)
    /* CEA74 800DE274 2801B08F */  lw         $s0, 0x128($sp)
    /* CEA78 800DE278 3801BD27 */  addiu      $sp, $sp, 0x138
    /* CEA7C 800DE27C 0800E003 */  jr         $ra
    /* CEA80 800DE280 00000000 */   nop
endlabel func_800DE1C8
