.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80012158

dlabel D_80012158
    /* 2958 80012158 */ .asciz "Civilopedia: Seven Wonders"
    /* 436976696C6F70656469613A20536576656E20576F6E646572730000 */
.align 2
enddlabel D_80012158


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800AD994, 0x12C

glabel func_800AD994
    /* 9E194 800AD994 30FDBD27 */  addiu      $sp, $sp, -0x2D0
    /* 9E198 800AD998 CC02BFAF */  sw         $ra, 0x2CC($sp)
    /* 9E19C 800AD99C C802B0AF */  sw         $s0, 0x2C8($sp)
    /* 9E1A0 800AD9A0 2800A427 */  addiu      $a0, $sp, 0x28
    /* 9E1A4 800AD9A4 ADC5020C */  jal        func_800B16B4
    /* 9E1A8 800AD9A8 00200524 */   addiu     $a1, $zero, 0x2000
    /* 9E1AC 800AD9AC 2800B027 */  addiu      $s0, $sp, 0x28
  .L800AD9B0:
    /* 9E1B0 800AD9B0 A008858F */  lw         $a1, %gp_rel(D_80158D78)($gp)
    /* 9E1B4 800AD9B4 01000224 */  addiu      $v0, $zero, 0x1
    /* 9E1B8 800AD9B8 1000A0AF */  sw         $zero, 0x10($sp)
    /* 9E1BC 800AD9BC 1400A0AF */  sw         $zero, 0x14($sp)
    /* 9E1C0 800AD9C0 1800A0AF */  sw         $zero, 0x18($sp)
    /* 9E1C4 800AD9C4 1C00A0AF */  sw         $zero, 0x1C($sp)
    /* 9E1C8 800AD9C8 2000A2AF */  sw         $v0, 0x20($sp)
    /* 9E1CC 800AD9CC 21200002 */  addu       $a0, $s0, $zero
    /* 9E1D0 800AD9D0 6F060624 */  addiu      $a2, $zero, 0x66F
    /* 9E1D4 800AD9D4 2CE0020C */  jal        func_800B80B0
    /* 9E1D8 800AD9D8 21380000 */   addu      $a3, $zero, $zero
    /* 9E1DC 800AD9DC 0180053C */  lui        $a1, %hi(D_80012158)
    /* 9E1E0 800AD9E0 5821A524 */  addiu      $a1, $a1, %lo(D_80012158)
    /* 9E1E4 800AD9E4 1CC8020C */  jal        func_800B2070
    /* 9E1E8 800AD9E8 21200002 */   addu      $a0, $s0, $zero
    /* 9E1EC 800AD9EC 21200002 */  addu       $a0, $s0, $zero
    /* 9E1F0 800AD9F0 D3C7020C */  jal        func_800B1F4C
    /* 9E1F4 800AD9F4 02000524 */   addiu     $a1, $zero, 0x2
    /* 9E1F8 800AD9F8 23001024 */  addiu      $s0, $zero, 0x23
    /* 9E1FC 800AD9FC C0181000 */  sll        $v1, $s0, 3
  .L800ADA00:
    /* 9E200 800ADA00 1180013C */  lui        $at, %hi(D_8010D06A)
    /* 9E204 800ADA04 21082300 */  addu       $at, $at, $v1
    /* 9E208 800ADA08 6AD02280 */  lb         $v0, %lo(D_8010D06A)($at)
    /* 9E20C 800ADA0C 00000000 */  nop
    /* 9E210 800ADA10 FFFF4228 */  slti       $v0, $v0, -0x1
    /* 9E214 800ADA14 0A004014 */  bnez       $v0, .L800ADA40
    /* 9E218 800ADA18 00000000 */   nop
    /* 9E21C 800ADA1C 1180013C */  lui        $at, %hi(D_8010D064)
    /* 9E220 800ADA20 21082300 */  addu       $at, $at, $v1
    /* 9E224 800ADA24 64D0248C */  lw         $a0, %lo(D_8010D064)($at)
    /* 9E228 800ADA28 A63A030C */  jal        func_800CEA98
    /* 9E22C 800ADA2C 00000000 */   nop
    /* 9E230 800ADA30 2800A427 */  addiu      $a0, $sp, 0x28
    /* 9E234 800ADA34 21284000 */  addu       $a1, $v0, $zero
    /* 9E238 800ADA38 A8C9020C */  jal        func_800B26A0
    /* 9E23C 800ADA3C 21300002 */   addu      $a2, $s0, $zero
  .L800ADA40:
    /* 9E240 800ADA40 01001026 */  addiu      $s0, $s0, 0x1
    /* 9E244 800ADA44 4300022A */  slti       $v0, $s0, 0x43
    /* 9E248 800ADA48 EDFF4014 */  bnez       $v0, .L800ADA00
    /* 9E24C 800ADA4C C0181000 */   sll       $v1, $s0, 3
    /* 9E250 800ADA50 2800A427 */  addiu      $a0, $sp, 0x28
    /* 9E254 800ADA54 21280000 */  addu       $a1, $zero, $zero
    /* 9E258 800ADA58 78000624 */  addiu      $a2, $zero, 0x78
    /* 9E25C 800ADA5C ACE2020C */  jal        func_800B8AB0
    /* 9E260 800ADA60 E8030724 */   addiu     $a3, $zero, 0x3E8
    /* 9E264 800ADA64 2800A427 */  addiu      $a0, $sp, 0x28
    /* 9E268 800ADA68 21280000 */  addu       $a1, $zero, $zero
    /* 9E26C 800ADA6C 78000624 */  addiu      $a2, $zero, 0x78
    /* 9E270 800ADA70 B0E2020C */  jal        func_800B8AC0
    /* 9E274 800ADA74 E8030724 */   addiu     $a3, $zero, 0x3E8
    /* 9E278 800ADA78 2800A427 */  addiu      $a0, $sp, 0x28
    /* 9E27C 800ADA7C 52DF020C */  jal        func_800B7D48
    /* 9E280 800ADA80 21280000 */   addu      $a1, $zero, $zero
    /* 9E284 800ADA84 21804000 */  addu       $s0, $v0, $zero
    /* 9E288 800ADA88 05000006 */  bltz       $s0, .L800ADAA0
    /* 9E28C 800ADA8C 00000000 */   nop
    /* 9E290 800ADA90 53B4020C */  jal        func_800AD14C
    /* 9E294 800ADA94 21200002 */   addu      $a0, $s0, $zero
    /* 9E298 800ADA98 6CB60208 */  j          .L800AD9B0
    /* 9E29C 800ADA9C 2800B027 */   addiu     $s0, $sp, 0x28
  .L800ADAA0:
    /* 9E2A0 800ADAA0 2800A427 */  addiu      $a0, $sp, 0x28
    /* 9E2A4 800ADAA4 0AC7020C */  jal        func_800B1C28
    /* 9E2A8 800ADAA8 02000524 */   addiu     $a1, $zero, 0x2
    /* 9E2AC 800ADAAC CC02BF8F */  lw         $ra, 0x2CC($sp)
    /* 9E2B0 800ADAB0 C802B08F */  lw         $s0, 0x2C8($sp)
    /* 9E2B4 800ADAB4 D002BD27 */  addiu      $sp, $sp, 0x2D0
    /* 9E2B8 800ADAB8 0800E003 */  jr         $ra
    /* 9E2BC 800ADABC 00000000 */   nop
endlabel func_800AD994
