.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_800121D8

dlabel D_800121D8
    /* 29D8 800121D8 */ .asciz "Command:\n \n \nEnter\nDelete\nDone"
    /* 436F6D6D616E643A0A200A200A456E7465720A44656C6574650A446F6E650000 */
.align 2
enddlabel D_800121D8


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800B6EA0, 0xEA8

glabel func_800B6EA0
    /* A76A0 800B6EA0 78FFBD27 */  addiu      $sp, $sp, -0x88
    /* A76A4 800B6EA4 8400BFAF */  sw         $ra, 0x84($sp)
    /* A76A8 800B6EA8 8000BEAF */  sw         $fp, 0x80($sp)
    /* A76AC 800B6EAC 7C00B7AF */  sw         $s7, 0x7C($sp)
    /* A76B0 800B6EB0 7800B6AF */  sw         $s6, 0x78($sp)
    /* A76B4 800B6EB4 7400B5AF */  sw         $s5, 0x74($sp)
    /* A76B8 800B6EB8 7000B4AF */  sw         $s4, 0x70($sp)
    /* A76BC 800B6EBC 6C00B3AF */  sw         $s3, 0x6C($sp)
    /* A76C0 800B6EC0 6800B2AF */  sw         $s2, 0x68($sp)
    /* A76C4 800B6EC4 6400B1AF */  sw         $s1, 0x64($sp)
    /* A76C8 800B6EC8 6000B0AF */  sw         $s0, 0x60($sp)
    /* A76CC 800B6ECC 21908000 */  addu       $s2, $a0, $zero
    /* A76D0 800B6ED0 3000428E */  lw         $v0, 0x30($s2)
    /* A76D4 800B6ED4 00000000 */  nop
    /* A76D8 800B6ED8 20004230 */  andi       $v0, $v0, 0x20
    /* A76DC 800B6EDC 09004014 */  bnez       $v0, .L800B6F04
    /* A76E0 800B6EE0 00000000 */   nop
    /* A76E4 800B6EE4 BDCC020C */  jal        func_800B32F4
    /* A76E8 800B6EE8 00000000 */   nop
    /* A76EC 800B6EEC 89034014 */  bnez       $v0, .L800B7D14
    /* A76F0 800B6EF0 00000000 */   nop
    /* A76F4 800B6EF4 2FD8020C */  jal        func_800B60BC
    /* A76F8 800B6EF8 21204002 */   addu      $a0, $s2, $zero
    /* A76FC 800B6EFC 0DD9020C */  jal        func_800B6434
    /* A7700 800B6F00 21204002 */   addu      $a0, $s2, $zero
  .L800B6F04:
    /* A7704 800B6F04 2802448E */  lw         $a0, 0x228($s2)
    /* A7708 800B6F08 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* A770C 800B6F0C 0B008210 */  beq        $a0, $v0, .L800B6F3C
    /* A7710 800B6F10 00000000 */   nop
    /* A7714 800B6F14 A81E040C */  jal        func_80107AA0
    /* A7718 800B6F18 00000000 */   nop
    /* A771C 800B6F1C 06004010 */  beqz       $v0, .L800B6F38
    /* A7720 800B6F20 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* A7724 800B6F24 3000428E */  lw         $v0, 0x30($s2)
    /* A7728 800B6F28 00000000 */  nop
    /* A772C 800B6F2C 20004234 */  ori        $v0, $v0, 0x20
    /* A7730 800B6F30 45DF0208 */  j          .L800B7D14
    /* A7734 800B6F34 300042AE */   sw        $v0, 0x30($s2)
  .L800B6F38:
    /* A7738 800B6F38 280242AE */  sw         $v0, 0x228($s2)
  .L800B6F3C:
    /* A773C 800B6F3C 7907040C */  jal        func_80101DE4
    /* A7740 800B6F40 01000424 */   addiu     $a0, $zero, 0x1
    /* A7744 800B6F44 3000428E */  lw         $v0, 0x30($s2)
    /* A7748 800B6F48 4000033C */  lui        $v1, (0x400000 >> 16)
    /* A774C 800B6F4C 24104300 */  and        $v0, $v0, $v1
    /* A7750 800B6F50 05004010 */  beqz       $v0, .L800B6F68
    /* A7754 800B6F54 80000224 */   addiu     $v0, $zero, 0x80
    /* A7758 800B6F58 16801E3C */  lui        $fp, %hi(D_801592E4)
    /* A775C 800B6F5C E492DE87 */  lh         $fp, %lo(D_801592E4)($fp)
    /* A7760 800B6F60 1680013C */  lui        $at, %hi(D_801592E4)
    /* A7764 800B6F64 E49222A4 */  sh         $v0, %lo(D_801592E4)($at)
  .L800B6F68:
    /* A7768 800B6F68 3000428E */  lw         $v0, 0x30($s2)
    /* A776C 800B6F6C 00000000 */  nop
    /* A7770 800B6F70 00404230 */  andi       $v0, $v0, 0x4000
    /* A7774 800B6F74 80024014 */  bnez       $v0, .L800B7978
    /* A7778 800B6F78 00000000 */   nop
    /* A777C 800B6F7C CC00428E */  lw         $v0, 0xCC($s2)
    /* A7780 800B6F80 D000438E */  lw         $v1, 0xD0($s2)
    /* A7784 800B6F84 3400448E */  lw         $a0, 0x34($s2)
    /* A7788 800B6F88 3800458E */  lw         $a1, 0x38($s2)
    /* A778C 800B6F8C 1800A2A7 */  sh         $v0, 0x18($sp)
    /* A7790 800B6F90 1A00A3A7 */  sh         $v1, 0x1A($sp)
    /* A7794 800B6F94 21104400 */  addu       $v0, $v0, $a0
    /* A7798 800B6F98 1C00A2A7 */  sh         $v0, 0x1C($sp)
    /* A779C 800B6F9C 21186500 */  addu       $v1, $v1, $a1
    /* A77A0 800B6FA0 1E00A3A7 */  sh         $v1, 0x1E($sp)
    /* A77A4 800B6FA4 8001428E */  lw         $v0, 0x180($s2)
    /* A77A8 800B6FA8 00000000 */  nop
    /* A77AC 800B6FAC A4014010 */  beqz       $v0, .L800B7640
    /* A77B0 800B6FB0 00000000 */   nop
    /* A77B4 800B6FB4 1180023C */  lui        $v0, %hi(D_8010CBEC)
    /* A77B8 800B6FB8 ECCB428C */  lw         $v0, %lo(D_8010CBEC)($v0)
    /* A77BC 800B6FBC 00000000 */  nop
    /* A77C0 800B6FC0 0400448C */  lw         $a0, 0x4($v0)
    /* A77C4 800B6FC4 D707040C */  jal        func_80101F5C
    /* A77C8 800B6FC8 2C011124 */   addiu     $s1, $zero, 0x12C
    /* A77CC 800B6FCC D8000224 */  addiu      $v0, $zero, 0xD8
    /* A77D0 800B6FD0 2000A2A7 */  sh         $v0, 0x20($sp)
    /* A77D4 800B6FD4 20000224 */  addiu      $v0, $zero, 0x20
    /* A77D8 800B6FD8 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A77DC 800B6FDC 2400B1A7 */  sh         $s1, 0x24($sp)
    /* A77E0 800B6FE0 98000224 */  addiu      $v0, $zero, 0x98
    /* A77E4 800B6FE4 2600A2A7 */  sh         $v0, 0x26($sp)
    /* A77E8 800B6FE8 2000B027 */  addiu      $s0, $sp, 0x20
    /* A77EC 800B6FEC 21200002 */  addu       $a0, $s0, $zero
    /* A77F0 800B6FF0 A314020C */  jal        func_8008528C
    /* A77F4 800B6FF4 21280000 */   addu      $a1, $zero, $zero
    /* A77F8 800B6FF8 D001428E */  lw         $v0, 0x1D0($s2)
    /* A77FC 800B6FFC 00000000 */  nop
    /* A7800 800B7000 0F004014 */  bnez       $v0, .L800B7040
    /* A7804 800B7004 E8000224 */   addiu     $v0, $zero, 0xE8
    /* A7808 800B7008 2000A2A7 */  sh         $v0, 0x20($sp)
    /* A780C 800B700C 38000224 */  addiu      $v0, $zero, 0x38
    /* A7810 800B7010 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7814 800B7014 2400B1A7 */  sh         $s1, 0x24($sp)
    /* A7818 800B7018 70000224 */  addiu      $v0, $zero, 0x70
    /* A781C 800B701C 2600A2A7 */  sh         $v0, 0x26($sp)
    /* A7820 800B7020 0180043C */  lui        $a0, %hi(D_800121D8)
    /* A7824 800B7024 D8218424 */  addiu      $a0, $a0, %lo(D_800121D8)
    /* A7828 800B7028 21280002 */  addu       $a1, $s0, $zero
    /* A782C 800B702C DC0F040C */  jal        func_80103F70
    /* A7830 800B7030 10000624 */   addiu     $a2, $zero, 0x10
    /* A7834 800B7034 D00142AE */  sw         $v0, 0x1D0($s2)
    /* A7838 800B7038 03000224 */  addiu      $v0, $zero, 0x3
    /* A783C 800B703C 040242A6 */  sh         $v0, 0x204($s2)
  .L800B7040:
    /* A7840 800B7040 D001448E */  lw         $a0, 0x1D0($s2)
    /* A7844 800B7044 7D11040C */  jal        func_801045F4
    /* A7848 800B7048 00000000 */   nop
    /* A784C 800B704C 30000224 */  addiu      $v0, $zero, 0x30
    /* A7850 800B7050 2000A2A7 */  sh         $v0, 0x20($sp)
    /* A7854 800B7054 10000224 */  addiu      $v0, $zero, 0x10
    /* A7858 800B7058 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A785C 800B705C C8000224 */  addiu      $v0, $zero, 0xC8
    /* A7860 800B7060 2400A2A7 */  sh         $v0, 0x24($sp)
    /* A7864 800B7064 B0000224 */  addiu      $v0, $zero, 0xB0
    /* A7868 800B7068 2600A2A7 */  sh         $v0, 0x26($sp)
    /* A786C 800B706C 2000A427 */  addiu      $a0, $sp, 0x20
    /* A7870 800B7070 A314020C */  jal        func_8008528C
    /* A7874 800B7074 21280000 */   addu      $a1, $zero, $zero
    /* A7878 800B7078 D401428E */  lw         $v0, 0x1D4($s2)
    /* A787C 800B707C 00000000 */  nop
    /* A7880 800B7080 04014014 */  bnez       $v0, .L800B7494
    /* A7884 800B7084 21800000 */   addu      $s0, $zero, $zero
    /* A7888 800B7088 40000224 */  addiu      $v0, $zero, 0x40
    /* A788C 800B708C 2000A2A7 */  sh         $v0, 0x20($sp)
    /* A7890 800B7090 28000224 */  addiu      $v0, $zero, 0x28
    /* A7894 800B7094 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7898 800B7098 B8000224 */  addiu      $v0, $zero, 0xB8
    /* A789C 800B709C 2400A2A7 */  sh         $v0, 0x24($sp)
    /* A78A0 800B70A0 90000224 */  addiu      $v0, $zero, 0x90
    /* A78A4 800B70A4 2600A2A7 */  sh         $v0, 0x26($sp)
    /* A78A8 800B70A8 04024386 */  lh         $v1, 0x204($s2)
    /* A78AC 800B70AC 00000000 */  nop
    /* A78B0 800B70B0 0700622C */  sltiu      $v0, $v1, 0x7
    /* A78B4 800B70B4 F7004010 */  beqz       $v0, .L800B7494
    /* A78B8 800B70B8 80100300 */   sll       $v0, $v1, 2
    /* A78BC 800B70BC 0180013C */  lui        $at, %hi(jtbl_800123E4)
    /* A78C0 800B70C0 21082200 */  addu       $at, $at, $v0
    /* A78C4 800B70C4 E423228C */  lw         $v0, %lo(jtbl_800123E4)($at)
    /* A78C8 800B70C8 00000000 */  nop
    /* A78CC 800B70CC 08004000 */  jr         $v0
    /* A78D0 800B70D0 00000000 */   nop
  .L800B70D4:
    /* A78D4 800B70D4 21880000 */  addu       $s1, $zero, $zero
    /* A78D8 800B70D8 1280133C */  lui        $s3, %hi(D_801208EC)
    /* A78DC 800B70DC EC087326 */  addiu      $s3, $s3, %lo(D_801208EC)
    /* A78E0 800B70E0 80801100 */  sll        $s0, $s1, 2
  .L800B70E4:
    /* A78E4 800B70E4 21201102 */  addu       $a0, $s0, $s1
    /* A78E8 800B70E8 80200400 */  sll        $a0, $a0, 2
    /* A78EC 800B70EC 21209100 */  addu       $a0, $a0, $s1
    /* A78F0 800B70F0 21209300 */  addu       $a0, $a0, $s3
    /* A78F4 800B70F4 2000A527 */  addiu      $a1, $sp, 0x20
    /* A78F8 800B70F8 DC0F040C */  jal        func_80103F70
    /* A78FC 800B70FC 10000624 */   addiu     $a2, $zero, 0x10
    /* A7900 800B7100 21801202 */  addu       $s0, $s0, $s2
    /* A7904 800B7104 D40102AE */  sw         $v0, 0x1D4($s0)
    /* A7908 800B7108 2200A297 */  lhu        $v0, 0x22($sp)
    /* A790C 800B710C 00000000 */  nop
    /* A7910 800B7110 0C004224 */  addiu      $v0, $v0, 0xC
    /* A7914 800B7114 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7918 800B7118 01003126 */  addiu      $s1, $s1, 0x1
    /* A791C 800B711C 0A00222A */  slti       $v0, $s1, 0xA
    /* A7920 800B7120 F0FF4014 */  bnez       $v0, .L800B70E4
    /* A7924 800B7124 80801100 */   sll       $s0, $s1, 2
    /* A7928 800B7128 25DD0208 */  j          .L800B7494
    /* A792C 800B712C 21800000 */   addu      $s0, $zero, $zero
  .L800B7130:
    /* A7930 800B7130 21880000 */  addu       $s1, $zero, $zero
    /* A7934 800B7134 1280133C */  lui        $s3, %hi(D_801209C0)
    /* A7938 800B7138 C0097326 */  addiu      $s3, $s3, %lo(D_801209C0)
    /* A793C 800B713C 80801100 */  sll        $s0, $s1, 2
  .L800B7140:
    /* A7940 800B7140 21201102 */  addu       $a0, $s0, $s1
    /* A7944 800B7144 80200400 */  sll        $a0, $a0, 2
    /* A7948 800B7148 21209100 */  addu       $a0, $a0, $s1
    /* A794C 800B714C 21209300 */  addu       $a0, $a0, $s3
    /* A7950 800B7150 2000A527 */  addiu      $a1, $sp, 0x20
    /* A7954 800B7154 DC0F040C */  jal        func_80103F70
    /* A7958 800B7158 10000624 */   addiu     $a2, $zero, 0x10
    /* A795C 800B715C 21801202 */  addu       $s0, $s0, $s2
    /* A7960 800B7160 D40102AE */  sw         $v0, 0x1D4($s0)
    /* A7964 800B7164 2200A297 */  lhu        $v0, 0x22($sp)
    /* A7968 800B7168 00000000 */  nop
    /* A796C 800B716C 0C004224 */  addiu      $v0, $v0, 0xC
    /* A7970 800B7170 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7974 800B7174 01003126 */  addiu      $s1, $s1, 0x1
    /* A7978 800B7178 0A00222A */  slti       $v0, $s1, 0xA
    /* A797C 800B717C F0FF4014 */  bnez       $v0, .L800B7140
    /* A7980 800B7180 80801100 */   sll       $s0, $s1, 2
    /* A7984 800B7184 25DD0208 */  j          .L800B7494
    /* A7988 800B7188 21800000 */   addu      $s0, $zero, $zero
  .L800B718C:
    /* A798C 800B718C 21880000 */  addu       $s1, $zero, $zero
    /* A7990 800B7190 1280133C */  lui        $s3, %hi(D_80120A94)
    /* A7994 800B7194 940A7326 */  addiu      $s3, $s3, %lo(D_80120A94)
    /* A7998 800B7198 80801100 */  sll        $s0, $s1, 2
  .L800B719C:
    /* A799C 800B719C 21201102 */  addu       $a0, $s0, $s1
    /* A79A0 800B71A0 80200400 */  sll        $a0, $a0, 2
    /* A79A4 800B71A4 21209100 */  addu       $a0, $a0, $s1
    /* A79A8 800B71A8 21209300 */  addu       $a0, $a0, $s3
    /* A79AC 800B71AC 2000A527 */  addiu      $a1, $sp, 0x20
    /* A79B0 800B71B0 DC0F040C */  jal        func_80103F70
    /* A79B4 800B71B4 10000624 */   addiu     $a2, $zero, 0x10
    /* A79B8 800B71B8 21801202 */  addu       $s0, $s0, $s2
    /* A79BC 800B71BC D40102AE */  sw         $v0, 0x1D4($s0)
    /* A79C0 800B71C0 2200A297 */  lhu        $v0, 0x22($sp)
    /* A79C4 800B71C4 00000000 */  nop
    /* A79C8 800B71C8 0C004224 */  addiu      $v0, $v0, 0xC
    /* A79CC 800B71CC 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A79D0 800B71D0 01003126 */  addiu      $s1, $s1, 0x1
    /* A79D4 800B71D4 0500222A */  slti       $v0, $s1, 0x5
    /* A79D8 800B71D8 F0FF4014 */  bnez       $v0, .L800B719C
    /* A79DC 800B71DC 80801100 */   sll       $s0, $s1, 2
    /* A79E0 800B71E0 25DD0208 */  j          .L800B7494
    /* A79E4 800B71E4 21800000 */   addu      $s0, $zero, $zero
  .L800B71E8:
    /* A79E8 800B71E8 21880000 */  addu       $s1, $zero, $zero
    /* A79EC 800B71EC 1280133C */  lui        $s3, %hi(D_80120B00)
    /* A79F0 800B71F0 000B7326 */  addiu      $s3, $s3, %lo(D_80120B00)
    /* A79F4 800B71F4 80801100 */  sll        $s0, $s1, 2
  .L800B71F8:
    /* A79F8 800B71F8 21201102 */  addu       $a0, $s0, $s1
    /* A79FC 800B71FC 80200400 */  sll        $a0, $a0, 2
    /* A7A00 800B7200 21209100 */  addu       $a0, $a0, $s1
    /* A7A04 800B7204 21209300 */  addu       $a0, $a0, $s3
    /* A7A08 800B7208 2000A527 */  addiu      $a1, $sp, 0x20
    /* A7A0C 800B720C DC0F040C */  jal        func_80103F70
    /* A7A10 800B7210 10000624 */   addiu     $a2, $zero, 0x10
    /* A7A14 800B7214 21801202 */  addu       $s0, $s0, $s2
    /* A7A18 800B7218 D40102AE */  sw         $v0, 0x1D4($s0)
    /* A7A1C 800B721C 2200A297 */  lhu        $v0, 0x22($sp)
    /* A7A20 800B7220 00000000 */  nop
    /* A7A24 800B7224 0C004224 */  addiu      $v0, $v0, 0xC
    /* A7A28 800B7228 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7A2C 800B722C 01003126 */  addiu      $s1, $s1, 0x1
    /* A7A30 800B7230 0900222A */  slti       $v0, $s1, 0x9
    /* A7A34 800B7234 F0FF4014 */  bnez       $v0, .L800B71F8
    /* A7A38 800B7238 80801100 */   sll       $s0, $s1, 2
    /* A7A3C 800B723C 25DD0208 */  j          .L800B7494
    /* A7A40 800B7240 21800000 */   addu      $s0, $zero, $zero
  .L800B7244:
    /* A7A44 800B7244 0E024586 */  lh         $a1, 0x20E($s2)
    /* A7A48 800B7248 00000000 */  nop
    /* A7A4C 800B724C 80280500 */  sll        $a1, $a1, 2
    /* A7A50 800B7250 1280013C */  lui        $at, %hi(D_80120BD6)
    /* A7A54 800B7254 21082500 */  addu       $at, $at, $a1
    /* A7A58 800B7258 D60B2394 */  lhu        $v1, %lo(D_80120BD6)($at)
    /* A7A5C 800B725C 00000000 */  nop
    /* A7A60 800B7260 001C0300 */  sll        $v1, $v1, 16
    /* A7A64 800B7264 03240300 */  sra        $a0, $v1, 16
    /* A7A68 800B7268 6666023C */  lui        $v0, (0x66666667 >> 16)
    /* A7A6C 800B726C 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
    /* A7A70 800B7270 18008200 */  mult       $a0, $v0
    /* A7A74 800B7274 10400000 */  mfhi       $t0
    /* A7A78 800B7278 83100800 */  sra        $v0, $t0, 2
    /* A7A7C 800B727C C31F0300 */  sra        $v1, $v1, 31
    /* A7A80 800B7280 23104300 */  subu       $v0, $v0, $v1
    /* A7A84 800B7284 00140200 */  sll        $v0, $v0, 16
    /* A7A88 800B7288 03A40200 */  sra        $s4, $v0, 16
    /* A7A8C 800B728C 0C024386 */  lh         $v1, 0x20C($s2)
    /* A7A90 800B7290 00000000 */  nop
    /* A7A94 800B7294 FFFF6224 */  addiu      $v0, $v1, -0x1
    /* A7A98 800B7298 23A08202 */  subu       $s4, $s4, $v0
    /* A7A9C 800B729C 1280013C */  lui        $at, %hi(D_80120BD4)
    /* A7AA0 800B72A0 21082500 */  addu       $at, $at, $a1
    /* A7AA4 800B72A4 D40B3094 */  lhu        $s0, %lo(D_80120BD4)($at)
    /* A7AA8 800B72A8 80100300 */  sll        $v0, $v1, 2
    /* A7AAC 800B72AC 21104300 */  addu       $v0, $v0, $v1
    /* A7AB0 800B72B0 40100200 */  sll        $v0, $v0, 1
    /* A7AB4 800B72B4 16004018 */  blez       $v0, .L800B7310
    /* A7AB8 800B72B8 21880000 */   addu      $s1, $zero, $zero
    /* A7ABC 800B72BC 7F000524 */  addiu      $a1, $zero, 0x7F
    /* A7AC0 800B72C0 0C024386 */  lh         $v1, 0x20C($s2)
    /* A7AC4 800B72C4 00000000 */  nop
    /* A7AC8 800B72C8 80100300 */  sll        $v0, $v1, 2
    /* A7ACC 800B72CC 21104300 */  addu       $v0, $v0, $v1
    /* A7AD0 800B72D0 40200200 */  sll        $a0, $v0, 1
    /* A7AD4 800B72D4 01000326 */  addiu      $v1, $s0, 0x1
  .L800B72D8:
    /* A7AD8 800B72D8 FF006230 */  andi       $v0, $v1, 0xFF
    /* A7ADC 800B72DC C0FF4224 */  addiu      $v0, $v0, -0x40
    /* A7AE0 800B72E0 BD00422C */  sltiu      $v0, $v0, 0xBD
    /* A7AE4 800B72E4 02004014 */  bnez       $v0, .L800B72F0
    /* A7AE8 800B72E8 21806000 */   addu      $s0, $v1, $zero
    /* A7AEC 800B72EC 43007024 */  addiu      $s0, $v1, 0x43
  .L800B72F0:
    /* A7AF0 800B72F0 FF000232 */  andi       $v0, $s0, 0xFF
    /* A7AF4 800B72F4 02004514 */  bne        $v0, $a1, .L800B7300
    /* A7AF8 800B72F8 00000000 */   nop
    /* A7AFC 800B72FC 01001026 */  addiu      $s0, $s0, 0x1
  .L800B7300:
    /* A7B00 800B7300 01003126 */  addiu      $s1, $s1, 0x1
    /* A7B04 800B7304 2A102402 */  slt        $v0, $s1, $a0
    /* A7B08 800B7308 F3FF4014 */  bnez       $v0, .L800B72D8
    /* A7B0C 800B730C 01000326 */   addiu     $v1, $s0, 0x1
  .L800B7310:
    /* A7B10 800B7310 0C025386 */  lh         $s3, 0x20C($s2)
    /* A7B14 800B7314 00000000 */  nop
    /* A7B18 800B7318 80101300 */  sll        $v0, $s3, 2
    /* A7B1C 800B731C 21105300 */  addu       $v0, $v0, $s3
    /* A7B20 800B7320 40980200 */  sll        $s3, $v0, 1
    /* A7B24 800B7324 21880000 */  addu       $s1, $zero, $zero
    /* A7B28 800B7328 7F001624 */  addiu      $s6, $zero, 0x7F
    /* A7B2C 800B732C 1280153C */  lui        $s5, %hi(D_80120C98)
    /* A7B30 800B7330 980CB526 */  addiu      $s5, $s5, %lo(D_80120C98)
  .L800B7334:
    /* A7B34 800B7334 2A103402 */  slt        $v0, $s1, $s4
    /* A7B38 800B7338 0A00232A */  slti       $v1, $s1, 0xA
    /* A7B3C 800B733C 24104300 */  and        $v0, $v0, $v1
    /* A7B40 800B7340 4E004010 */  beqz       $v0, .L800B747C
    /* A7B44 800B7344 0B00822A */   slti      $v0, $s4, 0xB
    /* A7B48 800B7348 0E024286 */  lh         $v0, 0x20E($s2)
    /* A7B4C 800B734C 00000000 */  nop
    /* A7B50 800B7350 80100200 */  sll        $v0, $v0, 2
    /* A7B54 800B7354 1280013C */  lui        $at, %hi(D_80120BD6)
    /* A7B58 800B7358 21082200 */  addu       $at, $at, $v0
    /* A7B5C 800B735C D60B2284 */  lh         $v0, %lo(D_80120BD6)($at)
    /* A7B60 800B7360 00000000 */  nop
    /* A7B64 800B7364 2A106202 */  slt        $v0, $s3, $v0
    /* A7B68 800B7368 21004010 */  beqz       $v0, .L800B73F0
    /* A7B6C 800B736C 21280000 */   addu      $a1, $zero, $zero
    /* A7B70 800B7370 80101100 */  sll        $v0, $s1, 2
    /* A7B74 800B7374 21105100 */  addu       $v0, $v0, $s1
    /* A7B78 800B7378 80100200 */  sll        $v0, $v0, 2
    /* A7B7C 800B737C 21105100 */  addu       $v0, $v0, $s1
    /* A7B80 800B7380 21205500 */  addu       $a0, $v0, $s5
  .L800B7384:
    /* A7B84 800B7384 FF000232 */  andi       $v0, $s0, 0xFF
    /* A7B88 800B7388 C0FF4224 */  addiu      $v0, $v0, -0x40
    /* A7B8C 800B738C BD00422C */  sltiu      $v0, $v0, 0xBD
    /* A7B90 800B7390 03004014 */  bnez       $v0, .L800B73A0
    /* A7B94 800B7394 FF000232 */   andi      $v0, $s0, 0xFF
    /* A7B98 800B7398 43001026 */  addiu      $s0, $s0, 0x43
    /* A7B9C 800B739C FF000232 */  andi       $v0, $s0, 0xFF
  .L800B73A0:
    /* A7BA0 800B73A0 02005614 */  bne        $v0, $s6, .L800B73AC
    /* A7BA4 800B73A4 21188500 */   addu      $v1, $a0, $a1
    /* A7BA8 800B73A8 01001026 */  addiu      $s0, $s0, 0x1
  .L800B73AC:
    /* A7BAC 800B73AC 02121000 */  srl        $v0, $s0, 8
    /* A7BB0 800B73B0 000062A0 */  sb         $v0, 0x0($v1)
    /* A7BB4 800B73B4 010070A0 */  sb         $s0, 0x1($v1)
    /* A7BB8 800B73B8 01007326 */  addiu      $s3, $s3, 0x1
    /* A7BBC 800B73BC 0200A524 */  addiu      $a1, $a1, 0x2
    /* A7BC0 800B73C0 1400A328 */  slti       $v1, $a1, 0x14
    /* A7BC4 800B73C4 0E024286 */  lh         $v0, 0x20E($s2)
    /* A7BC8 800B73C8 00000000 */  nop
    /* A7BCC 800B73CC 80100200 */  sll        $v0, $v0, 2
    /* A7BD0 800B73D0 1280013C */  lui        $at, %hi(D_80120BD6)
    /* A7BD4 800B73D4 21082200 */  addu       $at, $at, $v0
    /* A7BD8 800B73D8 D60B2284 */  lh         $v0, %lo(D_80120BD6)($at)
    /* A7BDC 800B73DC 00000000 */  nop
    /* A7BE0 800B73E0 2A106202 */  slt        $v0, $s3, $v0
    /* A7BE4 800B73E4 24186200 */  and        $v1, $v1, $v0
    /* A7BE8 800B73E8 E6FF6014 */  bnez       $v1, .L800B7384
    /* A7BEC 800B73EC 01001026 */   addiu     $s0, $s0, 0x1
  .L800B73F0:
    /* A7BF0 800B73F0 1400A228 */  slti       $v0, $a1, 0x14
    /* A7BF4 800B73F4 0E004010 */  beqz       $v0, .L800B7430
    /* A7BF8 800B73F8 80101100 */   sll       $v0, $s1, 2
    /* A7BFC 800B73FC 21105100 */  addu       $v0, $v0, $s1
    /* A7C00 800B7400 80100200 */  sll        $v0, $v0, 2
    /* A7C04 800B7404 21105100 */  addu       $v0, $v0, $s1
    /* A7C08 800B7408 21185500 */  addu       $v1, $v0, $s5
    /* A7C0C 800B740C 81000624 */  addiu      $a2, $zero, 0x81
    /* A7C10 800B7410 40000424 */  addiu      $a0, $zero, 0x40
    /* A7C14 800B7414 21106500 */  addu       $v0, $v1, $a1
  .L800B7418:
    /* A7C18 800B7418 000046A0 */  sb         $a2, 0x0($v0)
    /* A7C1C 800B741C 010044A0 */  sb         $a0, 0x1($v0)
    /* A7C20 800B7420 0200A524 */  addiu      $a1, $a1, 0x2
    /* A7C24 800B7424 1400A228 */  slti       $v0, $a1, 0x14
    /* A7C28 800B7428 FBFF4014 */  bnez       $v0, .L800B7418
    /* A7C2C 800B742C 21106500 */   addu      $v0, $v1, $a1
  .L800B7430:
    /* A7C30 800B7430 80201100 */  sll        $a0, $s1, 2
    /* A7C34 800B7434 21209100 */  addu       $a0, $a0, $s1
    /* A7C38 800B7438 80200400 */  sll        $a0, $a0, 2
    /* A7C3C 800B743C 21209100 */  addu       $a0, $a0, $s1
    /* A7C40 800B7440 21209500 */  addu       $a0, $a0, $s5
    /* A7C44 800B7444 21108500 */  addu       $v0, $a0, $a1
    /* A7C48 800B7448 000040A0 */  sb         $zero, 0x0($v0)
    /* A7C4C 800B744C 2000A527 */  addiu      $a1, $sp, 0x20
    /* A7C50 800B7450 DC0F040C */  jal        func_80103F70
    /* A7C54 800B7454 10000624 */   addiu     $a2, $zero, 0x10
    /* A7C58 800B7458 80181100 */  sll        $v1, $s1, 2
    /* A7C5C 800B745C 21187200 */  addu       $v1, $v1, $s2
    /* A7C60 800B7460 D40162AC */  sw         $v0, 0x1D4($v1)
    /* A7C64 800B7464 2200A297 */  lhu        $v0, 0x22($sp)
    /* A7C68 800B7468 00000000 */  nop
    /* A7C6C 800B746C 0C004224 */  addiu      $v0, $v0, 0xC
    /* A7C70 800B7470 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7C74 800B7474 CDDC0208 */  j          .L800B7334
    /* A7C78 800B7478 01003126 */   addiu     $s1, $s1, 0x1
  .L800B747C:
    /* A7C7C 800B747C 03004010 */  beqz       $v0, .L800B748C
    /* A7C80 800B7480 0A000224 */   addiu     $v0, $zero, 0xA
    /* A7C84 800B7484 24DD0208 */  j          .L800B7490
    /* A7C88 800B7488 100254A6 */   sh        $s4, 0x210($s2)
  .L800B748C:
    /* A7C8C 800B748C 100242A6 */  sh         $v0, 0x210($s2)
  .L800B7490:
    /* A7C90 800B7490 21800000 */  addu       $s0, $zero, $zero
  .L800B7494:
    /* A7C94 800B7494 80101000 */  sll        $v0, $s0, 2
  .L800B7498:
    /* A7C98 800B7498 21105200 */  addu       $v0, $v0, $s2
    /* A7C9C 800B749C D401448C */  lw         $a0, 0x1D4($v0)
    /* A7CA0 800B74A0 00000000 */  nop
    /* A7CA4 800B74A4 03008010 */  beqz       $a0, .L800B74B4
    /* A7CA8 800B74A8 00000000 */   nop
    /* A7CAC 800B74AC 7D11040C */  jal        func_801045F4
    /* A7CB0 800B74B0 00000000 */   nop
  .L800B74B4:
    /* A7CB4 800B74B4 01001026 */  addiu      $s0, $s0, 0x1
    /* A7CB8 800B74B8 0A00022A */  slti       $v0, $s0, 0xA
    /* A7CBC 800B74BC F6FF4014 */  bnez       $v0, .L800B7498
    /* A7CC0 800B74C0 80101000 */   sll       $v0, $s0, 2
    /* A7CC4 800B74C4 2800B027 */  addiu      $s0, $sp, 0x28
    /* A7CC8 800B74C8 A59E030C */  jal        SetPolyF4
    /* A7CCC 800B74CC 21200002 */   addu      $a0, $s0, $zero
    /* A7CD0 800B74D0 21200002 */  addu       $a0, $s0, $zero
    /* A7CD4 800B74D4 999E030C */  jal        SetSemiTrans
    /* A7CD8 800B74D8 01000524 */   addiu     $a1, $zero, 0x1
    /* A7CDC 800B74DC FF000224 */  addiu      $v0, $zero, 0xFF
    /* A7CE0 800B74E0 2C00A2A3 */  sb         $v0, 0x2C($sp)
    /* A7CE4 800B74E4 2D00A0A3 */  sb         $zero, 0x2D($sp)
    /* A7CE8 800B74E8 2E00A0A3 */  sb         $zero, 0x2E($sp)
    /* A7CEC 800B74EC 04024386 */  lh         $v1, 0x204($s2)
    /* A7CF0 800B74F0 06000224 */  addiu      $v0, $zero, 0x6
    /* A7CF4 800B74F4 07006210 */  beq        $v1, $v0, .L800B7514
    /* A7CF8 800B74F8 50001124 */   addiu     $s1, $zero, 0x50
    /* A7CFC 800B74FC 04025186 */  lh         $s1, 0x204($s2)
    /* A7D00 800B7500 00000000 */  nop
    /* A7D04 800B7504 40101100 */  sll        $v0, $s1, 1
    /* A7D08 800B7508 21105100 */  addu       $v0, $v0, $s1
    /* A7D0C 800B750C 80100200 */  sll        $v0, $v0, 2
    /* A7D10 800B7510 38005124 */  addiu      $s1, $v0, 0x38
  .L800B7514:
    /* A7D14 800B7514 E8000224 */  addiu      $v0, $zero, 0xE8
    /* A7D18 800B7518 3000A2A7 */  sh         $v0, 0x30($sp)
    /* A7D1C 800B751C 3200B1A7 */  sh         $s1, 0x32($sp)
    /* A7D20 800B7520 0C010324 */  addiu      $v1, $zero, 0x10C
    /* A7D24 800B7524 3400A3A7 */  sh         $v1, 0x34($sp)
    /* A7D28 800B7528 3600B1A7 */  sh         $s1, 0x36($sp)
    /* A7D2C 800B752C 3800A2A7 */  sh         $v0, 0x38($sp)
    /* A7D30 800B7530 0C002226 */  addiu      $v0, $s1, 0xC
    /* A7D34 800B7534 3A00A2A7 */  sh         $v0, 0x3A($sp)
    /* A7D38 800B7538 3C00A3A7 */  sh         $v1, 0x3C($sp)
    /* A7D3C 800B753C 3E00A2A7 */  sh         $v0, 0x3E($sp)
    /* A7D40 800B7540 2800B027 */  addiu      $s0, $sp, 0x28
    /* A7D44 800B7544 928E030C */  jal        DrawPrim
    /* A7D48 800B7548 21200002 */   addu      $a0, $s0, $zero
    /* A7D4C 800B754C 2C8D030C */  jal        DrawSync
    /* A7D50 800B7550 21200000 */   addu      $a0, $zero, $zero
    /* A7D54 800B7554 06024386 */  lh         $v1, 0x206($s2)
    /* A7D58 800B7558 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* A7D5C 800B755C 18006210 */  beq        $v1, $v0, .L800B75C0
    /* A7D60 800B7560 40100300 */   sll       $v0, $v1, 1
    /* A7D64 800B7564 21104300 */  addu       $v0, $v0, $v1
    /* A7D68 800B7568 80100200 */  sll        $v0, $v0, 2
    /* A7D6C 800B756C 40004424 */  addiu      $a0, $v0, 0x40
    /* A7D70 800B7570 08024586 */  lh         $a1, 0x208($s2)
    /* A7D74 800B7574 00000000 */  nop
    /* A7D78 800B7578 40180500 */  sll        $v1, $a1, 1
    /* A7D7C 800B757C 21186500 */  addu       $v1, $v1, $a1
    /* A7D80 800B7580 80180300 */  sll        $v1, $v1, 2
    /* A7D84 800B7584 28006524 */  addiu      $a1, $v1, 0x28
    /* A7D88 800B7588 3000A4A7 */  sh         $a0, 0x30($sp)
    /* A7D8C 800B758C 3200A5A7 */  sh         $a1, 0x32($sp)
    /* A7D90 800B7590 4C004224 */  addiu      $v0, $v0, 0x4C
    /* A7D94 800B7594 3400A2A7 */  sh         $v0, 0x34($sp)
    /* A7D98 800B7598 3600A5A7 */  sh         $a1, 0x36($sp)
    /* A7D9C 800B759C 3800A4A7 */  sh         $a0, 0x38($sp)
    /* A7DA0 800B75A0 34006324 */  addiu      $v1, $v1, 0x34
    /* A7DA4 800B75A4 3A00A3A7 */  sh         $v1, 0x3A($sp)
    /* A7DA8 800B75A8 3C00A2A7 */  sh         $v0, 0x3C($sp)
    /* A7DAC 800B75AC 3E00A3A7 */  sh         $v1, 0x3E($sp)
    /* A7DB0 800B75B0 928E030C */  jal        DrawPrim
    /* A7DB4 800B75B4 21200002 */   addu      $a0, $s0, $zero
    /* A7DB8 800B75B8 2C8D030C */  jal        DrawSync
    /* A7DBC 800B75BC 21200000 */   addu      $a0, $zero, $zero
  .L800B75C0:
    /* A7DC0 800B75C0 0000428E */  lw         $v0, 0x0($s2)
    /* A7DC4 800B75C4 00000000 */  nop
    /* A7DC8 800B75C8 3800428C */  lw         $v0, 0x38($v0)
    /* A7DCC 800B75CC 00000000 */  nop
    /* A7DD0 800B75D0 0400448C */  lw         $a0, 0x4($v0)
    /* A7DD4 800B75D4 D707040C */  jal        func_80101F5C
    /* A7DD8 800B75D8 00000000 */   nop
    /* A7DDC 800B75DC EC00438E */  lw         $v1, 0xEC($s2)
    /* A7DE0 800B75E0 F400428E */  lw         $v0, 0xF4($s2)
    /* A7DE4 800B75E4 00000000 */  nop
    /* A7DE8 800B75E8 21186200 */  addu       $v1, $v1, $v0
    /* A7DEC 800B75EC 0A024486 */  lh         $a0, 0x20A($s2)
    /* A7DF0 800B75F0 00000000 */  nop
    /* A7DF4 800B75F4 40100400 */  sll        $v0, $a0, 1
    /* A7DF8 800B75F8 21104400 */  addu       $v0, $v0, $a0
    /* A7DFC 800B75FC 40100200 */  sll        $v0, $v0, 1
    /* A7E00 800B7600 21186200 */  addu       $v1, $v1, $v0
    /* A7E04 800B7604 F000428E */  lw         $v0, 0xF0($s2)
    /* A7E08 800B7608 3000A3A7 */  sh         $v1, 0x30($sp)
    /* A7E0C 800B760C 3200A2A7 */  sh         $v0, 0x32($sp)
    /* A7E10 800B7610 0C006424 */  addiu      $a0, $v1, 0xC
    /* A7E14 800B7614 3400A4A7 */  sh         $a0, 0x34($sp)
    /* A7E18 800B7618 3600A2A7 */  sh         $v0, 0x36($sp)
    /* A7E1C 800B761C 3800A3A7 */  sh         $v1, 0x38($sp)
    /* A7E20 800B7620 0C004224 */  addiu      $v0, $v0, 0xC
    /* A7E24 800B7624 3A00A2A7 */  sh         $v0, 0x3A($sp)
    /* A7E28 800B7628 3C00A4A7 */  sh         $a0, 0x3C($sp)
    /* A7E2C 800B762C 3E00A2A7 */  sh         $v0, 0x3E($sp)
    /* A7E30 800B7630 928E030C */  jal        DrawPrim
    /* A7E34 800B7634 2800A427 */   addiu     $a0, $sp, 0x28
    /* A7E38 800B7638 2C8D030C */  jal        DrawSync
    /* A7E3C 800B763C 21200000 */   addu      $a0, $zero, $zero
  .L800B7640:
    /* A7E40 800B7640 0000428E */  lw         $v0, 0x0($s2)
    /* A7E44 800B7644 00000000 */  nop
    /* A7E48 800B7648 3800428C */  lw         $v0, 0x38($v0)
    /* A7E4C 800B764C 00000000 */  nop
    /* A7E50 800B7650 0400448C */  lw         $a0, 0x4($v0)
    /* A7E54 800B7654 D707040C */  jal        func_80101F5C
    /* A7E58 800B7658 00000000 */   nop
    /* A7E5C 800B765C CC004296 */  lhu        $v0, 0xCC($s2)
    /* A7E60 800B7660 00000000 */  nop
    /* A7E64 800B7664 F8FF4224 */  addiu      $v0, $v0, -0x8
    /* A7E68 800B7668 2000A2A7 */  sh         $v0, 0x20($sp)
    /* A7E6C 800B766C D0004296 */  lhu        $v0, 0xD0($s2)
    /* A7E70 800B7670 00000000 */  nop
    /* A7E74 800B7674 F0FF4224 */  addiu      $v0, $v0, -0x10
    /* A7E78 800B7678 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7E7C 800B767C CC004296 */  lhu        $v0, 0xCC($s2)
    /* A7E80 800B7680 34004396 */  lhu        $v1, 0x34($s2)
    /* A7E84 800B7684 00000000 */  nop
    /* A7E88 800B7688 21104300 */  addu       $v0, $v0, $v1
    /* A7E8C 800B768C 08004224 */  addiu      $v0, $v0, 0x8
    /* A7E90 800B7690 2400A2A7 */  sh         $v0, 0x24($sp)
    /* A7E94 800B7694 D0004296 */  lhu        $v0, 0xD0($s2)
    /* A7E98 800B7698 38004396 */  lhu        $v1, 0x38($s2)
    /* A7E9C 800B769C 00000000 */  nop
    /* A7EA0 800B76A0 21104300 */  addu       $v0, $v0, $v1
    /* A7EA4 800B76A4 10004224 */  addiu      $v0, $v0, 0x10
    /* A7EA8 800B76A8 2600A2A7 */  sh         $v0, 0x26($sp)
    /* A7EAC 800B76AC 2000A427 */  addiu      $a0, $sp, 0x20
    /* A7EB0 800B76B0 A314020C */  jal        func_8008528C
    /* A7EB4 800B76B4 21280000 */   addu      $a1, $zero, $zero
    /* A7EB8 800B76B8 1801448E */  lw         $a0, 0x118($s2)
    /* A7EBC 800B76BC 00000000 */  nop
    /* A7EC0 800B76C0 23008010 */  beqz       $a0, .L800B7750
    /* A7EC4 800B76C4 00000000 */   nop
    /* A7EC8 800B76C8 0002428E */  lw         $v0, 0x200($s2)
    /* A7ECC 800B76CC 00000000 */  nop
    /* A7ED0 800B76D0 1C004014 */  bnez       $v0, .L800B7744
    /* A7ED4 800B76D4 00000000 */   nop
    /* A7ED8 800B76D8 3400508E */  lw         $s0, 0x34($s2)
    /* A7EDC 800B76DC 00000000 */  nop
    /* A7EE0 800B76E0 C2171000 */  srl        $v0, $s0, 31
    /* A7EE4 800B76E4 21800202 */  addu       $s0, $s0, $v0
    /* A7EE8 800B76E8 AD87030C */  jal        func_800E1EB4
    /* A7EEC 800B76EC 43801000 */   sra       $s0, $s0, 1
    /* A7EF0 800B76F0 40180200 */  sll        $v1, $v0, 1
    /* A7EF4 800B76F4 21186200 */  addu       $v1, $v1, $v0
    /* A7EF8 800B76F8 23800302 */  subu       $s0, $s0, $v1
    /* A7EFC 800B76FC CC004296 */  lhu        $v0, 0xCC($s2)
    /* A7F00 800B7700 00000000 */  nop
    /* A7F04 800B7704 21800202 */  addu       $s0, $s0, $v0
    /* A7F08 800B7708 4000B0A7 */  sh         $s0, 0x40($sp)
    /* A7F0C 800B770C D0004296 */  lhu        $v0, 0xD0($s2)
    /* A7F10 800B7710 00000000 */  nop
    /* A7F14 800B7714 F2FF4224 */  addiu      $v0, $v0, -0xE
    /* A7F18 800B7718 4200A2A7 */  sh         $v0, 0x42($sp)
    /* A7F1C 800B771C 40010224 */  addiu      $v0, $zero, 0x140
    /* A7F20 800B7720 4400A2A7 */  sh         $v0, 0x44($sp)
    /* A7F24 800B7724 D0004296 */  lhu        $v0, 0xD0($s2)
    /* A7F28 800B7728 00000000 */  nop
    /* A7F2C 800B772C 4600A2A7 */  sh         $v0, 0x46($sp)
    /* A7F30 800B7730 1801448E */  lw         $a0, 0x118($s2)
    /* A7F34 800B7734 4000A527 */  addiu      $a1, $sp, 0x40
    /* A7F38 800B7738 DC0F040C */  jal        func_80103F70
    /* A7F3C 800B773C 10000624 */   addiu     $a2, $zero, 0x10
    /* A7F40 800B7740 000242AE */  sw         $v0, 0x200($s2)
  .L800B7744:
    /* A7F44 800B7744 0002448E */  lw         $a0, 0x200($s2)
    /* A7F48 800B7748 7D11040C */  jal        func_801045F4
    /* A7F4C 800B774C 00000000 */   nop
  .L800B7750:
    /* A7F50 800B7750 8001428E */  lw         $v0, 0x180($s2)
    /* A7F54 800B7754 00000000 */  nop
    /* A7F58 800B7758 24004010 */  beqz       $v0, .L800B77EC
    /* A7F5C 800B775C 00000000 */   nop
    /* A7F60 800B7760 1280043C */  lui        $a0, %hi(D_80120D6C)
    /* A7F64 800B7764 6C0D8424 */  addiu      $a0, $a0, %lo(D_80120D6C)
    /* A7F68 800B7768 00008290 */  lbu        $v0, 0x0($a0)
    /* A7F6C 800B776C 00000000 */  nop
    /* A7F70 800B7770 1E004010 */  beqz       $v0, .L800B77EC
    /* A7F74 800B7774 00000000 */   nop
    /* A7F78 800B7778 FC01428E */  lw         $v0, 0x1FC($s2)
    /* A7F7C 800B777C 00000000 */  nop
    /* A7F80 800B7780 17004014 */  bnez       $v0, .L800B77E0
    /* A7F84 800B7784 2000A527 */   addiu     $a1, $sp, 0x20
    /* A7F88 800B7788 EC004296 */  lhu        $v0, 0xEC($s2)
    /* A7F8C 800B778C F4004396 */  lhu        $v1, 0xF4($s2)
    /* A7F90 800B7790 00000000 */  nop
    /* A7F94 800B7794 21104300 */  addu       $v0, $v0, $v1
    /* A7F98 800B7798 2000A2A7 */  sh         $v0, 0x20($sp)
    /* A7F9C 800B779C F0004296 */  lhu        $v0, 0xF0($s2)
    /* A7FA0 800B77A0 00000000 */  nop
    /* A7FA4 800B77A4 04004224 */  addiu      $v0, $v0, 0x4
    /* A7FA8 800B77A8 2200A2A7 */  sh         $v0, 0x22($sp)
    /* A7FAC 800B77AC EC004296 */  lhu        $v0, 0xEC($s2)
    /* A7FB0 800B77B0 F4004396 */  lhu        $v1, 0xF4($s2)
    /* A7FB4 800B77B4 00000000 */  nop
    /* A7FB8 800B77B8 21104300 */  addu       $v0, $v0, $v1
    /* A7FBC 800B77BC 40014224 */  addiu      $v0, $v0, 0x140
    /* A7FC0 800B77C0 2400A2A7 */  sh         $v0, 0x24($sp)
    /* A7FC4 800B77C4 F0004296 */  lhu        $v0, 0xF0($s2)
    /* A7FC8 800B77C8 00000000 */  nop
    /* A7FCC 800B77CC 0C004224 */  addiu      $v0, $v0, 0xC
    /* A7FD0 800B77D0 2600A2A7 */  sh         $v0, 0x26($sp)
    /* A7FD4 800B77D4 DC0F040C */  jal        func_80103F70
    /* A7FD8 800B77D8 10000624 */   addiu     $a2, $zero, 0x10
    /* A7FDC 800B77DC FC0142AE */  sw         $v0, 0x1FC($s2)
  .L800B77E0:
    /* A7FE0 800B77E0 FC01448E */  lw         $a0, 0x1FC($s2)
    /* A7FE4 800B77E4 7D11040C */  jal        func_801045F4
    /* A7FE8 800B77E8 00000000 */   nop
  .L800B77EC:
    /* A7FEC 800B77EC CC01428E */  lw         $v0, 0x1CC($s2)
    /* A7FF0 800B77F0 00000000 */  nop
    /* A7FF4 800B77F4 24004010 */  beqz       $v0, .L800B7888
    /* A7FF8 800B77F8 4000A627 */   addiu     $a2, $sp, 0x40
    /* A7FFC 800B77FC 4000A0A7 */  sh         $zero, 0x40($sp)
    /* A8000 800B7800 CC01428E */  lw         $v0, 0x1CC($s2)
    /* A8004 800B7804 00000000 */  nop
    /* A8008 800B7808 08004294 */  lhu        $v0, 0x8($v0)
    /* A800C 800B780C 00000000 */  nop
    /* A8010 800B7810 4200A2A7 */  sh         $v0, 0x42($sp)
    /* A8014 800B7814 00010224 */  addiu      $v0, $zero, 0x100
    /* A8018 800B7818 4400A2A7 */  sh         $v0, 0x44($sp)
    /* A801C 800B781C CC01428E */  lw         $v0, 0x1CC($s2)
    /* A8020 800B7820 00000000 */  nop
    /* A8024 800B7824 08004294 */  lhu        $v0, 0x8($v0)
    /* A8028 800B7828 00000000 */  nop
    /* A802C 800B782C 10004224 */  addiu      $v0, $v0, 0x10
    /* A8030 800B7830 4600A2A7 */  sh         $v0, 0x46($sp)
    /* A8034 800B7834 CC004296 */  lhu        $v0, 0xCC($s2)
    /* A8038 800B7838 00000000 */  nop
    /* A803C 800B783C F8FF4224 */  addiu      $v0, $v0, -0x8
    /* A8040 800B7840 4800A2A7 */  sh         $v0, 0x48($sp)
    /* A8044 800B7844 D0004296 */  lhu        $v0, 0xD0($s2)
    /* A8048 800B7848 00000000 */  nop
    /* A804C 800B784C F0FF4224 */  addiu      $v0, $v0, -0x10
    /* A8050 800B7850 4A00A2A7 */  sh         $v0, 0x4A($sp)
    /* A8054 800B7854 CC004296 */  lhu        $v0, 0xCC($s2)
    /* A8058 800B7858 00000000 */  nop
    /* A805C 800B785C F8004224 */  addiu      $v0, $v0, 0xF8
    /* A8060 800B7860 4C00A2A7 */  sh         $v0, 0x4C($sp)
    /* A8064 800B7864 D0004296 */  lhu        $v0, 0xD0($s2)
    /* A8068 800B7868 00000000 */  nop
    /* A806C 800B786C 4E00A2A7 */  sh         $v0, 0x4E($sp)
    /* A8070 800B7870 CC01428E */  lw         $v0, 0x1CC($s2)
    /* A8074 800B7874 0000458E */  lw         $a1, 0x0($s2)
    /* A8078 800B7878 0000448C */  lw         $a0, 0x0($v0)
    /* A807C 800B787C 2C00A524 */  addiu      $a1, $a1, 0x2C
    /* A8080 800B7880 1FE4030C */  jal        func_800F907C
    /* A8084 800B7884 4800A727 */   addiu     $a3, $sp, 0x48
  .L800B7888:
    /* A8088 800B7888 16024286 */  lh         $v0, 0x216($s2)
    /* A808C 800B788C 00000000 */  nop
    /* A8090 800B7890 40004004 */  bltz       $v0, .L800B7994
    /* A8094 800B7894 4000B027 */   addiu     $s0, $sp, 0x40
    /* A8098 800B7898 BD9E030C */  jal        SetTile
    /* A809C 800B789C 21200002 */   addu      $a0, $s0, $zero
    /* A80A0 800B78A0 08000324 */  addiu      $v1, $zero, 0x8
    /* A80A4 800B78A4 4800A3A7 */  sh         $v1, 0x48($sp)
    /* A80A8 800B78A8 18024296 */  lhu        $v0, 0x218($s2)
    /* A80AC 800B78AC 00000000 */  nop
    /* A80B0 800B78B0 4A00A2A7 */  sh         $v0, 0x4A($sp)
    /* A80B4 800B78B4 34004296 */  lhu        $v0, 0x34($s2)
    /* A80B8 800B78B8 00000000 */  nop
    /* A80BC 800B78BC F0FF4224 */  addiu      $v0, $v0, -0x10
    /* A80C0 800B78C0 4C00A2A7 */  sh         $v0, 0x4C($sp)
    /* A80C4 800B78C4 4E00A3A7 */  sh         $v1, 0x4E($sp)
    /* A80C8 800B78C8 16024386 */  lh         $v1, 0x216($s2)
    /* A80CC 800B78CC 64000224 */  addiu      $v0, $zero, 0x64
    /* A80D0 800B78D0 07006214 */  bne        $v1, $v0, .L800B78F0
    /* A80D4 800B78D4 4000B127 */   addiu     $s1, $sp, 0x40
    /* A80D8 800B78D8 4400A0A3 */  sb         $zero, 0x44($sp)
    /* A80DC 800B78DC F0000224 */  addiu      $v0, $zero, 0xF0
    /* A80E0 800B78E0 4500A2A3 */  sb         $v0, 0x45($sp)
    /* A80E4 800B78E4 4600A0A3 */  sb         $zero, 0x46($sp)
    /* A80E8 800B78E8 58DE0208 */  j          .L800B7960
    /* A80EC 800B78EC 21200002 */   addu      $a0, $s0, $zero
  .L800B78F0:
    /* A80F0 800B78F0 4400A0A3 */  sb         $zero, 0x44($sp)
    /* A80F4 800B78F4 4500A0A3 */  sb         $zero, 0x45($sp)
    /* A80F8 800B78F8 4600A0A3 */  sb         $zero, 0x46($sp)
    /* A80FC 800B78FC 928E030C */  jal        DrawPrim
    /* A8100 800B7900 21202002 */   addu      $a0, $s1, $zero
    /* A8104 800B7904 16024386 */  lh         $v1, 0x216($s2)
    /* A8108 800B7908 3400428E */  lw         $v0, 0x34($s2)
    /* A810C 800B790C 00000000 */  nop
    /* A8110 800B7910 F0FF4224 */  addiu      $v0, $v0, -0x10
    /* A8114 800B7914 18006200 */  mult       $v1, $v0
    /* A8118 800B7918 12180000 */  mflo       $v1
    /* A811C 800B791C EB51023C */  lui        $v0, (0x51EB851F >> 16)
    /* A8120 800B7920 1F854234 */  ori        $v0, $v0, (0x51EB851F & 0xFFFF)
    /* A8124 800B7924 18006200 */  mult       $v1, $v0
    /* A8128 800B7928 10400000 */  mfhi       $t0
    /* A812C 800B792C 43810800 */  sra        $s0, $t0, 5
    /* A8130 800B7930 C31F0300 */  sra        $v1, $v1, 31
    /* A8134 800B7934 23800302 */  subu       $s0, $s0, $v1
    /* A8138 800B7938 2C8D030C */  jal        DrawSync
    /* A813C 800B793C 21200000 */   addu      $a0, $zero, $zero
    /* A8140 800B7940 4C00B0A7 */  sh         $s0, 0x4C($sp)
    /* A8144 800B7944 08000224 */  addiu      $v0, $zero, 0x8
    /* A8148 800B7948 4E00A2A7 */  sh         $v0, 0x4E($sp)
    /* A814C 800B794C 4400A0A3 */  sb         $zero, 0x44($sp)
    /* A8150 800B7950 FF000224 */  addiu      $v0, $zero, 0xFF
    /* A8154 800B7954 4500A2A3 */  sb         $v0, 0x45($sp)
    /* A8158 800B7958 4600A0A3 */  sb         $zero, 0x46($sp)
    /* A815C 800B795C 21202002 */  addu       $a0, $s1, $zero
  .L800B7960:
    /* A8160 800B7960 928E030C */  jal        DrawPrim
    /* A8164 800B7964 00000000 */   nop
    /* A8168 800B7968 2C8D030C */  jal        DrawSync
    /* A816C 800B796C 21200000 */   addu      $a0, $zero, $zero
    /* A8170 800B7970 65DE0208 */  j          .L800B7994
    /* A8174 800B7974 00000000 */   nop
  .L800B7978:
    /* A8178 800B7978 0000428E */  lw         $v0, 0x0($s2)
    /* A817C 800B797C 00000000 */  nop
    /* A8180 800B7980 3800428C */  lw         $v0, 0x38($v0)
    /* A8184 800B7984 00000000 */  nop
    /* A8188 800B7988 0400448C */  lw         $a0, 0x4($v0)
    /* A818C 800B798C D707040C */  jal        func_80101F5C
    /* A8190 800B7990 00000000 */   nop
  .L800B7994:
    /* A8194 800B7994 2000428E */  lw         $v0, 0x20($s2)
    /* A8198 800B7998 00000000 */  nop
    /* A819C 800B799C 94004010 */  beqz       $v0, .L800B7BF0
    /* A81A0 800B79A0 21204002 */   addu      $a0, $s2, $zero
    /* A81A4 800B79A4 1401448E */  lw         $a0, 0x114($s2)
    /* A81A8 800B79A8 00000000 */  nop
    /* A81AC 800B79AC 08008424 */  addiu      $a0, $a0, 0x8
    /* A81B0 800B79B0 00240400 */  sll        $a0, $a0, 16
    /* A81B4 800B79B4 03240400 */  sra        $a0, $a0, 16
    /* A81B8 800B79B8 D0EC030C */  jal        func_800FB340
    /* A81BC 800B79BC 08000524 */   addiu     $a1, $zero, 0x8
    /* A81C0 800B79C0 04024386 */  lh         $v1, 0x204($s2)
    /* A81C4 800B79C4 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* A81C8 800B79C8 0D006214 */  bne        $v1, $v0, .L800B7A00
    /* A81CC 800B79CC 00000000 */   nop
    /* A81D0 800B79D0 3400428E */  lw         $v0, 0x34($s2)
    /* A81D4 800B79D4 00000000 */  nop
    /* A81D8 800B79D8 C21F0200 */  srl        $v1, $v0, 31
    /* A81DC 800B79DC 21104300 */  addu       $v0, $v0, $v1
    /* A81E0 800B79E0 43980200 */  sra        $s3, $v0, 1
    /* A81E4 800B79E4 0401428E */  lw         $v0, 0x104($s2)
    /* A81E8 800B79E8 00000000 */  nop
    /* A81EC 800B79EC C21F0200 */  srl        $v1, $v0, 31
    /* A81F0 800B79F0 21104300 */  addu       $v0, $v0, $v1
    /* A81F4 800B79F4 43100200 */  sra        $v0, $v0, 1
    /* A81F8 800B79F8 81DE0208 */  j          .L800B7A04
    /* A81FC 800B79FC 23986202 */   subu      $s3, $s3, $v0
  .L800B7A00:
    /* A8200 800B7A00 E400538E */  lw         $s3, 0xE4($s2)
  .L800B7A04:
    /* A8204 800B7A04 E800518E */  lw         $s1, 0xE8($s2)
    /* A8208 800B7A08 7C01508E */  lw         $s0, 0x17C($s2)
    /* A820C 800B7A0C FFFF7626 */  addiu      $s6, $s3, -0x1
    /* A8210 800B7A10 00BC1600 */  sll        $s7, $s6, 16
  .L800B7A14:
    /* A8214 800B7A14 73000012 */  beqz       $s0, .L800B7BE4
    /* A8218 800B7A18 01000424 */   addiu     $a0, $zero, 0x1
    /* A821C 800B7A1C 0C00048E */  lw         $a0, 0xC($s0)
    /* A8220 800B7A20 00000000 */  nop
    /* A8224 800B7A24 30008284 */  lh         $v0, 0x30($a0)
    /* A8228 800B7A28 2C008384 */  lh         $v1, 0x2C($a0)
    /* A822C 800B7A2C 00000000 */  nop
    /* A8230 800B7A30 23104300 */  subu       $v0, $v0, $v1
    /* A8234 800B7A34 00140200 */  sll        $v0, $v0, 16
    /* A8238 800B7A38 03A40200 */  sra        $s4, $v0, 16
    /* A823C 800B7A3C 32008284 */  lh         $v0, 0x32($a0)
    /* A8240 800B7A40 2E008384 */  lh         $v1, 0x2E($a0)
    /* A8244 800B7A44 00000000 */  nop
    /* A8248 800B7A48 23104300 */  subu       $v0, $v0, $v1
    /* A824C 800B7A4C 00140200 */  sll        $v0, $v0, 16
    /* A8250 800B7A50 03AC0200 */  sra        $s5, $v0, 16
    /* A8254 800B7A54 8C01428E */  lw         $v0, 0x18C($s2)
    /* A8258 800B7A58 00000000 */  nop
    /* A825C 800B7A5C 0C004010 */  beqz       $v0, .L800B7A90
    /* A8260 800B7A60 00000000 */   nop
    /* A8264 800B7A64 1000B3AF */  sw         $s3, 0x10($sp)
    /* A8268 800B7A68 1400B1AF */  sw         $s1, 0x14($sp)
    /* A826C 800B7A6C 8C01428E */  lw         $v0, 0x18C($s2)
    /* A8270 800B7A70 0C00048E */  lw         $a0, 0xC($s0)
    /* A8274 800B7A74 0000458E */  lw         $a1, 0x0($s2)
    /* A8278 800B7A78 0000068E */  lw         $a2, 0x0($s0)
    /* A827C 800B7A7C 0400078E */  lw         $a3, 0x4($s0)
    /* A8280 800B7A80 09F84000 */  jalr       $v0
    /* A8284 800B7A84 00000000 */   nop
    /* A8288 800B7A88 CADE0208 */  j          .L800B7B28
    /* A828C 800B7A8C 00000000 */   nop
  .L800B7A90:
    /* A8290 800B7A90 3800428E */  lw         $v0, 0x38($s2)
    /* A8294 800B7A94 00000000 */  nop
    /* A8298 800B7A98 FCFF4224 */  addiu      $v0, $v0, -0x4
    /* A829C 800B7A9C 2A105500 */  slt        $v0, $v0, $s5
    /* A82A0 800B7AA0 18004010 */  beqz       $v0, .L800B7B04
    /* A82A4 800B7AA4 4000A627 */   addiu     $a2, $sp, 0x40
    /* A82A8 800B7AA8 4000A0A7 */  sh         $zero, 0x40($sp)
    /* A82AC 800B7AAC 4200A0A7 */  sh         $zero, 0x42($sp)
    /* A82B0 800B7AB0 4400B4A7 */  sh         $s4, 0x44($sp)
    /* A82B4 800B7AB4 38004296 */  lhu        $v0, 0x38($s2)
    /* A82B8 800B7AB8 00000000 */  nop
    /* A82BC 800B7ABC FCFF4224 */  addiu      $v0, $v0, -0x4
    /* A82C0 800B7AC0 4600A2A7 */  sh         $v0, 0x46($sp)
    /* A82C4 800B7AC4 4800B3A7 */  sh         $s3, 0x48($sp)
    /* A82C8 800B7AC8 4A00B1A7 */  sh         $s1, 0x4A($sp)
    /* A82CC 800B7ACC 21107402 */  addu       $v0, $s3, $s4
    /* A82D0 800B7AD0 4C00A2A7 */  sh         $v0, 0x4C($sp)
    /* A82D4 800B7AD4 38004296 */  lhu        $v0, 0x38($s2)
    /* A82D8 800B7AD8 00000000 */  nop
    /* A82DC 800B7ADC 21102202 */  addu       $v0, $s1, $v0
    /* A82E0 800B7AE0 FCFF4224 */  addiu      $v0, $v0, -0x4
    /* A82E4 800B7AE4 4E00A2A7 */  sh         $v0, 0x4E($sp)
    /* A82E8 800B7AE8 0000458E */  lw         $a1, 0x0($s2)
    /* A82EC 800B7AEC 0C00048E */  lw         $a0, 0xC($s0)
    /* A82F0 800B7AF0 2C00A524 */  addiu      $a1, $a1, 0x2C
    /* A82F4 800B7AF4 1FE4030C */  jal        func_800F907C
    /* A82F8 800B7AF8 4800A727 */   addiu     $a3, $sp, 0x48
    /* A82FC 800B7AFC CADE0208 */  j          .L800B7B28
    /* A8300 800B7B00 00000000 */   nop
  .L800B7B04:
    /* A8304 800B7B04 003C1300 */  sll        $a3, $s3, 16
    /* A8308 800B7B08 00141100 */  sll        $v0, $s1, 16
    /* A830C 800B7B0C 03140200 */  sra        $v0, $v0, 16
    /* A8310 800B7B10 1000A2AF */  sw         $v0, 0x10($sp)
    /* A8314 800B7B14 5000A427 */  addiu      $a0, $sp, 0x50
    /* A8318 800B7B18 0C00058E */  lw         $a1, 0xC($s0)
    /* A831C 800B7B1C 0000468E */  lw         $a2, 0x0($s2)
    /* A8320 800B7B20 89EE030C */  jal        func_800FBA24
    /* A8324 800B7B24 033C0700 */   sra       $a3, $a3, 16
  .L800B7B28:
    /* A8328 800B7B28 3000428E */  lw         $v0, 0x30($s2)
    /* A832C 800B7B2C 0200033C */  lui        $v1, (0x20000 >> 16)
    /* A8330 800B7B30 24104300 */  and        $v0, $v0, $v1
    /* A8334 800B7B34 19004010 */  beqz       $v0, .L800B7B9C
    /* A8338 800B7B38 00000000 */   nop
    /* A833C 800B7B3C 6C01428E */  lw         $v0, 0x16C($s2)
    /* A8340 800B7B40 00000000 */  nop
    /* A8344 800B7B44 15000216 */  bne        $s0, $v0, .L800B7B9C
    /* A8348 800B7B48 FFFF2626 */   addiu     $a2, $s1, -0x1
    /* A834C 800B7B4C 21387402 */  addu       $a3, $s3, $s4
    /* A8350 800B7B50 21103502 */  addu       $v0, $s1, $s5
    /* A8354 800B7B54 1800B6A7 */  sh         $s6, 0x18($sp)
    /* A8358 800B7B58 1A00A6A7 */  sh         $a2, 0x1A($sp)
    /* A835C 800B7B5C 1C00A7A7 */  sh         $a3, 0x1C($sp)
    /* A8360 800B7B60 1E00A2A7 */  sh         $v0, 0x1E($sp)
    /* A8364 800B7B64 0000448E */  lw         $a0, 0x0($s2)
    /* A8368 800B7B68 5400438E */  lw         $v1, 0x54($s2)
    /* A836C 800B7B6C 00340600 */  sll        $a2, $a2, 16
    /* A8370 800B7B70 003C0700 */  sll        $a3, $a3, 16
    /* A8374 800B7B74 033C0700 */  sra        $a3, $a3, 16
    /* A8378 800B7B78 00140200 */  sll        $v0, $v0, 16
    /* A837C 800B7B7C 03140200 */  sra        $v0, $v0, 16
    /* A8380 800B7B80 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* A8384 800B7B84 1000A2AF */  sw         $v0, 0x10($sp)
    /* A8388 800B7B88 1400A3AF */  sw         $v1, 0x14($sp)
    /* A838C 800B7B8C 032C1700 */  sra        $a1, $s7, 16
    /* A8390 800B7B90 03340600 */  sra        $a2, $a2, 16
    /* A8394 800B7B94 C413020C */  jal        func_80084F10
    /* A8398 800B7B98 FFFFE724 */   addiu     $a3, $a3, -0x1
  .L800B7B9C:
    /* A839C 800B7B9C 0800028E */  lw         $v0, 0x8($s0)
    /* A83A0 800B7BA0 00000000 */  nop
    /* A83A4 800B7BA4 0A004010 */  beqz       $v0, .L800B7BD0
    /* A83A8 800B7BA8 21307402 */   addu      $a2, $s3, $s4
    /* A83AC 800B7BAC A800428E */  lw         $v0, 0xA8($s2)
    /* A83B0 800B7BB0 F4FFA726 */  addiu      $a3, $s5, -0xC
    /* A83B4 800B7BB4 43380700 */  sra        $a3, $a3, 1
    /* A83B8 800B7BB8 1000A0AF */  sw         $zero, 0x10($sp)
    /* A83BC 800B7BBC 21204002 */  addu       $a0, $s2, $zero
    /* A83C0 800B7BC0 0800058E */  lw         $a1, 0x8($s0)
    /* A83C4 800B7BC4 2130C200 */  addu       $a2, $a2, $v0
    /* A83C8 800B7BC8 C4CA020C */  jal        func_800B2B10
    /* A83CC 800B7BCC 21382702 */   addu      $a3, $s1, $a3
  .L800B7BD0:
    /* A83D0 800B7BD0 21883502 */  addu       $s1, $s1, $s5
    /* A83D4 800B7BD4 A400428E */  lw         $v0, 0xA4($s2)
    /* A83D8 800B7BD8 1000108E */  lw         $s0, 0x10($s0)
    /* A83DC 800B7BDC 85DE0208 */  j          .L800B7A14
    /* A83E0 800B7BE0 21882202 */   addu      $s1, $s1, $v0
  .L800B7BE4:
    /* A83E4 800B7BE4 D0EC030C */  jal        func_800FB340
    /* A83E8 800B7BE8 01000524 */   addiu     $a1, $zero, 0x1
    /* A83EC 800B7BEC 21204002 */  addu       $a0, $s2, $zero
  .L800B7BF0:
    /* A83F0 800B7BF0 30CB020C */  jal        func_800B2CC0
    /* A83F4 800B7BF4 01000524 */   addiu     $a1, $zero, 0x1
    /* A83F8 800B7BF8 1800428E */  lw         $v0, 0x18($s2)
    /* A83FC 800B7BFC 00000000 */  nop
    /* A8400 800B7C00 20004010 */  beqz       $v0, .L800B7C84
    /* A8404 800B7C04 00000000 */   nop
    /* A8408 800B7C08 8001518E */  lw         $s1, 0x180($s2)
    /* A840C 800B7C0C 00000000 */  nop
    /* A8410 800B7C10 1C002012 */  beqz       $s1, .L800B7C84
    /* A8414 800B7C14 21980000 */   addu      $s3, $zero, $zero
  .L800B7C18:
    /* A8418 800B7C18 48004492 */  lbu        $a0, 0x48($s2)
    /* A841C 800B7C1C 54E9030C */  jal        func_800FA550
    /* A8420 800B7C20 00000000 */   nop
    /* A8424 800B7C24 D1C7020C */  jal        func_800B1F44
    /* A8428 800B7C28 21204002 */   addu      $a0, $s2, $zero
    /* A842C 800B7C2C 21804000 */  addu       $s0, $v0, $zero
    /* A8430 800B7C30 D1C7020C */  jal        func_800B1F44
    /* A8434 800B7C34 21204002 */   addu      $a0, $s2, $zero
    /* A8438 800B7C38 18001302 */  mult       $s0, $s3
    /* A843C 800B7C3C F0004796 */  lhu        $a3, 0xF0($s2)
    /* A8440 800B7C40 12400000 */  mflo       $t0
    /* A8444 800B7C44 2138E800 */  addu       $a3, $a3, $t0
    /* A8448 800B7C48 43100200 */  sra        $v0, $v0, 1
    /* A844C 800B7C4C 2138E200 */  addu       $a3, $a3, $v0
    /* A8450 800B7C50 FAFFE724 */  addiu      $a3, $a3, -0x6
    /* A8454 800B7C54 003C0700 */  sll        $a3, $a3, 16
    /* A8458 800B7C58 EC004686 */  lh         $a2, 0xEC($s2)
    /* A845C 800B7C5C 05000224 */  addiu      $v0, $zero, 0x5
    /* A8460 800B7C60 1000A2AF */  sw         $v0, 0x10($sp)
    /* A8464 800B7C64 0000448E */  lw         $a0, 0x0($s2)
    /* A8468 800B7C68 1000258E */  lw         $a1, 0x10($s1)
    /* A846C 800B7C6C 59E7030C */  jal        func_800F9D64
    /* A8470 800B7C70 033C0700 */   sra       $a3, $a3, 16
    /* A8474 800B7C74 1800318E */  lw         $s1, 0x18($s1)
    /* A8478 800B7C78 00000000 */  nop
    /* A847C 800B7C7C E6FF2016 */  bnez       $s1, .L800B7C18
    /* A8480 800B7C80 01007326 */   addiu     $s3, $s3, 0x1
  .L800B7C84:
    /* A8484 800B7C84 3000428E */  lw         $v0, 0x30($s2)
    /* A8488 800B7C88 0400033C */  lui        $v1, (0x41000 >> 16)
    /* A848C 800B7C8C 00106334 */  ori        $v1, $v1, (0x41000 & 0xFFFF)
    /* A8490 800B7C90 24104300 */  and        $v0, $v0, $v1
    /* A8494 800B7C94 00100324 */  addiu      $v1, $zero, 0x1000
    /* A8498 800B7C98 03004314 */  bne        $v0, $v1, .L800B7CA8
    /* A849C 800B7C9C 00000000 */   nop
    /* A84A0 800B7CA0 ADD0020C */  jal        func_800B42B4
    /* A84A4 800B7CA4 21204002 */   addu      $a0, $s2, $zero
  .L800B7CA8:
    /* A84A8 800B7CA8 3000428E */  lw         $v0, 0x30($s2)
    /* A84AC 800B7CAC 00000000 */  nop
    /* A84B0 800B7CB0 20004234 */  ori        $v0, $v0, 0x20
    /* A84B4 800B7CB4 300042AE */  sw         $v0, 0x30($s2)
    /* A84B8 800B7CB8 4000033C */  lui        $v1, (0x400000 >> 16)
    /* A84BC 800B7CBC 24104300 */  and        $v0, $v0, $v1
    /* A84C0 800B7CC0 03004010 */  beqz       $v0, .L800B7CD0
    /* A84C4 800B7CC4 00000000 */   nop
    /* A84C8 800B7CC8 1680013C */  lui        $at, %hi(D_801592E4)
    /* A84CC 800B7CCC E4923EA4 */  sh         $fp, %lo(D_801592E4)($at)
  .L800B7CD0:
    /* A84D0 800B7CD0 3000428E */  lw         $v0, 0x30($s2)
    /* A84D4 800B7CD4 8000033C */  lui        $v1, (0x800000 >> 16)
    /* A84D8 800B7CD8 24104300 */  and        $v0, $v0, $v1
    /* A84DC 800B7CDC 0D004010 */  beqz       $v0, .L800B7D14
    /* A84E0 800B7CE0 00000000 */   nop
    /* A84E4 800B7CE4 16024486 */  lh         $a0, 0x216($s2)
    /* A84E8 800B7CE8 00000000 */  nop
    /* A84EC 800B7CEC 02008424 */  addiu      $a0, $a0, 0x2
    /* A84F0 800B7CF0 0ABE010C */  jal        func_8006F828
    /* A84F4 800B7CF4 02000524 */   addiu     $a1, $zero, 0x2
    /* A84F8 800B7CF8 00140200 */  sll        $v0, $v0, 16
    /* A84FC 800B7CFC 03140200 */  sra        $v0, $v0, 16
    /* A8500 800B7D00 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* A8504 800B7D04 03004314 */  bne        $v0, $v1, .L800B7D14
    /* A8508 800B7D08 FEFF0224 */   addiu     $v0, $zero, -0x2
    /* A850C 800B7D0C DAD1020C */  jal        func_800B4768
    /* A8510 800B7D10 BC0042AE */   sw        $v0, 0xBC($s2)
  .L800B7D14:
    /* A8514 800B7D14 8400BF8F */  lw         $ra, 0x84($sp)
    /* A8518 800B7D18 8000BE8F */  lw         $fp, 0x80($sp)
    /* A851C 800B7D1C 7C00B78F */  lw         $s7, 0x7C($sp)
    /* A8520 800B7D20 7800B68F */  lw         $s6, 0x78($sp)
    /* A8524 800B7D24 7400B58F */  lw         $s5, 0x74($sp)
    /* A8528 800B7D28 7000B48F */  lw         $s4, 0x70($sp)
    /* A852C 800B7D2C 6C00B38F */  lw         $s3, 0x6C($sp)
    /* A8530 800B7D30 6800B28F */  lw         $s2, 0x68($sp)
    /* A8534 800B7D34 6400B18F */  lw         $s1, 0x64($sp)
    /* A8538 800B7D38 6000B08F */  lw         $s0, 0x60($sp)
    /* A853C 800B7D3C 8800BD27 */  addiu      $sp, $sp, 0x88
    /* A8540 800B7D40 0800E003 */  jr         $ra
    /* A8544 800B7D44 00000000 */   nop
endlabel func_800B6EA0
