.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_80010828

dlabel jtbl_80010828
    /* 1028 80010828 A0A60580 */ .word .L8005A6A0
    /* 102C 8001082C C0A60580 */ .word .L8005A6C0
    /* 1030 80010830 C0A60580 */ .word .L8005A6C0
    /* 1034 80010834 70A60580 */ .word .L8005A670
    /* 1038 80010838 70A60580 */ .word .L8005A670
    /* 103C 8001083C 70A60580 */ .word .L8005A670
    /* 1040 80010840 70A60580 */ .word .L8005A670
    /* 1044 80010844 70A60580 */ .word .L8005A670
    /* 1048 80010848 70A60580 */ .word .L8005A670
    /* 104C 8001084C 70A60580 */ .word .L8005A670
    /* 1050 80010850 B0A60580 */ .word .L8005A6B0
    /* 1054 80010854 C0A60580 */ .word .L8005A6C0
    /* 1058 80010858 C0A60580 */ .word .L8005A6C0
    /* 105C 8001085C C0A60580 */ .word .L8005A6C0
    /* 1060 80010860 C0A60580 */ .word .L8005A6C0
    /* 1064 80010864 C0A60580 */ .word .L8005A6C0
    /* 1068 80010868 C0A60580 */ .word .L8005A6C0
    /* 106C 8001086C C0A60580 */ .word .L8005A6C0
    /* 1070 80010870 C0A60580 */ .word .L8005A6C0
    /* 1074 80010874 C0A60580 */ .word .L8005A6C0
    /* 1078 80010878 C0A60580 */ .word .L8005A6C0
    /* 107C 8001087C C0A60580 */ .word .L8005A6C0
    /* 1080 80010880 C0A60580 */ .word .L8005A6C0
    /* 1084 80010884 C0A60580 */ .word .L8005A6C0
    /* 1088 80010888 C0A60580 */ .word .L8005A6C0
    /* 108C 8001088C C0A60580 */ .word .L8005A6C0
    /* 1090 80010890 B0A60580 */ .word .L8005A6B0
    /* 1094 80010894 00000000 */ .word 0x00000000
enddlabel jtbl_80010828


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8005A60C, 0xD0

glabel func_8005A60C
    /* 4AE0C 8005A60C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 4AE10 8005A610 1400BFAF */  sw         $ra, 0x14($sp)
    /* 4AE14 8005A614 1000B0AF */  sw         $s0, 0x10($sp)
    /* 4AE18 8005A618 40100400 */  sll        $v0, $a0, 1
    /* 4AE1C 8005A61C 21104400 */  addu       $v0, $v0, $a0
    /* 4AE20 8005A620 80100200 */  sll        $v0, $v0, 2
    /* 4AE24 8005A624 21104400 */  addu       $v0, $v0, $a0
    /* 4AE28 8005A628 40100200 */  sll        $v0, $v0, 1
    /* 4AE2C 8005A62C 1180013C */  lui        $at, %hi(D_8010D6C3)
    /* 4AE30 8005A630 21082200 */  addu       $at, $at, $v0
    /* 4AE34 8005A634 C3D62290 */  lbu        $v0, %lo(D_8010D6C3)($at)
    /* 4AE38 8005A638 00000000 */  nop
    /* 4AE3C 8005A63C FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 4AE40 8005A640 00160200 */  sll        $v0, $v0, 24
    /* 4AE44 8005A644 031E0200 */  sra        $v1, $v0, 24
    /* 4AE48 8005A648 1B00622C */  sltiu      $v0, $v1, 0x1B
    /* 4AE4C 8005A64C 1C004010 */  beqz       $v0, .L8005A6C0
    /* 4AE50 8005A650 01001024 */   addiu     $s0, $zero, 0x1
    /* 4AE54 8005A654 80100300 */  sll        $v0, $v1, 2
    /* 4AE58 8005A658 0180013C */  lui        $at, %hi(jtbl_80010828)
    /* 4AE5C 8005A65C 21082200 */  addu       $at, $at, $v0
    /* 4AE60 8005A660 2808228C */  lw         $v0, %lo(jtbl_80010828)($at)
    /* 4AE64 8005A664 00000000 */  nop
    /* 4AE68 8005A668 08004000 */  jr         $v0
    /* 4AE6C 8005A66C 00000000 */   nop
  .L8005A670:
    /* 4AE70 8005A670 40100400 */  sll        $v0, $a0, 1
    /* 4AE74 8005A674 21104400 */  addu       $v0, $v0, $a0
    /* 4AE78 8005A678 80100200 */  sll        $v0, $v0, 2
    /* 4AE7C 8005A67C 21104400 */  addu       $v0, $v0, $a0
    /* 4AE80 8005A680 40100200 */  sll        $v0, $v0, 1
    /* 4AE84 8005A684 1180013C */  lui        $at, %hi(D_8010D6C3)
    /* 4AE88 8005A688 21082200 */  addu       $at, $at, $v0
    /* 4AE8C 8005A68C C3D62580 */  lb         $a1, %lo(D_8010D6C3)($at)
    /* 4AE90 8005A690 8F64010C */  jal        func_8005923C
    /* 4AE94 8005A694 00000000 */   nop
    /* 4AE98 8005A698 B2690108 */  j          .L8005A6C8
    /* 4AE9C 8005A69C 21100002 */   addu      $v0, $s0, $zero
  .L8005A6A0:
    /* 4AEA0 8005A6A0 D966010C */  jal        func_80059B64
    /* 4AEA4 8005A6A4 00000000 */   nop
    /* 4AEA8 8005A6A8 B2690108 */  j          .L8005A6C8
    /* 4AEAC 8005A6AC 21100002 */   addu      $v0, $s0, $zero
  .L8005A6B0:
    /* 4AEB0 8005A6B0 2F68010C */  jal        func_8005A0BC
    /* 4AEB4 8005A6B4 00000000 */   nop
    /* 4AEB8 8005A6B8 B2690108 */  j          .L8005A6C8
    /* 4AEBC 8005A6BC 21100002 */   addu      $v0, $s0, $zero
  .L8005A6C0:
    /* 4AEC0 8005A6C0 21800000 */  addu       $s0, $zero, $zero
    /* 4AEC4 8005A6C4 21100002 */  addu       $v0, $s0, $zero
  .L8005A6C8:
    /* 4AEC8 8005A6C8 1400BF8F */  lw         $ra, 0x14($sp)
    /* 4AECC 8005A6CC 1000B08F */  lw         $s0, 0x10($sp)
    /* 4AED0 8005A6D0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 4AED4 8005A6D4 0800E003 */  jr         $ra
    /* 4AED8 8005A6D8 00000000 */   nop
endlabel func_8005A60C
