.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80012C28

dlabel D_80012C28
    /* 3428 80012C28 */ .asciz "Structural"
    /* 5374727563747572616C0000 */
.align 2
enddlabel D_80012C28

.align 2
nonmatching D_80012C34

dlabel D_80012C34
    /* 3434 80012C34 */ .asciz "Propulsion"
    /* 50726F70756C73696F6E0000 */
.align 2
enddlabel D_80012C34

.align 2
nonmatching D_80012C40

dlabel D_80012C40
    /* 3440 80012C40 */ .asciz "Habitation"
    /* 48616269746174696F6E0000 */
.align 2
enddlabel D_80012C40

.align 2
nonmatching D_80012C4C

dlabel D_80012C4C
    /* 344C 80012C4C */ .asciz "Life Support"
    /* 4C69666520537570706F727400000000 */
.align 2
enddlabel D_80012C4C

.align 2
nonmatching D_80012C5C

dlabel D_80012C5C
    /* 345C 80012C5C */ .asciz "Solar panel"
    /* 536F6C61722070616E656C00 */
.align 2
enddlabel D_80012C5C

.align 2
nonmatching D_80012C68

dlabel D_80012C68
    /* 3468 80012C68 */ .asciz "Population"
    /* 506F70756C6174696F6E0000 */
.align 2
enddlabel D_80012C68


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800CD5B0, 0x524

glabel func_800CD5B0
    /* BDDB0 800CD5B0 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* BDDB4 800CD5B4 2400BFAF */  sw         $ra, 0x24($sp)
    /* BDDB8 800CD5B8 2000B4AF */  sw         $s4, 0x20($sp)
    /* BDDBC 800CD5BC 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* BDDC0 800CD5C0 1800B2AF */  sw         $s2, 0x18($sp)
    /* BDDC4 800CD5C4 1400B1AF */  sw         $s1, 0x14($sp)
    /* BDDC8 800CD5C8 1000B0AF */  sw         $s0, 0x10($sp)
    /* BDDCC 800CD5CC 21908000 */  addu       $s2, $a0, $zero
    /* BDDD0 800CD5D0 21980000 */  addu       $s3, $zero, $zero
    /* BDDD4 800CD5D4 CB1A030C */  jal        func_800C6B2C
    /* BDDD8 800CD5D8 62014426 */   addiu     $a0, $s2, 0x162
    /* BDDDC 800CD5DC 21880000 */  addu       $s1, $zero, $zero
    /* BDDE0 800CD5E0 1180143C */  lui        $s4, %hi(D_80117A7C)
    /* BDDE4 800CD5E4 7C7A9426 */  addiu      $s4, $s4, %lo(D_80117A7C)
  .L800CD5E8:
    /* BDDE8 800CD5E8 48014486 */  lh         $a0, 0x148($s2)
    /* BDDEC 800CD5EC 00000000 */  nop
    /* BDDF0 800CD5F0 40100400 */  sll        $v0, $a0, 1
    /* BDDF4 800CD5F4 21104400 */  addu       $v0, $v0, $a0
    /* BDDF8 800CD5F8 80100200 */  sll        $v0, $v0, 2
    /* BDDFC 800CD5FC 23104400 */  subu       $v0, $v0, $a0
    /* BDE00 800CD600 00110200 */  sll        $v0, $v0, 4
    /* BDE04 800CD604 23104400 */  subu       $v0, $v0, $a0
    /* BDE08 800CD608 C0100200 */  sll        $v0, $v0, 3
    /* BDE0C 800CD60C 002C1100 */  sll        $a1, $s1, 16
    /* BDE10 800CD610 032C0500 */  sra        $a1, $a1, 16
    /* BDE14 800CD614 40180500 */  sll        $v1, $a1, 1
    /* BDE18 800CD618 21105400 */  addu       $v0, $v0, $s4
    /* BDE1C 800CD61C 21186200 */  addu       $v1, $v1, $v0
    /* BDE20 800CD620 00007084 */  lh         $s0, 0x0($v1)
    /* BDE24 800CD624 F520030C */  jal        func_800C83D4
    /* BDE28 800CD628 00000000 */   nop
    /* BDE2C 800CD62C 2A105000 */  slt        $v0, $v0, $s0
    /* BDE30 800CD630 02004010 */  beqz       $v0, .L800CD63C
    /* BDE34 800CD634 01002226 */   addiu     $v0, $s1, 0x1
    /* BDE38 800CD638 01001324 */  addiu      $s3, $zero, 0x1
  .L800CD63C:
    /* BDE3C 800CD63C 21884000 */  addu       $s1, $v0, $zero
    /* BDE40 800CD640 00140200 */  sll        $v0, $v0, 16
    /* BDE44 800CD644 03140200 */  sra        $v0, $v0, 16
    /* BDE48 800CD648 06004228 */  slti       $v0, $v0, 0x6
    /* BDE4C 800CD64C E6FF4014 */  bnez       $v0, .L800CD5E8
    /* BDE50 800CD650 00000000 */   nop
    /* BDE54 800CD654 21880000 */  addu       $s1, $zero, $zero
    /* BDE58 800CD658 62015426 */  addiu      $s4, $s2, 0x162
  .L800CD65C:
    /* BDE5C 800CD65C 00141100 */  sll        $v0, $s1, 16
    /* BDE60 800CD660 031C0200 */  sra        $v1, $v0, 16
    /* BDE64 800CD664 06006228 */  slti       $v0, $v1, 0x6
    /* BDE68 800CD668 45004010 */  beqz       $v0, .L800CD780
    /* BDE6C 800CD66C 0600622C */   sltiu     $v0, $v1, 0x6
    /* BDE70 800CD670 20004010 */  beqz       $v0, .L800CD6F4
    /* BDE74 800CD674 80100300 */   sll       $v0, $v1, 2
    /* BDE78 800CD678 0180013C */  lui        $at, %hi(jtbl_80012C80)
    /* BDE7C 800CD67C 21082200 */  addu       $at, $at, $v0
    /* BDE80 800CD680 802C228C */  lw         $v0, %lo(jtbl_80012C80)($at)
    /* BDE84 800CD684 00000000 */  nop
    /* BDE88 800CD688 08004000 */  jr         $v0
    /* BDE8C 800CD68C 00000000 */   nop
  .L800CD690:
    /* BDE90 800CD690 0180053C */  lui        $a1, %hi(D_80012C28)
    /* BDE94 800CD694 282CA524 */  addiu      $a1, $a1, %lo(D_80012C28)
    /* BDE98 800CD698 BB350308 */  j          .L800CD6EC
    /* BDE9C 800CD69C 62014426 */   addiu     $a0, $s2, 0x162
  .L800CD6A0:
    /* BDEA0 800CD6A0 0180053C */  lui        $a1, %hi(D_80012C34)
    /* BDEA4 800CD6A4 342CA524 */  addiu      $a1, $a1, %lo(D_80012C34)
    /* BDEA8 800CD6A8 BB350308 */  j          .L800CD6EC
    /* BDEAC 800CD6AC 62014426 */   addiu     $a0, $s2, 0x162
  .L800CD6B0:
    /* BDEB0 800CD6B0 1680053C */  lui        $a1, %hi(D_801591AC)
    /* BDEB4 800CD6B4 AC91A524 */  addiu      $a1, $a1, %lo(D_801591AC)
    /* BDEB8 800CD6B8 BB350308 */  j          .L800CD6EC
    /* BDEBC 800CD6BC 62014426 */   addiu     $a0, $s2, 0x162
  .L800CD6C0:
    /* BDEC0 800CD6C0 0180053C */  lui        $a1, %hi(D_80012C40)
    /* BDEC4 800CD6C4 402CA524 */  addiu      $a1, $a1, %lo(D_80012C40)
    /* BDEC8 800CD6C8 BB350308 */  j          .L800CD6EC
    /* BDECC 800CD6CC 62014426 */   addiu     $a0, $s2, 0x162
  .L800CD6D0:
    /* BDED0 800CD6D0 0180053C */  lui        $a1, %hi(D_80012C4C)
    /* BDED4 800CD6D4 4C2CA524 */  addiu      $a1, $a1, %lo(D_80012C4C)
    /* BDED8 800CD6D8 BB350308 */  j          .L800CD6EC
    /* BDEDC 800CD6DC 62014426 */   addiu     $a0, $s2, 0x162
  .L800CD6E0:
    /* BDEE0 800CD6E0 62014426 */  addiu      $a0, $s2, 0x162
    /* BDEE4 800CD6E4 0180053C */  lui        $a1, %hi(D_80012C5C)
    /* BDEE8 800CD6E8 5C2CA524 */  addiu      $a1, $a1, %lo(D_80012C5C)
  .L800CD6EC:
    /* BDEEC 800CD6EC 9987030C */  jal        func_800E1E64
    /* BDEF0 800CD6F0 00000000 */   nop
  .L800CD6F4:
    /* BDEF4 800CD6F4 F71A030C */  jal        func_800C6BDC
    /* BDEF8 800CD6F8 21208002 */   addu      $a0, $s4, $zero
    /* BDEFC 800CD6FC 48014386 */  lh         $v1, 0x148($s2)
    /* BDF00 800CD700 00000000 */  nop
    /* BDF04 800CD704 40100300 */  sll        $v0, $v1, 1
    /* BDF08 800CD708 21104300 */  addu       $v0, $v0, $v1
    /* BDF0C 800CD70C 80100200 */  sll        $v0, $v0, 2
    /* BDF10 800CD710 23104300 */  subu       $v0, $v0, $v1
    /* BDF14 800CD714 00110200 */  sll        $v0, $v0, 4
    /* BDF18 800CD718 23104300 */  subu       $v0, $v0, $v1
    /* BDF1C 800CD71C C0100200 */  sll        $v0, $v0, 3
    /* BDF20 800CD720 001C1100 */  sll        $v1, $s1, 16
    /* BDF24 800CD724 03840300 */  sra        $s0, $v1, 16
    /* BDF28 800CD728 1180043C */  lui        $a0, %hi(D_80117A7C)
    /* BDF2C 800CD72C 7C7A8424 */  addiu      $a0, $a0, %lo(D_80117A7C)
    /* BDF30 800CD730 40181000 */  sll        $v1, $s0, 1
    /* BDF34 800CD734 21104400 */  addu       $v0, $v0, $a0
    /* BDF38 800CD738 21186200 */  addu       $v1, $v1, $v0
    /* BDF3C 800CD73C 00006584 */  lh         $a1, 0x0($v1)
    /* BDF40 800CD740 9C1B030C */  jal        func_800C6E70
    /* BDF44 800CD744 21208002 */   addu      $a0, $s4, $zero
    /* BDF48 800CD748 07006012 */  beqz       $s3, .L800CD768
    /* BDF4C 800CD74C 00000000 */   nop
    /* BDF50 800CD750 05000016 */  bnez       $s0, .L800CD768
    /* BDF54 800CD754 00000000 */   nop
    /* BDF58 800CD758 1680053C */  lui        $a1, %hi(D_801591B4)
    /* BDF5C 800CD75C B491A524 */  addiu      $a1, $a1, %lo(D_801591B4)
    /* BDF60 800CD760 9987030C */  jal        func_800E1E64
    /* BDF64 800CD764 21208002 */   addu      $a0, $s4, $zero
  .L800CD768:
    /* BDF68 800CD768 1680053C */  lui        $a1, %hi(D_801591B8)
    /* BDF6C 800CD76C B891A524 */  addiu      $a1, $a1, %lo(D_801591B8)
    /* BDF70 800CD770 9987030C */  jal        func_800E1E64
    /* BDF74 800CD774 62014426 */   addiu     $a0, $s2, 0x162
    /* BDF78 800CD778 97350308 */  j          .L800CD65C
    /* BDF7C 800CD77C 01003126 */   addiu     $s1, $s1, 0x1
  .L800CD780:
    /* BDF80 800CD780 62015126 */  addiu      $s1, $s2, 0x162
    /* BDF84 800CD784 0180053C */  lui        $a1, %hi(D_80012C68)
    /* BDF88 800CD788 682CA524 */  addiu      $a1, $a1, %lo(D_80012C68)
    /* BDF8C 800CD78C 9987030C */  jal        func_800E1E64
    /* BDF90 800CD790 21202002 */   addu      $a0, $s1, $zero
    /* BDF94 800CD794 F71A030C */  jal        func_800C6BDC
    /* BDF98 800CD798 21202002 */   addu      $a0, $s1, $zero
    /* BDF9C 800CD79C 48014386 */  lh         $v1, 0x148($s2)
    /* BDFA0 800CD7A0 00000000 */  nop
    /* BDFA4 800CD7A4 40100300 */  sll        $v0, $v1, 1
    /* BDFA8 800CD7A8 21104300 */  addu       $v0, $v0, $v1
    /* BDFAC 800CD7AC 80100200 */  sll        $v0, $v0, 2
    /* BDFB0 800CD7B0 23104300 */  subu       $v0, $v0, $v1
    /* BDFB4 800CD7B4 00110200 */  sll        $v0, $v0, 4
    /* BDFB8 800CD7B8 23104300 */  subu       $v0, $v0, $v1
    /* BDFBC 800CD7BC C0100200 */  sll        $v0, $v0, 3
    /* BDFC0 800CD7C0 1180013C */  lui        $at, %hi(D_80117A82)
    /* BDFC4 800CD7C4 21082200 */  addu       $at, $at, $v0
    /* BDFC8 800CD7C8 827A2584 */  lh         $a1, %lo(D_80117A82)($at)
    /* BDFCC 800CD7CC 9C1B030C */  jal        func_800C6E70
    /* BDFD0 800CD7D0 21202002 */   addu      $a0, $s1, $zero
    /* BDFD4 800CD7D4 1680053C */  lui        $a1, %hi(D_801591BC)
    /* BDFD8 800CD7D8 BC91A524 */  addiu      $a1, $a1, %lo(D_801591BC)
    /* BDFDC 800CD7DC 9987030C */  jal        func_800E1E64
    /* BDFE0 800CD7E0 21202002 */   addu      $a0, $s1, $zero
    /* BDFE4 800CD7E4 1680053C */  lui        $a1, %hi(D_801591B8)
    /* BDFE8 800CD7E8 B891A524 */  addiu      $a1, $a1, %lo(D_801591B8)
    /* BDFEC 800CD7EC 9987030C */  jal        func_800E1E64
    /* BDFF0 800CD7F0 21202002 */   addu      $a0, $s1, $zero
    /* BDFF4 800CD7F4 1680053C */  lui        $a1, %hi(D_801591C4)
    /* BDFF8 800CD7F8 C491A524 */  addiu      $a1, $a1, %lo(D_801591C4)
    /* BDFFC 800CD7FC 9987030C */  jal        func_800E1E64
    /* BE000 800CD800 21202002 */   addu      $a0, $s1, $zero
    /* BE004 800CD804 F71A030C */  jal        func_800C6BDC
    /* BE008 800CD808 21202002 */   addu      $a0, $s1, $zero
    /* BE00C 800CD80C 1680053C */  lui        $a1, %hi(D_8015917C)
    /* BE010 800CD810 7C91A58C */  lw         $a1, %lo(D_8015917C)($a1)
    /* BE014 800CD814 9C1B030C */  jal        func_800C6E70
    /* BE018 800CD818 21202002 */   addu      $a0, $s1, $zero
    /* BE01C 800CD81C 0B1B030C */  jal        func_800C6C2C
    /* BE020 800CD820 21202002 */   addu      $a0, $s1, $zero
    /* BE024 800CD824 1680053C */  lui        $a1, %hi(D_801591B8)
    /* BE028 800CD828 B891A524 */  addiu      $a1, $a1, %lo(D_801591B8)
    /* BE02C 800CD82C 9987030C */  jal        func_800E1E64
    /* BE030 800CD830 21202002 */   addu      $a0, $s1, $zero
    /* BE034 800CD834 21202002 */  addu       $a0, $s1, $zero
    /* BE038 800CD838 731B030C */  jal        func_800C6DCC
    /* BE03C 800CD83C CD000524 */   addiu     $a1, $zero, 0xCD
    /* BE040 800CD840 F71A030C */  jal        func_800C6BDC
    /* BE044 800CD844 21202002 */   addu      $a0, $s1, $zero
    /* BE048 800CD848 1680053C */  lui        $a1, %hi(D_80159180)
    /* BE04C 800CD84C 8091A58C */  lw         $a1, %lo(D_80159180)($a1)
    /* BE050 800CD850 9C1B030C */  jal        func_800C6E70
    /* BE054 800CD854 21202002 */   addu      $a0, $s1, $zero
    /* BE058 800CD858 0B1B030C */  jal        func_800C6C2C
    /* BE05C 800CD85C 21202002 */   addu      $a0, $s1, $zero
    /* BE060 800CD860 1680053C */  lui        $a1, %hi(D_801591B8)
    /* BE064 800CD864 B891A524 */  addiu      $a1, $a1, %lo(D_801591B8)
    /* BE068 800CD868 9987030C */  jal        func_800E1E64
    /* BE06C 800CD86C 21202002 */   addu      $a0, $s1, $zero
    /* BE070 800CD870 21202002 */  addu       $a0, $s1, $zero
    /* BE074 800CD874 731B030C */  jal        func_800C6DCC
    /* BE078 800CD878 CE000524 */   addiu     $a1, $zero, 0xCE
    /* BE07C 800CD87C F71A030C */  jal        func_800C6BDC
    /* BE080 800CD880 21202002 */   addu      $a0, $s1, $zero
    /* BE084 800CD884 1680053C */  lui        $a1, %hi(D_80159174)
    /* BE088 800CD888 7491A58C */  lw         $a1, %lo(D_80159174)($a1)
    /* BE08C 800CD88C 6666103C */  lui        $s0, (0x66666667 >> 16)
    /* BE090 800CD890 67661036 */  ori        $s0, $s0, (0x66666667 & 0xFFFF)
    /* BE094 800CD894 1800B000 */  mult       $a1, $s0
    /* BE098 800CD898 10380000 */  mfhi       $a3
    /* BE09C 800CD89C 83100700 */  sra        $v0, $a3, 2
    /* BE0A0 800CD8A0 C32F0500 */  sra        $a1, $a1, 31
    /* BE0A4 800CD8A4 21202002 */  addu       $a0, $s1, $zero
    /* BE0A8 800CD8A8 9C1B030C */  jal        func_800C6E70
    /* BE0AC 800CD8AC 23284500 */   subu      $a1, $v0, $a1
    /* BE0B0 800CD8B0 1680053C */  lui        $a1, %hi(D_801591CC)
    /* BE0B4 800CD8B4 CC91A524 */  addiu      $a1, $a1, %lo(D_801591CC)
    /* BE0B8 800CD8B8 9987030C */  jal        func_800E1E64
    /* BE0BC 800CD8BC 21202002 */   addu      $a0, $s1, $zero
    /* BE0C0 800CD8C0 1680063C */  lui        $a2, %hi(D_80159174)
    /* BE0C4 800CD8C4 7491C68C */  lw         $a2, %lo(D_80159174)($a2)
    /* BE0C8 800CD8C8 00000000 */  nop
    /* BE0CC 800CD8CC 1800D000 */  mult       $a2, $s0
    /* BE0D0 800CD8D0 10380000 */  mfhi       $a3
    /* BE0D4 800CD8D4 83100700 */  sra        $v0, $a3, 2
    /* BE0D8 800CD8D8 C31F0600 */  sra        $v1, $a2, 31
    /* BE0DC 800CD8DC 23104300 */  subu       $v0, $v0, $v1
    /* BE0E0 800CD8E0 80280200 */  sll        $a1, $v0, 2
    /* BE0E4 800CD8E4 2128A200 */  addu       $a1, $a1, $v0
    /* BE0E8 800CD8E8 40280500 */  sll        $a1, $a1, 1
    /* BE0EC 800CD8EC 21202002 */  addu       $a0, $s1, $zero
    /* BE0F0 800CD8F0 9C1B030C */  jal        func_800C6E70
    /* BE0F4 800CD8F4 2328C500 */   subu      $a1, $a2, $a1
    /* BE0F8 800CD8F8 1680053C */  lui        $a1, %hi(D_801591D0)
    /* BE0FC 800CD8FC D091A524 */  addiu      $a1, $a1, %lo(D_801591D0)
    /* BE100 800CD900 9987030C */  jal        func_800E1E64
    /* BE104 800CD904 21202002 */   addu      $a0, $s1, $zero
    /* BE108 800CD908 1680053C */  lui        $a1, %hi(D_801591D4)
    /* BE10C 800CD90C D491A524 */  addiu      $a1, $a1, %lo(D_801591D4)
    /* BE110 800CD910 9987030C */  jal        func_800E1E64
    /* BE114 800CD914 21202002 */   addu      $a0, $s1, $zero
    /* BE118 800CD918 1680053C */  lui        $a1, %hi(D_801591B8)
    /* BE11C 800CD91C B891A524 */  addiu      $a1, $a1, %lo(D_801591B8)
    /* BE120 800CD920 9987030C */  jal        func_800E1E64
    /* BE124 800CD924 21202002 */   addu      $a0, $s1, $zero
    /* BE128 800CD928 1680053C */  lui        $a1, %hi(D_801591AC)
    /* BE12C 800CD92C AC91A524 */  addiu      $a1, $a1, %lo(D_801591AC)
    /* BE130 800CD930 9987030C */  jal        func_800E1E64
    /* BE134 800CD934 21202002 */   addu      $a0, $s1, $zero
    /* BE138 800CD938 F71A030C */  jal        func_800C6BDC
    /* BE13C 800CD93C 21202002 */   addu      $a0, $s1, $zero
    /* BE140 800CD940 1680053C */  lui        $a1, %hi(D_80159184)
    /* BE144 800CD944 8491A58C */  lw         $a1, %lo(D_80159184)($a1)
    /* BE148 800CD948 9C1B030C */  jal        func_800C6E70
    /* BE14C 800CD94C 21202002 */   addu      $a0, $s1, $zero
    /* BE150 800CD950 0B1B030C */  jal        func_800C6C2C
    /* BE154 800CD954 21202002 */   addu      $a0, $s1, $zero
    /* BE158 800CD958 48014386 */  lh         $v1, 0x148($s2)
    /* BE15C 800CD95C 00000000 */  nop
    /* BE160 800CD960 40100300 */  sll        $v0, $v1, 1
    /* BE164 800CD964 21104300 */  addu       $v0, $v0, $v1
    /* BE168 800CD968 80100200 */  sll        $v0, $v0, 2
    /* BE16C 800CD96C 23104300 */  subu       $v0, $v0, $v1
    /* BE170 800CD970 00110200 */  sll        $v0, $v0, 4
    /* BE174 800CD974 23104300 */  subu       $v0, $v0, $v1
    /* BE178 800CD978 C0100200 */  sll        $v0, $v0, 3
    /* BE17C 800CD97C 1180013C */  lui        $at, %hi(D_80117A74)
    /* BE180 800CD980 21082200 */  addu       $at, $at, $v0
    /* BE184 800CD984 747A2290 */  lbu        $v0, %lo(D_80117A74)($at)
    /* BE188 800CD988 00000000 */  nop
    /* BE18C 800CD98C 08004230 */  andi       $v0, $v0, 0x8
    /* BE190 800CD990 0B004010 */  beqz       $v0, .L800CD9C0
    /* BE194 800CD994 62015026 */   addiu     $s0, $s2, 0x162
    /* BE198 800CD998 CD1A030C */  jal        func_800C6B34
    /* BE19C 800CD99C 21202002 */   addu      $a0, $s1, $zero
    /* BE1A0 800CD9A0 151B030C */  jal        func_800C6C54
    /* BE1A4 800CD9A4 21202002 */   addu      $a0, $s1, $zero
    /* BE1A8 800CD9A8 21202002 */  addu       $a0, $s1, $zero
    /* BE1AC 800CD9AC 731B030C */  jal        func_800C6DCC
    /* BE1B0 800CD9B0 EB000524 */   addiu     $a1, $zero, 0xEB
    /* BE1B4 800CD9B4 1F1B030C */  jal        func_800C6C7C
    /* BE1B8 800CD9B8 21202002 */   addu      $a0, $s1, $zero
    /* BE1BC 800CD9BC 62015026 */  addiu      $s0, $s2, 0x162
  .L800CD9C0:
    /* BE1C0 800CD9C0 1680053C */  lui        $a1, %hi(D_801591B8)
    /* BE1C4 800CD9C4 B891A524 */  addiu      $a1, $a1, %lo(D_801591B8)
    /* BE1C8 800CD9C8 9987030C */  jal        func_800E1E64
    /* BE1CC 800CD9CC 21200002 */   addu      $a0, $s0, $zero
    /* BE1D0 800CD9D0 21200002 */  addu       $a0, $s0, $zero
    /* BE1D4 800CD9D4 731B030C */  jal        func_800C6DCC
    /* BE1D8 800CD9D8 CF000524 */   addiu     $a1, $zero, 0xCF
    /* BE1DC 800CD9DC F71A030C */  jal        func_800C6BDC
    /* BE1E0 800CD9E0 21200002 */   addu      $a0, $s0, $zero
    /* BE1E4 800CD9E4 1680053C */  lui        $a1, %hi(D_80159188)
    /* BE1E8 800CD9E8 8891A58C */  lw         $a1, %lo(D_80159188)($a1)
    /* BE1EC 800CD9EC 6666113C */  lui        $s1, (0x66666667 >> 16)
    /* BE1F0 800CD9F0 67663136 */  ori        $s1, $s1, (0x66666667 & 0xFFFF)
    /* BE1F4 800CD9F4 1800B100 */  mult       $a1, $s1
    /* BE1F8 800CD9F8 10380000 */  mfhi       $a3
    /* BE1FC 800CD9FC 83100700 */  sra        $v0, $a3, 2
    /* BE200 800CDA00 C32F0500 */  sra        $a1, $a1, 31
    /* BE204 800CDA04 21200002 */  addu       $a0, $s0, $zero
    /* BE208 800CDA08 9C1B030C */  jal        func_800C6E70
    /* BE20C 800CDA0C 23284500 */   subu      $a1, $v0, $a1
    /* BE210 800CDA10 1680053C */  lui        $a1, %hi(D_801591D8)
    /* BE214 800CDA14 D891A524 */  addiu      $a1, $a1, %lo(D_801591D8)
    /* BE218 800CDA18 9987030C */  jal        func_800E1E64
    /* BE21C 800CDA1C 21200002 */   addu      $a0, $s0, $zero
    /* BE220 800CDA20 1680063C */  lui        $a2, %hi(D_80159188)
    /* BE224 800CDA24 8891C68C */  lw         $a2, %lo(D_80159188)($a2)
    /* BE228 800CDA28 00000000 */  nop
    /* BE22C 800CDA2C 1800D100 */  mult       $a2, $s1
    /* BE230 800CDA30 10380000 */  mfhi       $a3
    /* BE234 800CDA34 83100700 */  sra        $v0, $a3, 2
    /* BE238 800CDA38 C31F0600 */  sra        $v1, $a2, 31
    /* BE23C 800CDA3C 23104300 */  subu       $v0, $v0, $v1
    /* BE240 800CDA40 80280200 */  sll        $a1, $v0, 2
    /* BE244 800CDA44 2128A200 */  addu       $a1, $a1, $v0
    /* BE248 800CDA48 40280500 */  sll        $a1, $a1, 1
    /* BE24C 800CDA4C 21200002 */  addu       $a0, $s0, $zero
    /* BE250 800CDA50 9C1B030C */  jal        func_800C6E70
    /* BE254 800CDA54 2328C500 */   subu      $a1, $a2, $a1
    /* BE258 800CDA58 CD1A030C */  jal        func_800C6B34
    /* BE25C 800CDA5C 21200002 */   addu      $a0, $s0, $zero
    /* BE260 800CDA60 1680053C */  lui        $a1, %hi(D_801591DC)
    /* BE264 800CDA64 DC91A524 */  addiu      $a1, $a1, %lo(D_801591DC)
    /* BE268 800CDA68 9987030C */  jal        func_800E1E64
    /* BE26C 800CDA6C 21200002 */   addu      $a0, $s0, $zero
    /* BE270 800CDA70 62035026 */  addiu      $s0, $s2, 0x362
    /* BE274 800CDA74 CB1A030C */  jal        func_800C6B2C
    /* BE278 800CDA78 21200002 */   addu      $a0, $s0, $zero
    /* BE27C 800CDA7C 21200002 */  addu       $a0, $s0, $zero
    /* BE280 800CDA80 731B030C */  jal        func_800C6DCC
    /* BE284 800CDA84 D0000524 */   addiu     $a1, $zero, 0xD0
    /* BE288 800CDA88 F71A030C */  jal        func_800C6BDC
    /* BE28C 800CDA8C 21200002 */   addu      $a0, $s0, $zero
    /* BE290 800CDA90 CD1A030C */  jal        func_800C6B34
    /* BE294 800CDA94 21200002 */   addu      $a0, $s0, $zero
    /* BE298 800CDA98 1680053C */  lui        $a1, %hi(D_80159178)
    /* BE29C 800CDA9C 7891A58C */  lw         $a1, %lo(D_80159178)($a1)
    /* BE2A0 800CDAA0 9C1B030C */  jal        func_800C6E70
    /* BE2A4 800CDAA4 21200002 */   addu      $a0, $s0, $zero
    /* BE2A8 800CDAA8 0B1B030C */  jal        func_800C6C2C
    /* BE2AC 800CDAAC 21200002 */   addu      $a0, $s0, $zero
    /* BE2B0 800CDAB0 2400BF8F */  lw         $ra, 0x24($sp)
    /* BE2B4 800CDAB4 2000B48F */  lw         $s4, 0x20($sp)
    /* BE2B8 800CDAB8 1C00B38F */  lw         $s3, 0x1C($sp)
    /* BE2BC 800CDABC 1800B28F */  lw         $s2, 0x18($sp)
    /* BE2C0 800CDAC0 1400B18F */  lw         $s1, 0x14($sp)
    /* BE2C4 800CDAC4 1000B08F */  lw         $s0, 0x10($sp)
    /* BE2C8 800CDAC8 2800BD27 */  addiu      $sp, $sp, 0x28
    /* BE2CC 800CDACC 0800E003 */  jr         $ra
    /* BE2D0 800CDAD0 00000000 */   nop
endlabel func_800CD5B0
