.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80010AE4

dlabel D_80010AE4
    /* 12E4 80010AE4 */ .asciz "Insufficient free memory blocks."
    /* 496E73756666696369656E742066726565206D656D6F727920626C6F636B732E00000000 */
.align 2
enddlabel D_80010AE4

.align 2
nonmatching D_80010B08

dlabel D_80010B08
    /* 1308 80010B08 */ .asciz "To save game, %d free blocks of"
    /* 546F20736176652067616D652C202564206672656520626C6F636B73206F6600 */
.align 2
enddlabel D_80010B08

.align 2
nonmatching D_80010B28

dlabel D_80010B28
    /* 1328 80010B28 */ .asciz "Memory Card space are needed."
    /* 4D656D6F7279204361726420737061636520617265206E65656465642E000000 */
.align 2
enddlabel D_80010B28

.align 2
nonmatching D_80010B48

dlabel D_80010B48
    /* 1348 80010B48 */ .asciz "Delete old saved files?"
    /* 44656C657465206F6C642073617665642066696C65733F00 */
.align 2
enddlabel D_80010B48

.align 2
nonmatching D_80010B60

dlabel D_80010B60
    /* 1360 80010B60 */ .asciz "Deleting old saved games."
    /* 44656C6574696E67206F6C642073617665642067616D65732E000000 */
.align 2
enddlabel D_80010B60

.align 2
nonmatching D_80010B7C

dlabel D_80010B7C
    /* 137C 80010B7C */ .asciz "%d Files\n"
    /* 25642046696C65730A000000 */
.align 2
enddlabel D_80010B7C

.align 2
nonmatching D_80010B88

dlabel D_80010B88
    /* 1388 80010B88 */ .asciz "Error reading data."
    /* 4572726F722072656164696E6720646174612E00 */
.align 2
enddlabel D_80010B88

.align 2
nonmatching D_80010B9C

dlabel D_80010B9C
    /* 139C 80010B9C */ .asciz "Slot %d:Select files to delete (%d empty blocks)"
    /* 536C6F742025643A53656C6563742066696C657320746F2064656C6574652028256420656D70747920626C6F636B732900000000 */
.align 2
enddlabel D_80010B9C

.align 2
nonmatching D_80010BD0

dlabel D_80010BD0
    /* 13D0 80010BD0 */ .asciz "%s\n%s (%d blocks)"
    /* 25730A25732028256420626C6F636B7329000000 */
.align 2
enddlabel D_80010BD0

.align 2
nonmatching D_80010BE4

dlabel D_80010BE4
    /* 13E4 80010BE4 */ .asciz "Deleting data."
    /* 44656C6574696E6720646174612E0000 */
.align 2
enddlabel D_80010BE4

.align 2
nonmatching D_80010BF4

dlabel D_80010BF4
    /* 13F4 80010BF4 */ .asciz "^This file uses %d memory blocks."
    /* 5E546869732066696C652075736573202564206D656D6F727920626C6F636B732E000000 */
.align 2
enddlabel D_80010BF4


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8006ECFC, 0xB2C

glabel func_8006ECFC
    /* 5F4FC 8006ECFC 70FFBD27 */  addiu      $sp, $sp, -0x90
    /* 5F500 8006ED00 8C00BFAF */  sw         $ra, 0x8C($sp)
    /* 5F504 8006ED04 8800BEAF */  sw         $fp, 0x88($sp)
    /* 5F508 8006ED08 8400B7AF */  sw         $s7, 0x84($sp)
    /* 5F50C 8006ED0C 8000B6AF */  sw         $s6, 0x80($sp)
    /* 5F510 8006ED10 7C00B5AF */  sw         $s5, 0x7C($sp)
    /* 5F514 8006ED14 7800B4AF */  sw         $s4, 0x78($sp)
    /* 5F518 8006ED18 7400B3AF */  sw         $s3, 0x74($sp)
    /* 5F51C 8006ED1C 7000B2AF */  sw         $s2, 0x70($sp)
    /* 5F520 8006ED20 6C00B1AF */  sw         $s1, 0x6C($sp)
    /* 5F524 8006ED24 6800B0AF */  sw         $s0, 0x68($sp)
    /* 5F528 8006ED28 21B88000 */  addu       $s7, $a0, $zero
    /* 5F52C 8006ED2C 2180A000 */  addu       $s0, $a1, $zero
    /* 5F530 8006ED30 3E82030C */  jal        __builtin_new
    /* 5F534 8006ED34 9C020424 */   addiu     $a0, $zero, 0x29C
    /* 5F538 8006ED38 21204000 */  addu       $a0, $v0, $zero
    /* 5F53C 8006ED3C ADC5020C */  jal        func_800B16B4
    /* 5F540 8006ED40 00200524 */   addiu     $a1, $zero, 0x2000
    /* 5F544 8006ED44 21984000 */  addu       $s3, $v0, $zero
    /* 5F548 8006ED48 8000023C */  lui        $v0, (0x800001 >> 16)
    /* 5F54C 8006ED4C 01004234 */  ori        $v0, $v0, (0x800001 & 0xFFFF)
    /* 5F550 8006ED50 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5F554 8006ED54 21206002 */  addu       $a0, $s3, $zero
    /* 5F558 8006ED58 21280000 */  addu       $a1, $zero, $zero
    /* 5F55C 8006ED5C 21300000 */  addu       $a2, $zero, $zero
    /* 5F560 8006ED60 1EC7020C */  jal        func_800B1C78
    /* 5F564 8006ED64 21380000 */   addu      $a3, $zero, $zero
    /* 5F568 8006ED68 FEFFE526 */  addiu      $a1, $s7, -0x2
    /* 5F56C 8006ED6C 002C0500 */  sll        $a1, $a1, 16
    /* 5F570 8006ED70 21206002 */  addu       $a0, $s3, $zero
    /* 5F574 8006ED74 8BE2020C */  jal        func_800B8A2C
    /* 5F578 8006ED78 032C0500 */   sra       $a1, $a1, 16
    /* 5F57C 8006ED7C 0180053C */  lui        $a1, %hi(D_80010AE4)
    /* 5F580 8006ED80 E40AA524 */  addiu      $a1, $a1, %lo(D_80010AE4)
    /* 5F584 8006ED84 1CC8020C */  jal        func_800B2070
    /* 5F588 8006ED88 21206002 */   addu      $a0, $s3, $zero
    /* 5F58C 8006ED8C 21206002 */  addu       $a0, $s3, $zero
    /* 5F590 8006ED90 39C8020C */  jal        func_800B20E4
    /* 5F594 8006ED94 40010524 */   addiu     $a1, $zero, 0x140
    /* 5F598 8006ED98 1280043C */  lui        $a0, %hi(D_80121340)
    /* 5F59C 8006ED9C 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 5F5A0 8006EDA0 0180053C */  lui        $a1, %hi(D_80010B08)
    /* 5F5A4 8006EDA4 080BA524 */  addiu      $a1, $a1, %lo(D_80010B08)
    /* 5F5A8 8006EDA8 E187030C */  jal        sprintf
    /* 5F5AC 8006EDAC 21300002 */   addu      $a2, $s0, $zero
    /* 5F5B0 8006EDB0 1280053C */  lui        $a1, %hi(D_80121340)
    /* 5F5B4 8006EDB4 4013A524 */  addiu      $a1, $a1, %lo(D_80121340)
    /* 5F5B8 8006EDB8 69C7020C */  jal        func_800B1DA4
    /* 5F5BC 8006EDBC 21206002 */   addu      $a0, $s3, $zero
    /* 5F5C0 8006EDC0 0180053C */  lui        $a1, %hi(D_80010B28)
    /* 5F5C4 8006EDC4 280BA524 */  addiu      $a1, $a1, %lo(D_80010B28)
    /* 5F5C8 8006EDC8 69C7020C */  jal        func_800B1DA4
    /* 5F5CC 8006EDCC 21206002 */   addu      $a0, $s3, $zero
    /* 5F5D0 8006EDD0 0180053C */  lui        $a1, %hi(D_80010B48)
    /* 5F5D4 8006EDD4 480BA524 */  addiu      $a1, $a1, %lo(D_80010B48)
    /* 5F5D8 8006EDD8 69C7020C */  jal        func_800B1DA4
    /* 5F5DC 8006EDDC 21206002 */   addu      $a0, $s3, $zero
    /* 5F5E0 8006EDE0 21206002 */  addu       $a0, $s3, $zero
    /* 5F5E4 8006EDE4 1680053C */  lui        $a1, %hi(D_801586F4)
    /* 5F5E8 8006EDE8 F486A524 */  addiu      $a1, $a1, %lo(D_801586F4)
    /* 5F5EC 8006EDEC A8C9020C */  jal        func_800B26A0
    /* 5F5F0 8006EDF0 21300000 */   addu      $a2, $zero, $zero
    /* 5F5F4 8006EDF4 21206002 */  addu       $a0, $s3, $zero
    /* 5F5F8 8006EDF8 1680053C */  lui        $a1, %hi(D_801586F8)
    /* 5F5FC 8006EDFC F886A524 */  addiu      $a1, $a1, %lo(D_801586F8)
    /* 5F600 8006EE00 A8C9020C */  jal        func_800B26A0
    /* 5F604 8006EE04 01000624 */   addiu     $a2, $zero, 0x1
    /* 5F608 8006EE08 21206002 */  addu       $a0, $s3, $zero
    /* 5F60C 8006EE0C 52DF020C */  jal        func_800B7D48
    /* 5F610 8006EE10 21280000 */   addu      $a1, $zero, $zero
    /* 5F614 8006EE14 04006012 */  beqz       $s3, .L8006EE28
    /* 5F618 8006EE18 21884000 */   addu      $s1, $v0, $zero
    /* 5F61C 8006EE1C 21206002 */  addu       $a0, $s3, $zero
    /* 5F620 8006EE20 0AC7020C */  jal        func_800B1C28
    /* 5F624 8006EE24 03000524 */   addiu     $a1, $zero, 0x3
  .L8006EE28:
    /* 5F628 8006EE28 72022006 */  bltz       $s1, .L8006F7F4
    /* 5F62C 8006EE2C FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 5F630 8006EE30 70022012 */  beqz       $s1, .L8006F7F4
    /* 5F634 8006EE34 21100000 */   addu      $v0, $zero, $zero
    /* 5F638 8006EE38 FED4030C */  jal        func_800F53F8
    /* 5F63C 8006EE3C CC080424 */   addiu     $a0, $zero, 0x8CC
    /* 5F640 8006EE40 640282AF */  sw         $v0, %gp_rel(D_8015873C)($gp)
    /* 5F644 8006EE44 7CD6030C */  jal        func_800F59F0
    /* 5F648 8006EE48 21204000 */   addu      $a0, $v0, $zero
    /* 5F64C 8006EE4C 21B04000 */  addu       $s6, $v0, $zero
    /* 5F650 8006EE50 0002D526 */  addiu      $s5, $s6, 0x200
    /* 5F654 8006EE54 3E82030C */  jal        __builtin_new
    /* 5F658 8006EE58 9C020424 */   addiu     $a0, $zero, 0x29C
    /* 5F65C 8006EE5C 21204000 */  addu       $a0, $v0, $zero
    /* 5F660 8006EE60 ADC5020C */  jal        func_800B16B4
    /* 5F664 8006EE64 00200524 */   addiu     $a1, $zero, 0x2000
    /* 5F668 8006EE68 21984000 */  addu       $s3, $v0, $zero
    /* 5F66C 8006EE6C 08000224 */  addiu      $v0, $zero, 0x8
    /* 5F670 8006EE70 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5F674 8006EE74 21206002 */  addu       $a0, $s3, $zero
    /* 5F678 8006EE78 21280000 */  addu       $a1, $zero, $zero
    /* 5F67C 8006EE7C 21300000 */  addu       $a2, $zero, $zero
    /* 5F680 8006EE80 1EC7020C */  jal        func_800B1C78
    /* 5F684 8006EE84 21380000 */   addu      $a3, $zero, $zero
    /* 5F688 8006EE88 21206002 */  addu       $a0, $s3, $zero
    /* 5F68C 8006EE8C F8FF0524 */  addiu      $a1, $zero, -0x8
    /* 5F690 8006EE90 5AC8020C */  jal        func_800B2168
    /* 5F694 8006EE94 F8FF0624 */   addiu     $a2, $zero, -0x8
    /* 5F698 8006EE98 0180053C */  lui        $a1, %hi(D_80010B60)
    /* 5F69C 8006EE9C 600BA524 */  addiu      $a1, $a1, %lo(D_80010B60)
    /* 5F6A0 8006EEA0 1CC8020C */  jal        func_800B2070
    /* 5F6A4 8006EEA4 21206002 */   addu      $a0, $s3, $zero
    /* 5F6A8 8006EEA8 21206002 */  addu       $a0, $s3, $zero
    /* 5F6AC 8006EEAC 39C8020C */  jal        func_800B20E4
    /* 5F6B0 8006EEB0 00010524 */   addiu     $a1, $zero, 0x100
    /* 5F6B4 8006EEB4 1680053C */  lui        $a1, %hi(D_801586C0)
    /* 5F6B8 8006EEB8 C086A524 */  addiu      $a1, $a1, %lo(D_801586C0)
    /* 5F6BC 8006EEBC 69C7020C */  jal        func_800B1DA4
    /* 5F6C0 8006EEC0 21206002 */   addu      $a0, $s3, $zero
    /* 5F6C4 8006EEC4 0180053C */  lui        $a1, %hi(D_8001093C)
    /* 5F6C8 8006EEC8 3C09A524 */  addiu      $a1, $a1, %lo(D_8001093C)
    /* 5F6CC 8006EECC 69C7020C */  jal        func_800B1DA4
    /* 5F6D0 8006EED0 21206002 */   addu      $a0, $s3, $zero
    /* 5F6D4 8006EED4 0180053C */  lui        $a1, %hi(D_800108F4)
    /* 5F6D8 8006EED8 F408A524 */  addiu      $a1, $a1, %lo(D_800108F4)
    /* 5F6DC 8006EEDC 69C7020C */  jal        func_800B1DA4
    /* 5F6E0 8006EEE0 21206002 */   addu      $a0, $s3, $zero
    /* 5F6E4 8006EEE4 1680053C */  lui        $a1, %hi(D_801586C0)
    /* 5F6E8 8006EEE8 C086A524 */  addiu      $a1, $a1, %lo(D_801586C0)
    /* 5F6EC 8006EEEC 69C7020C */  jal        func_800B1DA4
    /* 5F6F0 8006EEF0 21206002 */   addu      $a0, $s3, $zero
    /* 5F6F4 8006EEF4 21206002 */  addu       $a0, $s3, $zero
    /* 5F6F8 8006EEF8 52DF020C */  jal        func_800B7D48
    /* 5F6FC 8006EEFC 21280000 */   addu      $a1, $zero, $zero
    /* 5F700 8006EF00 94E2020C */  jal        func_800B8A50
    /* 5F704 8006EF04 21206002 */   addu      $a0, $s3, $zero
    /* 5F708 8006EF08 8E12040C */  jal        func_80104A38
    /* 5F70C 8006EF0C 00000000 */   nop
    /* 5F710 8006EF10 2120E002 */  addu       $a0, $s7, $zero
    /* 5F714 8006EF14 0ABE010C */  jal        func_8006F828
    /* 5F718 8006EF18 01000524 */   addiu     $a1, $zero, 0x1
    /* 5F71C 8006EF1C 00140200 */  sll        $v0, $v0, 16
    /* 5F720 8006EF20 2C024104 */  bgez       $v0, .L8006F7D4
    /* 5F724 8006EF24 00000000 */   nop
    /* 5F728 8006EF28 7B22040C */  jal        func_801089EC
    /* 5F72C 8006EF2C 21800000 */   addu      $s0, $zero, $zero
    /* 5F730 8006EF30 00140200 */  sll        $v0, $v0, 16
    /* 5F734 8006EF34 03F40200 */  sra        $fp, $v0, 16
    /* 5F738 8006EF38 8822040C */  jal        func_80108A20
    /* 5F73C 8006EF3C 2120C003 */   addu      $a0, $fp, $zero
    /* 5F740 8006EF40 1280043C */  lui        $a0, %hi(D_80121340)
    /* 5F744 8006EF44 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 5F748 8006EF48 1680053C */  lui        $a1, %hi(D_801586FC)
    /* 5F74C 8006EF4C FC86A524 */  addiu      $a1, $a1, %lo(D_801586FC)
    /* 5F750 8006EF50 E187030C */  jal        sprintf
    /* 5F754 8006EF54 2130E002 */   addu      $a2, $s7, $zero
  .L8006EF58:
    /* 5F758 8006EF58 1280043C */  lui        $a0, %hi(D_80121340)
    /* 5F75C 8006EF5C 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 5F760 8006EF60 858A030C */  jal        firstfile
    /* 5F764 8006EF64 2000A527 */   addiu     $a1, $sp, 0x20
    /* 5F768 8006EF68 21184000 */  addu       $v1, $v0, $zero
    /* 5F76C 8006EF6C 07006014 */  bnez       $v1, .L8006EF8C
    /* 5F770 8006EF70 00000000 */   nop
    /* 5F774 8006EF74 01001026 */  addiu      $s0, $s0, 0x1
    /* 5F778 8006EF78 1400022A */  slti       $v0, $s0, 0x14
    /* 5F77C 8006EF7C F6FF4014 */  bnez       $v0, .L8006EF58
    /* 5F780 8006EF80 00000000 */   nop
    /* 5F784 8006EF84 11026010 */  beqz       $v1, .L8006F7CC
    /* 5F788 8006EF88 00000000 */   nop
  .L8006EF8C:
    /* 5F78C 8006EF8C 41006010 */  beqz       $v1, .L8006F094
    /* 5F790 8006EF90 21A00000 */   addu      $s4, $zero, $zero
  .L8006EF94:
    /* 5F794 8006EF94 C0201400 */  sll        $a0, $s4, 3
    /* 5F798 8006EF98 23209400 */  subu       $a0, $a0, $s4
    /* 5F79C 8006EF9C 80200400 */  sll        $a0, $a0, 2
    /* 5F7A0 8006EFA0 21209400 */  addu       $a0, $a0, $s4
    /* 5F7A4 8006EFA4 80200400 */  sll        $a0, $a0, 2
    /* 5F7A8 8006EFA8 2120A402 */  addu       $a0, $s5, $a0
    /* 5F7AC 8006EFAC 1680053C */  lui        $a1, %hi(D_801586EC)
    /* 5F7B0 8006EFB0 EC86A524 */  addiu      $a1, $a1, %lo(D_801586EC)
    /* 5F7B4 8006EFB4 E187030C */  jal        sprintf
    /* 5F7B8 8006EFB8 2130E002 */   addu      $a2, $s7, $zero
    /* 5F7BC 8006EFBC 21800000 */  addu       $s0, $zero, $zero
    /* 5F7C0 8006EFC0 2000A293 */  lbu        $v0, 0x20($sp)
    /* 5F7C4 8006EFC4 00000000 */  nop
    /* 5F7C8 8006EFC8 16004010 */  beqz       $v0, .L8006F024
    /* 5F7CC 8006EFCC 2000A527 */   addiu     $a1, $sp, 0x20
    /* 5F7D0 8006EFD0 C0101400 */  sll        $v0, $s4, 3
    /* 5F7D4 8006EFD4 23105400 */  subu       $v0, $v0, $s4
    /* 5F7D8 8006EFD8 80100200 */  sll        $v0, $v0, 2
    /* 5F7DC 8006EFDC 21105400 */  addu       $v0, $v0, $s4
    /* 5F7E0 8006EFE0 80100200 */  sll        $v0, $v0, 2
    /* 5F7E4 8006EFE4 21305500 */  addu       $a2, $v0, $s5
    /* 5F7E8 8006EFE8 2120D000 */  addu       $a0, $a2, $s0
  .L8006EFEC:
    /* 5F7EC 8006EFEC 2118A000 */  addu       $v1, $a1, $zero
    /* 5F7F0 8006EFF0 21107000 */  addu       $v0, $v1, $s0
    /* 5F7F4 8006EFF4 00004290 */  lbu        $v0, 0x0($v0)
    /* 5F7F8 8006EFF8 00000000 */  nop
    /* 5F7FC 8006EFFC 050082A0 */  sb         $v0, 0x5($a0)
    /* 5F800 8006F000 01001026 */  addiu      $s0, $s0, 0x1
    /* 5F804 8006F004 21187000 */  addu       $v1, $v1, $s0
    /* 5F808 8006F008 00006290 */  lbu        $v0, 0x0($v1)
    /* 5F80C 8006F00C 00000000 */  nop
    /* 5F810 8006F010 2B100200 */  sltu       $v0, $zero, $v0
    /* 5F814 8006F014 1400032A */  slti       $v1, $s0, 0x14
    /* 5F818 8006F018 24104300 */  and        $v0, $v0, $v1
    /* 5F81C 8006F01C F3FF4014 */  bnez       $v0, .L8006EFEC
    /* 5F820 8006F020 2120D000 */   addu      $a0, $a2, $s0
  .L8006F024:
    /* 5F824 8006F024 C0101400 */  sll        $v0, $s4, 3
    /* 5F828 8006F028 23105400 */  subu       $v0, $v0, $s4
    /* 5F82C 8006F02C 80100200 */  sll        $v0, $v0, 2
    /* 5F830 8006F030 21105400 */  addu       $v0, $v0, $s4
    /* 5F834 8006F034 80100200 */  sll        $v0, $v0, 2
    /* 5F838 8006F038 21105500 */  addu       $v0, $v0, $s5
    /* 5F83C 8006F03C 21185000 */  addu       $v1, $v0, $s0
    /* 5F840 8006F040 050060A0 */  sb         $zero, 0x5($v1)
    /* 5F844 8006F044 21184000 */  addu       $v1, $v0, $zero
    /* 5F848 8006F048 3800A28F */  lw         $v0, 0x38($sp)
    /* 5F84C 8006F04C 00000000 */  nop
    /* 5F850 8006F050 02004104 */  bgez       $v0, .L8006F05C
    /* 5F854 8006F054 00000000 */   nop
    /* 5F858 8006F058 FF1F4224 */  addiu      $v0, $v0, 0x1FFF
  .L8006F05C:
    /* 5F85C 8006F05C 43130200 */  sra        $v0, $v0, 13
    /* 5F860 8006F060 640062A4 */  sh         $v0, 0x64($v1)
    /* 5F864 8006F064 01009426 */  addiu      $s4, $s4, 0x1
    /* 5F868 8006F068 21800000 */  addu       $s0, $zero, $zero
  .L8006F06C:
    /* 5F86C 8006F06C 758A030C */  jal        func_800E29D4
    /* 5F870 8006F070 2000A427 */   addiu     $a0, $sp, 0x20
    /* 5F874 8006F074 21184000 */  addu       $v1, $v0, $zero
    /* 5F878 8006F078 C6FF6014 */  bnez       $v1, .L8006EF94
    /* 5F87C 8006F07C 01001026 */   addiu     $s0, $s0, 0x1
    /* 5F880 8006F080 1400022A */  slti       $v0, $s0, 0x14
    /* 5F884 8006F084 F9FF4014 */  bnez       $v0, .L8006F06C
    /* 5F888 8006F088 00000000 */   nop
    /* 5F88C 8006F08C C1FF6014 */  bnez       $v1, .L8006EF94
    /* 5F890 8006F090 00000000 */   nop
  .L8006F094:
    /* 5F894 8006F094 21800000 */  addu       $s0, $zero, $zero
  .L8006F098:
    /* 5F898 8006F098 2A101402 */  slt        $v0, $s0, $s4
    /* 5F89C 8006F09C A5004010 */  beqz       $v0, .L8006F334
    /* 5F8A0 8006F0A0 0F001124 */   addiu     $s1, $zero, 0xF
    /* 5F8A4 8006F0A4 0180043C */  lui        $a0, %hi(D_80010B7C)
    /* 5F8A8 8006F0A8 7C0B8424 */  addiu      $a0, $a0, %lo(D_80010B7C)
    /* 5F8AC 8006F0AC 4551000C */  jal        func_80014514
    /* 5F8B0 8006F0B0 21288002 */   addu      $a1, $s4, $zero
    /* 5F8B4 8006F0B4 C0101000 */  sll        $v0, $s0, 3
    /* 5F8B8 8006F0B8 23105000 */  subu       $v0, $v0, $s0
    /* 5F8BC 8006F0BC 80100200 */  sll        $v0, $v0, 2
    /* 5F8C0 8006F0C0 21105000 */  addu       $v0, $v0, $s0
    /* 5F8C4 8006F0C4 80100200 */  sll        $v0, $v0, 2
    /* 5F8C8 8006F0C8 2188A202 */  addu       $s1, $s5, $v0
    /* 5F8CC 8006F0CC 21202002 */  addu       $a0, $s1, $zero
    /* 5F8D0 8006F0D0 27C1010C */  jal        func_8007049C
    /* 5F8D4 8006F0D4 2128C002 */   addu      $a1, $s6, $zero
    /* 5F8D8 8006F0D8 00140200 */  sll        $v0, $v0, 16
    /* 5F8DC 8006F0DC 03140200 */  sra        $v0, $v0, 16
    /* 5F8E0 8006F0E0 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 5F8E4 8006F0E4 19004314 */  bne        $v0, $v1, .L8006F14C
    /* 5F8E8 8006F0E8 2120C002 */   addu      $a0, $s6, $zero
    /* 5F8EC 8006F0EC 0180053C */  lui        $a1, %hi(D_80010B88)
    /* 5F8F0 8006F0F0 880BA524 */  addiu      $a1, $a1, %lo(D_80010B88)
    /* 5F8F4 8006F0F4 0300A288 */  lwl        $v0, 0x3($a1)
    /* 5F8F8 8006F0F8 0000A298 */  lwr        $v0, 0x0($a1)
    /* 5F8FC 8006F0FC 0700A388 */  lwl        $v1, 0x7($a1)
    /* 5F900 8006F100 0400A398 */  lwr        $v1, 0x4($a1)
    /* 5F904 8006F104 0B00A488 */  lwl        $a0, 0xB($a1)
    /* 5F908 8006F108 0800A498 */  lwr        $a0, 0x8($a1)
    /* 5F90C 8006F10C 210022AA */  swl        $v0, 0x21($s1)
    /* 5F910 8006F110 1E0022BA */  swr        $v0, 0x1E($s1)
    /* 5F914 8006F114 250023AA */  swl        $v1, 0x25($s1)
    /* 5F918 8006F118 220023BA */  swr        $v1, 0x22($s1)
    /* 5F91C 8006F11C 290024AA */  swl        $a0, 0x29($s1)
    /* 5F920 8006F120 260024BA */  swr        $a0, 0x26($s1)
    /* 5F924 8006F124 0F00A288 */  lwl        $v0, 0xF($a1)
    /* 5F928 8006F128 0C00A298 */  lwr        $v0, 0xC($a1)
    /* 5F92C 8006F12C 1300A388 */  lwl        $v1, 0x13($a1)
    /* 5F930 8006F130 1000A398 */  lwr        $v1, 0x10($a1)
    /* 5F934 8006F134 2D0022AA */  swl        $v0, 0x2D($s1)
    /* 5F938 8006F138 2A0022BA */  swr        $v0, 0x2A($s1)
    /* 5F93C 8006F13C 310023AA */  swl        $v1, 0x31($s1)
    /* 5F940 8006F140 2E0023BA */  swr        $v1, 0x2E($s1)
    /* 5F944 8006F144 CABC0108 */  j          .L8006F328
    /* 5F948 8006F148 520020A2 */   sb        $zero, 0x52($s1)
  .L8006F14C:
    /* 5F94C 8006F14C 0400D126 */  addiu      $s1, $s6, 0x4
    /* 5F950 8006F150 04000524 */  addiu      $a1, $zero, 0x4
    /* 5F954 8006F154 3F51000C */  jal        func_800144FC
    /* 5F958 8006F158 01000624 */   addiu     $a2, $zero, 0x1
    /* 5F95C 8006F15C 0400C292 */  lbu        $v0, 0x4($s6)
    /* 5F960 8006F160 00000000 */  nop
    /* 5F964 8006F164 2A004010 */  beqz       $v0, .L8006F210
    /* 5F968 8006F168 21900000 */   addu      $s2, $zero, $zero
    /* 5F96C 8006F16C C0101000 */  sll        $v0, $s0, 3
    /* 5F970 8006F170 23105000 */  subu       $v0, $v0, $s0
    /* 5F974 8006F174 80100200 */  sll        $v0, $v0, 2
    /* 5F978 8006F178 21105000 */  addu       $v0, $v0, $s0
    /* 5F97C 8006F17C 80100200 */  sll        $v0, $v0, 2
    /* 5F980 8006F180 21285500 */  addu       $a1, $v0, $s5
    /* 5F984 8006F184 C0101000 */  sll        $v0, $s0, 3
    /* 5F988 8006F188 23105000 */  subu       $v0, $v0, $s0
    /* 5F98C 8006F18C 80100200 */  sll        $v0, $v0, 2
    /* 5F990 8006F190 21105000 */  addu       $v0, $v0, $s0
    /* 5F994 8006F194 80100200 */  sll        $v0, $v0, 2
    /* 5F998 8006F198 21305500 */  addu       $a2, $v0, $s5
  .L8006F19C:
    /* 5F99C 8006F19C 3100422A */  slti       $v0, $s2, 0x31
    /* 5F9A0 8006F1A0 1C004010 */  beqz       $v0, .L8006F214
    /* 5F9A4 8006F1A4 C0101000 */   sll       $v0, $s0, 3
    /* 5F9A8 8006F1A8 00002492 */  lbu        $a0, 0x0($s1)
    /* 5F9AC 8006F1AC 00000000 */  nop
    /* 5F9B0 8006F1B0 80008324 */  addiu      $v1, $a0, 0x80
    /* 5F9B4 8006F1B4 FF006330 */  andi       $v1, $v1, 0xFF
    /* 5F9B8 8006F1B8 2000632C */  sltiu      $v1, $v1, 0x20
    /* 5F9BC 8006F1BC 00002292 */  lbu        $v0, 0x0($s1)
    /* 5F9C0 8006F1C0 00000000 */  nop
    /* 5F9C4 8006F1C4 E000422C */  sltiu      $v0, $v0, 0xE0
    /* 5F9C8 8006F1C8 01004238 */  xori       $v0, $v0, 0x1
    /* 5F9CC 8006F1CC 25186200 */  or         $v1, $v1, $v0
    /* 5F9D0 8006F1D0 06006010 */  beqz       $v1, .L8006F1EC
    /* 5F9D4 8006F1D4 2110B200 */   addu      $v0, $a1, $s2
    /* 5F9D8 8006F1D8 1E0044A0 */  sb         $a0, 0x1E($v0)
    /* 5F9DC 8006F1DC 01003126 */  addiu      $s1, $s1, 0x1
    /* 5F9E0 8006F1E0 01005226 */  addiu      $s2, $s2, 0x1
    /* 5F9E4 8006F1E4 7CBC0108 */  j          .L8006F1F0
    /* 5F9E8 8006F1E8 2118B200 */   addu      $v1, $a1, $s2
  .L8006F1EC:
    /* 5F9EC 8006F1EC 2118D200 */  addu       $v1, $a2, $s2
  .L8006F1F0:
    /* 5F9F0 8006F1F0 00002292 */  lbu        $v0, 0x0($s1)
    /* 5F9F4 8006F1F4 00000000 */  nop
    /* 5F9F8 8006F1F8 1E0062A0 */  sb         $v0, 0x1E($v1)
    /* 5F9FC 8006F1FC 01003126 */  addiu      $s1, $s1, 0x1
    /* 5FA00 8006F200 00002292 */  lbu        $v0, 0x0($s1)
    /* 5FA04 8006F204 00000000 */  nop
    /* 5FA08 8006F208 E4FF4014 */  bnez       $v0, .L8006F19C
    /* 5FA0C 8006F20C 01005226 */   addiu     $s2, $s2, 0x1
  .L8006F210:
    /* 5FA10 8006F210 C0101000 */  sll        $v0, $s0, 3
  .L8006F214:
    /* 5FA14 8006F214 23105000 */  subu       $v0, $v0, $s0
    /* 5FA18 8006F218 80100200 */  sll        $v0, $v0, 2
    /* 5FA1C 8006F21C 21105000 */  addu       $v0, $v0, $s0
    /* 5FA20 8006F220 80100200 */  sll        $v0, $v0, 2
    /* 5FA24 8006F224 21285500 */  addu       $a1, $v0, $s5
    /* 5FA28 8006F228 2110B200 */  addu       $v0, $a1, $s2
    /* 5FA2C 8006F22C 1E0040A0 */  sb         $zero, 0x1E($v0)
    /* 5FA30 8006F230 00002292 */  lbu        $v0, 0x0($s1)
    /* 5FA34 8006F234 00000000 */  nop
    /* 5FA38 8006F238 06004010 */  beqz       $v0, .L8006F254
    /* 5FA3C 8006F23C 21202002 */   addu      $a0, $s1, $zero
    /* 5FA40 8006F240 5200A524 */  addiu      $a1, $a1, 0x52
    /* 5FA44 8006F244 C187030C */  jal        func_800E1F04
    /* 5FA48 8006F248 12000624 */   addiu     $a2, $zero, 0x12
    /* 5FA4C 8006F24C 9DBC0108 */  j          .L8006F274
    /* 5FA50 8006F250 C0101000 */   sll       $v0, $s0, 3
  .L8006F254:
    /* 5FA54 8006F254 C0101000 */  sll        $v0, $s0, 3
    /* 5FA58 8006F258 23105000 */  subu       $v0, $v0, $s0
    /* 5FA5C 8006F25C 80100200 */  sll        $v0, $v0, 2
    /* 5FA60 8006F260 21105000 */  addu       $v0, $v0, $s0
    /* 5FA64 8006F264 80100200 */  sll        $v0, $v0, 2
    /* 5FA68 8006F268 21105500 */  addu       $v0, $v0, $s5
    /* 5FA6C 8006F26C 520040A0 */  sb         $zero, 0x52($v0)
    /* 5FA70 8006F270 C0101000 */  sll        $v0, $s0, 3
  .L8006F274:
    /* 5FA74 8006F274 23105000 */  subu       $v0, $v0, $s0
    /* 5FA78 8006F278 80100200 */  sll        $v0, $v0, 2
    /* 5FA7C 8006F27C 21105000 */  addu       $v0, $v0, $s0
    /* 5FA80 8006F280 80100200 */  sll        $v0, $v0, 2
    /* 5FA84 8006F284 21105500 */  addu       $v0, $v0, $s5
    /* 5FA88 8006F288 0200C392 */  lbu        $v1, 0x2($s6)
    /* 5FA8C 8006F28C 00000000 */  nop
    /* 5FA90 8006F290 03006330 */  andi       $v1, $v1, 0x3
    /* 5FA94 8006F294 FF006330 */  andi       $v1, $v1, 0xFF
    /* 5FA98 8006F298 660043A4 */  sh         $v1, 0x66($v0)
    /* 5FA9C 8006F29C 22006010 */  beqz       $v1, .L8006F328
    /* 5FAA0 8006F2A0 21900000 */   addu      $s2, $zero, $zero
    /* 5FAA4 8006F2A4 C0101000 */  sll        $v0, $s0, 3
    /* 5FAA8 8006F2A8 23105000 */  subu       $v0, $v0, $s0
    /* 5FAAC 8006F2AC 80100200 */  sll        $v0, $v0, 2
    /* 5FAB0 8006F2B0 21105000 */  addu       $v0, $v0, $s0
    /* 5FAB4 8006F2B4 80100200 */  sll        $v0, $v0, 2
    /* 5FAB8 8006F2B8 21885500 */  addu       $s1, $v0, $s5
  .L8006F2BC:
    /* 5FABC 8006F2BC 3E82030C */  jal        __builtin_new
    /* 5FAC0 8006F2C0 94000424 */   addiu     $a0, $zero, 0x94
    /* 5FAC4 8006F2C4 FCEC030C */  jal        func_800FB3F0
    /* 5FAC8 8006F2C8 21204000 */   addu      $a0, $v0, $zero
    /* 5FACC 8006F2CC 80181200 */  sll        $v1, $s2, 2
    /* 5FAD0 8006F2D0 21187100 */  addu       $v1, $v1, $s1
    /* 5FAD4 8006F2D4 680062AC */  sw         $v0, 0x68($v1)
    /* 5FAD8 8006F2D8 002D1000 */  sll        $a1, $s0, 20
    /* 5FADC 8006F2DC 10000224 */  addiu      $v0, $zero, 0x10
    /* 5FAE0 8006F2E0 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5FAE4 8006F2E4 C0111200 */  sll        $v0, $s2, 7
    /* 5FAE8 8006F2E8 80004224 */  addiu      $v0, $v0, 0x80
    /* 5FAEC 8006F2EC 2110C202 */  addu       $v0, $s6, $v0
    /* 5FAF0 8006F2F0 1400A2AF */  sw         $v0, 0x14($sp)
    /* 5FAF4 8006F2F4 6000C226 */  addiu      $v0, $s6, 0x60
    /* 5FAF8 8006F2F8 1800A2AF */  sw         $v0, 0x18($sp)
    /* 5FAFC 8006F2FC 6800648C */  lw         $a0, 0x68($v1)
    /* 5FB00 8006F300 032C0500 */  sra        $a1, $a1, 16
    /* 5FB04 8006F304 2130C003 */  addu       $a2, $fp, $zero
    /* 5FB08 8006F308 90ED030C */  jal        func_800FB640
    /* 5FB0C 8006F30C 04000724 */   addiu     $a3, $zero, 0x4
    /* 5FB10 8006F310 01005226 */  addiu      $s2, $s2, 0x1
    /* 5FB14 8006F314 66002286 */  lh         $v0, 0x66($s1)
    /* 5FB18 8006F318 00000000 */  nop
    /* 5FB1C 8006F31C 2A104202 */  slt        $v0, $s2, $v0
    /* 5FB20 8006F320 E6FF4014 */  bnez       $v0, .L8006F2BC
    /* 5FB24 8006F324 00000000 */   nop
  .L8006F328:
    /* 5FB28 8006F328 26BC0108 */  j          .L8006F098
    /* 5FB2C 8006F32C 01001026 */   addiu     $s0, $s0, 0x1
  .L8006F330:
    /* 5FB30 8006F330 0F001124 */  addiu      $s1, $zero, 0xF
  .L8006F334:
    /* 5FB34 8006F334 0E00801A */  blez       $s4, .L8006F370
    /* 5FB38 8006F338 21800000 */   addu      $s0, $zero, $zero
    /* 5FB3C 8006F33C C0101000 */  sll        $v0, $s0, 3
  .L8006F340:
    /* 5FB40 8006F340 23105000 */  subu       $v0, $v0, $s0
    /* 5FB44 8006F344 80100200 */  sll        $v0, $v0, 2
    /* 5FB48 8006F348 21105000 */  addu       $v0, $v0, $s0
    /* 5FB4C 8006F34C 80100200 */  sll        $v0, $v0, 2
    /* 5FB50 8006F350 21105500 */  addu       $v0, $v0, $s5
    /* 5FB54 8006F354 64004284 */  lh         $v0, 0x64($v0)
    /* 5FB58 8006F358 00000000 */  nop
    /* 5FB5C 8006F35C 23882202 */  subu       $s1, $s1, $v0
    /* 5FB60 8006F360 01001026 */  addiu      $s0, $s0, 0x1
    /* 5FB64 8006F364 2A101402 */  slt        $v0, $s0, $s4
    /* 5FB68 8006F368 F5FF4014 */  bnez       $v0, .L8006F340
    /* 5FB6C 8006F36C C0101000 */   sll       $v0, $s0, 3
  .L8006F370:
    /* 5FB70 8006F370 0F00222A */  slti       $v0, $s1, 0xF
    /* 5FB74 8006F374 EC004010 */  beqz       $v0, .L8006F728
    /* 5FB78 8006F378 00000000 */   nop
    /* 5FB7C 8006F37C 04006012 */  beqz       $s3, .L8006F390
    /* 5FB80 8006F380 00000000 */   nop
    /* 5FB84 8006F384 21206002 */  addu       $a0, $s3, $zero
    /* 5FB88 8006F388 0AC7020C */  jal        func_800B1C28
    /* 5FB8C 8006F38C 03000524 */   addiu     $a1, $zero, 0x3
  .L8006F390:
    /* 5FB90 8006F390 3E82030C */  jal        __builtin_new
    /* 5FB94 8006F394 9C020424 */   addiu     $a0, $zero, 0x29C
    /* 5FB98 8006F398 21204000 */  addu       $a0, $v0, $zero
    /* 5FB9C 8006F39C ADC5020C */  jal        func_800B16B4
    /* 5FBA0 8006F3A0 00200524 */   addiu     $a1, $zero, 0x2000
    /* 5FBA4 8006F3A4 21984000 */  addu       $s3, $v0, $zero
    /* 5FBA8 8006F3A8 8000023C */  lui        $v0, (0x800001 >> 16)
    /* 5FBAC 8006F3AC 01004234 */  ori        $v0, $v0, (0x800001 & 0xFFFF)
    /* 5FBB0 8006F3B0 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5FBB4 8006F3B4 21206002 */  addu       $a0, $s3, $zero
    /* 5FBB8 8006F3B8 21280000 */  addu       $a1, $zero, $zero
    /* 5FBBC 8006F3BC 21300000 */  addu       $a2, $zero, $zero
    /* 5FBC0 8006F3C0 1EC7020C */  jal        func_800B1C78
    /* 5FBC4 8006F3C4 21380000 */   addu      $a3, $zero, $zero
    /* 5FBC8 8006F3C8 FEFFE526 */  addiu      $a1, $s7, -0x2
    /* 5FBCC 8006F3CC 002C0500 */  sll        $a1, $a1, 16
    /* 5FBD0 8006F3D0 21206002 */  addu       $a0, $s3, $zero
    /* 5FBD4 8006F3D4 8BE2020C */  jal        func_800B8A2C
    /* 5FBD8 8006F3D8 032C0500 */   sra       $a1, $a1, 16
    /* 5FBDC 8006F3DC 1C000224 */  addiu      $v0, $zero, 0x1C
    /* 5FBE0 8006F3E0 580162AE */  sw         $v0, 0x158($s3)
    /* 5FBE4 8006F3E4 21206002 */  addu       $a0, $s3, $zero
    /* 5FBE8 8006F3E8 05000524 */  addiu      $a1, $zero, 0x5
    /* 5FBEC 8006F3EC F5C7020C */  jal        func_800B1FD4
    /* 5FBF0 8006F3F0 2C010624 */   addiu     $a2, $zero, 0x12C
    /* 5FBF4 8006F3F4 1280043C */  lui        $a0, %hi(D_80121340)
    /* 5FBF8 8006F3F8 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 5FBFC 8006F3FC 0180053C */  lui        $a1, %hi(D_80010B9C)
    /* 5FC00 8006F400 9C0BA524 */  addiu      $a1, $a1, %lo(D_80010B9C)
    /* 5FC04 8006F404 0100E626 */  addiu      $a2, $s7, 0x1
    /* 5FC08 8006F408 E187030C */  jal        sprintf
    /* 5FC0C 8006F40C 21382002 */   addu      $a3, $s1, $zero
    /* 5FC10 8006F410 0780053C */  lui        $a1, %hi(func_8006EC14)
    /* 5FC14 8006F414 14ECA524 */  addiu      $a1, $a1, %lo(func_8006EC14)
    /* 5FC18 8006F418 37C9020C */  jal        func_800B24DC
    /* 5FC1C 8006F41C 21206002 */   addu      $a0, $s3, $zero
    /* 5FC20 8006F420 1280053C */  lui        $a1, %hi(D_80121340)
    /* 5FC24 8006F424 4013A524 */  addiu      $a1, $a1, %lo(D_80121340)
    /* 5FC28 8006F428 1CC8020C */  jal        func_800B2070
    /* 5FC2C 8006F42C 21206002 */   addu      $a0, $s3, $zero
    /* 5FC30 8006F430 21206002 */  addu       $a0, $s3, $zero
    /* 5FC34 8006F434 39C8020C */  jal        func_800B20E4
    /* 5FC38 8006F438 90020524 */   addiu     $a1, $zero, 0x290
    /* 5FC3C 8006F43C 1B00801A */  blez       $s4, .L8006F4AC
    /* 5FC40 8006F440 21800000 */   addu      $s0, $zero, $zero
    /* 5FC44 8006F444 1280113C */  lui        $s1, %hi(D_80121340)
    /* 5FC48 8006F448 40133126 */  addiu      $s1, $s1, %lo(D_80121340)
    /* 5FC4C 8006F44C C0101000 */  sll        $v0, $s0, 3
  .L8006F450:
    /* 5FC50 8006F450 23105000 */  subu       $v0, $v0, $s0
    /* 5FC54 8006F454 80100200 */  sll        $v0, $v0, 2
    /* 5FC58 8006F458 21105000 */  addu       $v0, $v0, $s0
    /* 5FC5C 8006F45C 80100200 */  sll        $v0, $v0, 2
    /* 5FC60 8006F460 21105500 */  addu       $v0, $v0, $s5
    /* 5FC64 8006F464 64004384 */  lh         $v1, 0x64($v0)
    /* 5FC68 8006F468 00000000 */  nop
    /* 5FC6C 8006F46C 0B006018 */  blez       $v1, .L8006F49C
    /* 5FC70 8006F470 21202002 */   addu      $a0, $s1, $zero
    /* 5FC74 8006F474 1000A3AF */  sw         $v1, 0x10($sp)
    /* 5FC78 8006F478 0180053C */  lui        $a1, %hi(D_80010BD0)
    /* 5FC7C 8006F47C D00BA524 */  addiu      $a1, $a1, %lo(D_80010BD0)
    /* 5FC80 8006F480 1E004624 */  addiu      $a2, $v0, 0x1E
    /* 5FC84 8006F484 E187030C */  jal        sprintf
    /* 5FC88 8006F488 52004724 */   addiu     $a3, $v0, 0x52
    /* 5FC8C 8006F48C 21206002 */  addu       $a0, $s3, $zero
    /* 5FC90 8006F490 21282002 */  addu       $a1, $s1, $zero
    /* 5FC94 8006F494 A8C9020C */  jal        func_800B26A0
    /* 5FC98 8006F498 21300002 */   addu      $a2, $s0, $zero
  .L8006F49C:
    /* 5FC9C 8006F49C 01001026 */  addiu      $s0, $s0, 0x1
    /* 5FCA0 8006F4A0 2A101402 */  slt        $v0, $s0, $s4
    /* 5FCA4 8006F4A4 EAFF4014 */  bnez       $v0, .L8006F450
    /* 5FCA8 8006F4A8 C0101000 */   sll       $v0, $s0, 3
  .L8006F4AC:
    /* 5FCAC 8006F4AC 21206002 */  addu       $a0, $s3, $zero
    /* 5FCB0 8006F4B0 52DF020C */  jal        func_800B7D48
    /* 5FCB4 8006F4B4 21280000 */   addu      $a1, $zero, $zero
    /* 5FCB8 8006F4B8 21884000 */  addu       $s1, $v0, $zero
    /* 5FCBC 8006F4BC 9A002006 */  bltz       $s1, .L8006F728
    /* 5FCC0 8006F4C0 00000000 */   nop
    /* 5FCC4 8006F4C4 04006012 */  beqz       $s3, .L8006F4D8
    /* 5FCC8 8006F4C8 00000000 */   nop
    /* 5FCCC 8006F4CC 21206002 */  addu       $a0, $s3, $zero
    /* 5FCD0 8006F4D0 0AC7020C */  jal        func_800B1C28
    /* 5FCD4 8006F4D4 03000524 */   addiu     $a1, $zero, 0x3
  .L8006F4D8:
    /* 5FCD8 8006F4D8 3E82030C */  jal        __builtin_new
    /* 5FCDC 8006F4DC 9C020424 */   addiu     $a0, $zero, 0x29C
    /* 5FCE0 8006F4E0 21204000 */  addu       $a0, $v0, $zero
    /* 5FCE4 8006F4E4 ADC5020C */  jal        func_800B16B4
    /* 5FCE8 8006F4E8 00200524 */   addiu     $a1, $zero, 0x2000
    /* 5FCEC 8006F4EC 21984000 */  addu       $s3, $v0, $zero
    /* 5FCF0 8006F4F0 8000023C */  lui        $v0, (0x800001 >> 16)
    /* 5FCF4 8006F4F4 01004234 */  ori        $v0, $v0, (0x800001 & 0xFFFF)
    /* 5FCF8 8006F4F8 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5FCFC 8006F4FC 21206002 */  addu       $a0, $s3, $zero
    /* 5FD00 8006F500 21280000 */  addu       $a1, $zero, $zero
    /* 5FD04 8006F504 21300000 */  addu       $a2, $zero, $zero
    /* 5FD08 8006F508 1EC7020C */  jal        func_800B1C78
    /* 5FD0C 8006F50C 21380000 */   addu      $a3, $zero, $zero
    /* 5FD10 8006F510 FEFFE526 */  addiu      $a1, $s7, -0x2
    /* 5FD14 8006F514 002C0500 */  sll        $a1, $a1, 16
    /* 5FD18 8006F518 21206002 */  addu       $a0, $s3, $zero
    /* 5FD1C 8006F51C 8BE2020C */  jal        func_800B8A2C
    /* 5FD20 8006F520 032C0500 */   sra       $a1, $a1, 16
    /* 5FD24 8006F524 0180053C */  lui        $a1, %hi(D_80010BE4)
    /* 5FD28 8006F528 E40BA524 */  addiu      $a1, $a1, %lo(D_80010BE4)
    /* 5FD2C 8006F52C 1CC8020C */  jal        func_800B2070
    /* 5FD30 8006F530 21206002 */   addu      $a0, $s3, $zero
    /* 5FD34 8006F534 C0801100 */  sll        $s0, $s1, 3
    /* 5FD38 8006F538 23801102 */  subu       $s0, $s0, $s1
    /* 5FD3C 8006F53C 80801000 */  sll        $s0, $s0, 2
    /* 5FD40 8006F540 21801102 */  addu       $s0, $s0, $s1
    /* 5FD44 8006F544 80801000 */  sll        $s0, $s0, 2
    /* 5FD48 8006F548 2180B002 */  addu       $s0, $s5, $s0
    /* 5FD4C 8006F54C 1280043C */  lui        $a0, %hi(D_80121340)
    /* 5FD50 8006F550 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 5FD54 8006F554 1680053C */  lui        $a1, %hi(D_80158704)
    /* 5FD58 8006F558 0487A524 */  addiu      $a1, $a1, %lo(D_80158704)
    /* 5FD5C 8006F55C 1E000626 */  addiu      $a2, $s0, 0x1E
    /* 5FD60 8006F560 E187030C */  jal        sprintf
    /* 5FD64 8006F564 52000726 */   addiu     $a3, $s0, 0x52
    /* 5FD68 8006F568 1280053C */  lui        $a1, %hi(D_80121340)
    /* 5FD6C 8006F56C 4013A524 */  addiu      $a1, $a1, %lo(D_80121340)
    /* 5FD70 8006F570 69C7020C */  jal        func_800B1DA4
    /* 5FD74 8006F574 21206002 */   addu      $a0, $s3, $zero
    /* 5FD78 8006F578 52000292 */  lbu        $v0, 0x52($s0)
    /* 5FD7C 8006F57C 00000000 */  nop
    /* 5FD80 8006F580 06004010 */  beqz       $v0, .L8006F59C
    /* 5FD84 8006F584 C0101100 */   sll       $v0, $s1, 3
    /* 5FD88 8006F588 1680053C */  lui        $a1, %hi(D_801586C0)
    /* 5FD8C 8006F58C C086A524 */  addiu      $a1, $a1, %lo(D_801586C0)
    /* 5FD90 8006F590 69C7020C */  jal        func_800B1DA4
    /* 5FD94 8006F594 21206002 */   addu      $a0, $s3, $zero
    /* 5FD98 8006F598 C0101100 */  sll        $v0, $s1, 3
  .L8006F59C:
    /* 5FD9C 8006F59C 23105100 */  subu       $v0, $v0, $s1
    /* 5FDA0 8006F5A0 80100200 */  sll        $v0, $v0, 2
    /* 5FDA4 8006F5A4 21105100 */  addu       $v0, $v0, $s1
    /* 5FDA8 8006F5A8 80100200 */  sll        $v0, $v0, 2
    /* 5FDAC 8006F5AC 21805500 */  addu       $s0, $v0, $s5
    /* 5FDB0 8006F5B0 1280043C */  lui        $a0, %hi(D_80121340)
    /* 5FDB4 8006F5B4 40138424 */  addiu      $a0, $a0, %lo(D_80121340)
    /* 5FDB8 8006F5B8 0180053C */  lui        $a1, %hi(D_80010BF4)
    /* 5FDBC 8006F5BC F40BA524 */  addiu      $a1, $a1, %lo(D_80010BF4)
    /* 5FDC0 8006F5C0 64000686 */  lh         $a2, 0x64($s0)
    /* 5FDC4 8006F5C4 E187030C */  jal        sprintf
    /* 5FDC8 8006F5C8 00000000 */   nop
    /* 5FDCC 8006F5CC 1280053C */  lui        $a1, %hi(D_80121340)
    /* 5FDD0 8006F5D0 4013A524 */  addiu      $a1, $a1, %lo(D_80121340)
    /* 5FDD4 8006F5D4 69C7020C */  jal        func_800B1DA4
    /* 5FDD8 8006F5D8 21206002 */   addu      $a0, $s3, $zero
    /* 5FDDC 8006F5DC 0180053C */  lui        $a1, %hi(D_80010C18)
    /* 5FDE0 8006F5E0 180CA524 */  addiu      $a1, $a1, %lo(D_80010C18)
    /* 5FDE4 8006F5E4 69C7020C */  jal        func_800B1DA4
    /* 5FDE8 8006F5E8 21206002 */   addu      $a0, $s3, $zero
    /* 5FDEC 8006F5EC 21206002 */  addu       $a0, $s3, $zero
    /* 5FDF0 8006F5F0 1680053C */  lui        $a1, %hi(D_801586F4)
    /* 5FDF4 8006F5F4 F486A524 */  addiu      $a1, $a1, %lo(D_801586F4)
    /* 5FDF8 8006F5F8 A8C9020C */  jal        func_800B26A0
    /* 5FDFC 8006F5FC 21300000 */   addu      $a2, $zero, $zero
    /* 5FE00 8006F600 21206002 */  addu       $a0, $s3, $zero
    /* 5FE04 8006F604 1680053C */  lui        $a1, %hi(D_801586F8)
    /* 5FE08 8006F608 F886A524 */  addiu      $a1, $a1, %lo(D_801586F8)
    /* 5FE0C 8006F60C A8C9020C */  jal        func_800B26A0
    /* 5FE10 8006F610 01000624 */   addiu     $a2, $zero, 0x1
    /* 5FE14 8006F614 21206002 */  addu       $a0, $s3, $zero
    /* 5FE18 8006F618 52DF020C */  jal        func_800B7D48
    /* 5FE1C 8006F61C 21280000 */   addu      $a1, $zero, $zero
    /* 5FE20 8006F620 21184000 */  addu       $v1, $v0, $zero
    /* 5FE24 8006F624 01000224 */  addiu      $v0, $zero, 0x1
    /* 5FE28 8006F628 3D006214 */  bne        $v1, $v0, .L8006F720
    /* 5FE2C 8006F62C FEFF0224 */   addiu     $v0, $zero, -0x2
    /* 5FE30 8006F630 51C1010C */  jal        func_80070544
    /* 5FE34 8006F634 21200002 */   addu      $a0, $s0, $zero
    /* 5FE38 8006F638 00140200 */  sll        $v0, $v0, 16
    /* 5FE3C 8006F63C 03140200 */  sra        $v0, $v0, 16
    /* 5FE40 8006F640 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 5FE44 8006F644 2E004314 */  bne        $v0, $v1, .L8006F700
    /* 5FE48 8006F648 00000000 */   nop
    /* 5FE4C 8006F64C 03006012 */  beqz       $s3, .L8006F65C
    /* 5FE50 8006F650 21206002 */   addu      $a0, $s3, $zero
    /* 5FE54 8006F654 0AC7020C */  jal        func_800B1C28
    /* 5FE58 8006F658 03000524 */   addiu     $a1, $zero, 0x3
  .L8006F65C:
    /* 5FE5C 8006F65C 3E82030C */  jal        __builtin_new
    /* 5FE60 8006F660 9C020424 */   addiu     $a0, $zero, 0x29C
    /* 5FE64 8006F664 21204000 */  addu       $a0, $v0, $zero
    /* 5FE68 8006F668 ADC5020C */  jal        func_800B16B4
    /* 5FE6C 8006F66C 00200524 */   addiu     $a1, $zero, 0x2000
    /* 5FE70 8006F670 21984000 */  addu       $s3, $v0, $zero
    /* 5FE74 8006F674 01000224 */  addiu      $v0, $zero, 0x1
    /* 5FE78 8006F678 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5FE7C 8006F67C 21206002 */  addu       $a0, $s3, $zero
    /* 5FE80 8006F680 21280000 */  addu       $a1, $zero, $zero
    /* 5FE84 8006F684 21300000 */  addu       $a2, $zero, $zero
    /* 5FE88 8006F688 1EC7020C */  jal        func_800B1C78
    /* 5FE8C 8006F68C 21380000 */   addu      $a3, $zero, $zero
    /* 5FE90 8006F690 21206002 */  addu       $a0, $s3, $zero
    /* 5FE94 8006F694 F8FF0524 */  addiu      $a1, $zero, -0x8
    /* 5FE98 8006F698 5AC8020C */  jal        func_800B2168
    /* 5FE9C 8006F69C F8FF0624 */   addiu     $a2, $zero, -0x8
    /* 5FEA0 8006F6A0 0180053C */  lui        $a1, %hi(D_80010C34)
    /* 5FEA4 8006F6A4 340CA524 */  addiu      $a1, $a1, %lo(D_80010C34)
    /* 5FEA8 8006F6A8 1CC8020C */  jal        func_800B2070
    /* 5FEAC 8006F6AC 21206002 */   addu      $a0, $s3, $zero
    /* 5FEB0 8006F6B0 21206002 */  addu       $a0, $s3, $zero
    /* 5FEB4 8006F6B4 39C8020C */  jal        func_800B20E4
    /* 5FEB8 8006F6B8 00010524 */   addiu     $a1, $zero, 0x100
    /* 5FEBC 8006F6BC 1680053C */  lui        $a1, %hi(D_801586C0)
    /* 5FEC0 8006F6C0 C086A524 */  addiu      $a1, $a1, %lo(D_801586C0)
    /* 5FEC4 8006F6C4 69C7020C */  jal        func_800B1DA4
    /* 5FEC8 8006F6C8 21206002 */   addu      $a0, $s3, $zero
    /* 5FECC 8006F6CC 0180053C */  lui        $a1, %hi(D_80010C4C)
    /* 5FED0 8006F6D0 4C0CA524 */  addiu      $a1, $a1, %lo(D_80010C4C)
    /* 5FED4 8006F6D4 69C7020C */  jal        func_800B1DA4
    /* 5FED8 8006F6D8 21206002 */   addu      $a0, $s3, $zero
    /* 5FEDC 8006F6DC 1680053C */  lui        $a1, %hi(D_801586C0)
    /* 5FEE0 8006F6E0 C086A524 */  addiu      $a1, $a1, %lo(D_801586C0)
    /* 5FEE4 8006F6E4 69C7020C */  jal        func_800B1DA4
    /* 5FEE8 8006F6E8 21206002 */   addu      $a0, $s3, $zero
    /* 5FEEC 8006F6EC 21206002 */  addu       $a0, $s3, $zero
    /* 5FEF0 8006F6F0 52DF020C */  jal        func_800B7D48
    /* 5FEF4 8006F6F4 21280000 */   addu      $a1, $zero, $zero
    /* 5FEF8 8006F6F8 CDBC0108 */  j          .L8006F334
    /* 5FEFC 8006F6FC 0F001124 */   addiu     $s1, $zero, 0xF
  .L8006F700:
    /* 5FF00 8006F700 C0101100 */  sll        $v0, $s1, 3
    /* 5FF04 8006F704 23105100 */  subu       $v0, $v0, $s1
    /* 5FF08 8006F708 80100200 */  sll        $v0, $v0, 2
    /* 5FF0C 8006F70C 21105100 */  addu       $v0, $v0, $s1
    /* 5FF10 8006F710 80100200 */  sll        $v0, $v0, 2
    /* 5FF14 8006F714 21105500 */  addu       $v0, $v0, $s5
    /* 5FF18 8006F718 CCBC0108 */  j          .L8006F330
    /* 5FF1C 8006F71C 640040A4 */   sh        $zero, 0x64($v0)
  .L8006F720:
    /* 5FF20 8006F720 04FF6214 */  bne        $v1, $v0, .L8006F334
    /* 5FF24 8006F724 0F001124 */   addiu     $s1, $zero, 0xF
  .L8006F728:
    /* 5FF28 8006F728 21800000 */  addu       $s0, $zero, $zero
  .L8006F72C:
    /* 5FF2C 8006F72C 2A101402 */  slt        $v0, $s0, $s4
    /* 5FF30 8006F730 26004010 */  beqz       $v0, .L8006F7CC
    /* 5FF34 8006F734 C0101000 */   sll       $v0, $s0, 3
    /* 5FF38 8006F738 21184000 */  addu       $v1, $v0, $zero
    /* 5FF3C 8006F73C 23105000 */  subu       $v0, $v0, $s0
    /* 5FF40 8006F740 80100200 */  sll        $v0, $v0, 2
    /* 5FF44 8006F744 21105000 */  addu       $v0, $v0, $s0
    /* 5FF48 8006F748 80100200 */  sll        $v0, $v0, 2
    /* 5FF4C 8006F74C 21105500 */  addu       $v0, $v0, $s5
    /* 5FF50 8006F750 66004284 */  lh         $v0, 0x66($v0)
    /* 5FF54 8006F754 00000000 */  nop
    /* 5FF58 8006F758 1A004018 */  blez       $v0, .L8006F7C4
    /* 5FF5C 8006F75C 21880000 */   addu      $s1, $zero, $zero
    /* 5FF60 8006F760 23107000 */  subu       $v0, $v1, $s0
  .L8006F764:
    /* 5FF64 8006F764 80100200 */  sll        $v0, $v0, 2
    /* 5FF68 8006F768 21105000 */  addu       $v0, $v0, $s0
    /* 5FF6C 8006F76C 80100200 */  sll        $v0, $v0, 2
    /* 5FF70 8006F770 21105500 */  addu       $v0, $v0, $s5
    /* 5FF74 8006F774 80181100 */  sll        $v1, $s1, 2
    /* 5FF78 8006F778 21186200 */  addu       $v1, $v1, $v0
    /* 5FF7C 8006F77C 6800648C */  lw         $a0, 0x68($v1)
    /* 5FF80 8006F780 00000000 */  nop
    /* 5FF84 8006F784 03008010 */  beqz       $a0, .L8006F794
    /* 5FF88 8006F788 00000000 */   nop
    /* 5FF8C 8006F78C 12ED030C */  jal        func_800FB448
    /* 5FF90 8006F790 03000524 */   addiu     $a1, $zero, 0x3
  .L8006F794:
    /* 5FF94 8006F794 01003126 */  addiu      $s1, $s1, 0x1
    /* 5FF98 8006F798 C0181000 */  sll        $v1, $s0, 3
    /* 5FF9C 8006F79C 23107000 */  subu       $v0, $v1, $s0
    /* 5FFA0 8006F7A0 80100200 */  sll        $v0, $v0, 2
    /* 5FFA4 8006F7A4 21105000 */  addu       $v0, $v0, $s0
    /* 5FFA8 8006F7A8 80100200 */  sll        $v0, $v0, 2
    /* 5FFAC 8006F7AC 21105500 */  addu       $v0, $v0, $s5
    /* 5FFB0 8006F7B0 66004284 */  lh         $v0, 0x66($v0)
    /* 5FFB4 8006F7B4 00000000 */  nop
    /* 5FFB8 8006F7B8 2A102202 */  slt        $v0, $s1, $v0
    /* 5FFBC 8006F7BC E9FF4014 */  bnez       $v0, .L8006F764
    /* 5FFC0 8006F7C0 23107000 */   subu      $v0, $v1, $s0
  .L8006F7C4:
    /* 5FFC4 8006F7C4 CBBD0108 */  j          .L8006F72C
    /* 5FFC8 8006F7C8 01001026 */   addiu     $s0, $s0, 0x1
  .L8006F7CC:
    /* 5FFCC 8006F7CC 9822040C */  jal        func_80108A60
    /* 5FFD0 8006F7D0 2120C003 */   addu      $a0, $fp, $zero
  .L8006F7D4:
    /* 5FFD4 8006F7D4 03006012 */  beqz       $s3, .L8006F7E4
    /* 5FFD8 8006F7D8 21206002 */   addu      $a0, $s3, $zero
    /* 5FFDC 8006F7DC 0AC7020C */  jal        func_800B1C28
    /* 5FFE0 8006F7E0 03000524 */   addiu     $a1, $zero, 0x3
  .L8006F7E4:
    /* 5FFE4 8006F7E4 6402848F */  lw         $a0, %gp_rel(D_8015873C)($gp)
    /* 5FFE8 8006F7E8 C6D5030C */  jal        func_800F5718
    /* 5FFEC 8006F7EC 00000000 */   nop
    /* 5FFF0 8006F7F0 21100000 */  addu       $v0, $zero, $zero
  .L8006F7F4:
    /* 5FFF4 8006F7F4 8C00BF8F */  lw         $ra, 0x8C($sp)
    /* 5FFF8 8006F7F8 8800BE8F */  lw         $fp, 0x88($sp)
    /* 5FFFC 8006F7FC 8400B78F */  lw         $s7, 0x84($sp)
    /* 60000 8006F800 8000B68F */  lw         $s6, 0x80($sp)
    /* 60004 8006F804 7C00B58F */  lw         $s5, 0x7C($sp)
    /* 60008 8006F808 7800B48F */  lw         $s4, 0x78($sp)
    /* 6000C 8006F80C 7400B38F */  lw         $s3, 0x74($sp)
    /* 60010 8006F810 7000B28F */  lw         $s2, 0x70($sp)
    /* 60014 8006F814 6C00B18F */  lw         $s1, 0x6C($sp)
    /* 60018 8006F818 6800B08F */  lw         $s0, 0x68($sp)
    /* 6001C 8006F81C 9000BD27 */  addiu      $sp, $sp, 0x90
    /* 60020 8006F820 0800E003 */  jr         $ra
    /* 60024 8006F824 00000000 */   nop
endlabel func_8006ECFC
