.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_80012680

dlabel jtbl_80012680
    /* 2E80 80012680 C8A40B80 */ .word .L800BA4C8
    /* 2E84 80012684 9CA70B80 */ .word .L800BA79C
    /* 2E88 80012688 B4A50B80 */ .word .L800BA5B4
    /* 2E8C 8001268C 9CA70B80 */ .word .L800BA79C
    /* 2E90 80012690 54A60B80 */ .word .L800BA654
    /* 2E94 80012694 9CA70B80 */ .word .L800BA79C
    /* 2E98 80012698 90A40B80 */ .word .L800BA490
    /* 2E9C 8001269C 9CA70B80 */ .word .L800BA79C
    /* 2EA0 800126A0 9CA70B80 */ .word .L800BA79C
    /* 2EA4 800126A4 9CA70B80 */ .word .L800BA79C
    /* 2EA8 800126A8 9CA70B80 */ .word .L800BA79C
    /* 2EAC 800126AC 9CA70B80 */ .word .L800BA79C
    /* 2EB0 800126B0 9CA70B80 */ .word .L800BA79C
    /* 2EB4 800126B4 9CA70B80 */ .word .L800BA79C
    /* 2EB8 800126B8 9CA70B80 */ .word .L800BA79C
    /* 2EBC 800126BC 9CA70B80 */ .word .L800BA79C
    /* 2EC0 800126C0 9CA70B80 */ .word .L800BA79C
    /* 2EC4 800126C4 9CA70B80 */ .word .L800BA79C
    /* 2EC8 800126C8 9CA70B80 */ .word .L800BA79C
    /* 2ECC 800126CC 9CA70B80 */ .word .L800BA79C
    /* 2ED0 800126D0 9CA70B80 */ .word .L800BA79C
    /* 2ED4 800126D4 9CA70B80 */ .word .L800BA79C
    /* 2ED8 800126D8 9CA70B80 */ .word .L800BA79C
    /* 2EDC 800126DC 9CA70B80 */ .word .L800BA79C
    /* 2EE0 800126E0 9CA70B80 */ .word .L800BA79C
    /* 2EE4 800126E4 9CA70B80 */ .word .L800BA79C
    /* 2EE8 800126E8 9CA70B80 */ .word .L800BA79C
    /* 2EEC 800126EC 9CA70B80 */ .word .L800BA79C
    /* 2EF0 800126F0 9CA70B80 */ .word .L800BA79C
    /* 2EF4 800126F4 9CA70B80 */ .word .L800BA79C
    /* 2EF8 800126F8 9CA70B80 */ .word .L800BA79C
    /* 2EFC 800126FC 9CA70B80 */ .word .L800BA79C
    /* 2F00 80012700 9CA70B80 */ .word .L800BA79C
    /* 2F04 80012704 9CA70B80 */ .word .L800BA79C
    /* 2F08 80012708 9CA70B80 */ .word .L800BA79C
    /* 2F0C 8001270C 9CA70B80 */ .word .L800BA79C
    /* 2F10 80012710 9CA70B80 */ .word .L800BA79C
    /* 2F14 80012714 9CA70B80 */ .word .L800BA79C
    /* 2F18 80012718 9CA70B80 */ .word .L800BA79C
    /* 2F1C 8001271C 9CA70B80 */ .word .L800BA79C
    /* 2F20 80012720 9CA70B80 */ .word .L800BA79C
    /* 2F24 80012724 9CA70B80 */ .word .L800BA79C
    /* 2F28 80012728 9CA70B80 */ .word .L800BA79C
    /* 2F2C 8001272C 9CA70B80 */ .word .L800BA79C
    /* 2F30 80012730 9CA70B80 */ .word .L800BA79C
    /* 2F34 80012734 9CA70B80 */ .word .L800BA79C
    /* 2F38 80012738 04A70B80 */ .word .L800BA704
    /* 2F3C 8001273C 9CA70B80 */ .word .L800BA79C
    /* 2F40 80012740 78A70B80 */ .word .L800BA778
enddlabel jtbl_80012680


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800BA43C, 0x3AC

glabel func_800BA43C
    /* AAC3C 800BA43C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* AAC40 800BA440 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* AAC44 800BA444 02001124 */  addiu      $s1, $zero, 0x2
    /* AAC48 800BA448 5EFF8424 */  addiu      $a0, $a0, -0xA2
    /* AAC4C 800BA44C 00240400 */  sll        $a0, $a0, 16
    /* AAC50 800BA450 03240400 */  sra        $a0, $a0, 16
    /* AAC54 800BA454 2400B3AF */  sw         $s3, 0x24($sp)
    /* AAC58 800BA458 1280133C */  lui        $s3, %hi(D_80121134)
    /* AAC5C 800BA45C 34117386 */  lh         $s3, %lo(D_80121134)($s3)
    /* AAC60 800BA460 3100822C */  sltiu      $v0, $a0, 0x31
    /* AAC64 800BA464 2800BFAF */  sw         $ra, 0x28($sp)
    /* AAC68 800BA468 2000B2AF */  sw         $s2, 0x20($sp)
    /* AAC6C 800BA46C CB004010 */  beqz       $v0, .L800BA79C
    /* AAC70 800BA470 1800B0AF */   sw        $s0, 0x18($sp)
    /* AAC74 800BA474 80100400 */  sll        $v0, $a0, 2
    /* AAC78 800BA478 0180013C */  lui        $at, %hi(jtbl_80012680)
    /* AAC7C 800BA47C 21082200 */  addu       $at, $at, $v0
    /* AAC80 800BA480 8026228C */  lw         $v0, %lo(jtbl_80012680)($at)
    /* AAC84 800BA484 00000000 */  nop
    /* AAC88 800BA488 08004000 */  jr         $v0
    /* AAC8C 800BA48C 00000000 */   nop
  .L800BA490:
    /* AAC90 800BA490 1280103C */  lui        $s0, %hi(D_80121134)
    /* AAC94 800BA494 34111026 */  addiu      $s0, $s0, %lo(D_80121134)
    /* AAC98 800BA498 00000386 */  lh         $v1, 0x0($s0)
    /* AAC9C 800BA49C FFFF2226 */  addiu      $v0, $s1, -0x1
    /* AACA0 800BA4A0 2A104300 */  slt        $v0, $v0, $v1
    /* AACA4 800BA4A4 BD004010 */  beqz       $v0, .L800BA79C
    /* AACA8 800BA4A8 5E000424 */   addiu     $a0, $zero, 0x5E
    /* AACAC 800BA4AC 21280000 */  addu       $a1, $zero, $zero
    /* AACB0 800BA4B0 21300000 */  addu       $a2, $zero, $zero
    /* AACB4 800BA4B4 2B9D020C */  jal        func_800A74AC
    /* AACB8 800BA4B8 21380000 */   addu      $a3, $zero, $zero
    /* AACBC 800BA4BC 00000296 */  lhu        $v0, 0x0($s0)
    /* AACC0 800BA4C0 7AE90208 */  j          .L800BA5E8
    /* AACC4 800BA4C4 23105100 */   subu      $v0, $v0, $s1
  .L800BA4C8:
    /* AACC8 800BA4C8 1280103C */  lui        $s0, %hi(D_80121134)
    /* AACCC 800BA4CC 34111026 */  addiu      $s0, $s0, %lo(D_80121134)
    /* AACD0 800BA4D0 00000286 */  lh         $v0, 0x0($s0)
    /* AACD4 800BA4D4 1280043C */  lui        $a0, %hi(D_80121136)
    /* AACD8 800BA4D8 36118484 */  lh         $a0, %lo(D_80121136)($a0)
    /* AACDC 800BA4DC 21184000 */  addu       $v1, $v0, $zero
    /* AACE0 800BA4E0 2A104400 */  slt        $v0, $v0, $a0
    /* AACE4 800BA4E4 AD004010 */  beqz       $v0, .L800BA79C
    /* AACE8 800BA4E8 21107100 */   addu      $v0, $v1, $s1
    /* AACEC 800BA4EC 000002A6 */  sh         $v0, 0x0($s0)
    /* AACF0 800BA4F0 00140200 */  sll        $v0, $v0, 16
    /* AACF4 800BA4F4 031C0200 */  sra        $v1, $v0, 16
    /* AACF8 800BA4F8 2A106400 */  slt        $v0, $v1, $a0
    /* AACFC 800BA4FC 0E004014 */  bnez       $v0, .L800BA538
    /* AAD00 800BA500 21280000 */   addu      $a1, $zero, $zero
    /* AAD04 800BA504 FFFF8224 */  addiu      $v0, $a0, -0x1
    /* AAD08 800BA508 0F006210 */  beq        $v1, $v0, .L800BA548
    /* AAD0C 800BA50C 5E000424 */   addiu     $a0, $zero, 0x5E
    /* AAD10 800BA510 21280000 */  addu       $a1, $zero, $zero
    /* AAD14 800BA514 21300000 */  addu       $a2, $zero, $zero
    /* AAD18 800BA518 2B9D020C */  jal        func_800A74AC
    /* AAD1C 800BA51C 21380000 */   addu      $a3, $zero, $zero
    /* AAD20 800BA520 1280023C */  lui        $v0, %hi(D_80121136)
    /* AAD24 800BA524 36114294 */  lhu        $v0, %lo(D_80121136)($v0)
    /* AAD28 800BA528 00000000 */  nop
    /* AAD2C 800BA52C FFFF4224 */  addiu      $v0, $v0, -0x1
    /* AAD30 800BA530 52E90208 */  j          .L800BA548
    /* AAD34 800BA534 000002A6 */   sh        $v0, 0x0($s0)
  .L800BA538:
    /* AAD38 800BA538 5E000424 */  addiu      $a0, $zero, 0x5E
    /* AAD3C 800BA53C 21300000 */  addu       $a2, $zero, $zero
    /* AAD40 800BA540 2B9D020C */  jal        func_800A74AC
    /* AAD44 800BA544 21380000 */   addu      $a3, $zero, $zero
  .L800BA548:
    /* AAD48 800BA548 1280043C */  lui        $a0, %hi(D_801210C8)
    /* AAD4C 800BA54C C8108424 */  addiu      $a0, $a0, %lo(D_801210C8)
    /* AAD50 800BA550 0000828C */  lw         $v0, 0x0($a0)
    /* AAD54 800BA554 1280033C */  lui        $v1, %hi(D_80121134)
    /* AAD58 800BA558 34116384 */  lh         $v1, %lo(D_80121134)($v1)
    /* AAD5C 800BA55C 0F004224 */  addiu      $v0, $v0, 0xF
    /* AAD60 800BA560 2A104300 */  slt        $v0, $v0, $v1
    /* AAD64 800BA564 8D004010 */  beqz       $v0, .L800BA79C
    /* AAD68 800BA568 00000000 */   nop
    /* AAD6C 800BA56C 1A007100 */  div        $zero, $v1, $s1
    /* AAD70 800BA570 02002016 */  bnez       $s1, .L800BA57C
    /* AAD74 800BA574 00000000 */   nop
    /* AAD78 800BA578 0D000700 */  break      7
  .L800BA57C:
    /* AAD7C 800BA57C FFFF0124 */  addiu      $at, $zero, -0x1
    /* AAD80 800BA580 04002116 */  bne        $s1, $at, .L800BA594
    /* AAD84 800BA584 0080013C */   lui       $at, (0x80000000 >> 16)
    /* AAD88 800BA588 02006114 */  bne        $v1, $at, .L800BA594
    /* AAD8C 800BA58C 00000000 */   nop
    /* AAD90 800BA590 0D000600 */  break      6
  .L800BA594:
    /* AAD94 800BA594 12100000 */  mflo       $v0
    /* AAD98 800BA598 00000000 */  nop
    /* AAD9C 800BA59C 00000000 */  nop
    /* AADA0 800BA5A0 18005100 */  mult       $v0, $s1
    /* AADA4 800BA5A4 12400000 */  mflo       $t0
    /* AADA8 800BA5A8 F2FF0225 */  addiu      $v0, $t0, -0xE
    /* AADAC 800BA5AC E7E90208 */  j          .L800BA79C
    /* AADB0 800BA5B0 000082AC */   sw        $v0, 0x0($a0)
  .L800BA5B4:
    /* AADB4 800BA5B4 1280103C */  lui        $s0, %hi(D_80121134)
    /* AADB8 800BA5B8 34111026 */  addiu      $s0, $s0, %lo(D_80121134)
    /* AADBC 800BA5BC 00000286 */  lh         $v0, 0x0($s0)
    /* AADC0 800BA5C0 00000000 */  nop
    /* AADC4 800BA5C4 75004018 */  blez       $v0, .L800BA79C
    /* AADC8 800BA5C8 5E000424 */   addiu     $a0, $zero, 0x5E
    /* AADCC 800BA5CC 21280000 */  addu       $a1, $zero, $zero
    /* AADD0 800BA5D0 21300000 */  addu       $a2, $zero, $zero
    /* AADD4 800BA5D4 2B9D020C */  jal        func_800A74AC
    /* AADD8 800BA5D8 21380000 */   addu      $a3, $zero, $zero
    /* AADDC 800BA5DC 00000296 */  lhu        $v0, 0x0($s0)
    /* AADE0 800BA5E0 00000000 */  nop
    /* AADE4 800BA5E4 FFFF4224 */  addiu      $v0, $v0, -0x1
  .L800BA5E8:
    /* AADE8 800BA5E8 000002A6 */  sh         $v0, 0x0($s0)
    /* AADEC 800BA5EC 00140200 */  sll        $v0, $v0, 16
    /* AADF0 800BA5F0 1280033C */  lui        $v1, %hi(D_801210C8)
    /* AADF4 800BA5F4 C810638C */  lw         $v1, %lo(D_801210C8)($v1)
    /* AADF8 800BA5F8 03140200 */  sra        $v0, $v0, 16
    /* AADFC 800BA5FC 2A184300 */  slt        $v1, $v0, $v1
    /* AAE00 800BA600 66006010 */  beqz       $v1, .L800BA79C
    /* AAE04 800BA604 00000000 */   nop
    /* AAE08 800BA608 1A005100 */  div        $zero, $v0, $s1
    /* AAE0C 800BA60C 02002016 */  bnez       $s1, .L800BA618
    /* AAE10 800BA610 00000000 */   nop
    /* AAE14 800BA614 0D000700 */  break      7
  .L800BA618:
    /* AAE18 800BA618 FFFF0124 */  addiu      $at, $zero, -0x1
    /* AAE1C 800BA61C 04002116 */  bne        $s1, $at, .L800BA630
    /* AAE20 800BA620 0080013C */   lui       $at, (0x80000000 >> 16)
    /* AAE24 800BA624 02004114 */  bne        $v0, $at, .L800BA630
    /* AAE28 800BA628 00000000 */   nop
    /* AAE2C 800BA62C 0D000600 */  break      6
  .L800BA630:
    /* AAE30 800BA630 12100000 */  mflo       $v0
    /* AAE34 800BA634 00000000 */  nop
    /* AAE38 800BA638 00000000 */  nop
    /* AAE3C 800BA63C 18005100 */  mult       $v0, $s1
    /* AAE40 800BA640 12400000 */  mflo       $t0
    /* AAE44 800BA644 1280013C */  lui        $at, %hi(D_801210C8)
    /* AAE48 800BA648 C81028AC */  sw         $t0, %lo(D_801210C8)($at)
    /* AAE4C 800BA64C E7E90208 */  j          .L800BA79C
    /* AAE50 800BA650 00000000 */   nop
  .L800BA654:
    /* AAE54 800BA654 1280103C */  lui        $s0, %hi(D_80121134)
    /* AAE58 800BA658 34111026 */  addiu      $s0, $s0, %lo(D_80121134)
    /* AAE5C 800BA65C 00000286 */  lh         $v0, 0x0($s0)
    /* AAE60 800BA660 1280033C */  lui        $v1, %hi(D_80121136)
    /* AAE64 800BA664 36116384 */  lh         $v1, %lo(D_80121136)($v1)
    /* AAE68 800BA668 01004224 */  addiu      $v0, $v0, 0x1
    /* AAE6C 800BA66C 2A104300 */  slt        $v0, $v0, $v1
    /* AAE70 800BA670 4A004010 */  beqz       $v0, .L800BA79C
    /* AAE74 800BA674 5E000424 */   addiu     $a0, $zero, 0x5E
    /* AAE78 800BA678 21280000 */  addu       $a1, $zero, $zero
    /* AAE7C 800BA67C 21300000 */  addu       $a2, $zero, $zero
    /* AAE80 800BA680 2B9D020C */  jal        func_800A74AC
    /* AAE84 800BA684 21380000 */   addu      $a3, $zero, $zero
    /* AAE88 800BA688 00000296 */  lhu        $v0, 0x0($s0)
    /* AAE8C 800BA68C 1280033C */  lui        $v1, %hi(D_801210C8)
    /* AAE90 800BA690 C810638C */  lw         $v1, %lo(D_801210C8)($v1)
    /* AAE94 800BA694 01004224 */  addiu      $v0, $v0, 0x1
    /* AAE98 800BA698 0F006324 */  addiu      $v1, $v1, 0xF
    /* AAE9C 800BA69C 000002A6 */  sh         $v0, 0x0($s0)
    /* AAEA0 800BA6A0 00140200 */  sll        $v0, $v0, 16
    /* AAEA4 800BA6A4 03140200 */  sra        $v0, $v0, 16
    /* AAEA8 800BA6A8 2A186200 */  slt        $v1, $v1, $v0
    /* AAEAC 800BA6AC 3B006010 */  beqz       $v1, .L800BA79C
    /* AAEB0 800BA6B0 00000000 */   nop
    /* AAEB4 800BA6B4 1A005100 */  div        $zero, $v0, $s1
    /* AAEB8 800BA6B8 02002016 */  bnez       $s1, .L800BA6C4
    /* AAEBC 800BA6BC 00000000 */   nop
    /* AAEC0 800BA6C0 0D000700 */  break      7
  .L800BA6C4:
    /* AAEC4 800BA6C4 FFFF0124 */  addiu      $at, $zero, -0x1
    /* AAEC8 800BA6C8 04002116 */  bne        $s1, $at, .L800BA6DC
    /* AAECC 800BA6CC 0080013C */   lui       $at, (0x80000000 >> 16)
    /* AAED0 800BA6D0 02004114 */  bne        $v0, $at, .L800BA6DC
    /* AAED4 800BA6D4 00000000 */   nop
    /* AAED8 800BA6D8 0D000600 */  break      6
  .L800BA6DC:
    /* AAEDC 800BA6DC 12100000 */  mflo       $v0
    /* AAEE0 800BA6E0 00000000 */  nop
    /* AAEE4 800BA6E4 00000000 */  nop
    /* AAEE8 800BA6E8 18005100 */  mult       $v0, $s1
    /* AAEEC 800BA6EC 12400000 */  mflo       $t0
    /* AAEF0 800BA6F0 F2FF0225 */  addiu      $v0, $t0, -0xE
    /* AAEF4 800BA6F4 1280013C */  lui        $at, %hi(D_801210C8)
    /* AAEF8 800BA6F8 C81022AC */  sw         $v0, %lo(D_801210C8)($at)
    /* AAEFC 800BA6FC E7E90208 */  j          .L800BA79C
    /* AAF00 800BA700 00000000 */   nop
  .L800BA704:
    /* AAF04 800BA704 68000424 */  addiu      $a0, $zero, 0x68
    /* AAF08 800BA708 21280000 */  addu       $a1, $zero, $zero
    /* AAF0C 800BA70C 21300000 */  addu       $a2, $zero, $zero
    /* AAF10 800BA710 2B9D020C */  jal        func_800A74AC
    /* AAF14 800BA714 21380000 */   addu      $a3, $zero, $zero
    /* AAF18 800BA718 21880000 */  addu       $s1, $zero, $zero
    /* AAF1C 800BA71C 21800000 */  addu       $s0, $zero, $zero
    /* AAF20 800BA720 1280123C */  lui        $s2, %hi(D_801210C4)
    /* AAF24 800BA724 C4105226 */  addiu      $s2, $s2, %lo(D_801210C4)
  .L800BA728:
    /* AAF28 800BA728 0000448E */  lw         $a0, 0x0($s2)
    /* AAF2C 800BA72C 8ACA010C */  jal        func_80072A28
    /* AAF30 800BA730 21280002 */   addu      $a1, $s0, $zero
    /* AAF34 800BA734 06004010 */  beqz       $v0, .L800BA750
    /* AAF38 800BA738 00000000 */   nop
    /* AAF3C 800BA73C 01003126 */  addiu      $s1, $s1, 0x1
    /* AAF40 800BA740 70004386 */  lh         $v1, 0x70($s2)
    /* AAF44 800BA744 FFFF2226 */  addiu      $v0, $s1, -0x1
    /* AAF48 800BA748 07004310 */  beq        $v0, $v1, .L800BA768
    /* AAF4C 800BA74C 01080424 */   addiu     $a0, $zero, 0x801
  .L800BA750:
    /* AAF50 800BA750 01001026 */  addiu      $s0, $s0, 0x1
    /* AAF54 800BA754 5D00022A */  slti       $v0, $s0, 0x5D
    /* AAF58 800BA758 10004010 */  beqz       $v0, .L800BA79C
    /* AAF5C 800BA75C 00000000 */   nop
    /* AAF60 800BA760 CAE90208 */  j          .L800BA728
    /* AAF64 800BA764 00000000 */   nop
  .L800BA768:
    /* AAF68 800BA768 149C020C */  jal        func_800A7050
    /* AAF6C 800BA76C 21280002 */   addu      $a1, $s0, $zero
    /* AAF70 800BA770 E7E90208 */  j          .L800BA79C
    /* AAF74 800BA774 00000000 */   nop
  .L800BA778:
    /* AAF78 800BA778 68000424 */  addiu      $a0, $zero, 0x68
    /* AAF7C 800BA77C 21280000 */  addu       $a1, $zero, $zero
    /* AAF80 800BA780 21300000 */  addu       $a2, $zero, $zero
    /* AAF84 800BA784 2B9D020C */  jal        func_800A74AC
    /* AAF88 800BA788 21380000 */   addu      $a3, $zero, $zero
    /* AAF8C 800BA78C 1280043C */  lui        $a0, %hi(D_80120D84)
    /* AAF90 800BA790 840D8424 */  addiu      $a0, $a0, %lo(D_80120D84)
    /* AAF94 800BA794 29E5020C */  jal        func_800B94A4
    /* AAF98 800BA798 00000000 */   nop
  .L800BA79C:
    /* AAF9C 800BA79C 1280023C */  lui        $v0, %hi(D_80121134)
    /* AAFA0 800BA7A0 34114284 */  lh         $v0, %lo(D_80121134)($v0)
    /* AAFA4 800BA7A4 00000000 */  nop
    /* AAFA8 800BA7A8 07006212 */  beq        $s3, $v0, .L800BA7C8
    /* AAFAC 800BA7AC 00000000 */   nop
    /* AAFB0 800BA7B0 1280043C */  lui        $a0, %hi(D_80121118)
    /* AAFB4 800BA7B4 1811848C */  lw         $a0, %lo(D_80121118)($a0)
    /* AAFB8 800BA7B8 E511040C */  jal        func_80104794
    /* AAFBC 800BA7BC 00000000 */   nop
    /* AAFC0 800BA7C0 1280013C */  lui        $at, %hi(D_80121118)
    /* AAFC4 800BA7C4 181120AC */  sw         $zero, %lo(D_80121118)($at)
  .L800BA7C8:
    /* AAFC8 800BA7C8 2800BF8F */  lw         $ra, 0x28($sp)
    /* AAFCC 800BA7CC 2400B38F */  lw         $s3, 0x24($sp)
    /* AAFD0 800BA7D0 2000B28F */  lw         $s2, 0x20($sp)
    /* AAFD4 800BA7D4 1C00B18F */  lw         $s1, 0x1C($sp)
    /* AAFD8 800BA7D8 1800B08F */  lw         $s0, 0x18($sp)
    /* AAFDC 800BA7DC 3000BD27 */  addiu      $sp, $sp, 0x30
    /* AAFE0 800BA7E0 0800E003 */  jr         $ra
    /* AAFE4 800BA7E4 00000000 */   nop
endlabel func_800BA43C
