name: slus
sha1: 362a030a231fc5952010909faf848a8a461bbb3c
options:
  basename: slus
  target_path: disks/us/SLUS_007.92
  base_path: ../..
  platform: psx
  gp_value: 0x80054710
  compiler: GCC

  asm_path: asm/us/slus
  src_path: src/slus
  build_path: build/us/slus

  ld_script_path: build/us/generated/slus.ld

  global_vram_start: 0x80000000
  global_vram_end: 0x80200000

  find_file_boundaries: False

  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/us/symbols_slus.txt

  undefined_funcs_auto_path: build/us/generated/undefined_funcs_auto_slus.txt
  undefined_syms_auto_path: build/us/generated/undefined_syms_auto_slus.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: True

  migrate_rodata_to_functions: True
  create_data_pads: False
  create_c_files: True

segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    bss_size: 0x141380
    align: 4
    subalign: 4
    subsegments:
      - [0x800, .rodata, game]
      - [0x7C04, rodata, psyq]
      - [0x87E4, c, game]
      - [0x1D0CC, asm, psyq]
      - [0x37710, data, data]
      - { start: 0x46CB8, type: bss, vram: 0x800564B8, name: bss }

  - [0x46CB8]
