.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
nonmatching jtbl_8001729C

dlabel jtbl_8001729C
    /* 7A9C 8001729C 9CAD0280 */ .word .L8002AD9C
    /* 7AA0 800172A0 DCAD0280 */ .word .L8002ADDC
    /* 7AA4 800172A4 ECAD0280 */ .word .L8002ADEC
    /* 7AA8 800172A8 FCAD0280 */ .word .L8002ADFC
    /* 7AAC 800172AC 0CAE0280 */ .word .L8002AE0C
    /* 7AB0 800172B0 1CAE0280 */ .word .L8002AE1C
    /* 7AB4 800172B4 2CAE0280 */ .word .L8002AE2C
    /* 7AB8 800172B8 3CAE0280 */ .word .L8002AE3C
enddlabel jtbl_8001729C


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8002AD74, 0x100

glabel func_8002AD74
    /* 1B574 8002AD74 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1B578 8002AD78 1800BFAF */  sw         $ra, 0x18($sp)
    /* 1B57C 8002AD7C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 1B580 8002AD80 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1B584 8002AD84 1E7E000C */  jal        func_8001F878
    /* 1B588 8002AD88 01000424 */   addiu     $a0, $zero, 0x1
    /* 1B58C 8002AD8C 5EA6000C */  jal        func_80029978
    /* 1B590 8002AD90 01001024 */   addiu     $s0, $zero, 0x1
    /* 1B594 8002AD94 0180113C */  lui        $s1, %hi(jtbl_8001729C)
    /* 1B598 8002AD98 9C723126 */  addiu      $s1, $s1, %lo(jtbl_8001729C)
  .L8002AD9C:
    /* 1B59C 8002AD9C 88AA000C */  jal        func_8002AA20
    /* 1B5A0 8002ADA0 29040424 */   addiu     $a0, $zero, 0x429
    /* 1B5A4 8002ADA4 2D005010 */  beq        $v0, $s0, .L8002AE5C
    /* 1B5A8 8002ADA8 00000000 */   nop
    /* 1B5AC 8002ADAC BC0B90A3 */  sb         $s0, %gp_rel(D_800552CC)($gp)
    /* 1B5B0 8002ADB0 EAAA000C */  jal        func_8002ABA8
    /* 1B5B4 8002ADB4 00000000 */   nop
    /* 1B5B8 8002ADB8 21184000 */  addu       $v1, $v0, $zero
    /* 1B5BC 8002ADBC 0800622C */  sltiu      $v0, $v1, 0x8
    /* 1B5C0 8002ADC0 20004010 */  beqz       $v0, .L8002AE44
    /* 1B5C4 8002ADC4 80100300 */   sll       $v0, $v1, 2
    /* 1B5C8 8002ADC8 21105100 */  addu       $v0, $v0, $s1
    /* 1B5CC 8002ADCC 0000428C */  lw         $v0, 0x0($v0)
    /* 1B5D0 8002ADD0 00000000 */  nop
    /* 1B5D4 8002ADD4 08004000 */  jr         $v0
    /* 1B5D8 8002ADD8 00000000 */   nop
  .L8002ADDC:
    /* 1B5DC 8002ADDC 4088000C */  jal        func_80022100
    /* 1B5E0 8002ADE0 00000000 */   nop
    /* 1B5E4 8002ADE4 91AB0008 */  j          .L8002AE44
    /* 1B5E8 8002ADE8 00000000 */   nop
  .L8002ADEC:
    /* 1B5EC 8002ADEC EA8D000C */  jal        func_800237A8
    /* 1B5F0 8002ADF0 00000000 */   nop
    /* 1B5F4 8002ADF4 91AB0008 */  j          .L8002AE44
    /* 1B5F8 8002ADF8 00000000 */   nop
  .L8002ADFC:
    /* 1B5FC 8002ADFC 8A91000C */  jal        func_80024628
    /* 1B600 8002AE00 00000000 */   nop
    /* 1B604 8002AE04 91AB0008 */  j          .L8002AE44
    /* 1B608 8002AE08 00000000 */   nop
  .L8002AE0C:
    /* 1B60C 8002AE0C 0D96000C */  jal        func_80025834
    /* 1B610 8002AE10 00000000 */   nop
    /* 1B614 8002AE14 91AB0008 */  j          .L8002AE44
    /* 1B618 8002AE18 00000000 */   nop
  .L8002AE1C:
    /* 1B61C 8002AE1C F497000C */  jal        func_80025FD0
    /* 1B620 8002AE20 00000000 */   nop
    /* 1B624 8002AE24 91AB0008 */  j          .L8002AE44
    /* 1B628 8002AE28 00000000 */   nop
  .L8002AE2C:
    /* 1B62C 8002AE2C BBA1000C */  jal        func_800286EC
    /* 1B630 8002AE30 00000000 */   nop
    /* 1B634 8002AE34 91AB0008 */  j          .L8002AE44
    /* 1B638 8002AE38 00000000 */   nop
  .L8002AE3C:
    /* 1B63C 8002AE3C CCA5000C */  jal        func_80029730
    /* 1B640 8002AE40 00000000 */   nop
  .L8002AE44:
    /* 1B644 8002AE44 1E7E000C */  jal        func_8001F878
    /* 1B648 8002AE48 01000424 */   addiu     $a0, $zero, 0x1
    /* 1B64C 8002AE4C 5EA6000C */  jal        func_80029978
    /* 1B650 8002AE50 00000000 */   nop
    /* 1B654 8002AE54 67AB0008 */  j          .L8002AD9C
    /* 1B658 8002AE58 00000000 */   nop
  .L8002AE5C:
    /* 1B65C 8002AE5C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 1B660 8002AE60 1400B18F */  lw         $s1, 0x14($sp)
    /* 1B664 8002AE64 1000B08F */  lw         $s0, 0x10($sp)
    /* 1B668 8002AE68 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 1B66C 8002AE6C 0800E003 */  jr         $ra
    /* 1B670 8002AE70 00000000 */   nop
endlabel func_8002AD74
