.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80016A88

dlabel D_80016A88
    /* 7288 80016A88 */ .asciz "    SsVabOepnHead : failed!\n  "
    /* 2020202053735661624F65706E48656164203A206661696C6564210A20200000 */
.align 2
enddlabel D_80016A88

.align 2
nonmatching D_80016AA8

dlabel D_80016AA8
    /* 72A8 80016AA8 */ .asciz "   SsVabTransBody : failed!\n  "
    /* 20202053735661625472616E73426F6479203A206661696C6564210A20200000 */
.align 2
enddlabel D_80016AA8


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_80019B9C, 0xF8

glabel func_80019B9C
    /* A39C 80019B9C D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* A3A0 80019BA0 2400BFAF */  sw         $ra, 0x24($sp)
    /* A3A4 80019BA4 2000B2AF */  sw         $s2, 0x20($sp)
    /* A3A8 80019BA8 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* A3AC 80019BAC 1800B0AF */  sw         $s0, 0x18($sp)
    /* A3B0 80019BB0 6E68000C */  jal        func_8001A1B8
    /* A3B4 80019BB4 21888000 */   addu      $s1, $a0, $zero
    /* A3B8 80019BB8 C0030424 */  addiu      $a0, $zero, 0x3C0
    /* A3BC 80019BBC C7CB000C */  jal        FntLoad
    /* A3C0 80019BC0 00010524 */   addiu     $a1, $zero, 0x100
    /* A3C4 80019BC4 01001224 */  addiu      $s2, $zero, 0x1
    /* A3C8 80019BC8 1000B2AF */  sw         $s2, 0x10($sp)
    /* A3CC 80019BCC 00020224 */  addiu      $v0, $zero, 0x200
    /* A3D0 80019BD0 1400A2AF */  sw         $v0, 0x14($sp)
    /* A3D4 80019BD4 20000424 */  addiu      $a0, $zero, 0x20
    /* A3D8 80019BD8 68000524 */  addiu      $a1, $zero, 0x68
    /* A3DC 80019BDC 00010624 */  addiu      $a2, $zero, 0x100
    /* A3E0 80019BE0 EFCB000C */  jal        FntOpen
    /* A3E4 80019BE4 80000724 */   addiu     $a3, $zero, 0x80
    /* A3E8 80019BE8 21804000 */  addu       $s0, $v0, $zero
    /* A3EC 80019BEC B7CB000C */  jal        SetDumpFnt
    /* A3F0 80019BF0 21200002 */   addu      $a0, $s0, $zero
    /* A3F4 80019BF4 05002012 */  beqz       $s1, .L80019C0C
    /* A3F8 80019BF8 00000000 */   nop
    /* A3FC 80019BFC 07003212 */  beq        $s1, $s2, .L80019C1C
    /* A400 80019C00 00000000 */   nop
    /* A404 80019C04 0D670008 */  j          .L80019C34
    /* A408 80019C08 1000A0AF */   sw        $zero, 0x10($sp)
  .L80019C0C:
    /* A40C 80019C0C 0180053C */  lui        $a1, %hi(D_80016A88)
    /* A410 80019C10 886AA524 */  addiu      $a1, $a1, %lo(D_80016A88)
    /* A414 80019C14 0A670008 */  j          .L80019C28
    /* A418 80019C18 21200002 */   addu      $a0, $s0, $zero
  .L80019C1C:
    /* A41C 80019C1C 21200002 */  addu       $a0, $s0, $zero
    /* A420 80019C20 0180053C */  lui        $a1, %hi(D_80016AA8)
    /* A424 80019C24 A86AA524 */  addiu      $a1, $a1, %lo(D_80016AA8)
  .L80019C28:
    /* A428 80019C28 64CD000C */  jal        FntPrint
    /* A42C 80019C2C 00000000 */   nop
    /* A430 80019C30 1000A0AF */  sw         $zero, 0x10($sp)
  .L80019C34:
    /* A434 80019C34 40010424 */  addiu      $a0, $zero, 0x140
    /* A438 80019C38 F0000524 */  addiu      $a1, $zero, 0xF0
    /* A43C 80019C3C 04000624 */  addiu      $a2, $zero, 0x4
    /* A440 80019C40 37E1000C */  jal        GsInitGraph2
    /* A444 80019C44 21380000 */   addu      $a3, $zero, $zero
    /* A448 80019C48 14CF000C */  jal        SetDispMask
    /* A44C 80019C4C 01000424 */   addiu     $a0, $zero, 0x1
    /* A450 80019C50 9DCC000C */  jal        FntFlush
    /* A454 80019C54 21200002 */   addu      $a0, $s0, $zero
  .L80019C58:
    /* A458 80019C58 23B3000C */  jal        VSync
    /* A45C 80019C5C 21200000 */   addu      $a0, $zero, $zero
    /* A460 80019C60 946C000C */  jal        func_8001B250
    /* A464 80019C64 00000000 */   nop
    /* A468 80019C68 FBFF4010 */  beqz       $v0, .L80019C58
    /* A46C 80019C6C 00000000 */   nop
    /* A470 80019C70 6E68000C */  jal        func_8001A1B8
    /* A474 80019C74 00000000 */   nop
    /* A478 80019C78 2400BF8F */  lw         $ra, 0x24($sp)
    /* A47C 80019C7C 2000B28F */  lw         $s2, 0x20($sp)
    /* A480 80019C80 1C00B18F */  lw         $s1, 0x1C($sp)
    /* A484 80019C84 1800B08F */  lw         $s0, 0x18($sp)
    /* A488 80019C88 2800BD27 */  addiu      $sp, $sp, 0x28
    /* A48C 80019C8C 0800E003 */  jr         $ra
    /* A490 80019C90 00000000 */   nop
endlabel func_80019B9C
