.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
nonmatching jtbl_8001721C

dlabel jtbl_8001721C
    /* 7A1C 8001721C 74E40180 */ .word .L8001E474
    /* 7A20 80017220 D4E40180 */ .word .L8001E4D4
    /* 7A24 80017224 34E50180 */ .word .L8001E534
    /* 7A28 80017228 94E50180 */ .word .L8001E594
    /* 7A2C 8001722C F4E50180 */ .word .L8001E5F4
    /* 7A30 80017230 00000000 */ .word 0x00000000
enddlabel jtbl_8001721C


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8001E330, 0x348

glabel func_8001E330
    /* EB30 8001E330 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* EB34 8001E334 2400BFAF */  sw         $ra, 0x24($sp)
    /* EB38 8001E338 2000B4AF */  sw         $s4, 0x20($sp)
    /* EB3C 8001E33C 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* EB40 8001E340 1800B2AF */  sw         $s2, 0x18($sp)
    /* EB44 8001E344 1400B1AF */  sw         $s1, 0x14($sp)
    /* EB48 8001E348 21A08000 */  addu       $s4, $a0, $zero
    /* EB4C 8001E34C 00240400 */  sll        $a0, $a0, 16
    /* EB50 8001E350 03240400 */  sra        $a0, $a0, 16
    /* EB54 8001E354 06008428 */  slti       $a0, $a0, 0x6
    /* EB58 8001E358 02008014 */  bnez       $a0, .L8001E364
    /* EB5C 8001E35C 1000B0AF */   sw        $s0, 0x10($sp)
    /* EB60 8001E360 05001424 */  addiu      $s4, $zero, 0x5
  .L8001E364:
    /* EB64 8001E364 00141400 */  sll        $v0, $s4, 16
    /* EB68 8001E368 03140200 */  sra        $v0, $v0, 16
    /* EB6C 8001E36C 200C82AF */  sw         $v0, %gp_rel(D_80055330)($gp)
    /* EB70 8001E370 1380043C */  lui        $a0, %hi(D_8012A0E0)
    /* EB74 8001E374 E0A08424 */  addiu      $a0, $a0, %lo(D_8012A0E0)
    /* EB78 8001E378 1580053C */  lui        $a1, %hi(D_8014C2F4)
    /* EB7C 8001E37C F4C2A524 */  addiu      $a1, $a1, %lo(D_8014C2F4)
    /* EB80 8001E380 1D6C000C */  jal        func_8001B074
    /* EB84 8001E384 3D000624 */   addiu     $a2, $zero, 0x3D
    /* EB88 8001E388 10000224 */  addiu      $v0, $zero, 0x10
    /* EB8C 8001E38C 1380013C */  lui        $at, %hi(D_8012A978)
    /* EB90 8001E390 78A922A4 */  sh         $v0, %lo(D_8012A978)($at)
    /* EB94 8001E394 48001324 */  addiu      $s3, $zero, 0x48
    /* EB98 8001E398 1380013C */  lui        $at, %hi(D_8012A97A)
    /* EB9C 8001E39C 7AA933A4 */  sh         $s3, %lo(D_8012A97A)($at)
    /* EBA0 8001E3A0 90001224 */  addiu      $s2, $zero, 0x90
    /* EBA4 8001E3A4 1380013C */  lui        $at, %hi(D_8012A97C)
    /* EBA8 8001E3A8 7CA932A4 */  sh         $s2, %lo(D_8012A97C)($at)
    /* EBAC 8001E3AC 70001024 */  addiu      $s0, $zero, 0x70
    /* EBB0 8001E3B0 1380013C */  lui        $at, %hi(D_8012A97E)
    /* EBB4 8001E3B4 7EA930A4 */  sh         $s0, %lo(D_8012A97E)($at)
    /* EBB8 8001E3B8 1380013C */  lui        $at, %hi(D_8012A982)
    /* EBBC 8001E3BC 82A920A0 */  sb         $zero, %lo(D_8012A982)($at)
    /* EBC0 8001E3C0 1380013C */  lui        $at, %hi(D_8012A983)
    /* EBC4 8001E3C4 83A920A0 */  sb         $zero, %lo(D_8012A983)($at)
    /* EBC8 8001E3C8 38001124 */  addiu      $s1, $zero, 0x38
    /* EBCC 8001E3CC 1380013C */  lui        $at, %hi(D_8012A98E)
    /* EBD0 8001E3D0 8EA931A4 */  sh         $s1, %lo(D_8012A98E)($at)
    /* EBD4 8001E3D4 1380013C */  lui        $at, %hi(D_8012A992)
    /* EBD8 8001E3D8 92A920A4 */  sh         $zero, %lo(D_8012A992)($at)
    /* EBDC 8001E3DC 1380043C */  lui        $a0, %hi(D_8012A0E0)
    /* EBE0 8001E3E0 E0A08424 */  addiu      $a0, $a0, %lo(D_8012A0E0)
    /* EBE4 8001E3E4 1580053C */  lui        $a1, %hi(D_8014C2F4)
    /* EBE8 8001E3E8 F4C2A524 */  addiu      $a1, $a1, %lo(D_8014C2F4)
    /* EBEC 8001E3EC 1D6C000C */  jal        func_8001B074
    /* EBF0 8001E3F0 23000624 */   addiu     $a2, $zero, 0x23
    /* EBF4 8001E3F4 A0000224 */  addiu      $v0, $zero, 0xA0
    /* EBF8 8001E3F8 1380013C */  lui        $at, %hi(D_8012A5D0)
    /* EBFC 8001E3FC D0A522A4 */  sh         $v0, %lo(D_8012A5D0)($at)
    /* EC00 8001E400 1380013C */  lui        $at, %hi(D_8012A5D2)
    /* EC04 8001E404 D2A533A4 */  sh         $s3, %lo(D_8012A5D2)($at)
    /* EC08 8001E408 1380013C */  lui        $at, %hi(D_8012A5D4)
    /* EC0C 8001E40C D4A532A4 */  sh         $s2, %lo(D_8012A5D4)($at)
    /* EC10 8001E410 1380013C */  lui        $at, %hi(D_8012A5D6)
    /* EC14 8001E414 D6A530A4 */  sh         $s0, %lo(D_8012A5D6)($at)
    /* EC18 8001E418 1380013C */  lui        $at, %hi(D_8012A5DA)
    /* EC1C 8001E41C DAA520A0 */  sb         $zero, %lo(D_8012A5DA)($at)
    /* EC20 8001E420 70000224 */  addiu      $v0, $zero, 0x70
    /* EC24 8001E424 1380013C */  lui        $at, %hi(D_8012A5DB)
    /* EC28 8001E428 DBA522A0 */  sb         $v0, %lo(D_8012A5DB)($at)
    /* EC2C 8001E42C 1380013C */  lui        $at, %hi(D_8012A5E6)
    /* EC30 8001E430 E6A531A4 */  sh         $s1, %lo(D_8012A5E6)($at)
    /* EC34 8001E434 1380013C */  lui        $at, %hi(D_8012A5EA)
    /* EC38 8001E438 EAA520A4 */  sh         $zero, %lo(D_8012A5EA)($at)
    /* EC3C 8001E43C CE6D000C */  jal        func_8001B738
    /* EC40 8001E440 01000424 */   addiu     $a0, $zero, 0x1
    /* EC44 8001E444 FFFF8226 */  addiu      $v0, $s4, -0x1
    /* EC48 8001E448 00140200 */  sll        $v0, $v0, 16
    /* EC4C 8001E44C 031C0200 */  sra        $v1, $v0, 16
    /* EC50 8001E450 0500622C */  sltiu      $v0, $v1, 0x5
    /* EC54 8001E454 7F004010 */  beqz       $v0, .L8001E654
    /* EC58 8001E458 80100300 */   sll       $v0, $v1, 2
    /* EC5C 8001E45C 0180013C */  lui        $at, %hi(jtbl_8001721C)
    /* EC60 8001E460 21082200 */  addu       $at, $at, $v0
    /* EC64 8001E464 1C72228C */  lw         $v0, %lo(jtbl_8001721C)($at)
    /* EC68 8001E468 00000000 */  nop
    /* EC6C 8001E46C 08004000 */  jr         $v0
    /* EC70 8001E470 00000000 */   nop
  .L8001E474:
    /* EC74 8001E474 21800000 */  addu       $s0, $zero, $zero
  .L8001E478:
    /* EC78 8001E478 1380023C */  lui        $v0, %hi(D_8012A992)
    /* EC7C 8001E47C 92A94294 */  lhu        $v0, %lo(D_8012A992)($v0)
    /* EC80 8001E480 00000000 */  nop
    /* EC84 8001E484 33004224 */  addiu      $v0, $v0, 0x33
    /* EC88 8001E488 1380013C */  lui        $at, %hi(D_8012A992)
    /* EC8C 8001E48C 92A922A4 */  sh         $v0, %lo(D_8012A992)($at)
    /* EC90 8001E490 1380023C */  lui        $v0, %hi(D_8012A5EA)
    /* EC94 8001E494 EAA54294 */  lhu        $v0, %lo(D_8012A5EA)($v0)
    /* EC98 8001E498 00000000 */  nop
    /* EC9C 8001E49C 33004224 */  addiu      $v0, $v0, 0x33
    /* ECA0 8001E4A0 1380013C */  lui        $at, %hi(D_8012A5EA)
    /* ECA4 8001E4A4 EAA522A4 */  sh         $v0, %lo(D_8012A5EA)($at)
    /* ECA8 8001E4A8 E976000C */  jal        func_8001DBA4
    /* ECAC 8001E4AC 01000424 */   addiu     $a0, $zero, 0x1
    /* ECB0 8001E4B0 01000226 */  addiu      $v0, $s0, 0x1
    /* ECB4 8001E4B4 21804000 */  addu       $s0, $v0, $zero
    /* ECB8 8001E4B8 00140200 */  sll        $v0, $v0, 16
    /* ECBC 8001E4BC 03140200 */  sra        $v0, $v0, 16
    /* ECC0 8001E4C0 10004228 */  slti       $v0, $v0, 0x10
    /* ECC4 8001E4C4 61004010 */  beqz       $v0, .L8001E64C
    /* ECC8 8001E4C8 00000000 */   nop
    /* ECCC 8001E4CC 1E790008 */  j          .L8001E478
    /* ECD0 8001E4D0 00000000 */   nop
  .L8001E4D4:
    /* ECD4 8001E4D4 21800000 */  addu       $s0, $zero, $zero
  .L8001E4D8:
    /* ECD8 8001E4D8 1380023C */  lui        $v0, %hi(D_8012A992)
    /* ECDC 8001E4DC 92A94294 */  lhu        $v0, %lo(D_8012A992)($v0)
    /* ECE0 8001E4E0 00000000 */  nop
    /* ECE4 8001E4E4 66004224 */  addiu      $v0, $v0, 0x66
    /* ECE8 8001E4E8 1380013C */  lui        $at, %hi(D_8012A992)
    /* ECEC 8001E4EC 92A922A4 */  sh         $v0, %lo(D_8012A992)($at)
    /* ECF0 8001E4F0 1380023C */  lui        $v0, %hi(D_8012A5EA)
    /* ECF4 8001E4F4 EAA54294 */  lhu        $v0, %lo(D_8012A5EA)($v0)
    /* ECF8 8001E4F8 00000000 */  nop
    /* ECFC 8001E4FC 66004224 */  addiu      $v0, $v0, 0x66
    /* ED00 8001E500 1380013C */  lui        $at, %hi(D_8012A5EA)
    /* ED04 8001E504 EAA522A4 */  sh         $v0, %lo(D_8012A5EA)($at)
    /* ED08 8001E508 E976000C */  jal        func_8001DBA4
    /* ED0C 8001E50C 01000424 */   addiu     $a0, $zero, 0x1
    /* ED10 8001E510 01000226 */  addiu      $v0, $s0, 0x1
    /* ED14 8001E514 21804000 */  addu       $s0, $v0, $zero
    /* ED18 8001E518 00140200 */  sll        $v0, $v0, 16
    /* ED1C 8001E51C 03140200 */  sra        $v0, $v0, 16
    /* ED20 8001E520 10004228 */  slti       $v0, $v0, 0x10
    /* ED24 8001E524 49004010 */  beqz       $v0, .L8001E64C
    /* ED28 8001E528 00000000 */   nop
    /* ED2C 8001E52C 36790008 */  j          .L8001E4D8
    /* ED30 8001E530 00000000 */   nop
  .L8001E534:
    /* ED34 8001E534 21800000 */  addu       $s0, $zero, $zero
  .L8001E538:
    /* ED38 8001E538 1380023C */  lui        $v0, %hi(D_8012A992)
    /* ED3C 8001E53C 92A94294 */  lhu        $v0, %lo(D_8012A992)($v0)
    /* ED40 8001E540 00000000 */  nop
    /* ED44 8001E544 99004224 */  addiu      $v0, $v0, 0x99
    /* ED48 8001E548 1380013C */  lui        $at, %hi(D_8012A992)
    /* ED4C 8001E54C 92A922A4 */  sh         $v0, %lo(D_8012A992)($at)
    /* ED50 8001E550 1380023C */  lui        $v0, %hi(D_8012A5EA)
    /* ED54 8001E554 EAA54294 */  lhu        $v0, %lo(D_8012A5EA)($v0)
    /* ED58 8001E558 00000000 */  nop
    /* ED5C 8001E55C 99004224 */  addiu      $v0, $v0, 0x99
    /* ED60 8001E560 1380013C */  lui        $at, %hi(D_8012A5EA)
    /* ED64 8001E564 EAA522A4 */  sh         $v0, %lo(D_8012A5EA)($at)
    /* ED68 8001E568 E976000C */  jal        func_8001DBA4
    /* ED6C 8001E56C 01000424 */   addiu     $a0, $zero, 0x1
    /* ED70 8001E570 01000226 */  addiu      $v0, $s0, 0x1
    /* ED74 8001E574 21804000 */  addu       $s0, $v0, $zero
    /* ED78 8001E578 00140200 */  sll        $v0, $v0, 16
    /* ED7C 8001E57C 03140200 */  sra        $v0, $v0, 16
    /* ED80 8001E580 10004228 */  slti       $v0, $v0, 0x10
    /* ED84 8001E584 31004010 */  beqz       $v0, .L8001E64C
    /* ED88 8001E588 00000000 */   nop
    /* ED8C 8001E58C 4E790008 */  j          .L8001E538
    /* ED90 8001E590 00000000 */   nop
  .L8001E594:
    /* ED94 8001E594 21800000 */  addu       $s0, $zero, $zero
  .L8001E598:
    /* ED98 8001E598 1380023C */  lui        $v0, %hi(D_8012A992)
    /* ED9C 8001E59C 92A94294 */  lhu        $v0, %lo(D_8012A992)($v0)
    /* EDA0 8001E5A0 00000000 */  nop
    /* EDA4 8001E5A4 CC004224 */  addiu      $v0, $v0, 0xCC
    /* EDA8 8001E5A8 1380013C */  lui        $at, %hi(D_8012A992)
    /* EDAC 8001E5AC 92A922A4 */  sh         $v0, %lo(D_8012A992)($at)
    /* EDB0 8001E5B0 1380023C */  lui        $v0, %hi(D_8012A5EA)
    /* EDB4 8001E5B4 EAA54294 */  lhu        $v0, %lo(D_8012A5EA)($v0)
    /* EDB8 8001E5B8 00000000 */  nop
    /* EDBC 8001E5BC CC004224 */  addiu      $v0, $v0, 0xCC
    /* EDC0 8001E5C0 1380013C */  lui        $at, %hi(D_8012A5EA)
    /* EDC4 8001E5C4 EAA522A4 */  sh         $v0, %lo(D_8012A5EA)($at)
    /* EDC8 8001E5C8 E976000C */  jal        func_8001DBA4
    /* EDCC 8001E5CC 01000424 */   addiu     $a0, $zero, 0x1
    /* EDD0 8001E5D0 01000226 */  addiu      $v0, $s0, 0x1
    /* EDD4 8001E5D4 21804000 */  addu       $s0, $v0, $zero
    /* EDD8 8001E5D8 00140200 */  sll        $v0, $v0, 16
    /* EDDC 8001E5DC 03140200 */  sra        $v0, $v0, 16
    /* EDE0 8001E5E0 10004228 */  slti       $v0, $v0, 0x10
    /* EDE4 8001E5E4 19004010 */  beqz       $v0, .L8001E64C
    /* EDE8 8001E5E8 00000000 */   nop
    /* EDEC 8001E5EC 66790008 */  j          .L8001E598
    /* EDF0 8001E5F0 00000000 */   nop
  .L8001E5F4:
    /* EDF4 8001E5F4 21800000 */  addu       $s0, $zero, $zero
  .L8001E5F8:
    /* EDF8 8001E5F8 1380023C */  lui        $v0, %hi(D_8012A992)
    /* EDFC 8001E5FC 92A94294 */  lhu        $v0, %lo(D_8012A992)($v0)
    /* EE00 8001E600 00000000 */  nop
    /* EE04 8001E604 00014224 */  addiu      $v0, $v0, 0x100
    /* EE08 8001E608 1380013C */  lui        $at, %hi(D_8012A992)
    /* EE0C 8001E60C 92A922A4 */  sh         $v0, %lo(D_8012A992)($at)
    /* EE10 8001E610 1380023C */  lui        $v0, %hi(D_8012A5EA)
    /* EE14 8001E614 EAA54294 */  lhu        $v0, %lo(D_8012A5EA)($v0)
    /* EE18 8001E618 00000000 */  nop
    /* EE1C 8001E61C 00014224 */  addiu      $v0, $v0, 0x100
    /* EE20 8001E620 1380013C */  lui        $at, %hi(D_8012A5EA)
    /* EE24 8001E624 EAA522A4 */  sh         $v0, %lo(D_8012A5EA)($at)
    /* EE28 8001E628 E976000C */  jal        func_8001DBA4
    /* EE2C 8001E62C 01000424 */   addiu     $a0, $zero, 0x1
    /* EE30 8001E630 01000226 */  addiu      $v0, $s0, 0x1
    /* EE34 8001E634 21804000 */  addu       $s0, $v0, $zero
    /* EE38 8001E638 00140200 */  sll        $v0, $v0, 16
    /* EE3C 8001E63C 03140200 */  sra        $v0, $v0, 16
    /* EE40 8001E640 10004228 */  slti       $v0, $v0, 0x10
    /* EE44 8001E644 ECFF4014 */  bnez       $v0, .L8001E5F8
    /* EE48 8001E648 00000000 */   nop
  .L8001E64C:
    /* EE4C 8001E64C E976000C */  jal        func_8001DBA4
    /* EE50 8001E650 01000424 */   addiu     $a0, $zero, 0x1
  .L8001E654:
    /* EE54 8001E654 2400BF8F */  lw         $ra, 0x24($sp)
    /* EE58 8001E658 2000B48F */  lw         $s4, 0x20($sp)
    /* EE5C 8001E65C 1C00B38F */  lw         $s3, 0x1C($sp)
    /* EE60 8001E660 1800B28F */  lw         $s2, 0x18($sp)
    /* EE64 8001E664 1400B18F */  lw         $s1, 0x14($sp)
    /* EE68 8001E668 1000B08F */  lw         $s0, 0x10($sp)
    /* EE6C 8001E66C 2800BD27 */  addiu      $sp, $sp, 0x28
    /* EE70 8001E670 0800E003 */  jr         $ra
    /* EE74 8001E674 00000000 */   nop
endlabel func_8001E330
