.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
nonmatching jtbl_800172F4

dlabel jtbl_800172F4
    /* 7AF4 800172F4 E8B30280 */ .word .L8002B3E8
    /* 7AF8 800172F8 08B40280 */ .word .L8002B408
    /* 7AFC 800172FC 08B40280 */ .word .L8002B408
    /* 7B00 80017300 08B40280 */ .word .L8002B408
    /* 7B04 80017304 08B40280 */ .word .L8002B408
    /* 7B08 80017308 08B40280 */ .word .L8002B408
    /* 7B0C 8001730C 08B40280 */ .word .L8002B408
    /* 7B10 80017310 08B40280 */ .word .L8002B408
    /* 7B14 80017314 08B40280 */ .word .L8002B408
    /* 7B18 80017318 08B40280 */ .word .L8002B408
    /* 7B1C 8001731C 08B40280 */ .word .L8002B408
    /* 7B20 80017320 88B30280 */ .word .L8002B388
    /* 7B24 80017324 D4B30280 */ .word .L8002B3D4
    /* 7B28 80017328 08B40280 */ .word .L8002B408
    /* 7B2C 8001732C 08B40280 */ .word .L8002B408
    /* 7B30 80017330 08B40280 */ .word .L8002B408
    /* 7B34 80017334 08B40280 */ .word .L8002B408
    /* 7B38 80017338 08B40280 */ .word .L8002B408
    /* 7B3C 8001733C 08B40280 */ .word .L8002B408
    /* 7B40 80017340 08B40280 */ .word .L8002B408
    /* 7B44 80017344 08B40280 */ .word .L8002B408
    /* 7B48 80017348 08B40280 */ .word .L8002B408
    /* 7B4C 8001734C 08B40280 */ .word .L8002B408
    /* 7B50 80017350 08B40280 */ .word .L8002B408
    /* 7B54 80017354 08B40280 */ .word .L8002B408
    /* 7B58 80017358 08B40280 */ .word .L8002B408
    /* 7B5C 8001735C 08B40280 */ .word .L8002B408
    /* 7B60 80017360 98B30280 */ .word .L8002B398
    /* 7B64 80017364 08B40280 */ .word .L8002B408
    /* 7B68 80017368 08B40280 */ .word .L8002B408
    /* 7B6C 8001736C 08B40280 */ .word .L8002B408
    /* 7B70 80017370 08B40280 */ .word .L8002B408
    /* 7B74 80017374 E8B30280 */ .word .L8002B3E8
enddlabel jtbl_800172F4


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8002B300, 0x15C

glabel func_8002B300
    /* 1BB00 8002B300 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1BB04 8002B304 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 1BB08 8002B308 1800B2AF */  sw         $s2, 0x18($sp)
    /* 1BB0C 8002B30C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 1BB10 8002B310 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1BB14 8002B314 2188A000 */  addu       $s1, $a1, $zero
    /* 1BB18 8002B318 2190C000 */  addu       $s2, $a2, $zero
    /* 1BB1C 8002B31C 21808000 */  addu       $s0, $a0, $zero
  .L8002B320:
    /* 1BB20 8002B320 00002292 */  lbu        $v0, 0x0($s1)
    /* 1BB24 8002B324 00000000 */  nop
    /* 1BB28 8002B328 44004010 */  beqz       $v0, .L8002B43C
    /* 1BB2C 8002B32C 25000224 */   addiu     $v0, $zero, 0x25
    /* 1BB30 8002B330 00002392 */  lbu        $v1, 0x0($s1)
    /* 1BB34 8002B334 00000000 */  nop
    /* 1BB38 8002B338 3A006214 */  bne        $v1, $v0, .L8002B424
    /* 1BB3C 8002B33C 6C000224 */   addiu     $v0, $zero, 0x6C
    /* 1BB40 8002B340 01003126 */  addiu      $s1, $s1, 0x1
    /* 1BB44 8002B344 00002392 */  lbu        $v1, 0x0($s1)
    /* 1BB48 8002B348 00000000 */  nop
    /* 1BB4C 8002B34C 02006214 */  bne        $v1, $v0, .L8002B358
    /* 1BB50 8002B350 00000000 */   nop
    /* 1BB54 8002B354 01003126 */  addiu      $s1, $s1, 0x1
  .L8002B358:
    /* 1BB58 8002B358 00002292 */  lbu        $v0, 0x0($s1)
    /* 1BB5C 8002B35C 00000000 */  nop
    /* 1BB60 8002B360 A8FF4324 */  addiu      $v1, $v0, -0x58
    /* 1BB64 8002B364 2100622C */  sltiu      $v0, $v1, 0x21
    /* 1BB68 8002B368 27004010 */  beqz       $v0, .L8002B408
    /* 1BB6C 8002B36C 80100300 */   sll       $v0, $v1, 2
    /* 1BB70 8002B370 0180013C */  lui        $at, %hi(jtbl_800172F4)
    /* 1BB74 8002B374 21082200 */  addu       $at, $at, $v0
    /* 1BB78 8002B378 F472228C */  lw         $v0, %lo(jtbl_800172F4)($at)
    /* 1BB7C 8002B37C 00000000 */  nop
    /* 1BB80 8002B380 08004000 */  jr         $v0
    /* 1BB84 8002B384 00000000 */   nop
  .L8002B388:
    /* 1BB88 8002B388 04005226 */  addiu      $s2, $s2, 0x4
    /* 1BB8C 8002B38C FCFF4292 */  lbu        $v0, -0x4($s2)
    /* 1BB90 8002B390 06AD0008 */  j          .L8002B418
    /* 1BB94 8002B394 000002A2 */   sb        $v0, 0x0($s0)
  .L8002B398:
    /* 1BB98 8002B398 04005226 */  addiu      $s2, $s2, 0x4
    /* 1BB9C 8002B39C FCFF438E */  lw         $v1, -0x4($s2)
    /* 1BBA0 8002B3A0 FF000424 */  addiu      $a0, $zero, 0xFF
  .L8002B3A4:
    /* 1BBA4 8002B3A4 00006290 */  lbu        $v0, 0x0($v1)
    /* 1BBA8 8002B3A8 00000000 */  nop
    /* 1BBAC 8002B3AC 1B004010 */  beqz       $v0, .L8002B41C
    /* 1BBB0 8002B3B0 00000000 */   nop
    /* 1BBB4 8002B3B4 19008010 */  beqz       $a0, .L8002B41C
    /* 1BBB8 8002B3B8 FFFF8424 */   addiu     $a0, $a0, -0x1
    /* 1BBBC 8002B3BC 00006290 */  lbu        $v0, 0x0($v1)
    /* 1BBC0 8002B3C0 00000000 */  nop
    /* 1BBC4 8002B3C4 000002A2 */  sb         $v0, 0x0($s0)
    /* 1BBC8 8002B3C8 01006324 */  addiu      $v1, $v1, 0x1
    /* 1BBCC 8002B3CC E9AC0008 */  j          .L8002B3A4
    /* 1BBD0 8002B3D0 01001026 */   addiu     $s0, $s0, 0x1
  .L8002B3D4:
    /* 1BBD4 8002B3D4 04005226 */  addiu      $s2, $s2, 0x4
    /* 1BBD8 8002B3D8 FCFF448E */  lw         $a0, -0x4($s2)
    /* 1BBDC 8002B3DC 21280002 */  addu       $a1, $s0, $zero
    /* 1BBE0 8002B3E0 FEAC0008 */  j          .L8002B3F8
    /* 1BBE4 8002B3E4 0A000624 */   addiu     $a2, $zero, 0xA
  .L8002B3E8:
    /* 1BBE8 8002B3E8 04005226 */  addiu      $s2, $s2, 0x4
    /* 1BBEC 8002B3EC FCFF448E */  lw         $a0, -0x4($s2)
    /* 1BBF0 8002B3F0 21280002 */  addu       $a1, $s0, $zero
    /* 1BBF4 8002B3F4 10000624 */  addiu      $a2, $zero, 0x10
  .L8002B3F8:
    /* 1BBF8 8002B3F8 8AAC000C */  jal        func_8002B228
    /* 1BBFC 8002B3FC 01003126 */   addiu     $s1, $s1, 0x1
    /* 1BC00 8002B400 C8AC0008 */  j          .L8002B320
    /* 1BC04 8002B404 21800202 */   addu      $s0, $s0, $v0
  .L8002B408:
    /* 1BC08 8002B408 00002292 */  lbu        $v0, 0x0($s1)
    /* 1BC0C 8002B40C 00000000 */  nop
    /* 1BC10 8002B410 000002A2 */  sb         $v0, 0x0($s0)
    /* 1BC14 8002B414 01003126 */  addiu      $s1, $s1, 0x1
  .L8002B418:
    /* 1BC18 8002B418 01001026 */  addiu      $s0, $s0, 0x1
  .L8002B41C:
    /* 1BC1C 8002B41C C8AC0008 */  j          .L8002B320
    /* 1BC20 8002B420 01003126 */   addiu     $s1, $s1, 0x1
  .L8002B424:
    /* 1BC24 8002B424 00002292 */  lbu        $v0, 0x0($s1)
    /* 1BC28 8002B428 00000000 */  nop
    /* 1BC2C 8002B42C 000002A2 */  sb         $v0, 0x0($s0)
    /* 1BC30 8002B430 01003126 */  addiu      $s1, $s1, 0x1
    /* 1BC34 8002B434 C8AC0008 */  j          .L8002B320
    /* 1BC38 8002B438 01001026 */   addiu     $s0, $s0, 0x1
  .L8002B43C:
    /* 1BC3C 8002B43C 000000A2 */  sb         $zero, 0x0($s0)
    /* 1BC40 8002B440 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 1BC44 8002B444 1800B28F */  lw         $s2, 0x18($sp)
    /* 1BC48 8002B448 1400B18F */  lw         $s1, 0x14($sp)
    /* 1BC4C 8002B44C 1000B08F */  lw         $s0, 0x10($sp)
    /* 1BC50 8002B450 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 1BC54 8002B454 0800E003 */  jr         $ra
    /* 1BC58 8002B458 00000000 */   nop
endlabel func_8002B300
