.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80016A74

dlabel D_80016A74
    /* 7274 80016A74 */ .asciz "   SECTOR_No %8d"
    /* 202020534543544F525F4E6F2025386400000000 */
.align 2
enddlabel D_80016A74


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_80019A24, 0x178

glabel func_80019A24
    /* A224 80019A24 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* A228 80019A28 2800BFAF */  sw         $ra, 0x28($sp)
    /* A22C 80019A2C 2400B3AF */  sw         $s3, 0x24($sp)
    /* A230 80019A30 2000B2AF */  sw         $s2, 0x20($sp)
    /* A234 80019A34 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* A238 80019A38 1800B0AF */  sw         $s0, 0x18($sp)
    /* A23C 80019A3C 21908000 */  addu       $s2, $a0, $zero
    /* A240 80019A40 6E68000C */  jal        func_8001A1B8
    /* A244 80019A44 2198A000 */   addu      $s3, $a1, $zero
    /* A248 80019A48 C0030424 */  addiu      $a0, $zero, 0x3C0
    /* A24C 80019A4C C7CB000C */  jal        FntLoad
    /* A250 80019A50 00010524 */   addiu     $a1, $zero, 0x100
    /* A254 80019A54 01001024 */  addiu      $s0, $zero, 0x1
    /* A258 80019A58 1000B0AF */  sw         $s0, 0x10($sp)
    /* A25C 80019A5C 00020224 */  addiu      $v0, $zero, 0x200
    /* A260 80019A60 1400A2AF */  sw         $v0, 0x14($sp)
    /* A264 80019A64 20000424 */  addiu      $a0, $zero, 0x20
    /* A268 80019A68 68000524 */  addiu      $a1, $zero, 0x68
    /* A26C 80019A6C 00010624 */  addiu      $a2, $zero, 0x100
    /* A270 80019A70 EFCB000C */  jal        FntOpen
    /* A274 80019A74 80000724 */   addiu     $a3, $zero, 0x80
    /* A278 80019A78 21884000 */  addu       $s1, $v0, $zero
    /* A27C 80019A7C B7CB000C */  jal        SetDumpFnt
    /* A280 80019A80 21202002 */   addu      $a0, $s1, $zero
    /* A284 80019A84 05005012 */  beq        $s2, $s0, .L80019A9C
    /* A288 80019A88 02000224 */   addiu     $v0, $zero, 0x2
    /* A28C 80019A8C 07004212 */  beq        $s2, $v0, .L80019AAC
    /* A290 80019A90 00000000 */   nop
    /* A294 80019A94 CE660008 */  j          .L80019B38
    /* A298 80019A98 1000A0AF */   sw        $zero, 0x10($sp)
  .L80019A9C:
    /* A29C 80019A9C 0180053C */  lui        $a1, %hi(D_800169F4)
    /* A2A0 80019AA0 F469A524 */  addiu      $a1, $a1, %lo(D_800169F4)
    /* A2A4 80019AA4 AE660008 */  j          .L80019AB8
    /* A2A8 80019AA8 21202002 */   addu      $a0, $s1, $zero
  .L80019AAC:
    /* A2AC 80019AAC 21202002 */  addu       $a0, $s1, $zero
    /* A2B0 80019AB0 0180053C */  lui        $a1, %hi(D_80016A54)
    /* A2B4 80019AB4 546AA524 */  addiu      $a1, $a1, %lo(D_80016A54)
  .L80019AB8:
    /* A2B8 80019AB8 64CD000C */  jal        FntPrint
    /* A2BC 80019ABC 00000000 */   nop
    /* A2C0 80019AC0 0580053C */  lui        $a1, %hi(D_8005647C)
    /* A2C4 80019AC4 7C64A524 */  addiu      $a1, $a1, %lo(D_8005647C)
    /* A2C8 80019AC8 64CD000C */  jal        FntPrint
    /* A2CC 80019ACC 21202002 */   addu      $a0, $s1, $zero
    /* A2D0 80019AD0 21202002 */  addu       $a0, $s1, $zero
    /* A2D4 80019AD4 0180053C */  lui        $a1, %hi(D_80016A74)
    /* A2D8 80019AD8 746AA524 */  addiu      $a1, $a1, %lo(D_80016A74)
    /* A2DC 80019ADC 64CD000C */  jal        FntPrint
    /* A2E0 80019AE0 21306002 */   addu      $a2, $s3, $zero
    /* A2E4 80019AE4 0580053C */  lui        $a1, %hi(D_8005647C)
    /* A2E8 80019AE8 7C64A524 */  addiu      $a1, $a1, %lo(D_8005647C)
    /* A2EC 80019AEC 64CD000C */  jal        FntPrint
    /* A2F0 80019AF0 21202002 */   addu      $a0, $s1, $zero
    /* A2F4 80019AF4 0180053C */  lui        $a1, %hi(D_80016A14)
    /* A2F8 80019AF8 146AA524 */  addiu      $a1, $a1, %lo(D_80016A14)
    /* A2FC 80019AFC 64CD000C */  jal        FntPrint
    /* A300 80019B00 21202002 */   addu      $a0, $s1, $zero
    /* A304 80019B04 0580053C */  lui        $a1, %hi(D_80056480)
    /* A308 80019B08 8064A524 */  addiu      $a1, $a1, %lo(D_80056480)
    /* A30C 80019B0C 64CD000C */  jal        FntPrint
    /* A310 80019B10 21202002 */   addu      $a0, $s1, $zero
    /* A314 80019B14 0180053C */  lui        $a1, %hi(D_80016A34)
    /* A318 80019B18 346AA524 */  addiu      $a1, $a1, %lo(D_80016A34)
    /* A31C 80019B1C 64CD000C */  jal        FntPrint
    /* A320 80019B20 21202002 */   addu      $a0, $s1, $zero
    /* A324 80019B24 0580053C */  lui        $a1, %hi(D_80056480)
    /* A328 80019B28 8064A524 */  addiu      $a1, $a1, %lo(D_80056480)
    /* A32C 80019B2C 64CD000C */  jal        FntPrint
    /* A330 80019B30 21202002 */   addu      $a0, $s1, $zero
    /* A334 80019B34 1000A0AF */  sw         $zero, 0x10($sp)
  .L80019B38:
    /* A338 80019B38 40010424 */  addiu      $a0, $zero, 0x140
    /* A33C 80019B3C F0000524 */  addiu      $a1, $zero, 0xF0
    /* A340 80019B40 04000624 */  addiu      $a2, $zero, 0x4
    /* A344 80019B44 37E1000C */  jal        GsInitGraph2
    /* A348 80019B48 21380000 */   addu      $a3, $zero, $zero
    /* A34C 80019B4C 14CF000C */  jal        SetDispMask
    /* A350 80019B50 01000424 */   addiu     $a0, $zero, 0x1
    /* A354 80019B54 9DCC000C */  jal        FntFlush
    /* A358 80019B58 21202002 */   addu      $a0, $s1, $zero
  .L80019B5C:
    /* A35C 80019B5C 23B3000C */  jal        VSync
    /* A360 80019B60 21200000 */   addu      $a0, $zero, $zero
    /* A364 80019B64 946C000C */  jal        func_8001B250
    /* A368 80019B68 00000000 */   nop
    /* A36C 80019B6C FBFF4010 */  beqz       $v0, .L80019B5C
    /* A370 80019B70 00000000 */   nop
    /* A374 80019B74 6E68000C */  jal        func_8001A1B8
    /* A378 80019B78 00000000 */   nop
    /* A37C 80019B7C 2800BF8F */  lw         $ra, 0x28($sp)
    /* A380 80019B80 2400B38F */  lw         $s3, 0x24($sp)
    /* A384 80019B84 2000B28F */  lw         $s2, 0x20($sp)
    /* A388 80019B88 1C00B18F */  lw         $s1, 0x1C($sp)
    /* A38C 80019B8C 1800B08F */  lw         $s0, 0x18($sp)
    /* A390 80019B90 3000BD27 */  addiu      $sp, $sp, 0x30
    /* A394 80019B94 0800E003 */  jr         $ra
    /* A398 80019B98 00000000 */   nop
endlabel func_80019A24
