.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80016BF0

dlabel D_80016BF0
    /* 73F0 80016BF0 */ .asciz "Tex %d  "
    /* 546578202564202000000000 */
.align 2
enddlabel D_80016BF0


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8001CC58, 0x21C

glabel func_8001CC58
    /* D458 8001CC58 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* D45C 8001CC5C 3800BFAF */  sw         $ra, 0x38($sp)
    /* D460 8001CC60 3400B7AF */  sw         $s7, 0x34($sp)
    /* D464 8001CC64 3000B6AF */  sw         $s6, 0x30($sp)
    /* D468 8001CC68 2C00B5AF */  sw         $s5, 0x2C($sp)
    /* D46C 8001CC6C 2800B4AF */  sw         $s4, 0x28($sp)
    /* D470 8001CC70 2400B3AF */  sw         $s3, 0x24($sp)
    /* D474 8001CC74 2000B2AF */  sw         $s2, 0x20($sp)
    /* D478 8001CC78 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* D47C 8001CC7C 1800B0AF */  sw         $s0, 0x18($sp)
    /* D480 8001CC80 21B00000 */  addu       $s6, $zero, $zero
    /* D484 8001CC84 1280173C */  lui        $s7, %hi(D_80127368)
    /* D488 8001CC88 6873F726 */  addiu      $s7, $s7, %lo(D_80127368)
    /* D48C 8001CC8C 001C1600 */  sll        $v1, $s6, 16
  .L8001CC90:
    /* D490 8001CC90 031C0300 */  sra        $v1, $v1, 16
    /* D494 8001CC94 40100300 */  sll        $v0, $v1, 1
    /* D498 8001CC98 21104300 */  addu       $v0, $v0, $v1
    /* D49C 8001CC9C 80100200 */  sll        $v0, $v0, 2
    /* D4A0 8001CCA0 0180013C */  lui        $at, %hi(D_80016BCC)
    /* D4A4 8001CCA4 21082200 */  addu       $at, $at, $v0
    /* D4A8 8001CCA8 CC6B3094 */  lhu        $s0, %lo(D_80016BCC)($at)
    /* D4AC 8001CCAC 0180013C */  lui        $at, %hi(D_80016BD0)
    /* D4B0 8001CCB0 21082200 */  addu       $at, $at, $v0
    /* D4B4 8001CCB4 D06B3394 */  lhu        $s3, %lo(D_80016BD0)($at)
    /* D4B8 8001CCB8 0180013C */  lui        $at, %hi(D_80016BD2)
    /* D4BC 8001CCBC 21082200 */  addu       $at, $at, $v0
    /* D4C0 8001CCC0 D26B3494 */  lhu        $s4, %lo(D_80016BD2)($at)
    /* D4C4 8001CCC4 0180013C */  lui        $at, %hi(D_80016BD4)
    /* D4C8 8001CCC8 21082200 */  addu       $at, $at, $v0
    /* D4CC 8001CCCC D46B3594 */  lhu        $s5, %lo(D_80016BD4)($at)
    /* D4D0 8001CCD0 0180013C */  lui        $at, %hi(D_80016BD6)
    /* D4D4 8001CCD4 21082200 */  addu       $at, $at, $v0
    /* D4D8 8001CCD8 D66B3294 */  lhu        $s2, %lo(D_80016BD6)($at)
    /* D4DC 8001CCDC 0180013C */  lui        $at, %hi(D_80016BCE)
    /* D4E0 8001CCE0 21082200 */  addu       $at, $at, $v0
    /* D4E4 8001CCE4 CE6B3190 */  lbu        $s1, %lo(D_80016BCE)($at)
    /* D4E8 8001CCE8 0180043C */  lui        $a0, %hi(D_80016BF0)
    /* D4EC 8001CCEC F06B8424 */  addiu      $a0, $a0, %lo(D_80016BF0)
    /* D4F0 8001CCF0 5CAD000C */  jal        func_8002B570
    /* D4F4 8001CCF4 21282002 */   addu      $a1, $s1, $zero
    /* D4F8 8001CCF8 FFFF1032 */  andi       $s0, $s0, 0xFFFF
    /* D4FC 8001CCFC 7CAD000C */  jal        func_8002B5F0
    /* D500 8001CD00 21200002 */   addu      $a0, $s0, $zero
    /* D504 8001CD04 80801000 */  sll        $s0, $s0, 2
    /* D508 8001CD08 21101702 */  addu       $v0, $s0, $s7
    /* D50C 8001CD0C 0000448C */  lw         $a0, 0x0($v0)
    /* D510 8001CD10 1380013C */  lui        $at, %hi(D_80129868)
    /* D514 8001CD14 21083000 */  addu       $at, $at, $s0
    /* D518 8001CD18 6898258C */  lw         $a1, %lo(D_80129868)($at)
    /* D51C 8001CD1C AF6A000C */  jal        func_8001AABC
    /* D520 8001CD20 01000624 */   addiu     $a2, $zero, 0x1
    /* D524 8001CD24 00211100 */  sll        $a0, $s1, 4
    /* D528 8001CD28 21209100 */  addu       $a0, $a0, $s1
    /* D52C 8001CD2C 80200400 */  sll        $a0, $a0, 2
    /* D530 8001CD30 1580023C */  lui        $v0, %hi(D_8014C008)
    /* D534 8001CD34 08C04224 */  addiu      $v0, $v0, %lo(D_8014C008)
    /* D538 8001CD38 009C1300 */  sll        $s3, $s3, 16
    /* D53C 8001CD3C 00A41400 */  sll        $s4, $s4, 16
    /* D540 8001CD40 00AC1500 */  sll        $s5, $s5, 16
    /* D544 8001CD44 00941200 */  sll        $s2, $s2, 16
    /* D548 8001CD48 03941200 */  sra        $s2, $s2, 16
    /* D54C 8001CD4C 1000B2AF */  sw         $s2, 0x10($sp)
    /* D550 8001CD50 21208200 */  addu       $a0, $a0, $v0
    /* D554 8001CD54 032C1300 */  sra        $a1, $s3, 16
    /* D558 8001CD58 03341400 */  sra        $a2, $s4, 16
    /* D55C 8001CD5C 396B000C */  jal        func_8001ACE4
    /* D560 8001CD60 033C1500 */   sra       $a3, $s5, 16
    /* D564 8001CD64 0100C226 */  addiu      $v0, $s6, 0x1
    /* D568 8001CD68 21B04000 */  addu       $s6, $v0, $zero
    /* D56C 8001CD6C 00140200 */  sll        $v0, $v0, 16
    /* D570 8001CD70 03140200 */  sra        $v0, $v0, 16
    /* D574 8001CD74 03004228 */  slti       $v0, $v0, 0x3
    /* D578 8001CD78 C5FF4014 */  bnez       $v0, .L8001CC90
    /* D57C 8001CD7C 001C1600 */   sll       $v1, $s6, 16
    /* D580 8001CD80 6E68000C */  jal        func_8001A1B8
    /* D584 8001CD84 00011124 */   addiu     $s1, $zero, 0x100
    /* D588 8001CD88 1380043C */  lui        $a0, %hi(D_8012A0E0)
    /* D58C 8001CD8C E0A08424 */  addiu      $a0, $a0, %lo(D_8012A0E0)
    /* D590 8001CD90 1580053C */  lui        $a1, %hi(D_8014C008)
    /* D594 8001CD94 08C0A524 */  addiu      $a1, $a1, %lo(D_8014C008)
    /* D598 8001CD98 1D6C000C */  jal        func_8001B074
    /* D59C 8001CD9C 0A000624 */   addiu     $a2, $zero, 0xA
    /* D5A0 8001CDA0 1380013C */  lui        $at, %hi(D_8012A24C)
    /* D5A4 8001CDA4 4CA220A4 */  sh         $zero, %lo(D_8012A24C)($at)
    /* D5A8 8001CDA8 1380013C */  lui        $at, %hi(D_8012A24E)
    /* D5AC 8001CDAC 4EA220A4 */  sh         $zero, %lo(D_8012A24E)($at)
    /* D5B0 8001CDB0 1380013C */  lui        $at, %hi(D_8012A250)
    /* D5B4 8001CDB4 50A231A4 */  sh         $s1, %lo(D_8012A250)($at)
    /* D5B8 8001CDB8 F0001224 */  addiu      $s2, $zero, 0xF0
    /* D5BC 8001CDBC 1380013C */  lui        $at, %hi(D_8012A252)
    /* D5C0 8001CDC0 52A232A4 */  sh         $s2, %lo(D_8012A252)($at)
    /* D5C4 8001CDC4 1380013C */  lui        $at, %hi(D_8012A256)
    /* D5C8 8001CDC8 56A220A0 */  sb         $zero, %lo(D_8012A256)($at)
    /* D5CC 8001CDCC 1380013C */  lui        $at, %hi(D_8012A257)
    /* D5D0 8001CDD0 57A220A0 */  sb         $zero, %lo(D_8012A257)($at)
    /* D5D4 8001CDD4 1380103C */  lui        $s0, %hi(D_8012A0E0)
    /* D5D8 8001CDD8 E0A01026 */  addiu      $s0, $s0, %lo(D_8012A0E0)
    /* D5DC 8001CDDC 7E0100A2 */  sb         $zero, 0x17E($s0)
    /* D5E0 8001CDE0 7D0100A2 */  sb         $zero, 0x17D($s0)
    /* D5E4 8001CDE4 1380013C */  lui        $at, %hi(D_8012A25C)
    /* D5E8 8001CDE8 5CA220A0 */  sb         $zero, %lo(D_8012A25C)($at)
    /* D5EC 8001CDEC 21200002 */  addu       $a0, $s0, $zero
    /* D5F0 8001CDF0 1580053C */  lui        $a1, %hi(D_8014C04C)
    /* D5F4 8001CDF4 4CC0A524 */  addiu      $a1, $a1, %lo(D_8014C04C)
    /* D5F8 8001CDF8 1D6C000C */  jal        func_8001B074
    /* D5FC 8001CDFC 0B000624 */   addiu     $a2, $zero, 0xB
    /* D600 8001CE00 1380013C */  lui        $at, %hi(D_8012A270)
    /* D604 8001CE04 70A231A4 */  sh         $s1, %lo(D_8012A270)($at)
    /* D608 8001CE08 1380013C */  lui        $at, %hi(D_8012A272)
    /* D60C 8001CE0C 72A220A4 */  sh         $zero, %lo(D_8012A272)($at)
    /* D610 8001CE10 40000224 */  addiu      $v0, $zero, 0x40
    /* D614 8001CE14 1380013C */  lui        $at, %hi(D_8012A274)
    /* D618 8001CE18 74A222A4 */  sh         $v0, %lo(D_8012A274)($at)
    /* D61C 8001CE1C 1380013C */  lui        $at, %hi(D_8012A276)
    /* D620 8001CE20 76A232A4 */  sh         $s2, %lo(D_8012A276)($at)
    /* D624 8001CE24 1380013C */  lui        $at, %hi(D_8012A27A)
    /* D628 8001CE28 7AA220A0 */  sb         $zero, %lo(D_8012A27A)($at)
    /* D62C 8001CE2C 1380013C */  lui        $at, %hi(D_8012A27B)
    /* D630 8001CE30 7BA220A0 */  sb         $zero, %lo(D_8012A27B)($at)
    /* D634 8001CE34 A20100A2 */  sb         $zero, 0x1A2($s0)
    /* D638 8001CE38 A10100A2 */  sb         $zero, 0x1A1($s0)
    /* D63C 8001CE3C 1380013C */  lui        $at, %hi(D_8012A280)
    /* D640 8001CE40 80A220A0 */  sb         $zero, %lo(D_8012A280)($at)
    /* D644 8001CE44 3800BF8F */  lw         $ra, 0x38($sp)
    /* D648 8001CE48 3400B78F */  lw         $s7, 0x34($sp)
    /* D64C 8001CE4C 3000B68F */  lw         $s6, 0x30($sp)
    /* D650 8001CE50 2C00B58F */  lw         $s5, 0x2C($sp)
    /* D654 8001CE54 2800B48F */  lw         $s4, 0x28($sp)
    /* D658 8001CE58 2400B38F */  lw         $s3, 0x24($sp)
    /* D65C 8001CE5C 2000B28F */  lw         $s2, 0x20($sp)
    /* D660 8001CE60 1C00B18F */  lw         $s1, 0x1C($sp)
    /* D664 8001CE64 1800B08F */  lw         $s0, 0x18($sp)
    /* D668 8001CE68 4000BD27 */  addiu      $sp, $sp, 0x40
    /* D66C 8001CE6C 0800E003 */  jr         $ra
    /* D670 8001CE70 00000000 */   nop
endlabel func_8001CC58
