.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
nonmatching D_80016AF8

dlabel D_80016AF8
    /* 72F8 80016AF8 */ .asciz "mem_tim_data_xy_load: %d,%d  "
    /* 6D656D5F74696D5F646174615F78795F6C6F61643A2025642C25642020000000 */
.align 2
enddlabel D_80016AF8


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8001AEC4, 0x1B0

glabel func_8001AEC4
    /* B6C4 8001AEC4 C8FFBD27 */  addiu      $sp, $sp, -0x38
    /* B6C8 8001AEC8 3400BFAF */  sw         $ra, 0x34($sp)
    /* B6CC 8001AECC 3000B6AF */  sw         $s6, 0x30($sp)
    /* B6D0 8001AED0 2C00B5AF */  sw         $s5, 0x2C($sp)
    /* B6D4 8001AED4 2800B4AF */  sw         $s4, 0x28($sp)
    /* B6D8 8001AED8 2400B3AF */  sw         $s3, 0x24($sp)
    /* B6DC 8001AEDC 2000B2AF */  sw         $s2, 0x20($sp)
    /* B6E0 8001AEE0 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* B6E4 8001AEE4 1800B0AF */  sw         $s0, 0x18($sp)
    /* B6E8 8001AEE8 21A0A000 */  addu       $s4, $a1, $zero
    /* B6EC 8001AEEC 2188C000 */  addu       $s1, $a2, $zero
    /* B6F0 8001AEF0 2190E000 */  addu       $s2, $a3, $zero
    /* B6F4 8001AEF4 21802002 */  addu       $s0, $s1, $zero
    /* B6F8 8001AEF8 21984002 */  addu       $s3, $s2, $zero
    /* B6FC 8001AEFC 4800B697 */  lhu        $s6, 0x48($sp)
    /* B700 8001AF00 4C00B597 */  lhu        $s5, 0x4C($sp)
    /* B704 8001AF04 0D80053C */  lui        $a1, %hi(D_800CC1A8)
    /* B708 8001AF08 A8C1A524 */  addiu      $a1, $a1, %lo(D_800CC1A8)
    /* B70C 8001AF0C FFE5000C */  jal        GsGetTimInfo
    /* B710 8001AF10 04008424 */   addiu     $a0, $a0, 0x4
    /* B714 8001AF14 1000B0A7 */  sh         $s0, 0x10($sp)
    /* B718 8001AF18 1200B3A7 */  sh         $s3, 0x12($sp)
    /* B71C 8001AF1C 0D80103C */  lui        $s0, %hi(D_800CC1B0)
    /* B720 8001AF20 B0C11026 */  addiu      $s0, $s0, %lo(D_800CC1B0)
    /* B724 8001AF24 00000296 */  lhu        $v0, 0x0($s0)
    /* B728 8001AF28 00000000 */  nop
    /* B72C 8001AF2C 1400A2A7 */  sh         $v0, 0x14($sp)
    /* B730 8001AF30 02000296 */  lhu        $v0, 0x2($s0)
    /* B734 8001AF34 00000000 */  nop
    /* B738 8001AF38 1600A2A7 */  sh         $v0, 0x16($sp)
    /* B73C 8001AF3C 0400058E */  lw         $a1, 0x4($s0)
    /* B740 8001AF40 E5CF000C */  jal        LoadImage
    /* B744 8001AF44 1000A427 */   addiu     $a0, $sp, 0x10
    /* B748 8001AF48 3ACF000C */  jal        DrawSync
    /* B74C 8001AF4C 21200000 */   addu      $a0, $zero, $zero
    /* B750 8001AF50 1000B6A7 */  sh         $s6, 0x10($sp)
    /* B754 8001AF54 1200B5A7 */  sh         $s5, 0x12($sp)
    /* B758 8001AF58 0C000296 */  lhu        $v0, 0xC($s0)
    /* B75C 8001AF5C 00000000 */  nop
    /* B760 8001AF60 1400A2A7 */  sh         $v0, 0x14($sp)
    /* B764 8001AF64 0E000296 */  lhu        $v0, 0xE($s0)
    /* B768 8001AF68 00000000 */  nop
    /* B76C 8001AF6C 1600A2A7 */  sh         $v0, 0x16($sp)
    /* B770 8001AF70 1000058E */  lw         $a1, 0x10($s0)
    /* B774 8001AF74 E5CF000C */  jal        LoadImage
    /* B778 8001AF78 1000A427 */   addiu     $a0, $sp, 0x10
    /* B77C 8001AF7C F8FF048E */  lw         $a0, -0x8($s0)
    /* B780 8001AF80 008C1100 */  sll        $s1, $s1, 16
    /* B784 8001AF84 038C1100 */  sra        $s1, $s1, 16
    /* B788 8001AF88 00941200 */  sll        $s2, $s2, 16
    /* B78C 8001AF8C 03941200 */  sra        $s2, $s2, 16
    /* B790 8001AF90 03008430 */  andi       $a0, $a0, 0x3
    /* B794 8001AF94 21280000 */  addu       $a1, $zero, $zero
    /* B798 8001AF98 21302002 */  addu       $a2, $s1, $zero
    /* B79C 8001AF9C 63DA000C */  jal        GetTPage
    /* B7A0 8001AFA0 21384002 */   addu      $a3, $s2, $zero
    /* B7A4 8001AFA4 420082A6 */  sh         $v0, 0x42($s4)
    /* B7A8 8001AFA8 0180043C */  lui        $a0, %hi(D_80016AF8)
    /* B7AC 8001AFAC F86A8424 */  addiu      $a0, $a0, %lo(D_80016AF8)
    /* B7B0 8001AFB0 21282002 */  addu       $a1, $s1, $zero
    /* B7B4 8001AFB4 5CAD000C */  jal        func_8002B570
    /* B7B8 8001AFB8 21304002 */   addu      $a2, $s2, $zero
    /* B7BC 8001AFBC F8FF0296 */  lhu        $v0, -0x8($s0)
    /* B7C0 8001AFC0 00000000 */  nop
    /* B7C4 8001AFC4 000082A6 */  sh         $v0, 0x0($s4)
    /* B7C8 8001AFC8 07004230 */  andi       $v0, $v0, 0x7
    /* B7CC 8001AFCC 10004014 */  bnez       $v0, .L8001B010
    /* B7D0 8001AFD0 21200000 */   addu      $a0, $zero, $zero
    /* B7D4 8001AFD4 00140400 */  sll        $v0, $a0, 16
  .L8001AFD8:
    /* B7D8 8001AFD8 C3130200 */  sra        $v0, $v0, 15
    /* B7DC 8001AFDC 21105400 */  addu       $v0, $v0, $s4
    /* B7E0 8001AFE0 020056A4 */  sh         $s6, 0x2($v0)
    /* B7E4 8001AFE4 2118A402 */  addu       $v1, $s5, $a0
    /* B7E8 8001AFE8 220043A4 */  sh         $v1, 0x22($v0)
    /* B7EC 8001AFEC 01008224 */  addiu      $v0, $a0, 0x1
    /* B7F0 8001AFF0 21204000 */  addu       $a0, $v0, $zero
    /* B7F4 8001AFF4 00140200 */  sll        $v0, $v0, 16
    /* B7F8 8001AFF8 03140200 */  sra        $v0, $v0, 16
    /* B7FC 8001AFFC 10004228 */  slti       $v0, $v0, 0x10
    /* B800 8001B000 F5FF4014 */  bnez       $v0, .L8001AFD8
    /* B804 8001B004 00140400 */   sll       $v0, $a0, 16
    /* B808 8001B008 106C0008 */  j          .L8001B040
    /* B80C 8001B00C 00000000 */   nop
  .L8001B010:
    /* B810 8001B010 00140400 */  sll        $v0, $a0, 16
  .L8001B014:
    /* B814 8001B014 C3130200 */  sra        $v0, $v0, 15
    /* B818 8001B018 21105400 */  addu       $v0, $v0, $s4
    /* B81C 8001B01C 020056A4 */  sh         $s6, 0x2($v0)
    /* B820 8001B020 220055A4 */  sh         $s5, 0x22($v0)
    /* B824 8001B024 01008224 */  addiu      $v0, $a0, 0x1
    /* B828 8001B028 21204000 */  addu       $a0, $v0, $zero
    /* B82C 8001B02C 00140200 */  sll        $v0, $v0, 16
    /* B830 8001B030 03140200 */  sra        $v0, $v0, 16
    /* B834 8001B034 10004228 */  slti       $v0, $v0, 0x10
    /* B838 8001B038 F6FF4014 */  bnez       $v0, .L8001B014
    /* B83C 8001B03C 00140400 */   sll       $v0, $a0, 16
  .L8001B040:
    /* B840 8001B040 3ACF000C */  jal        DrawSync
    /* B844 8001B044 21200000 */   addu      $a0, $zero, $zero
    /* B848 8001B048 3400BF8F */  lw         $ra, 0x34($sp)
    /* B84C 8001B04C 3000B68F */  lw         $s6, 0x30($sp)
    /* B850 8001B050 2C00B58F */  lw         $s5, 0x2C($sp)
    /* B854 8001B054 2800B48F */  lw         $s4, 0x28($sp)
    /* B858 8001B058 2400B38F */  lw         $s3, 0x24($sp)
    /* B85C 8001B05C 2000B28F */  lw         $s2, 0x20($sp)
    /* B860 8001B060 1C00B18F */  lw         $s1, 0x1C($sp)
    /* B864 8001B064 1800B08F */  lw         $s0, 0x18($sp)
    /* B868 8001B068 3800BD27 */  addiu      $sp, $sp, 0x38
    /* B86C 8001B06C 0800E003 */  jr         $ra
    /* B870 8001B070 00000000 */   nop
endlabel func_8001AEC4
